### ISSUE TITLE
Record projection by expression doesn't allow the expression to be a variable

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-haskell#1009]
```
⊢  let e = { a = 10, b = "Text" } let s = { a : Natural } in e.({ a : Natural }) 

{ a = 10 }

⊢  let e = { a = 10, b = "Text" } let s = { a : Natural } in e.(s) 

it : { a : Natural }
e : { a : Natural, b : Text }

Error: Unbound variable: s

1:                                                               s

(stdin):1:63
```

This exact example has type inference tested by `dhall/dhall-lang/tests/type-inference/success/unit/RecordProjectionByTypeA.dhall`, but evidently something's wrong with the actual evaluation.

**Comment by quasicomputational** [comment]
Huh. Having added the example to the test suite under `normalization/success/unit/`, it works when the test suite runs and fails if I wibble its output, as you would expect if it was working, but it still breaks when I pass the test input to `dhall normalize`. I thought this would be a simple bug with a straightforward fix, but now I'm quite baffled at why the behaviour under test and the actual behaviour are differing.

**Comment by Gabriel439** [comment]
I found the bug: the `subst` function does not do the right thing for the `Project` constructor:

https://github.com/dhall-lang/dhall-haskell/blob/b001a61a02b691977525f8833798ea3bf1128bac/dhall/src/Dhall/Core.hs#L1138-L1140

Specifically, it does not substitute into `s` of `e.(s)`.  The above code should be:

```haskell
 subst x e (Project a b) = Project a' b'
   where 
    a' = subst x e a
    b' = subst x e b 
```

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1012
