### ISSUE TITLE
Question regarding type-checking of let binders

### ISSUE THREAD

**Issue by EggBaconAndSpam** [dhall-lang/dhall-haskell#1017]
When the type of the bound expression is small, is there any reason why we need to substitute in the resulting type? That is, since we don't have dependent types isn't `V x 0` guaranteed to not occur in `_B0` anyway? Could we just remove line 188 entirely?
https://github.com/dhall-lang/dhall-haskell/blob/6fee49d47ca4389b1d59b8237d3f76bb31c4a7a4/dhall/src/Dhall/TypeCheck.hs#L184-L196

**Comment by Gabriel439** [comment]
@EggBaconAndSpam: Yes, I believe you are correct.  The first branch implies that `x` is a term, so it shouldn't appear in the inferred type of the expression that `x` scopes over.  So the first branch should simplify down to:

```haskell
case Dhall.Core.normalize t of
    Const Type -> do
        let ctx' = fmap (Dhall.Core.shift 1 (V x 0)) (Dhall.Context.insert x (Dhall.Core.normalize _A1) ctx)
        loop ctx' rest
    ...

**Comment by EggBaconAndSpam** [comment]
well I think we do need ` let _B2 = Dhall.Core.shift (-1) (V x 0) _B1 ` to update any other occurrences of the bound name correctly (though they all are of de Bruijn index at least 1)

**Comment by Gabriel439** [comment]
You're welcome! 🙂
