### ISSUE TITLE
Also run the type-inference tests

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1021]
I noticed that `dhall:test:tasty` doesn't run these: https://github.com/dhall-lang/dhall-lang/tree/master/tests/type-inference. But maybe there's a reason?!

**Comment by sjakobi** [comment]
Maybe we should have a common test harness for the acceptance tests.

Each implementation should only need to plug in its specific commands  for typechecking, hashing etc. The harness then ensures that _all_ the acceptance tests are run. Explicitly skipping some tests should be possible too…

**Comment by f-f** [comment]
@sjakobi every language has specific facilities to run test, so I'm not sure this is really feasible.

Moreover, being able to skip tests and introduce them gradually it's a feature of the current test collection (which is just a bunch of files + high level instructions on how to verify them), so I'd say the responsibility of running all the tests should be on every implementation
