### ISSUE TITLE
InvalidField error message is outdated

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1025]
https://github.com/dhall-lang/dhall-haskell/blob/b9aeb345e4d9ed5bff9b9bd82ffeb76ff9d44ecc/dhall/src/Dhall/TypeCheck.hs#L2307-L2317

`{ foo = Type }` appears to be legal these days.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1026
