### ISSUE TITLE
Broken benchmarks

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1028]
```
≻ stack bench dhall:bench:dhall-parser
Cabal file warning in/home/simon/src/dhall-haskell/dhall-json/dhall-json.cabal@71:9: Unknown field: "maven-depends"
Cabal file warning in/home/simon/src/dhall-haskell/dhall-json/dhall-json.cabal@76:9: Unknown field: "java-sources"
dhall> benchmarks
Running 1 benchmarks...
Benchmark dhall-parser: RUNNING...
dhall-parser: Prelude: changeWorkingDirectory: does not exist (No such file or directory)
Benchmark dhall-parser: ERROR

--  While building package dhall-1.24.0 using:
      /home/simon/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 bench dhall-parser
    Process exited with code: ExitFailure 1
```

```
≻ stack bench dhall:bench:deep-nested-large-record
Cabal file warning in/home/simon/src/dhall-haskell/dhall-json/dhall-json.cabal@71:9: Unknown field: "maven-depends"
Cabal file warning in/home/simon/src/dhall-haskell/dhall-json/dhall-json.cabal@76:9: Unknown field: "java-sources"
dhall> benchmarks
Running 1 benchmarks...
Benchmark deep-nested-large-record: RUNNING...
deep-nested-large-record: 
↳ ./benchmark/deep-nested-large-record/prelude.dhall

Error: Invalid input

/home/simon/src/dhall-haskell/dhall/benchmark/deep-nested-large-record/prelude.dhall:2:23:
  |
2 |   { Big = constructors ./BigEnum.dhall
  |                       ^
expecting expression or whitespace

Benchmark deep-nested-large-record: ERROR

--  While building package dhall-1.24.0 using:
      /home/simon/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 bench deep-nested-large-record
    Process exited with code: ExitFailure 1
```
```
≻ stack bench dhall:bench:dhall-command
Cabal file warning in/home/simon/src/dhall-haskell/dhall-json/dhall-json.cabal@71:9: Unknown field: "maven-depends"
Cabal file warning in/home/simon/src/dhall-haskell/dhall-json/dhall-json.cabal@76:9: Unknown field: "java-sources"
dhall> benchmarks
Running 1 benchmarks...
Benchmark dhall-command: RUNNING...

Error: Invalid input

(stdin):1:1:
  |
1 | <empty line>
  | ^
unexpected end of input
expecting expression or whitespace

Benchmark dhall-command: ERROR

--  While building package dhall-1.24.0 using:
      /home/simon/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 bench dhall-command
    Process exited with code: ExitFailure 1
```

**Comment by sjakobi** [comment]
I'll submit a patch.

Would there be a point in running these in CI so they don't break again? We can use 

```
  -L,--time-limit SECS     Time limit to run a benchmark
```

to run them more quickly.

We could also switch from `criterion` to `gauge` to reduce build times…

**Comment by Gabriel439** [comment]
@sjakobi: Oh, I didn't even know that there was a `--time-limit` option.  If we can use that to make the benchmarks run more quickly then I'm fine enabling them in CI

**Comment by sjakobi** [comment]
I don't have much Nix experience. Any pointers on running the benchmarks on Hydra?

**Comment by sjakobi** [comment]
How is the `dhall-command` benchmark supposed to be used? Is it just a helper executable?

**Comment by Gabriel439** [comment]
Regarding `dhall-command`, see: #608

**Comment by sjakobi** [comment]
> Regarding `dhall-command`, see: #608

Thanks for the pointer! I think having `dhall-command` with its current behaviour as a benchmark is a bit awkward because it causes commands like `stack bench` or `cabal bench dhall` to fail. Why don't we simply profile the `dhall` executable? Would there be a problem with the ergonomics? (cc @FintanH)

**Comment by FintanH** [comment]
Well `dhall-command` was to allow any user to benchmark any dhall expression. It's extremely useful when you've come across a crazy case like we did at Formation. But I suppose it could be an executable rather than a benchmark and we could include the profiling flag in the cabal file (I think?).

**Comment by sjakobi** [comment]
@FintanH what I don't currently understand is why we need a separate executable / Cabal component for that. Why can't you simply use the `dhall` executable with profiling options?

BTW the instructions on using `dhall-command` in #608 don't seem to work for me.

```
$ stack bench --profile --library-profiling dhall:dhall-command <<< "./dhall/dhall-lang/Prelude/package.dhall"
Cabal file warning in/home/simon/src/dhall-haskell/dhall-json/dhall-json.cabal@71:9: Unknown field: "maven-depends"
Cabal file warning in/home/simon/src/dhall-haskell/dhall-json/dhall-json.cabal@76:9: Unknown field: "java-sources"
dhall> benchmarks
Running 1 benchmarks...
Benchmark dhall-command: RUNNING...

Error: Invalid input

(stdin):1:1:
  |
1 | <empty line>
  | ^
unexpected end of input
expecting expression or whitespace

Benchmark dhall-command: ERROR

--  While building package dhall-1.24.0 using:
      /home/simon/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 bench dhall-command "--benchmark-options=+RTS -p -RTS "
    Process exited with code: ExitFailure 1
```

Has the correct invocation changed?

**Comment by FintanH** [comment]
@sjakobi I just tried this on the latest `master` and it worked fine for me. What version are you on?

> Why can't you simply use the dhall executable with profiling options?

Oh that might be a good point. I'm not actually sure what the difference is between those two options. Hmmm so if I do `stack exec --profile --library-profiling dhall <<< "https://raw.githubusercontent.com/dhall-lang/dhall-lang/0a7f596d03b3ea760a96a8e03935f4baa64274e1/Prelude/package.dhall"` I don't get the  profiling output, i.e. `dhall.prof`. I'm not sure if this is just a quirk of `stack` or would it be the same with `cabal`.

**Comment by sjakobi** [comment]
@FintanH Maybe `stack` has changed? I'm using `v2.1.1`.

You can profile the dhall executable like this:

```
$ stack build --profile --library-profiling dhall
$ stack --profile exec --rts-options -p -- dhall <<< 'True && False'
```

I think you can't avoid the `build` step as `exec` doesn't start a build.

**Comment by sjakobi** [comment]
@FintanH Would you be ok with simply removing the `dhall-command` benchmark if I document the above profiling instructions somewhere, like the readme?

**Comment by sjakobi** [comment]
@FintanH See https://github.com/dhall-lang/dhall-haskell/pull/1033/commits/b052f2c5b3fdc4830bde1a0aa26f208918511168.

**Comment by FintanH** [comment]
@sjakobi: Ya, that works for me :100: thanks for cleaning up my cruft :sweat_smile: :heart:

**Comment by sjakobi** [comment]
My pleasure! :)
