### ISSUE TITLE
HTTP request overrides for HTTP imports

### ISSUE THREAD

**Issue by robbiemcmichael** [dhall-lang/dhall-haskell#1043]
I'm a big fan of the HTTP imports in Dhall, it makes it very easy to use libraries without needing to vendor / submodule / use a tool specific package manager. Unfortunately, for people unlucky enough to work at a large enterprise where all builds have to happen behind a caching proxy and have no connection to the outside world, using Dhall in production can be painful.

My proposal is that I'd like to use [`managerModifyRequest`](https://hackage.haskell.org/package/http-client-0.6.4/docs/Network-HTTP-Client.html#v:managerModifyRequest) to allow users to override certain HTTP requests. For example, we can simply intercept all requests for `github.com/<path>` and transform them to a request for `caching-proxy.domain/github/<path>`. This is much simpler for users compared to a man-in-the-middle proxy. The behaviour would be entirely opt-in, the main thing to do is figure out a sensible way to configure the HTTP request overrides.

I'm happy to do the implementation, just wanted to get a feel for whether there's any appetite for adding this feature and to see if anyone has anysuggestions for a better way to implement it.

**Comment by Gabriel439** [comment]
@robbiemcmichael: If this is not a change to the language (i.e. it is just a change to the Haskell API), then I have no objections to adding support for this.

**Comment by robbiemcmichael** [comment]
No changes needed to the language, just a change to the Haskell implementation around [here](https://github.com/dhall-lang/dhall-haskell/blob/92bdd56a3426bb912aadc0ab9b8a8effe0ec6714/dhall/src/Dhall/Import/HTTP.hs#L118) to allow some of the HTTP manager settings to be overridden. I'll find some time to implement it soon.

**Comment by GarrisonJ** [comment]
This would be fun to implement, but what would be the interface for allowing the user to specify managerModifyRequest?

**Comment by sjakobi** [comment]
Admittedly I don't understand how to set up `ManagerSettings` in a way that `managerModifyRequest` could change the request host. Alternatively, you could make [`fetchRemote`](https://github.com/dhall-lang/dhall-haskell/blob/75e6cc5ca7dccf4c8d5831f0aaa664fc3400f060/dhall/ghc-src/Dhall/Import/HTTP.hs#L262) configurable.

Regarding the user interface, I'm not sure what @robbiemcmichael had in mind. I'm wondering how you'd configure this in other tools.

If the main use case is to modify the host string, maybe an option that allows search-and-replace on the URL would work? E.g.

`--modify-url=github.com|cache.domain/github`

**Comment by ocharles** [comment]
It sounds like we just need proxy support, no? There are standard environment variables for that

**Comment by Gabriel439** [comment]
Yeah, I think all we need is support for configuring a forward proxy via a command-line option

**Comment by robbiemcmichael** [comment]
The `dhall` binaries already respect `http_proxy` and `https_proxy` environment variables so I don't think any changes are needed on the forward proxy side. The use case I'm describing here is for those people unlucky enough to work at a company where CI builds don't even get access to an internet facing proxy (it's crazy, I know).

When you're forced to route traffic through a private caching proxy, you need to rewrite the URLs on the client side otherwise the client will reject the certificates it receives from the caching proxy as it has a completely different domain from the one in the client's request. The only way to solve this with a forward proxy is to have a man-in-the-middle proxy which serves a spoofed certificate chain and to trust the CA used to sign these certificates.

I've already written a [library that can handle URL rewriting](https://github.com/robbiemcmichael/http-client-overrides) as I also need to use it for Elm package management and a colleague was looking at using it for [spago](https://github.com/spacchetti/spago). I was just waiting for it to at least be available in Stackage before proposing it here. I'm not entirely sure why it's not in Stackage, I think it might be related to the dependency on `http-client-tls` which has some dependencies of its own which aren't compiling with GHC 8.8.1 currently.

**Comment by Gabriel439** [comment]
Huh, I didn't even know that the executable respected `http{s}_proxy`!  I guess the `http-client` library took care of that for us.

I do agree that this is pretty crazy since it's clearly a reverse proxy jury rigged like a poor man's forward proxy.  That said, I'll see what we can do.

I think probably the most realistic thing we can do is expose this at the Haskell API level so that you can build your own `dhall` executable, but exposing this level of customization via a command-line parameter is probably going to be madness.

**Comment by robbiemcmichael** [comment]
@Gabriel439 The way I implemented [http-client-overrides](https://github.com/robbiemcmichael/http-client-overrides) was to use the environment variable `HTTP_CLIENT_OVERRIDES` as a path to a configuration file. If the environment variable isn't set, then it just returns the original manager and is identical to not using the library. If it is set, then the library does all the heavy lifting in terms of parsing the configuration file and setting [`managerModifyRequest`](https://hackage.haskell.org/package/http-client-0.6.4/docs/Network-HTTP-Client.html#v:managerModifyRequest) to override the requests.

I think the only change needed to dhall-haskell to support this is [here](https://github.com/dhall-lang/dhall-haskell/blob/fa84b0dc198d0de58ca4e8bae9cfcae410c1ad2e/dhall/ghc-src/Dhall/Import/HTTP.hs#L182) where we would replace

```haskell
HTTP.newManager settings
```

with 

```haskell
overrides <- withHttpClientOverridesThrow settings
HTTP.newManager overrides
```

**Comment by Gabriel439** [comment]
@robbiemcmichael: I think my main concern is that `http-client-overrides` depends on `yaml` which is a dependency we're trying to avoid (even for `dhall-to-yaml`!)

**Comment by robbiemcmichael** [comment]
@Gabriel439 No problem, the library at least simplifies the process for maintaining my own personal fork of `dhall-haskell` to solve this problem. I'll wait to see what you come up with for avoiding the dependency on `yaml` and I might be able to do the same thing.

It's probably also sensible to not make this change to `dhall-haskell` unless other people are running into the same problem. The number of people trying to use Dhall at large companies that prevent CI from accessing the internet in the name of security is probably pretty small.

**Comment by Gabriel439** [comment]
I believe this was fixed by https://github.com/dhall-lang/dhall-haskell/pull/2027
