### ISSUE TITLE
dhall-format and dhall-lsp-server for MacOS?

### ISSUE THREAD

**Issue by joshburkart** [dhall-lang/dhall-haskell#1047]
Hi! I'm wondering what the preferred way of installing `dhall-format` and `dhall-lsp-server` on MacOS is... Seems like the instructions for installing `dhall` using `brew` don't include installing these useful-seeming binaries.

Sorry if this is a dumb question!

**Comment by Gabriel439** [comment]
@joshburkart: `dhall format` is actually a sub-command of the `dhall` executable, so if you have `dhall` already installed using `brew` then you're good to go.

I plan to add `dhall-lsp-server` to `brew` once we release it to Hackage (ETA: ~1-2 weeks + however much time it takes `brew` to accept the pull request to add the `dhall-lsp-server` package to `brew`).

**Comment by joshburkart** [comment]
Thank you!!

**Comment by Gabriel439** [comment]
You're welcome! 🙂

**Comment by Gabriel439** [comment]
You can now download pre-built OS X executables from the releases page: https://github.com/dhall-lang/dhall-haskell/releases

I'm still in the process of adding `dhall-lsp-server` to `brew`
