### ISSUE TITLE
Release dhall-to-text

### ISSUE THREAD

**Issue by lorenzo** [dhall-lang/dhall-haskell#1055]
I'm having a hard time getting `dhall-to-text` in macOS, there is no binary release for it, it's not in homebrew and the last version published to hackage is somewhat old.

Is there anything blocking the release of this binary?

**Comment by Gabriel439** [comment]
See: https://github.com/Homebrew/homebrew-core/pull/41387

The only thing blocking it is the `brew` project merging that pull request

**Comment by sjakobi** [comment]
Can this be closed now that the `dhall-text` functionality is included in the `dhall` package?

**Comment by Gabriel439** [comment]
Yes, this is now available via the `dhall text` subcommand
