### ISSUE TITLE
yaml-to-dhall crashes (union in schema)

### ISSUE THREAD

**Issue by vvv** [dhall-lang/dhall-haskell#1074]
`yaml-to-dhall` (and `json-to-dhall`) crashes if there is a union in schema:
```
$ dhall-to-yaml <<<'let U = < Foo | Bar : Text > in U.Foo'
Foo
$ echo Foo | yaml-to-dhall '< Foo | Bar : Text >'

Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:78:14 in base:GHC.Err
  undefined, called at src/Dhall/JSONToDhall.hs:323:22 in dhall-json-1.3.0-3UOr6XfsCRnK61XKBZfXOr:Dhall.JSONToDhall
```
If unions are not supported by those utilities (which [seems to be the case](https://github.com/dhall-lang/dhall-json/issues/23#issuecomment-381448147)), they should explain this to the user and exit gracefully.

**Comment by Gabriel439** [comment]
Unions should be supported.  I'll take a look at this soon to figure out what went wrong here

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1083
