### ISSUE TITLE
Integrate `dhall-to-text` into `dhall` executable

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-haskell#1087]
Currently the [`dhall-to-text`](https://github.com/dhall-lang/dhall-haskell/blob/master/dhall-text/exec/Main.hs) executable is just a small wrapper around the library, so for ease of distribution (i.e. less binaries to install) would it make sense to just have it as a command under the `dhall` executable? (e.g. `dhall text` or `dhall --to-text`)

**Comment by Gabriel439** [comment]
@f-f: Yeah, I agree.  Having a `dhall text` command make a lot more sense
