### ISSUE TITLE
dhall-json: Remove {} field from < Inline : {} | Nested : Text >

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1092]
Since we also allow empty alternatives, `< Inline | Nested : Text >` should be sufficient.

If we want, we could keep the old schema working for backwards compatibility.

**Comment by Gabriel439** [comment]
Yeah, we should support the old schema for compatibility.  In this case there's essentially no cost for backwards compatibility because there's only one implementation of `dhall-to-json` to support

**Comment by sjakobi** [comment]
The `Prelude/JSON/Nesting` type was already changed in https://github.com/dhall-lang/dhall-lang/pull/541.

**Comment by sjakobi** [comment]
I'll make a PR.
