### ISSUE TITLE
`--file` option for `dhall-to-yaml`

### ISSUE THREAD

**Issue by alexhumphreys** [dhall-lang/dhall-haskell#1096]
I see there's a `--file` option for the `dhall` executable, as mentioned here https://github.com/dhall-lang/dhall-haskell/pull/1004

Would it be possible to add this to `dhall-to-yaml`? I find it easier to keep my import paths in order when I don't have to worry about what my current directory is when playing with STDIN.

**Comment by f-f** [comment]
It could also be a good idea to just bundle `dhall-to-json` and `dhall-to-yaml` into the `dhall` executable itself, as we already did for `dhall-to-text` in #1087 (AFAIK it wouldn't change much the dependency footprint, most of the dependencies are already overlapping)

**Comment by Gabriel439** [comment]
@f-f: There should be a separate issue to discuss that, but the main issue we're running into is that the `dhall` package is actually doing two separate things:

* Providing a native Haskell binding
* Providing the `dhall` executable

If we could split out the native Haskell binding into a smaller separate package (i.e. `dhall-core` or `dhall-api`) and leave the `dhall` package for the executable (and re-exporting the Haskell API for backwards compatibility) then I'd have less reservations about adding extra dependencies to the `dhall` package.  The reason why is that I'd like people using `dhall` as a native Haskell binding to have a smaller dependency footprint.

For example, if they were separate packages then somebody using the executable-free package to configure their Haskell program wouldn't need to depend on `repline`, `aeson`, `aeson-pretty`, `Diff`, `dotgen`, `cborg-json`, or `ansi-terminal`.  Similarly, we could freely add dependencies like `yaml` to the executable package guilt-free.

@alexhumphreys: Yeah, I can add a `--file` option to the various executables built by the `dhall-json` package.

**Comment by f-f** [comment]
@Gabriel439 agreed! Opened #1102 to discuss this

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1107

**Comment by alexhumphreys** [comment]
Sweet, thank you!
