### ISSUE TITLE
Dhall format/lint pretty printer improvements

### ISSUE THREAD

**Issue by jvanbruegge** [dhall-lang/dhall-haskell#1099]
The pretty printer has (IMO) a few issues, currently my workflow is using `dhall lint` and then manually fix these.
For example taking this freshly formatted file:
<details>
 <summary>LocalVolume.dhall</summary>

```dhall
let types = ../types.dhall

let defaults = ../defaults.dhall

let settings = ../settings.dhall

let utils = ../utils.dhall

in    λ(v : ./LocalVolume.dhall)
    →     defaults.PersistentVolume
        ⫽ { metadata =
                defaults.ObjectMeta
              ⫽ { name = v.name, namespace = Some v.namespace }
          , spec =
              Some
              (   defaults.PersistentVolumeSpec
                ⫽ { capacity =
                      [ { mapKey = "storage", mapValue = v.size } ]
                  , accessModes =
                      [ "ReadWriteOnce" ]
                  , persistentVolumeReclaimPolicy =
                      Some "Retain"
                  , storageClassName =
                      Some "local-storage"
                  , local =
                      Some { path = "/data/${v.directory}", fsType = None Text }
                  , nodeAffinity =
                      { required =
                          Some
                          { nodeSelectorTerms =
                              [   defaults.NodeSelectorTerm
                                ⫽ { matchExpressions =
                                      [ { key =
                                            "kubernetes.io/hostnames"
                                        , operator =
                                            "In"
                                        , values =
                                            utils.NonEmpty.toList
                                            Text
                                            settings.hosts
                                        }
                                      ]
                                  }
                              ]
                          }
                      }
                  }
              )
          }
      : types.PersistentVolume
```
</details>

I have to transform it to land at this:

<details>
<summary>LocalVolume.dhall</summary>

```dhall
let types = ../types.dhall
let defaults = ../defaults.dhall
let settings = ../settings.dhall
let utils = ../utils.dhall

in    λ(v : ./LocalVolume.dhall)
    →     defaults.PersistentVolume
        ⫽ { metadata =
                defaults.ObjectMeta
              ⫽ { name = v.name, namespace = Some v.namespace }
          , spec =
              Some
              (   defaults.PersistentVolumeSpec
                ⫽ { capacity = [ { mapKey = "storage", mapValue = v.size } ]
                  , accessModes = [ "ReadWriteOnce" ]
                  , persistentVolumeReclaimPolicy = Some "Retain"
                  , storageClassName = Some "local-storage"
                  , local = Some { path = "/data/${v.directory}", fsType = None Text }
                  , nodeAffinity =
                      { required =
                          Some
                          { nodeSelectorTerms =
                              [   defaults.NodeSelectorTerm
                                ⫽ { matchExpressions =
                                      [ { key = "kubernetes.io/hostnames"
                                        , operator = "In"
                                        , values =
                                            utils.NonEmpty.toList
                                            Text
                                            settings.hosts
                                        }
                                      ]
                                  }
                              ]
                          }
                      }
                  }
              )
          }
      : types.PersistentVolume
```
</details>

As you can see there are basically 3 changes I do:
1. Do not put an empty line between single line `let`s
2. Do not wrap record values if less than 80 characters
3. (Not visible above because happend to be right already) Align the arrow or the record merge operator 4 characters from the left, not the type signature

I just want to open this to have a discussion about the mentioned changes, I won't have time to work on these any time soon

**Comment by jvanbruegge** [comment]
> That won't dedent it as much as you requested, because I would still like to retain a two-space indent in between the variable bound by a let definition and its right hand side:

What I dislike about this is that the indent depends on the length of the variable identifier (at least AFAICT). I'd prefer a fixed indent a lot more.

**Comment by jvanbruegge** [comment]
oh, and I also agree, single line `let` and record value assignment is the same, so break if longer than 80 (including indentation) would be the right call here

**Comment by f-f** [comment]
Re blank lines between `let`s, would it be hard to "remember" the layout? E.g. I often keep together definitions that are contextual, e.g.:
```dhall
let a = ..
let b = ..

let c = ..
let d = ..
```

**Comment by basile-henry** [comment]
Regarding the `let` blank lines you could reintroduce them by using a multiple multi-let:

```dhall
let a = ..
let b = ..

in
let c = ..
let d = ..

in
```

**Comment by Gabriel439** [comment]
@jvanbruegge: The indent currently doesn't depend on the length of the identifier.  The indent is set to two spaces after the beginning of the identifier:

```
let␣longIdentifierName =
␣␣␣␣␣␣someExpression

in␣␣anotherExpression
```

The reason why the indent appears to be more than two spaces is because of the use of `//` and `:`, so your expression is indented like this:

```
let someIdentifier =
    ␣␣␣␣␣␣someExpression
    ␣␣␣␣⫽ anotherExpression
    ␣␣: typeAnnotations

in  result
```

... so the first line of the expression is indented 6 spaces, but the expression as a whole (including the type annotation) is only indented 2 spaces.

**Comment by joneshf** [comment]
> However, what I could do is make the maximum column parametrizable instead of hardcoding it to 80 characters.

Like a flag to `dhall format`? If so, I'm not too hot on this change. Many formatters these days have followed the pattern of limiting customization with the consensus being that it's a good decision. I know there's not an explicit goal to follow trends in the industry at large, but it would be nice to follow this one.

A different hardcoded number seems fine though, as it would still remain consistent across all Dhall files formatted with that version.

**Comment by jvanbruegge** [comment]
The single line records are fine from my side, and I would also prefer a hardcoded number (80 is fine). I just dont like the line wrapping in multiline records

**Comment by Profpatsch** [comment]
I’d prefer the formatter not to have any options.

**Comment by Gabriel439** [comment]
I'm closing this for now since it's not clear what remains to be done.
