### ISSUE TITLE
`dhall format` should prefer percent-encoded URL paths instead of quoted paths

### ISSUE THREAD

**Issue by philandstuff** [dhall-lang/dhall-haskell#1109]
Context: dhall-lang/dhall-lang#581

Currently `echo 'http://foo/bar%23baz' | dhall format` outputs `http://foo/"bar#baz"`.  I think (and proposed in the above issue on dhall-lang) it should be the other way around: the percent-encoded form should be preferred over the quoted form.

----

When formatting a URL, we can take most of our guidance from RFC 3986.  It defines [unreserved characters](https://tools.ietf.org/html/rfc3986#section-2.3) and says that URI normalizers should decode these characters whenever found; it also defines [reserved characters](https://tools.ietf.org/html/rfc3986#section-2.2) and says that URLs which differ only in the encoding of a reserved character may differ in meaning.

However, we also need to consider quoted path components, and be careful about how to convert a quoted-path-component to an unquoted path segment which may contain percent-encoded characters.  I think there are two choices for the behaviour here:

 1. when converting a quoted-path-component to a segment, percent-encode characters which are not valid `pchar`s.  All other characters should be left unconverted.
 2. converting a quoted-path-component to a segment, percent-encode characters which are `reserved`.  All other characters should be left unconverted.

You would choose option 1 if you believed a character which doesn't need to be quoted should behave the same whether quoted or not.  So, for example, the URLs `http://foo/bar:baz` and `http://foo/"bar:baz"` should be the same; and we should not normalize the latter to `http://foo/bar%3Abaz`.

You would choose option 2 if you believed that quoting is equivalent to percent-encoding all reserved characters.  So, for example, the URLs `http://foo/bar%3Abaz` and `http://foo/"bar:baz"` should be the same; and we should not normalize `http://foo/bar:baz` to either.

I think existing dhall-haskell behaviour is somewhat inconsistent between the two options: `http://foo/bar:baz` and `http://foo/bar%3Abaz` are not-necessarily-equivalent URLs which both normalize to `http://foo/"bar:baz"`.

A possibly-related fact is that `http://foo/foo%bar` normalizes to `http://foo/"fooºr"`, but `http://foo/bar%foo` normalizes to `http://foo/"bar%foo"`. It seems weird to percent-decode only if we have valid hex characters.

Therefore, the algorithm for formatting a URL should be:

 - [unreserved characters](https://tools.ietf.org/html/rfc3986#section-2.3) (ie `ALPHA / DIGIT / "-" / "." / "_" / "~"`) should not be encoded, and should be decoded if present in encoded form
 - [reserved characters](https://tools.ietf.org/html/rfc3986#section-2.2) (ie `gen-delims / sub-delims`) should have encoding preserved as-is
 - characters which are neither reserved nor unreserved will only ever be in
   encoded form (except for `%` in its role as percent-escaping); this should be
   preserved
 - quoted path segments should be converted to unquoted path segments by percent-encoding EITHER:
   - any character which is not a `pchar`, and leaving every other character in raw form, or
   - any character which is not `ALPHA / DIGIT / "-" / "." / "_" / "~"`
 - finally, all percent-encoding should use [uppercase hexadecimal digits](https://tools.ietf.org/html/rfc3986#section-2.1).

Note that Dhall currently accepts some ill-formed URLs: such as `http://foo/%3` which has an incomplete percent-encoding sequence.  I'm not sure if we need to cater for these or if we can just start rejecting them.

----
Some examples (which could inform test cases):

| Input  | Desired output | Notes |
| ------------- | ------------- |-----|
| `http://x/y%7ez`  | `http://x/y~z` | `~` is unreserved so we should always decode it |
| `http://x/y%3bz`  | `http://x/y%3Bz` | `;` is reserved so we should not decode it; however we should convert its encoding to uppercase |
| `http://x/y:z`  | `http://x/y:z`  | unencoded reserved characters should remain unencoded |
| `http://x/"y:z"`  | `http://x/y:z` or `http://x/y%3Az`, depending on our choice | see discussion above; `:` is a `pchar` but is reserved |
| `http://x/y@z`  | `http://x/y@z` | |
| `http://x/y%z`  | Error: invalid input | this is currently parsed by Dhall's ABNF but I think we should reject it as invalid |
| `http://x/"y%z"`  | `http://x/y%25z` | percents will always have to be encoded |
| `http://x/"y☃z"`  | `http://x/y%E2%98%83z` | non-ASCII characters should be percent-encoded as UTF-8 |

----

Finally, there are a couple of bugs in the current implementation which would be made moot by preferring percent-encoding: `echo 'http://foo/bar%22baz' | dhall format` produces the invalid output `http://foo/"bar"baz"`, and `echo 'http://foo/foo%2fbar' | dhall format` produces the invalid output `http://foo/"foo/bar"` (it is invalid because `/` is not a `quoted-path-character`).

**Comment by Gabriel439** [comment]
@philandstuff: Yeah, I will fix this soon.  Regarding option 1 vs. option 2, I plan to go with option 2 (percent-encoded all reserved characters)

**Comment by philandstuff** [comment]
I may be able to work on it myself since #1103 is no longer blocking me
