### ISSUE TITLE
Replace the `X` newtype with an empty data type?

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#1120]
We currently have `newtype X = X { forall a. a }`. Is there any reason to not just have `data X` (with no constructors)? With this, we can use `EmptyCase` to witness that there are no cases. This came up when writing a `Lift X` instance. While it's not possible to even create an `X`, I can technically pattern match on one, though I have to throw an error (the classic "the impossible happened").

**Comment by Gabriel439** [comment]
@ocharles: Why do you need to throw an `error` when you pattern match on an `X`?  Couldn't you do:

```haskell
example :: X -> Integer
example (X x) = x
```

**Comment by ocharles** [comment]
I have to construct an `X` in `Lift`:

```haskell
instance Lift X where
  lift _impossible = ? what goes here ?
```

The RHS of `lift` should be a Template Haskell expression that constructs an `X` based on the `X` in the LHS. But we know that there is no LHS, so the definition of `lift` should be:

```haskell
instance Lift X where lift = \case {}
```

That is, there are no possible pattern matches.

**Comment by Gabriel439** [comment]
@ocharles: Wouldn't it be:

```
instance Lift X where
    lift (X impossible) = impossible
```

**Comment by ocharles** [comment]
Oh, I guess that would work. Still unclear what the advantage of this approach is though.

**Comment by Gabriel439** [comment]
@ocharles: They're both equivalent.  The reason I like the `forall` formulation is that you get `absurd` for free (it's just the accessor function):

```haskell
newtype X = X { absurd :: forall a . a }
```

**Comment by ocharles** [comment]
Right but you don't get to have empty pattern matches, which I guess I
prefer. I think this answers my question though, and gives me a way to
write that Lift better

**Comment by sjakobi** [comment]
Why don't we simply use `Void` and get rid of a bit of custom code?

**Comment by Gabriel439** [comment]
@sjakobi: Back when I added `X` it was because `Void` was missing some instances that would be orphan instances.  If that's been fixed then we can remove `X` in factor of `Void` (or just make `X` a type synonym for `Void`)
