### ISSUE TITLE
Undocumented bottoms in surprising places

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1138]
While running the new `normalizeWithMIsConsistentWithNormalize` property test again with a larger `maxSuccesses`, I was surprised by an error from `normalizeWithM` which I previously believed to be total!

The problematic expression boils down to `<>.x || Type`. The standard requires the two arguments of `||` to be tested for equivalence if neither normalizes to `True` or `False`, and `normalizeWithM` uses `judgmentallyEqual` for this. `judgmentallyEqual` is just `convEmpty` and `convEmpty` relies on `eval`, which uses `error` in a few cases, for example `<>.x`.

As Haskell functions are generally expected to be total, I think it would be good to document the partiality of `eval` and the functions that rely on `eval`.

Currently the documentation of e.g. `normalize` even incorrectly claims totality:

https://github.com/dhall-lang/dhall-haskell/blob/e40e8477301e9965ea6f8571a88933ed81b371f4/dhall/src/Dhall/Core.hs#L1189-L1199

Regarding `normalizeWithM`, I wonder whether it could perform the equivalence tests without using `eval`, since it can take care of `beta-normalization` on its own.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1140

**Comment by sjakobi** [comment]
Regarding removing the use of `judgmentallyEqual` in `normalizeWithM`: I initially thought that a replacement could be as simple as

```
alphaEquivalent e0 e1 = alphaNormalize e0 == alphaNormalize e1
```

Now I see that, to compare `DoubleLit`s, we rely on `Dhall.Binary.encode`, so I think that a proper `equivalent` function for this usecase would involve a fair amount of boilerplate – unless anyone knows a way to do this with less boilerplate?!

**Comment by Gabriel439** [comment]
@sjakobi: I wouldn't worry too much about it.  I'd like to move towards less variants of core utilities.  If the partial normalization really bothers people then we could always make `Dhall.Eval` total, but so far nobody has complained.
