### ISSUE TITLE
`--documents` flag for dhall-to-yaml that doesn't require a `List`

### ISSUE THREAD

**Issue by alexhumphreys** [dhall-lang/dhall-haskell#1151]
This is probably the kind of thing that'll eventually be covered in the [dhall-cookbook](https://discourse.dhall-lang.org/t/topic-ideas-for-dhall-cookbook/48/4) but I thought I'd ask here to see if anyone's run into this yet.

I want to render a bunch of yaml documents (I think that's the word for the objects deliniated by `---` in a long yaml file) that have mostly the same type except for one field, which I don't know the type of.

My first attempt was to put them in a list and use `--documents`:

```
let knownStuff =
{ known1 = "1"
, known2 = "baz"
}

in
[ knownStuff // { values = { foo = 3 } }
, knownStuff // { values = { bar = "baz" } } -- doesn't work
]
```

But this errors with `Error: List elements should all have the same type`

I guess the alternative is to have multiple files like:

```
-- knownStuff.dhall
{ known1 = "1"
, known2 = "baz"
}
```
```
-- foo.dhall
./knownStuff.dhall //
{ values = { foo = 3 } }
```
```
-- bar.dhall
./knownStuff.dhall //
{ values = { bar = "baz" } }
```

And a script like:
```
#!/bin/bash
cat foo.dhall | dhall-to-yaml
cat bar.dhall | dhall-to-yaml
```

That works, but it goes from a single file and command, to something that's a bunch of files, and a full script to handle them. That example's pretty minimal, but my actual use case is like 10 files per deployment environment (dev/staging/production).

Maybe I missed some super easy way to achieve this, if so I'd appreciate any tips. 

But if not, I'm wondering if this is a common enough problem that `dhall-to-yaml` could handle it somehow? I'm just riffing here, but something like `--documents` that takes a record and only outputs the values of the top fields?

The current `--documents` flag that takes a `List` is nice and intuitive, and I can imagine any solution to this that's not some funky generic types thing would not be as slick, but thought I'd ask anyway :)

**Comment by Gabriel439** [comment]
@alexhumphreys: You can still do this using your original approach to put them all in one list.  `dhall-to-{json,yaml}` support three ways to unify disparate JSON types:

* Wrap each possibility in a different union alternative:

  ```dhall
    let knownStuff = { known1 = "1", known2 = "baz" }

    let Example = < Foo : { foo : Natural } | Bar : { bar : Text } >

    in  [ knownStuff ⫽ { values = Example.Foo { foo = 3 } }
        , knownStuff ⫽ { values = Example.Bar { bar = "baz" } }
        ]
  ```

* Make record fields optional and enable the `--omitNull` flag:

  ```dhall
    let knownStuff = { known1 = "1", known2 = "baz" }

    in  [ knownStuff ⫽ { values = { foo = Some 3, bar = None Text } }
        , knownStuff ⫽ { values = { bar = Some "baz", foo = None Natural } }
        ]
  ```

* (In the next release): use a general `JSON` type which can hold arbitrary JSON values

  ```dhall
    let JSON =
          https://raw.githubusercontent.com/dhall-lang/dhall-lang/788029db6b65ba660bc89b9c23d4df3f9cecccbc/Prelude/JSON/package.dhall

    let knownStuff = { known1 = "1", known2 = "baz" }

    in  [ knownStuff ⫽ { values = JSON.object (toMap { foo = JSON.number 3.0 }) }
        , knownStuff ⫽ { values = JSON.object (toMap { bar = JSON.string "baz" }) }
        ]
  ```

All three of these produce the same result:

```bash
$ dhall-to-yaml --documents --omitNull <<< './test.dhall' 
values:
  foo: 3
known2: baz
known1: '1'

---
values:
  bar: baz
known2: baz
known1: '1'
```

The first two approaches are already documented here:

* [`dhall-json` tutorial](https://hackage.haskell.org/package/dhall-json-1.3.0/docs/Dhall-JSON.html)

The last approach hasn't been released yet, but it would also be documented in that same module when published to Hackage.  Until then, you can read the documentation here:

* [`JSON/Type` from Prelude](https://github.com/dhall-lang/dhall-lang/blob/master/Prelude/JSON/Type)

**Comment by alexhumphreys** [comment]
That `JSON` type looks like what I'm after, Nice! Especially as making a union that could cover my particular scenario would be way more effort than the multiple files approach above.

Does that work for nested objects too? Something like:
```
JSON.object (toMap { foo = JSON.object { bar = JSON.number 3.0 } })
```
to
```
foo:
  bar: 3
```

**Comment by Gabriel439** [comment]
@alexbiehl: Yes, the `JSON` type supports arbitrarily nested values

**Comment by alexhumphreys** [comment]
Sounds good! I'll close this so. Thank you :)

**Comment by Gabriel439** [comment]
@alexhumphreys: You're welcome! 🙂
