### ISSUE TITLE
dhall-format breaking hash

### ISSUE THREAD

**Issue by amarrella** [dhall-lang/dhall-haskell#1158]
Hi :) 

I have an issue when i try to freeze a dhall import and then formatting, the hash starts with a 4 digit number and a sequence of letters, and this seems to cause the formatter to break down the hash :( 

In particular my hash looks like this next to the import:
```1630c1cb84680beda4654fa955644b94f9afd3c8b176a84f90272417a679f6f3```

In my .cache/dhall/ I see two files:
```
1630c1cb84680beda4654fa955644b94f9afd3c8b176a84f90272417a679f6f3
12201630c1cb84680beda4654fa955644b94f9afd3c8b176a84f90272417a679f6f3
```

So far so good, everything works fine.

Then i run `find . -name '*.dhall' | xargs -n 1 dhall lint --inplace`

And the sha breaks down in the file as:
```dhall
1630
c1cb84680beda4654fa955644b94f9afd3c8b176a84f90272417a679f6f3
```
To give more color: this import is with some headers and authorization, not sure if it's relevant to the formatter.

Can you help me debug the issue and work around it (besides not freezing those imports or not formatting after freezing?).

Thanks :) And thanks again for this fantastic project, I'm excited for v9.0.0!

**Comment by EggBaconAndSpam** [comment]
Hey!
Did you perhaps forget the `sha256:` prefix? The import should look like this:
`./import sha256:1630c1cb84680beda4654fa955644b94f9afd3c8b176a84f90272417a679f6f3`

**Comment by amarrella** [comment]
Hey :) the `sha256:` prefix is there, sorry it wasn't clear in my examples. Also the hash was simply generated by `dhall freeze`, i didn't put it there manually

**Comment by EggBaconAndSpam** [comment]
That is strange...

**Comment by amarrella** [comment]
The import (before formatting) looks like 
```dhall
let settings =
      https://raw.githubusercontent.com/my-org/my-private-repository/master/config/shared/iam/Kubernetes.dhall using [ { header =
                                                                                                                             "Authorization"
                                                                                                                         , value =
                                                                                                                             "token ${env:GITHUB_TOKEN as Text}"
                                                                                                                         }
                                                                                                                       ] sha256:1630c1cb84680beda4654fa955644b94f9afd3c8b176a84f90272417a679f6f3


```

and after formatting looks like
```dhall
let settings =
      https://raw.githubusercontent.com/my-org/my-private-repository/master/config/shared/iam/Kubernetes.dhall using   [ { header =
                                                                                                                               "Authorization"
                                                                                                                           , value =
                                                                                                                               "token ${env:GITHUB_TOKEN as Text}"
                                                                                                                           }
                                                                                                                         ]
                                                                                                                         sha256
                                                                                                                       : 1630
                                                                                                                         c1cb84680beda4654fa955644b94f9afd3c8b176a84f90272417a679f6f3


```

**Comment by EggBaconAndSpam** [comment]
Does the non-linted version still typecheck?

**Comment by amarrella** [comment]
> Does the non-linted version still typecheck?

Yes it works fine both with `dhall <<<` and `dhall-to-yaml <<<`
 (v.1.24.0)

I think it's the pretty printer not recognizing the hash as a string because it begins with a number and is not quoted (quoting doesn't work with hashes i think).

**Comment by EggBaconAndSpam** [comment]
I'm out of ideas...
Since it uses the same parser as `dhall` (i.e. running the type-checker), we know that `dhall format` works with the correct AST. This means that the pretty-printing must be messing things up. But then, how could we possibly end up with a line break **before the colon**?

```
  sha256
: 1630
  c1cb84...
```

For reference, this is the `Pretty` instance of `ImportHashed`:
```
instance Pretty ImportHashed where
    pretty (ImportHashed  Nothing p) =
      Pretty.pretty p
    pretty (ImportHashed (Just h) p) =
      Pretty.pretty p <> " sha256:" <> Pretty.pretty (show h)```

**Comment by amarrella** [comment]
Sorry it was a bad copy paste or github messing up. It wasn't before the colon, but after, aligned with the "number" (1630)

**Comment by amarrella** [comment]
Just checked again with my laptop (was on my phone), the indentation in the code snippet and what you posted is exactly what happens
```
  sha256
: 1630
  c1cb84...
```

You can try yourself by running `dhall format --inplace` on this file 
https://gist.github.com/amarrella/d7305bbf80e71dfdcab227cabff86447

**Comment by Gabriel439** [comment]
I can't reproduce this on `master` and I believe this is a duplicate of https://github.com/dhall-lang/dhall-haskell/issues/1093

https://github.com/dhall-lang/dhall-haskell/issues/1093#issuecomment-510625993 explains what the issue was and how it was fixed

**Comment by amarrella** [comment]
I confirm that the current master works fine :) 
Now I'm even more excited for the next release!
I'll close the issue, thanks! :)

**Comment by Gabriel439** [comment]
@amarrella: You're welcome! :slightly_smiling_face:
