### ISSUE TITLE
dhall-lsp-server tarball for macOS: Missing version number

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1165]
The tarball for macOS should probably also have the `1.0.0` version string:

![image](https://user-images.githubusercontent.com/3664523/62030586-af688300-b1e5-11e9-9d58-182c31e44cba.png)

See https://github.com/dhall-lang/dhall-haskell/releases/tag/1.25.0

**Comment by f-f** [comment]
Fix up in #1166
