### ISSUE TITLE
Release notes on dhall 1.25.0 have standard version typo

### ISSUE THREAD

**Issue by philandstuff** [dhall-lang/dhall-haskell#1168]
Hooray for [1.25.0](https://github.com/dhall-lang/dhall-haskell/releases/tag/1.25.0)!

However, it says it supports version 8.0.0 of the standard, only to rattle off a list of 9.0.0 features such as `toMap`...

Is it too late to edit the release notes?

**Comment by Gabriel439** [comment]
It is not too late!  🙂 

I just updated them to fix the mentioned version.  I'll also put up a pull request tonight to update the `CHANGELOG` file

**Comment by philandstuff** [comment]
Your fix updated the text, but didn't update the URL to the standard version release.

**Comment by Gabriel439** [comment]
Whoops!  Fixed

**Comment by Gabriel439** [comment]
Fix to the `CHANGELOG` here: https://github.com/dhall-lang/dhall-haskell/pull/1180
