### ISSUE TITLE
`dhall-lsp-server version` returns 0.0.1.1

### ISSUE THREAD

**Issue by amarrella** [dhall-lang/dhall-haskell#1170]
Is it supposed to be 1.0.0 instead?

https://github.com/dhall-lang/dhall-haskell/blob/master/dhall-lsp-server/app/Main.hs#L59

**Comment by EggBaconAndSpam** [comment]
Yes, thanks for pointing this out! It is high time we replaced the hard-coded version string.

**Comment by EggBaconAndSpam** [comment]
Fixed in #1171.
