### ISSUE TITLE
`--file` resolves paths differently between `dhall` and `dhall-to-yaml`

### ISSUE THREAD

**Issue by alexhumphreys** [dhall-lang/dhall-haskell#1183]
Possibly related to https://github.com/dhall-lang/dhall-haskell/pull/1004

I have a directory structure like so:
```
$ tree foo
foo
├── one.dhall
└── two.dhall
```
With the two files:
```
$ cat foo/one.dhall
{ foo = "bar" }

$ cat foo/two.dhall
let foo = ./one.dhall

in
{ baz = "buz"
, foo = foo.foo
}
```

When I use `dhall --file` to evaluate `foo/two.dhall` it works correctly:

```
$ dhall --file foo/two.dhall
{ baz = "buz", foo = "bar" }
```

And when I try the same thing with `dhall-to-yaml --file` it fails to resolve the imports:
```
$ dhall-to-yaml --file foo/two.dhall

↳ ./one.dhall

Error: Missing file ./one.dhall

1│           ./one.dhall
2│ 
```
Copying the file to the directory I'm running these commands from results in `dhall-to-yaml` resolving the `./one.dhall` import.
```
$ cp foo/one.dhall .
$ dhall-to-yaml --file foo/two.dhall
foo: bar
baz: buz
```
I'd expect these to behave the same, but if there's a reason they shouldn't that's cool too.

**Comment by sjakobi** [comment]
I can reproduce this and I'm working on a fix.
