### ISSUE TITLE
Implement "Treat multi-lets as syntactic sugar"

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1185]
* Standard change: https://github.com/dhall-lang/dhall-lang/pull/618
* Acceptance test update: https://github.com/dhall-lang/dhall-lang/pull/673
* Multi-let was originally introduced in https://github.com/dhall-lang/dhall-haskell/pull/675

I assume that we want to go back to representing `let` as

    Let Text (Maybe (Expr s a)) (Expr s a) (Expr s a)

?

Is anyone already working on a patch? Otherwise I'd make one.

**Comment by Gabriel439** [comment]
@sjakobi: Go for it!

Note that the original reason for preserving that information was so that `dhall format` would not change the nesting of `let` expressions, but it's probably fine if it's opinionated about removing nesting from them.

**Comment by sjakobi** [comment]
For the record: I have disabled the testcase from https://github.com/dhall-lang/dhall-lang/pull/673 in https://github.com/dhall-lang/dhall-haskell/pull/1200 for now.

**Comment by sjakobi** [comment]
Now that I've read https://github.com/dhall-lang/dhall-lang/issues/615 it seems to me that a _principled_ solution would involve adding a parameter for the format of `let` to `Expr`. That parameter could be `NonEmpty` for multi-let for the parser and pretty-printer, and `Identity` for normalization, binary encoding etc.

That seems like a rather large change to me, so I'm wondering whether it's worth doing it before @AndrasKovacs' NbE work changes everything anyway.

Maybe we should just try to fix the binary encoding (https://github.com/dhall-lang/dhall-lang/pull/673) for now, and have another look once the dust around NbE has settled.

Thoughts?

**Comment by Gabriel439** [comment]
@sjakobi: I think it's simpler to just drop multi-`let`s from the AST completely.  The only thing we were using them for is preserving nested `let` expressions from the original source when formatting.  However, I don't think users care much for that feature and they'd probably be fine with `dhall format` automatically merging nested `let` expressions into a single `let` expression.

**Comment by EggBaconAndSpam** [comment]
Plus, if we really wanted to, we could always recover whether or not a given let binder had a trailing `in` by inspecting the source code annotation (`Src`).
