### ISSUE TITLE
Use dhall-to-cabal to maintain package cabal config files

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-haskell#1189]
I think we could do some dogfooding to leverage the great work of @ocharles and others maintainers with dhall-to-cabal.

It would suppose some discipline to not update the cabal file (the generated cabal file has a warning at the beginning) but the dhall one and build the tool locally (there is no precompiled packages for now) to regenerate the cabal file each time (and remember to do it!) so i think there would have to be a consensus between maintainers.

**Comment by ocharles** [comment]
I think https://github.com/dhall-lang/dhall-to-cabal/issues/123 might be a prerequisite for this. You want to be able to use `cabal`, but without having to think about regenerating files.

**Comment by Profpatsch** [comment]
Uuuuh, can you describe how one would bootstrap dhall without an already existing dhall compiler then?

**Comment by ocharles** [comment]
There's not really a bootstrapping problem. You just need `dhall-to-cabal`, which depends on a `dhall` *release*, and releases would have generated `.cabal` files.

**Comment by Gabriel439** [comment]
So technically isn't a bootstrapping problem, but in my view most of the value of building against another library is testing the trunk branch before it has been released.  If we only test published releases we're not catching bugs early enough.

**Comment by Profpatsch** [comment]
> There's not really a bootstrapping problem. You just need `dhall-to-cabal`, which depends on a `dhall` _release_, and releases would have generated `.cabal` files. `dhall-to-cabal` can be supplied in the Nix shell.

That’s exactly the definition of a bootstrapping problem. You cannot create a release without having some compilation output (the cabal file in that case), so you cannot bootstrap dhall from source (the cabal dhall file) anymore.

**Comment by quasicomputational** [comment]
`dhall-to-cabal` itself is dogfooding and it hasn't been bad so far.

Mucking around with the generated `.cabal` output has occasionally been a necessity. When that has happened, the changes are pretty easy; the output of `dhall-to-cabal` isn't obscure. I don't think it'd happen much, if at all, so long as this repository sticks to released versions of `dhall-to-cabal`.

**Comment by Gabriel439** [comment]
I'm going to close this as I don't plan on doing this, and after further though I agree with @Profpatsch that there are concerns about bootstrapping issues if we do this.
