### ISSUE TITLE
Empty alternative does not trigger JSON name preservation

### ISSUE THREAD

**Issue by wezm** [dhall-lang/dhall-haskell#1201]
Possibly related to https://github.com/dhall-lang/dhall-haskell/pull/1080, https://github.com/dhall-lang/dhall-haskell/issues/1145

As per the `dhall-json` tests `nesting{0,1}`, the use of a record with fields `field`, `nesting`, and `contents` is supposed to preserve the name of the union alternative alongside the value, either Inline or Nested. However the behaviour does not trigger when the union alternative is empty.

For example, with this input:

```dhall
let Example = < Left : { foo : Natural } | Middle | Right : { bar : Bool } >

let Nesting = < Inline | Nested : Text >

in  { field    = "name"
    , nesting  = Nesting.Inline
    , contents = Example.Middle
    }
```

I expect this output:

```json
{ "name": "Middle" }
```

But instead get:

```json
{ "field": "name", "contents": "Middle", "nesting": "Inline" }
```

I have added a test case for this in my fork but I'm not familiar enough with Haskell to implement a fix: https://github.com/dhall-lang/dhall-haskell/compare/master...wezm:json-nesting-empty-alternative

**Comment by sjakobi** [comment]
Thanks for the testcase! That expected output looks very reasonable.

We should also handle empty alternatives with the `Nested` layout. For

```
let Example = < Left : { foo : Natural } | Middle | Right : { bar : Bool } >

let Nesting = < Inline | Nested : Text >

in  { field    = "name"
    , nesting  = Nesting.Nested "value"
    , contents = Example.Middle
    }
```

I'd propose generating `{ "name": "Middle", "value": {} }` by default. With `--omitEmpty` that would become just `{ "name": "Middle" }`.

I'll submit a PR soon.

**Comment by sjakobi** [comment]
> I'd propose generating `{ "name": "Middle", "value": {} }` by default.

Actually that should probably be `{ "name": "Middle", "value": null }` since `Nested` already supports non-record alternatives like `< Foo : Text >.Foo "bar"`.

@Gabriel439 Thoughts?

**Comment by Gabriel439** [comment]
@sjakobi: Yeah, `null` seems safer.  Also, `null` can be combined with the `--omitNull` flag so that the `value` field can be filtered out entirely at the user's discretion
