### ISSUE TITLE
(assert : NaN === NaN) fails

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1224]
This is one of the testcases introduced in https://github.com/dhall-lang/dhall-lang/pull/698.

This boils down to

```
> THalf nan == THalf nan
False
```

I have opened https://github.com/well-typed/cborg/issues/211 to find out whether the bug is on our part or on `cborg`'s.

**Comment by ocharles** [comment]
But NaN /= NaN in general, at least for IEEE Doubles. So this seems correct to me

**Comment by sjakobi** [comment]
[Dhall defines equivalence via the binary encoding](https://github.com/dhall-lang/dhall-lang/tree/master/standard#equivalence), where we have deterministic sequence of bytes for `NaN`.

**Comment by ocharles** [comment]
Ah yes. I had a feeling we were doing things differently, thanks for the clarification.

**Comment by Gabriel439** [comment]
I think it's simpler to fix this by comparing the bytes.  I have a fix up for this here: https://github.com/dhall-lang/dhall-haskell/pull/1231
