### ISSUE TITLE
UnionInputType documentation refers to it being a monoid, but it's not an instance of Monoid

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#1227]
I think it's a bit confusing that the documentation writes:

> The UnionInputType monoid allows you to build an InputType injector for a Dhall record.

Yet `UnionInputType` is only an instance of `Contravariant`.

Either we fix the documentation, or we make it an instance of `Monoid`. Even if `UnionInputType` is not a Haskell `Monoid`, we don't even expose the monoidal structure (I see no unit element).

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1230
