### ISSUE TITLE
Tutorial section "Import integrity" differs from observed behavior

### ISSUE THREAD

**Issue by doublescale** [dhall-lang/dhall-haskell#1234]
Dhall.Tutorial describes in the section about [Import integrity](http://hackage.haskell.org/package/dhall-1.25.0/docs/Dhall-Tutorial.html#g:16) a way to check that an imported value stays constant.
It shows an example that triggers "Error: Import integrity check failed" because of a hash mismatch when the imported value is changed.

However, with the current caching behavior, this doesn't always seem to happen.
Once the "correct" import has been evaluated once, changing the imported value has no effect anymore because the hashed value is looked up from the cache, if I understand it correctly.
According to my tests, this happened between 1.16.1 and 1.17.0 .

I assume that this is the desired behavior now and that the tutorial hasn't been updated to reflect this change yet.
If that is the case, is there a way to get similar checks in the current version, as the tutorial demonstrates?
It would be useful to use these hash annotations as part of a "snapshot test", to see if an imported value behaves the same after a refactoring.
Perhaps the cache-reading could be disabled by some flag?

([Here is the relevant section in the Dhall.Tutorial source](https://github.com/dhall-lang/dhall-haskell/blob/8c3db821dbc0ad8cfd01d09a58e88126bda717ab/dhall/src/Dhall/Tutorial.hs#L1520))

**Comment by sjakobi** [comment]
I agree that with the current behavior it can appear that configuration was changed while the result still contains the old cached value. I'd prefer `dhall`s default behavior to check the hashes.

> Perhaps the cache-reading could be disabled by some flag?

You can prevent `dhall` from using the cache by setting `XDG_CACHE_HOME=/var/empty`.

**Comment by Gabriel439** [comment]
Ah, yes, the documentation is wrong because it predates changes to the standard.  If the import is protected by an integrity check then it always succeeds until the integrity check is changed or removed.  You can even do `missing sha256:…` and the import will succeed if that hash is cached.

I'll fix the documentation soon to reflect that behavior

**Comment by Gabriel439** [comment]
Documentation fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1247

**Comment by doublescale** [comment]
Thank you for the helpful answers and fixes!

Setting `XDG_CACHE_HOME` does indeed make my use-case work, though it does take much longer, as is expected.
With the caching disabled, are remote resources still only requested once (as described [here](https://github.com/dhall-lang/dhall-lang/wiki/Safety-guarantees#cross-site-scripting-xss)), or can it result in multiple downloads from the same URL?

**Comment by Gabriel439** [comment]
@doublescale: When caching is disabled remote resources are fetched once per evaluation.  In other words, the interpreter will still cache remote imports in memory if the same expression imports a given URL more than once, but will not cache remote imports on disk if caching is disabled
