### ISSUE TITLE
:help command in repl

### ISSUE THREAD

**Issue by ejconlon** [dhall-lang/dhall-haskell#1236]
Hi all, loving the project! As a new dhall learner, I opened the repl and was presented with a cryptic turnstyle. The next thing I typed was "let x = 1" and got a strange error about unexpected end of input. I had no idea where to go from there. I think there are probably some easy wins here to help new users along!

I propose that we add a `:help` command and advertise it on repl startup. This could function like ghci :help by printing all available magic commands and their descriptions. Additionally, we can print simple information about particular repl quirks, like how let bindings need the magic :let command. I am imagining an experience like

```
$ dhall repl
Type :help for more information.
⊢ :help
Welcome to dhall repl vX.Y.Z!
Type any of some subset of expressions, blah blah, use the :let command blah blah.
The following commands are available:
:help - blah
:let - blah
:quit - blah
```

This seems pretty easy to add and I'd be happy to do so if we find agreement. Thanks!

**Comment by Gabriel439** [comment]
@ejconlon: Sorry, I was out on vacation.  I just wanted to say thank you for doing this! :slightly_smiling_face:
