### ISSUE TITLE
dhall-to-bash not recursively declare variables

### ISSUE THREAD

**Issue by contrun** [dhall-lang/dhall-haskell#1239]
`dhall-to-bash --declare var <<< '[1, 2, 3]'` works.

`dhall-to-bash --declare var <<< '{foo = "bar"}'` also works.

But this `dhall-to-bash --declare var <<< '[{foo = "bar"}]'` does not work.

Can we make `dhall-to-bash --declare` works for any `List X` whenever it works for X?

**Comment by sjakobi** [comment]
Apparently `bash` [doesn't really support arrays of arrays](https://stackoverflow.com/a/12317983/1013393).

What output would you expect?

**Comment by contrun** [comment]
I expect to get an indexed array variable of associative array variables. Thank you for the link. It seems impossible.
