### ISSUE TITLE
[CLI] format vs. lint - there should be only one

### ISSUE THREAD

**Issue by vvv** [dhall-lang/dhall-haskell#1252]
Help message makes me think that `dhall lint` and `dhall format` are pretty much identical.  This complicates the CLI.
```
$ dhall lint -h
Usage: dhall lint [--inplace FILE]
  Improve Dhall code

Available options:
  --inplace FILE           Modify the specified file in-place
  -h,--help                Show this help text
$ 
$ dhall format -h
Usage: dhall format [--check] [--inplace FILE]
  Formatter for the Dhall language

Available options:
  --check                  Only check if the input is formatted
  --inplace FILE           Modify the specified file in-place
  -h,--help                Show this help text
```
Can we let less useful command (`dhall lint`) go?

**Comment by ari-becker** [comment]
> @vvv: All `dhall` commands format the output. The only difference is that `dhall format` is essentially a no-op (i.e. the only thing it does is format the output).
> 
> However, we don't want to get rid of `dhall lint` because it is very useful. For example, one of the things that `dhall lint` does is migrate deprecated language idioms to their equivalent newer idioms, which allows us to remove deprecated language features earlier than we normally would. It also improves code in other ways (like removing unnecessary `let` bindings).

@Gabriel439 a suggestion - perhaps add a sentence or two in the `dhall lint` help section explaining that linting removes dead code and modernizes the rest? It's not like the functionality of the `lint` command changes *that* frequently, and it's starting to turn into a frequently asked question.

**Comment by vvv** [comment]
> a suggestion - perhaps add a sentence or two in the dhall lint help section explaining that linting removes dead code and modernizes the rest?

Yes please.  The problem is that it's impossible to discern from `--help` output alone the difference between these two commands.

The user thinks: “They look identical, but why there are two of them?  Which one should I use?”

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1264
