### ISSUE TITLE
Error injecting and interpreting lists

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-haskell#1254]
Hi, i've observed that `Dhall.inject` and `Dhall.input Dhall.auto` doesn't behave correctly with lists. In a ghci session with 0b3dae7
```
> pretty $ (Dhall.embed Dhall.inject) (["x"] :: [Text])
"[ \"x\" ] : Text"
> pretty $ (Dhall.embed Dhall.inject) ([1] :: [Int])
"[ +1 ] : Integer"
> pretty $ (Dhall.embed Dhall.inject) ([[1]] :: [[Int]])
"[ [ +1 ] : Integer ] : List Integer"
> Dhall.input Dhall.auto $ "[ +1 ]"
*** Exception:
 Error [0m: Expression doesn't match annotation

- Integer
+ List …

1│[ +1 ] : Integer

(input):1:1
> Dhall.input (Dhall.list Dhall.integer) $ "[ +1 ]" -- using explicit types works
[1]
```
It should be:
```
> pretty $ (Dhall.embed Dhall.inject) (["x"] :: [Text])
"[ \"x\" ] : List Text"
> pretty $ (Dhall.embed Dhall.inject) ([1] :: [Int])
"[ +1 ] : List Integer"
> pretty $ (Dhall.embed Dhall.inject) ([[1]] :: [[Int]])
"[ [ +1 ] : List Integer ] : List (List Integer)"
> Dhall.input Dhall.auto $ "[ +1 ]"
[1]
```

**Comment by jneira** [comment]
Maybe i'm missing something obvious but 
```
> fmap denote $  Dhall.Parser.exprFromText "" "[+1] : List Integer"
Right (Annot (ListLit Nothing (fromList [IntegerLit 1])) (App List Integer))
```
shoudn't be:
```
> fmap denote $  Dhall.Parser.exprFromText "" "[+1] : List Integer"
Right (ListLit (App List Integer) (fromList [IntegerLit 1]))
```
?

**Comment by sjakobi** [comment]
Looks like a regression due to https://github.com/dhall-lang/dhall-haskell/commit/0ee6ce6f6fd2afe9d227fa9d58a3e61fced33c21.

**Comment by jneira** [comment]
I've detected it merging the last version of `dhall-to-cabal` in `dhall-to-etlas` (talking about dogfooding :wink:)
I think we should add some tests over inject and interpret:
* A roundtrip between them?
* Some fixed tests with the basic types, including lists, a record and an union

**Comment by sjakobi** [comment]
I have a WIP patch (https://github.com/dhall-lang/dhall-haskell/commit/dd7ffcbacecf0d8b316c1e96c18a37d8acb66583) that fixes `inject`.

To fix `input`, I believe [`sequence`](https://github.com/dhall-lang/dhall-haskell/blob/0b3dae74965c792fdbe2951ed582835aac41268e/dhall/src/Dhall.hs#L762-L773) has to be changed but I haven't yet found out how…

**Comment by Gabriel439** [comment]
@sjakobi: The `input` issue isn't a `dhall` bug.  It's just due to GHC's defaulting rules.  If you don't specify the type of the expected result then GHC defaults to `Integer`

```
>>> :set -Wall
>>> Dhall.input Dhall.auto "[ +1 ]"

<interactive>:22:13: warning: [-Wtype-defaults]
    • Defaulting the following constraints to type ‘Integer’
        (Interpret a0)
          arising from a use of ‘auto’ at <interactive>:22:13-22
        (Show a0) arising from a use of ‘print’ at <interactive>:22:1-31
    • In the first argument of ‘input’, namely ‘auto’
      In the first argument of ‘GHC.GHCi.ghciStepIO ::
                                  forall a. IO a -> IO a’, namely
        ‘(input auto "[ +1 ]")’
      In a stmt of an interactive GHCi command:
        it <- GHC.GHCi.ghciStepIO :: forall a. IO a -> IO a
              (input auto "[ +1 ]")
*** Exception: 
Error: Expression doesn't match annotation

- Integer
+ List …

1│ [ +1 ] : Integer

(input):1:1
```

... and you can also reproduce with an explicit type annotation, too:

```
*Dhall> Dhall.input Dhall.auto "[ +1 ]" :: IO Integer
*** Exception: 
Error: Expression doesn't match annotation

- Integer
+ List …

1│ [ +1 ] : Integer

(input):1:1

```

**Comment by Gabriel439** [comment]
@sjakobi: I have a fix up here: https://github.com/dhall-lang/dhall-haskell/pull/1261

**Comment by Gabriel439** [comment]
@jneira: Also, we can only do property tests on a per-Haskell-type basis, but we can't do a property test over all possible Dhall expressions because the type of the corresponding Haskell value changes depending on the Dhall expression
