### ISSUE TITLE
Add automated tests for dhall-lsp-server

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1258]
dhall-lsp-server currently only has a few broken doctests – it would be nice if at least parts of the functionality were covered by automated tests.

I'm not sure what these tests should look like – I imagine testing at the protocol-level: Check that, given a certain request, dhall-lsp-server responds with the right message. How do other lsp servers set up their tests?

CC @EggBaconAndSpam, @PanAeon

**Comment by Gabriel439** [comment]
@sjakobi: It looks like the `lsp-test` package can be used for testing this: http://hackage.haskell.org/package/lsp-test-0.6.1.0/docs/Language-Haskell-LSP-Test.html

**Comment by sjakobi** [comment]
@mujx has started to work on this. See https://github.com/dhall-lang/dhall-haskell/pull/1396.

**Comment by Gabriel439** [comment]
Fixed by https://github.com/dhall-lang/dhall-haskell/pull/1396
