### ISSUE TITLE
dhall and dhall-to-json react to --file differently

### ISSUE THREAD

**Issue by vvv** [dhall-lang/dhall-haskell#1268]
Not sure if this is a problem, but I've noticed an irregularity in how `dhall` and `dhall-to-json` handle files with relative imports passed via `--file` option.

```
$ echo '< txt : Text | num : Natural >' >/tmp/X.dhall
$ echo 'let X = ./X.dhall in [ X.txt "abc", X.num 7 ]' >/tmp/xs.dhall
```

When this file is passed to `dhall` or `dhall-to-json` via stdin, and PWD != /tmp, the command will expectedly fail:
```
$ cd
$ dhall </tmp/xs.dhall

↳ ./X.dhall

Error: Missing file ./X.dhall

1│         ./X.dhall

(stdin):1:9
$ dhall-to-json </tmp/xs.dhall


↳ ./X.dhall

Error: Missing file ./X.dhall

1│         ./X.dhall

(stdin):1:9
```
This behaviour is covered in the [FAQ](https://github.com/dhall-lang/dhall-lang/wiki/Frequently-Asked-Questions-%28FAQ%29#imports-relative-to-my-top-level-file-are-not-working).

However, `dhall --file` will succeed, while `dhall-to-json --file` will not:
```
$ dhall --file /tmp/xs.dhall
[ < num : Natural | txt : Text >.txt "abc"
, < num : Natural | txt : Text >.num 7
]
$ dhall-to-json --file /tmp/xs.dhall


↳ ./X.dhall

Error: Missing file ./X.dhall

1│         ./X.dhall

/tmp/xs.dhall:1:9
```

**Comment by sjakobi** [comment]
Duplicate of #1183?! Should have been fixed in https://github.com/dhall-lang/dhall-haskell/commit/1700fa72d8d849e1be0af23498dc86b68c85b8be.

**Comment by Gabriel439** [comment]
Yeah, this was recently fixed and the fix will be available in the next release (1.26.0)

**Comment by vvv** [comment]
> Duplicate of #1183?!

@sjakobi Indeed.  Sorry for the noise.

**Comment by sjakobi** [comment]
Thanks for report @vvv! :+1: It could have been a previously unknown issues.
