### ISSUE TITLE
Cheatsheet

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-haskell#127]
I have created a cheatsheet, maybe it should be included in the official documentation as a quick overview of syntax & features.

The builtin functions are not listed yet, but should be added in a concise way.

https://github.com/Profpatsch/blog/blob/master/notes/dhall-cheatsheet.md

**Comment by Gabriel439** [comment]
Right now I'm working on setting up a `dhall-lang` GitHub project, with a language-agnostic repository where documentation like this can go (related to #8)

**Comment by Gabriel439** [comment]
@Profpatsch: Alright, I started to set up a language-agnostic repository here:

https://github.com/dhall-lang/dhall-lang

If you like, you can open a pull request to add the cheat sheet to that repository and reference it from the `README`

**Comment by Profpatsch** [comment]
https://github.com/dhall-lang/dhall-lang/pull/1
