### ISSUE TITLE
Why doesn't "dhall type" support imports?

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1277]
Currently it outputs

```
Import resolution is disabled
```

when the given expression contains an import.

Is there a reason why it shouldn't try to resolve imports?

**Comment by Gabriel439** [comment]
@sjakobi: No good reason.  When I initially added the `dhall {resolve,type,normalize}` subcommands the rationale was that each would only execute one phase of the interpretation pipeline, but in retrospect I think it was a mistake and think that `dhall type` should resolve imports like you request
