### ISSUE TITLE
[Feature Request] CLI flag to censor record values while printing error

### ISSUE THREAD

**Issue by ari-becker** [dhall-lang/dhall-haskell#1294]
I have some shell scripts which grab some sensitive strings from Dhall expressions. When the Dhall expressions succeed at parsing, the contents of these sensitive strings are hidden away from the user by the shell script.

However, if there is an error while parsing the expression, the CLI prints out the contents of what it did parse... including the sensitive strings.

Allowing the addition of a `--censor-on-error` (or similar) flag to censor the values of the records in the case of an error would improve the security of the scripts while only marginally making the error more difficult to diagnose.

**Comment by Gabriel439** [comment]
@ari-becker: Note that during the parsing phase we'd need to disable the display of the source code entirely, because during the parsing phase the code only exists as a string and hasn't been marshalled into a record yet

**Comment by ari-becker** [comment]
@Gabriel439 I still think that's reasonable. I've gotten to the point of familiarity where I can fix the vast majority of issues in my expressions with nothing more than a line number to tell me where I need to pay closer attention. Giving up the display of more source code than needed is still a net benefit.

**Comment by Gabriel439** [comment]
@ari-becker: I have an initial fix up here just for parsing errors: https://github.com/dhall-lang/dhall-haskell/pull/1312

I'll try to follow up with a second one for type errors

**Comment by ari-becker** [comment]
@Gabriel439 fantastic! Thank you!

**Comment by Gabriel439** [comment]
The final fix for type errors is up here: https://github.com/dhall-lang/dhall-haskell/pull/1329
