### ISSUE TITLE
pretty-printer mixes tabs and spaces

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-haskell#1296]
In dhall `1.25.0`, the pretty-printer outputs tabs followed by spaces, which leads to broken output depending on tab width.

For example looking at the text file in the chromium browser: 
![screenshot](https://user-images.githubusercontent.com/3153638/64521701-c6c48100-d2f8-11e9-91b1-4a37bdb3bed1.png)
The `cmd` is dedented too much.

My impression was that it is universally agreed on that mixing tabs and spaces is a bad idea. The only argument pro tabs is storage space, but that’s trivially alleviated by applying compression (e.g. when transferred via http or stored in git).

**Comment by Gabriel439** [comment]
@Profpatsch: Can you give a minimal reproducing example?  As far as I can tell the pretty-printer should not be emitting any tabs at all, with the exception of multi-line string literals that were indented using tabs (which it will preserve)

**Comment by Profpatsch** [comment]
Hm, I indeed cannot reproduce with plain `dhall format`, it must be a bug in `dhall-mode` for Emacs.
