### ISSUE TITLE
Why does `dhall type` normalize the inferred type?

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1300]
https://github.com/dhall-lang/dhall-haskell/blob/37f819c8bb8e7f7e772945cb9bde76b14110772a/dhall/src/Dhall/Main.hs#L485

It seems to me that – [since not all inferred types are normalized](https://github.com/dhall-lang/dhall-lang/issues/724) – this might cause `dhall type` to output types that don't (exactly) match the standard.

So I'm wondering why we apply this additional normalization…

**Comment by Gabriel439** [comment]
@sjakobi: I don't remember the reason, but if I had to guess it was probably to work around inferred types that weren't already normalized (i.e. the problem you're trying to address in https://github.com/dhall-lang/dhall-lang/issues/724)

I'd be fine with removing it if you want
