### ISSUE TITLE
Type-checking without output

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1323]
I'd like to have an option for `dhall type` that prevents it from outputting the type. Errors should however be printed as usual.

Potential use cases:
* Fast type-checking during development, similar to `ghc -fno-code`
* Benchmarking the typechecker

Regarding the name: `--no-print-type` is the best I've come up with so far.

**Comment by Gabriel439** [comment]
I suggest `--quiet`
