### ISSUE TITLE
dhall-nix: support for several dhall versions ? 

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#1333]
The fact that dhall-nix strictly follows a single dhall version has quite a negative impact on `dhallToNix` on the  nixos front.

As a matter of fact, `dhall-nix` is usually marked as broken. It is currently the case both in the stable (19.03) and unstable channel of nixos.

I guess there are other solutions to this problem. One that comes to mind is to take the pain and use a combination of dhallToNix, dhall, dhall-nix that works locally (but then why is  `dhallToNix` available in nixpkgs if it is broken most of the time).

Something that should be easy to use seems to require quite a complex setup to get going.

**Comment by Gabriel439** [comment]
@PierreR: Can you explain why it is currently marked broken?  As far as I know, the latest Hackage release of `dhall-nix` builds against the latest Hackage release of `dhall`

**Comment by PierreR** [comment]
@Gabriel439 dhall-nix is broken on nixos unstable currently because it used the latest LTS stackage version for dhall (1.24.0) with the latest hackage version of dhall-nix (which requires dhall-1.26).
In stable it is broken because `hnix` is broken (unsuitable megaparsec version).

I guess the solution would be to have `dhall-nix` on stackage.

**Comment by PierreR** [comment]
Could I use the `dhall-nix` binary directly instead of fetching it from nixpkgs ?

```
λ ~ → readlink -f $(which dhall-to-nix)
/nix/store/a2mm7j18ki8kg14w4dx2cr07bf704bq0-dhall-nix-1.1.8/bin/dhall-to-nix
```

I don't know how to do this. I have tried the following but without success:
```
self: super:

let dhall-nix = import /nix/store/a2mm7j18ki8kg14w4dx2cr07bf704bq0-dhall-nix-1.1.8;
in
{
    dhallToNix = super.dhallToNix.override {inherit dhall-nix;};
}
```

**Comment by Gabriel439** [comment]
@PierreR: I can't add `dhall-nix` to Stackage because `hnix` doesn't build on Stackage, yet.  See: https://github.com/commercialhaskell/stackage/blob/f5d1776c9c5d311469f889d251faa97bdd62e625/build-constraints.yaml#L1021

This repository also already provides a derivation for building `dhall-nix` which you can use directly, like this:

```nix
let
  nixpkgs = builtins.fetchTarball {
    url    = "https://github.com/NixOS/nixpkgs/archive/ed9745e096852ed812d322c25ced48001e984b8e.tar.gz";  # Recent `master`
    sha256 = "1hiwr8a4j5ypgnpjnqdldxypdyswdpw1njdnbrwf7lsbvw1nx8hw";
  };

  pkgs = import nixpkgs { config = {}; };

  dhall-haskell-src = pkgs.fetchFromGitHub {
    owner = "dhall-lang";

    repo = "dhall-haskell";

    rev = "65710954cf8f2217b9959cd73a5d8a40d03aab39";  #  Version 1.26.0

    sha256 = "0dql1wiis6apqg06qqmdv05ja5f0zimsmaqw6w4kpgyk9gnsw421";

    fetchSubmodules = true;
  };

  dhall-haskell = import dhall-haskell-src;

in
  dhall-haskell.dhall-nix
```

**Comment by PierreR** [comment]
@Gabriel439 After a long wait it eventually fails with:
```
4 out of 1107 tests failed (28.05s)
Test suite tasty: FAIL
Test suite logged to: dist/test/dhall-1.26.0-tasty.log
Test suite doctest: RUNNING...

when making flags consistent: warning:
    -O conflicts with --interactive; -O ignored.
/build/dhall-sdist/src/Dhall/Tutorial.hs:447: failure in expression `input auto "https://raw.githubusercontent.com/dhall-lang/dhall-haskell/18e4e9a18dc53271146df3ccf5b4177c3552236b/examples/True" :: IO Bool'
expected: "True"
 but got: "*** Exception: "
          "\ESC[1;31mError\ESC[0m: Remote host not found"
          ""
          "URL: https://raw.githubusercontent.com/dhall-lang/dhall-haskell/18e4e9a18dc53271146df3ccf5b4177c3552236b/examples/True"
          ""

Examples: 140  Tried: 134  Errors: 0  Failures: 1
Test suite doctest: FAIL
Test suite logged to: dist/test/dhall-1.26.0-doctest.log
0 of 2 test suites (0 of 2 test cases) passed.
```

**Comment by PierreR** [comment]
@Gabriel439 is there an easy way to use `dontCheck` for `dhall-nix` and all its dependencies ?

**Comment by PierreR** [comment]
There is no way to make this easier by just using `/nix/store/a2mm7j18ki8kg14w4dx2cr07bf704bq0-dhall-nix-1.1.8` (the cached executable in the nix store that is easy to install) inside .nix file ?

**Comment by Gabriel439** [comment]
@PierreR: You can turn off the tests like this:

```
let
  nixpkgs = builtins.fetchTarball {
    url    = "https://github.com/NixOS/nixpkgs/archive/ed9745e096852ed812d322c25ced48001e984b8e.tar.gz";
    sha256 = "1hiwr8a4j5ypgnpjnqdldxypdyswdpw1njdnbrwf7lsbvw1nx8hw";
  };

  pkgs = import nixpkgs { config = {}; };

  dhall-haskell-src = pkgs.fetchFromGitHub {
    owner = "dhall-lang";

    repo = "dhall-haskell";

    rev = "65710954cf8f2217b9959cd73a5d8a40d03aab39";

    sha256 = "0dql1wiis6apqg06qqmdv05ja5f0zimsmaqw6w4kpgyk9gnsw421";

    fetchSubmodules = true;
  };

  dhall-haskell = import dhall-haskell-src;

in
  pkgs.haskell.lib.dontCheck dhall-haskell.dhall-nix
```

I don't recommend writing Nix code that depends on a `/nix/store` path

**Comment by PierreR** [comment]
@Gabriel439 I might be missing something but I have tried this already.  It doesn't seem to work because the failing tests are on `dhall`, not `dhall-nix`. If I understand this correctly the `dontCheck` call only applies to `dhall-nix`, not its `dhall` dependency.

**Comment by Gabriel439** [comment]
@PierreR: Then you'll have to do one of the following:

* Fix `nixpkgs` to use the correct versions of `dhall`
* Fork or somehow reuse the logic from `dhall-haskell` to disable tests for `dhall`
* Turn off sandboxed builds locally (so that it will let `dhall` make HTTP requests as part of its test suite)

However, I think this is starting to stray far from the original issue of support for several dhall versions

**Comment by PierreR** [comment]
@Gabriel439 Thanks for your help.

Indeed I feel this thread exemplifies the original issue. It is almost impossible to use `dhallToNix` in a straightforward way (and be sure it will just work).

Not sure what I should make of that. I should probably go and use nix as a configuration format in my case (and go and use Dhall for more insensitive use cases related to Kubernetes for instance). That is quite a shame as I like to start with simple use case. Somehow the whole ecosystem behind nixpkgs is showing its limit in this case.

**Comment by Gabriel439** [comment]
I think the right solution is to open an issue against Nixpkgs to fix `dhall-to-nix`.  There's no reason for `dhall-to-nix` to be broken on Nixpkgs when the latest version of `dhall` and `dhall-nix` on Hackage build together.

**Comment by PierreR** [comment]
Yep you are right. This is a nixpkgs issue not a dhall one. I will close the issue and try to PR on nixpkgs. Thanks !

**Comment by Gabriel439** [comment]
@PierreR: You're welcome! 🙂

**Comment by PierreR** [comment]
@Gabriel439 this is a ridiculous question but what should I use to read a dhall file with dhallToNix ?
```
 let  unstablepkgs = import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz) {};
  conf = builtins.readFile /vagrant/config/box.dhall; # import is the same
  configData = unstablepkgs.dhallToNix config;
```
is failing with `error: value is a set while a string was expected`
while this is working fine:
```
let
  unstablepkgs = import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz) {};
  configData = unstablepkgs.dhallToNix ''
    {
      userName = "John Doe"
    } 
  '';
in
```

**Comment by PierreR** [comment]
For anyone interested I have ended up using this overlay:
```
self: super:

{
    haskellPackages = super.haskellPackages.override  {
     overrides = hself: hsuper:
       {
           dhall-nix = hsuper.dhall-nix.override { dhall = hsuper.dhall_1_26_0; };
       };
    };
}
```
with
```
self: super:

{
    haskellPackages = super.haskellPackages.override  {
     overrides = hself: hsuper:
       {
           dhall-nix = hsuper.dhall-nix.override { dhall = hsuper.dhall_1_26_0; };
       };
    };
}
```
It is a bit brittle because it depends on the current state of the unstable nixpkgs channel but can be improved by using a pinned nixpkgs version instead.
