### ISSUE TITLE
Dhall linux binaries seem broken in 1.26.1

### ISSUE THREAD

**Issue by amarrella** [dhall-lang/dhall-haskell#1345]
The linux binaries (i tested dhall and dhall-json) seem broken for the 1.26.1 release. 
If I run `tar -xj` on the files the result is a directory with some json files.

EDIT: also dhall-lsp-server, dhall-bash and dhall-nix for linux seem broken. So it's probably the overall linux build.

**Comment by Gabriel439** [comment]
It should be fixed now.  The issue is that I wrote a release script to automate uploading them and the script accidentally uploaded the docker images instead of the Linux archives.

**Comment by amarrella** [comment]
Didn't test on Linux yet but I quickly downloaded them and they look like the right binaries now! Thank you!

**Comment by Gabriel439** [comment]
@amarrella: You're welcome! 🙂
