### ISSUE TITLE
Relative file imports have different behavior depending on whether or not a hash is provided

### ISSUE THREAD

**Issue by TravisWhitaker** [dhall-lang/dhall-haskell#1351]
I'm seeing this behavior with dhall 1.24.0.

Suppose I have a directory setup like this:

```
$ cat a.dhall
{ b = ./b.dhall }
$ cat b.dhall
True
```

I can evaluate a.dhall like this:

```
$ dhall <<< './a.dhall'
{ b = True }
```

But not like this:

```
$ dhall --file ./a.dhall

↳ ./a.dhall/b.dhall

Error: Missing file /Users/traviswhitaker/sources/dingas/a.dhall/b.dhall

1:       ./b.dhall 

(stdin):1:7
```

This is a bit strange; a.dhall looks like it's being treated as a directory. Indeed, if I pretend that b.dhall is one dir up, it works:

```
$ cat a.dhall
{ b = ../b.dhall }
$ dhall --file a.dhall 
{ b = True }
```

Going back to `./b.dhall`, if I add b.dhall's hash with:

```
$ dhall freeze --all --inplace a.dhall 
$ cat a.dhall 
{ b =
    ./b.dhall sha256:27abdeddfe8503496adeb623466caa47da5f63abd2bc6fa19f6cfcb73ecfed70
}
```

This also makes evalutation with `--file` work:

```
$ dhall --file a.dhall 
{ b = True }
```

I wasn't able to find anything like this in the docs and it seems like accidental behavior. Am I just missing something? Does `dhall freeze` put all hashed files in the expression cache?

**Comment by sjakobi** [comment]
Can you try `v1.26.1`? `--file` used to get relative imports wrong, but that should be fixed.

**Comment by TravisWhitaker** [comment]
Ah, sure enough this works as expected with 1.26. Thanks for the heads up.
