### ISSUE TITLE
Disable auto formating on dhall freeze

### ISSUE THREAD

**Issue by DrSensor** [dhall-lang/dhall-haskell#1356]
Just noticed that `dhall freeze --inplace $file` will also auto format the code. I think this is unnecessary, especially when the auto formatter still doesn't retain the comments (https://github.com/dhall-lang/dhall-haskell/issues/145).

> plus I don't want to reformat my code for several reasons

**Comment by sjakobi** [comment]
> plus I don't want to reformat my code for several reasons

I think this enhancement could be quite a bit of work and extra maintenance burden, so it would be good to understand why you don't want your code to be reformatted.

**Comment by DrSensor** [comment]
Mostly because of these 2 reasons:

- Some peoples (including myself) don't agree with the style format since its hugely differ from the output which is JSON
- The auto-formatter not yet stable (the comment being removed)

I'm thinking to write a small shell script for this 🤔. I will let you know if it works.

**Comment by Gabriel439** [comment]
@DrSensor: You might want to try the `dhall-lsp-server` (paired with the corresponding VS code plugin).  I believe it supports freezing individual imports without reformatting the code (although I might be wrong)

**Comment by DrSensor** [comment]
@Gabriel439 thanks, it works great!

However, in doesn't work when there is this kind of error :thinking: 
![Screenshot_20191001_101117](https://user-images.githubusercontent.com/4953069/65931388-a5584000-e433-11e9-8ba6-37fbe635a4ef.png)

**Comment by Gabriel439** [comment]
@DrSensor: I believe this will fix your issue: https://github.com/dhall-lang/dhall-haskell/pull/1369

Would it be possible for you to build an `dhall-lsp-server` executable off of that branch to see if it resolves the problem for you?

**Comment by DrSensor** [comment]
Sorry but I'm not familiar with Haskell's build system. I can try it on the weekend though (no promise)

**Comment by sjakobi** [comment]
> Sorry but I'm not familiar with Haskell's build system.

It shouldn't be hard to set up:

1. Install `stack`: http://docs.haskellstack.org/en/stable/README/#how-to-install
2. Run `stack install dhall-lsp-server` in this repo.

**Comment by DrSensor** [comment]
@sjakobi is there a guide on how to produce the binary executable without installing it to the host machine?

**Comment by sjakobi** [comment]
If you just `stack build dhall-lsp-server`, you can then get the path to the executable with

    stack exec -- which dhall-lsp-server

**Comment by Profpatsch** [comment]
> * Some peoples (including myself) don't agree with the style format since its hugely differ from the output which is JSON

Even if there is disagreement, uniformly, automatically formatted code is a huge win for a language (see: golang, rust) and we should enforce formatting if possible.

> * The auto-formatter not yet stable (the comment being removed)

That is indeed a big problem, and we should solve it ASAP, it’s hindering adoption.

**Comment by Gabriel439** [comment]
Closing as I believe that using the language server is the solution to this issue
