### ISSUE TITLE
Unnecessary parentheses around toMap

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1358]
```dhall
toMap { a = True } # toMap { b = True }
```
is formatted as

```dhall
(toMap { a = True }) # (toMap { b = True })
```

Is there a good reason for this?

Otherwise we should probably get rid of the parentheses.

**Comment by Gabriel439** [comment]
@sjakobi: There isn't a reason for this.  I checked the code and `toMap` without a type annotation is definitely being formatted with the wrong precedence.  I have a fix up for this here: https://github.com/dhall-lang/dhall-haskell/pull/1360
