### ISSUE TITLE
Issues with type inference for annotated list literals

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1359]
1. It's redundant to check the kind of the type parameter starting in line 606. Type-inference for `List` already covers this. https://github.com/dhall-lang/dhall-haskell/blob/d6d3943fe5360a38a2b4ad3268b4588faefde410/dhall/src/Dhall/TypeCheck.hs#L597-L613

2. The subsequent check of the list elements is both wrong and apparently dead code, according to coverage reports. We're trying to compare the type of an element with the full `List X` annotation. If these were equivalent, the list would actually by ill-typed!

https://github.com/dhall-lang/dhall-haskell/blob/d6d3943fe5360a38a2b4ad3268b4588faefde410/dhall/src/Dhall/TypeCheck.hs#L615-L624

I think it would be best to completely get rid of the element processing here, but I'm not sure what would be the best way…

A) Pattern match for `ListLit (Just _) []` and throw a `BrokenInvariant` error.
B) Redefine the `ListLit` constructor to contain a `Either (Expr s a) (NonEmptySeq (Expr s a))`
C) Make separate constructors for empty and non-empty lists.

**Comment by Gabriel439** [comment]
@sjakobi: I think the right way to do this is to make separate constructors for empty and non-empty lists

**Comment by sjakobi** [comment]
I think creating separate constructors might be a slightly larger undertaking than I initially thought. In particular, we'd want (need?!) a data type for non-empty sequences:

* The [`nonempty-containers` package](http://hackage.haskell.org/package/nonempty-containers) contains a `NESeq` variant of `Seq` that would fit the bill nicely. The problem is that `nonempty-containers` currently requires `base >= 4.9` (i.e. `GHC >= 8.0`) and `containers >= 5.9`. I suspect that that support for GHC-7.10 could be added, but it seems like quite a bit of work and additional maintenance burden. The situation is probably similar with support for `containers-5.6`. The maintainer is a Dhall user though, which might facilitate support requests…

* There's [another package](http://hackage.haskell.org/package/non-empty-sequence) offering a `NonEmptySeq`, that would be compatible, but it's much less polished and lacks some functionality, most notably `mapWithIndex` and `reverse`.

Ultimately I wonder whether we're still committed to supporting GHC-7.10, even though Eta's future seems increasingly [uncertain](https://github.com/dhall-lang/dhall-haskell/pull/1248#issuecomment-535665535).

**Comment by Gabriel439** [comment]
In that case, maybe just add the `BrokenInvariant` assertion for now

**Comment by sjakobi** [comment]
I've updated #1359 to add a `ListLitInvariant` type error.
