### ISSUE TITLE
Type-checking record literals is slightly redundant

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1361]
It seems that we can get rid of the `case tT'` here. After two `loop`s, there's no way that we have anything but a `Const`.

https://github.com/dhall-lang/dhall-haskell/blob/d6d3943fe5360a38a2b4ad3268b4588faefde410/dhall/src/Dhall/TypeCheck.hs#L761-L773

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1362
