### ISSUE TITLE
Misplaced note regarding "builders"

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1364]
https://github.com/dhall-lang/dhall-haskell/blob/24bb8b7faef4ca925c443e3a1faf34efef2dca27/dhall/src/Dhall/Core.hs#L844-L853

I think this describes functionality that lives in `Dhall.Pretty.Internal` these days, but I'm not sure whether it should be cut-and-pasted verbatim.

**Comment by Gabriel439** [comment]
Yeah, this belongs in `Dhall.Pretty.Internal`, except replacing "builder" with "pretty printer"
