### ISSUE TITLE
Add `--version` option to dhall-to-yaml executable

### ISSUE THREAD

**Issue by vrom911** [dhall-lang/dhall-haskell#1371]
It seems that it somehow misses it:

```shell
$ dhall-to-yaml --version
Invalid option `--version'

Usage: dhall-to-yaml [--explain] [--omitNull | --omitEmpty] [--documents]
                     [--quoted] [[--key ARG] [--value ARG] | --noMaps]
                     [--file FILE]
  Compile Dhall to YAML
```
the same for short `-v`.

`dhall-to-json` executable has this option though

```shell
$ dhall-to-json --version
1.4.0
```

**Comment by sjakobi** [comment]
This was fixed in https://github.com/dhall-lang/dhall-haskell/commit/b556a65644ed5d656d0a75a795db7bf18518cb67.

**Comment by sjakobi** [comment]
Ah, no. It was already fixed in https://github.com/dhall-lang/dhall-haskell/pull/1199 and is released.
