### ISSUE TITLE
Why isn't () an instance of Interpret?

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1378]
It's an instance of Inject though…

**Comment by Gabriel439** [comment]
@sjakobi: No good reason.  This is probably just an oversight on my part

**Comment by sjakobi** [comment]
We do already have `unit`, which should be re-used to define the instance. This should be a very small patch.

https://github.com/dhall-lang/dhall-haskell/blob/613a44d512819820ac2df803ebb050751c387825/dhall/src/Dhall.hs#L796-L803

**Comment by jiegillet** [comment]
Very small patch sounds like a job for me!

**Comment by sjakobi** [comment]
Fixed in cc3e50e. Thank you @jiegillet! :)
