### ISSUE TITLE
Word* types should be translated to Natural, not Integer

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1381]
https://github.com/dhall-lang/dhall-haskell/blob/045ed99ae53ff8404699fd73cc4286f71cda8807/dhall/src/Dhall.hs#L1520-L1546

`Natural` allows more operations, so that should be more useful.

For completeness, an instance for `Word` should probably be added too.

**Comment by jiegillet** [comment]
Mind if I grab that one? I'm new to Dhall so it might take me a while but I'd like to learn.

**Comment by sjakobi** [comment]
@jiegillet Sounds great! :) Do ask questions in case you get stuck!

Suggestions for better documentation are also very welcome!

**Comment by sjakobi** [comment]
Fixed by #1381. Thanks @jiegillet! :)
