### ISSUE TITLE
A command to annotate let-bindings with their types

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1384]
I often want type annotations on my let-bindings but am too lazy to write them. It would be nice if there was a command that would infer these annotations and add them.

I'm not sure whether this could be an option (`--annotate`? `--annotate-lets`?) for `dhall format` or whether it should be a separate command. Or maybe it could even be added to `dhall lint`!?

**Comment by f-f** [comment]
I'd say this is the kind of things that `dhall lint` should do, but on the other hand you might want to opt in to this feature only, so having it in `format` might make sense? (Or both?)

**Comment by sjakobi** [comment]
I think it makes some sense as an option for `dhall lint` – it's fundamentally just another edit pass on the syntax tree. In `dhall format` we don't do anything like that.

It would be quite a bit more intricate than any existing lints. I think that we could get the types by extending `typeWithA` to return the resulting `Context` together with the type. We should probably look at how `dhall-lsp-server` looks up types in the AST though.

If this command relies on `typeWithA` though, any added type annotations will normalized and not in a form which most users would write themselves…

**Comment by Gabriel439** [comment]
Note the Dhall language server provides support for this!

As a general rule of thumb, I think if there isn't an obvious right choice or it requires user input or interaction to decide which things to annotate then it's better to handle via the language server.  `dhall lint` should be more opinionated

**Comment by Profpatsch** [comment]
Agree that this should be part of the language server, not `lint`.

**Comment by sjakobi** [comment]
Thanks for the feedback! :)

I guess I should get used to using `dhall-lsp-server` then. :)
