### ISSUE TITLE
strictText is inefficient

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1390]
https://github.com/dhall-lang/dhall-haskell/blob/6a8e7e12cc95376dfd9ddfba673e7d0ae0d3b191/dhall/src/Dhall.hs#L745-L746

Since `TextLit`s are internally represented using strict `Text`, there's no need to go through `lazyText` here. In fact it should be the other way round: `lazyText` should use `strictText`.

**Comment by Rizary** [comment]
@sjakobi I tried to switch between lazyText and strictText, how to test it?

**Comment by sjakobi** [comment]
> @sjakobi I tried to switch between lazyText and strictText, how to test it?

I think the existing doctests are good enough. I don't see what could go wrong here.

Thanks for the patch! :)

**Comment by Gabriel439** [comment]
Fixed by #1401
