### ISSUE TITLE
Marshalling HashMap

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1394]
In analogy to #1391 and #1392, we could also have support for `Interpret`ing and `Inject`ing `HashMap`s from `unordered-containers`.

~~Not sure whether we should also add a `newtype RecordHashMap` for `Inject`ing to `Record`.~~

**Comment by sjakobi** [comment]
> Not sure whether we should also add a `newtype RecordHashMap` for `Inject`ing to `Record`.

As pointed out in https://github.com/dhall-lang/dhall-haskell/issues/1392#issuecomment-540872043, `Inject` wouldn't currently allow this.

**Comment by tenniscp25** [comment]
I would love to work on this.

**Comment by Gabriel439** [comment]
@tenniscp25: Yeah, feel free to go for it! 🙂

**Comment by jiegillet** [comment]
Please check #1412, especially the tests, it should be very simple to add one  for `HashMap`s

**Comment by tenniscp25** [comment]
Thanks @jiegillet. Your tests help a lot.

Btw, do I need to run tests with nix? I tried running `stack test` from master and got a few errors.

**Comment by jiegillet** [comment]
You don't need nix. Make sure that you have the latest version of `stack` first.

**Comment by tenniscp25** [comment]
I'm using stack 2.1.3, which to my understanding is the latest version. 🤔

**Comment by tenniscp25** [comment]
Sorry. It was my fault. I forgot to update the git submodule.. 😞

**Comment by tenniscp25** [comment]
Are these doctest errors expected?

https://gist.github.com/tenniscp25/7622e5d199ac1f9292c9fe1f3e664dab

**Comment by sjakobi** [comment]
> Are these doctest errors expected?

The doctests in `dhall` are supposed to work – at least with `stack`. I believe we have some in `dhall-lsp-server` that are broken. @quasicomputational might be able to help with your errors.

For now I suggest you just use `stack test dhall:tasty`.

**Comment by Gabriel439** [comment]
Fixed by #1426
