### ISSUE TITLE
Marshalling Set and HashSet

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1395]
Both could be marshalled to `List`, similarly to `vector`:

https://github.com/dhall-lang/dhall-haskell/blob/d172e4b677ba7141eade7468cd7911dace9c024f/dhall/src/Dhall.hs#L792-L793
https://github.com/dhall-lang/dhall-haskell/blob/d172e4b677ba7141eade7468cd7911dace9c024f/dhall/src/Dhall.hs#L933-L934
https://github.com/dhall-lang/dhall-haskell/blob/d172e4b677ba7141eade7468cd7911dace9c024f/dhall/src/Dhall.hs#L1654-L1655

The behaviour for duplicates should be documented.

**Comment by Gabriel439** [comment]
@sjakobi: Actually, I was thinking about removing the dependency on `unordered-containers` (since we only use it for `reservedIdentifiers` to keep Dhall's dependency footprint smaller

**Comment by sjakobi** [comment]
@Gabriel439 That wouldn't really achieve a lot – we also have a bunch of transitive dependencies on `unordered-containers` via

* aeson
* aeson-pretty
* cborg-json
* charset
* parsers
* semigroupoids
* serialise

So we might as well keep the direct dependency and provide the instances.

**Comment by Gabriel439** [comment]
Oh yeah, never mind then

**Comment by jiegillet** [comment]
Allow me :)

**Comment by neongreen** [comment]
Should the `Set` one error out if the list contains duplicates?

**Comment by sjakobi** [comment]
> Should the `Set` one error out if the list contains duplicates?

I don't think so. I'd expect a user who interprets a `List` with set-semantics not to care about duplicates.

I'd be interested in different opinions on this though.

In principle, we can support different semantics by offering more than one `Type` for decoding `Set`s.

**Comment by jiegillet** [comment]
I agree, using `Set` means you don't want duplicates. 
@neongreen are you working on this one?

**Comment by neongreen** [comment]
I'm not working on it. I do have a local implementation, though, and I'm
curious whether it will match the official one.

For my usecase I *do* want to get an error if the list contains duplicates
– because it would signal that I certainly made an error when writing my
config.

I have no idea whether throwing an error would break any other usecases.
Probably yes.

**Comment by sjakobi** [comment]
Interesting! Feel free to make a PR @neongreen. Seems like we want to support both variants.

**Comment by sjakobi** [comment]
> For my usecase I *do* want to get an error if the list contains duplicates – because it would signal that I certainly made an error when writing my config.

Can you explain your scenario a bit? If you're interpreting a `List` as a set, why does it matter if there are duplicates?

**Comment by Gabriel439** [comment]
@neongreen: This would not break other use cases.  We already support custom errors when marshalling Dhall code to Haskell, so they are not limited to just type mismatch errors

**Comment by sjakobi** [comment]
I think in any case we can have both a `setFromList` and a `setFromDistinctList` `Type`.

I wonder which of the two an `Interpret` instance should use though. The recently added added instance for `Map` allows duplicates, but I'm not sure whether that's the right default.

**Comment by sjakobi** [comment]
#1395 fixed this.

@jiegillet FYI if you include `Fixes #XYZ` in a commit message, the addressed issue is closed automatically when the commit is merged.
