### ISSUE TITLE
Release frequency?

### ISSUE THREAD

**Issue by neongreen** [dhall-lang/dhall-haskell#1402]
dhall-haskell is moving very fast, with quality-of-life improvements being merged every several days. How do you decide on cutoff points for minor releases?

**Comment by Gabriel439** [comment]
@neongreen: We can release as often as users request.  Usually by default in the absence of any specific user request or important bug fix I cut a release once per month

**Comment by Gabriel439** [comment]
Also, in case people are wondering what happens if we cut a release of the Haskell implementation before the standard: it's totally fine.  We  just need to communicate that the implementation contains changes from an upcoming unreleased standard version.

**Comment by neongreen** [comment]
Ok, I'll keep this in mind. Thanks!

**Comment by Gabriel439** [comment]
@neongreen: You're welcome!
