### ISSUE TITLE
Extend the --no-cache flag to `dhall type` and `dhall resolve`

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1404]
https://github.com/dhall-lang/dhall-haskell/commit/37f819c8bb8e7f7e772945cb9bde76b14110772a introduced a `--no-cache` flag that prevents protected imports from being read from the (α-normalized) semantic cache. `dhall resolve` and `dhall type` should get the same option.

**Comment by jneira** [comment]
Maybe we should avoid the warning about missing cache if user are using that flag?

**Comment by sjakobi** [comment]
> Maybe we should avoid the warning about missing cache if user are using that flag?

That seems reasonable! Note that with `--no-cache`, `dhall` will still try to use the semi-semantic cache, e.g. `~/.cache/dhall-haskell` but I think it's fine to turn off the warning completely.

For reference, the warning was introduced in https://github.com/dhall-lang/dhall-haskell/commit/08747af8d30a9bcf11490076cdfc8eeca0e6c305.

**Comment by jneira** [comment]
btw, @sjakobi congrats for your great work with dhall-haskell in general and for help hacktoberfest participants

**Comment by jneira** [comment]
> For reference, the warning was introduced in 08747af

Yeah, turn off it could be done [at top level](https://github.com/dhall-lang/dhall-haskell/commit/08747af8d30a9bcf11490076cdfc8eeca0e6c305#diff-8b90d8c877d17f7f37345acc07a1b1f8R411), where we have at hand the command and flags

**Comment by sjakobi** [comment]
Fixed by #1434, #1436 and #1441. Thank you @StevenXL! :)
