### ISSUE TITLE
Install prpposed action quickly get out of date

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#1406]
The README proposes to install dhall via nix using this link:
https://hydra.dhall-lang.org/job/dhall-haskell/master/linux-dhall/latest

This is working fine except that the link gets quickly out of date. For instance this was the proposed action a few weeks ago:
```
nix-env -i /nix/store/sx3c3mcmmbrxdx1140fgywxklj3fazpj-dhall-1.26.1
```
This is not working anymore but the new path (/nix/store/ql1l2z00psx9f4ic0cynnbmb3c1nd66f-dhall-1.26.1) will.

Would it be possible to have an action that keeps working for the duration of the release (I don't quite understand why the same release would suddenly lead to a new storing path) ?

**Comment by sjakobi** [comment]
@PierreR These are the `master` builds:

> You can also install pre-built Linux binaries for **master** using Nix using Nix's channel mechanism by following the instructions at this link:

Don't you want to use official releases?

**Comment by PierreR** [comment]
@sjakobi That works nicely thanks.
