### ISSUE TITLE
toMap expects a record value

### ISSUE THREAD

**Issue by 9999years** [dhall-lang/dhall-haskell#1408]
The error message for `toMap {}` is confusing:

```
$ echo 'toMap {}' | dhall

Use "dhall --explain" for detailed errors

Error: ❰toMap❱ expects a record value

1│ toMap {}

(stdin):1:1
```

Proposal: Add `Did you mean 'toMap {=}'? '{}' is the empty record *type*, and '{=}' is the empty record *value*.`

**Comment by sjakobi** [comment]
I'm not sure whether we should make a special case for the empty record case.

We could definitely add `toMap {}` as an example to the error message though. We already have this for `merge`:

https://github.com/dhall-lang/dhall-haskell/blob/3e5cb3492222a1e10de07896ed9689df0a94dbd0/dhall/src/Dhall/TypeCheck.hs#L2917-L2930
 
For reference, here's the check of the argument type:

https://github.com/dhall-lang/dhall-haskell/blob/3e5cb3492222a1e10de07896ed9689df0a94dbd0/dhall/src/Dhall/TypeCheck.hs#L1025-L1027

**Comment by 9999years** [comment]
Looks awesome @mjgpy3, thanks for the quick fix! 🎉
