### ISSUE TITLE
Format tests: Add newlines at file ends

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1423]
The `dhall/tests/format/*B.dhall` files currently don't end in newlines. This makes editing them a bit annoying, since most editors automatically add newlines at the end.

It would be nice if we could get rid of this gotcha.

If there's a reason why these files shouldn't end in newlines, I'd be interested to know what it is!

**Comment by Gabriel439** [comment]
@sjakobi: There's no reason for them to not end in newlines.  They're only that way because the output of pretty-printing doesn't include a trailing newline
