### ISSUE TITLE
CI for dhall-json with -fgpl

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1425]
AFAIU we lost CI for dhall-json's HsYAML-based code in https://github.com/dhall-lang/dhall-haskell/pull/1417.

It would be good to have CI for both variants.

**Comment by Gabriel439** [comment]
@sjakobi: We are building `dhall-json` with `-fgpl`: https://github.com/dhall-lang/dhall-haskell/pull/1417/files#diff-c156cac2b10c7abb0ec25d4ec2622875R229

Did you mean without the flag?

**Comment by sjakobi** [comment]
Ah, thanks for pointing this out @Gabriel439! AppVeyor tests `dhall-json` with the default configuration (`-f-gpl`), so IMHO that's enough coverage.

**Comment by Gabriel439** [comment]
@sjakobi: You're welcome! 🙂

**Comment by sjakobi** [comment]
#1435 would fix this issue in a better way, so let's try to address it first.

**Comment by sjakobi** [comment]
Seems like we should have enabled CI earlier, since now we have a bug: https://github.com/dhall-lang/dhall-haskell/issues/1516 :/

`dhall-yaml` tests both the `aeson-yaml`-based and the `HsYAML`-based Dhall-to-YAML conversion logic now though.
