### ISSUE TITLE
Consistent CLI options in dhall-json

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1430]
https://github.com/dhall-lang/dhall-haskell/pull/1414 introduced the `--omissible-lists` option for `{json,yaml}-to-dhall`. The same option should eventually replace `--omitEmpty` in `dhall-to-{json,yaml}`.

It would also be nice to get rid of camelCase in the `dhall-json` options. Let's rename `--noMaps` to `--no-maps` and `--preserveNull` to `--preserve-null`.

**Comment by astynax** [comment]
Can I take this one?

**Comment by sjakobi** [comment]
@astynax That would be great! :)

If you have any questions, please ask right here!
