### ISSUE TITLE
Fix dhall-lsp-server to be "-Wall clean"

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-haskell#1446]
`dhall-lsp-server` is the only package left that we don't fail on warnings in CI.  The scope of this issue is to fix all the warnings and then to add `dhall-lsp-server` to this list so that CI can guard against future warnings:

https://github.com/dhall-lang/dhall-haskell/blob/7b414d9846ceb056fd7ee6a8147c03e3dd87ae60/nix/shared.nix#L172-L178

**Comment by sjakobi** [comment]
#1449 fixed this. Thanks @mebubo! :)
