### ISSUE TITLE
(missing) is parsed as a variable

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1454]
This is one of the bugs discovered by the new formatting idempotence test added in #1427. 

```
⊢ missing ? 1

1

⊢ (missing) ? 1

it : Natural

Error: Unbound variable: missing

1│  missing

(stdin):1:2
```

**Comment by sjakobi** [comment]
I think there are several things at play here:

1. `missing` is not a part of the `reversedIdentifiers`: https://github.com/dhall-lang/dhall-haskell/blob/62fd7a1b0d569ad61d98a4c24655ba29849c104c/dhall/src/Dhall/Syntax.hs#L1131-L1133

2. The parser for `missing` is defined as `keyword "missing"` and `keyword` requires whitespace following the keyword: https://github.com/dhall-lang/dhall-haskell/blob/62fd7a1b0d569ad61d98a4c24655ba29849c104c/dhall/src/Dhall/Parser/Token.hs#L664-L665

    Any idea why the whitespace is required?

**Comment by basile-henry** [comment]
@sjakobi It's probably to differentiate with variable names. So `missingSomething` is a variables but `missing` is a keyword. I guess it could be extended to invalid variable characters instead of just white space.

**Comment by sjakobi** [comment]
Hmm, maybe. Note that the `simpleLabel` parser, which `identifier` uses, checks that we don't parse a keyword:


https://github.com/dhall-lang/dhall-haskell/blob/62fd7a1b0d569ad61d98a4c24655ba29849c104c/dhall/src/Dhall/Parser/Token.hs#L330-L340

**Comment by sjakobi** [comment]
As @Gabriel439 pointed out in https://github.com/dhall-lang/dhall-haskell/pull/1458#issuecomment-545609268 this should be fixed by parsing whitespace more precisely, instead of bundling it with each token parser.

**Comment by sjakobi** [comment]
#1483 fixed this. Some of the tests I added in https://github.com/dhall-lang/dhall-lang/pull/788 (still?) fail though:

https://github.com/dhall-lang/dhall-haskell/blob/e931451a2b2892fa373c9dfc94b31bcd764131be/dhall/tests/Dhall/Test/Parser.hs#L133-L134

The variables `missingFoo` and `missing/` cannot be parsed. The situation is similar with other keywords though:

```
⊢ let ifx = 3 in ifx

Error: Invalid input

(stdin):1:18:
  |
1 | let ifx = 3 in ifx
  |                  ^
unexpected 'x'
expecting whitespace

⊢ let if/ = 3 in if/

Error: Invalid input

(stdin):1:18:
  |
1 | let if/ = 3 in if/
  |                  ^
unexpected '/'
expecting whitespace
```

Do we need an issue to track that? This one can be closed IMHO.
