### ISSUE TITLE
Example from tutorial fails to compile

### ISSUE THREAD

**Issue by dwhitney** [dhall-lang/dhall-haskell#1459]
I haven't done much haskell programming, so perhaps I've done something wrong. I setup a new project with the latest stack: `stack new tmp simple`. Then added `dhall` as a dependency to the cabal file, copy/paste the following into `src/Main.hs`

```haskell
{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE OverloadedStrings #-}

import Dhall

data Example = Example { foo :: Natural, bar :: Vector Double }
    deriving (Generic, Show)

instance FromDhall Example

main :: IO ()
main = do
    x <- input auto "./config.dhall"
    print (x :: Example)
```

it fails with the following error:

```
    Not in scope: type constructor or class 'FromDhall'
   |
9 | instance FromDhall Example
   |
```

**Comment by sjakobi** [comment]
The name of the `FromDhall` class was previously `Interpret`. It was renamed to `FromDhall` in v1.27.0, which isn't included in any Stackage snapshots yet.

I suggest that you add a constraint `>= 1.27.0 && < 1.28` to the `dhall` dependency in your `cabal` file. `stack` will then suggest how to modify your stack.yaml so it includes the right version of `dhall`.

**Comment by dwhitney** [comment]
Thanks!
