### ISSUE TITLE
Tips for uppercase fields in records

### ISSUE THREAD

**Issue by dwhitney** [dhall-lang/dhall-haskell#1461]
Hi I'm trying to use json-to-dhall with dhall-haskell to codegen some dhall types for use with AWS CloudFormation. In CloudFormation almost every field name in a record is in uppercase, with a corresponding dhall that looks something like:

```dhall
{ Documentation  : Optional Text
, DuplicatesAllowed : Optional Bool
, ItemType  : Optional Text
, PrimitiveType  : Optional (./PrimitiveType.dhall)
, PrimitiveItemType : Optional (./PrimitiveType.dhall)
, Required  : Optional Bool
, Type  : Optional Text 
, UpdateType  : Optional (./UpdateType.dhall)
}
```

How do I make this play nice with the fact that I can't have uppercase field names in Haskell?

TIA!

**Comment by dwhitney** [comment]
For more clarity - my desire is to create an ADT in Haskell that maps to the dhall types. Then do some processing, and spit out dhall types.

**Comment by sjakobi** [comment]
You can use `autoWith` with [`InterpretOptions`](http://hackage.haskell.org/package/dhall-1.27.0/docs/Dhall.html#v:defaultInterpretOptions) with an appropriate `fieldModifier`.

But I don't have much hands-on experience with the marshalling. You might find more help on #dhall channel [here](https://fpchat-invite.herokuapp.com/).

**Comment by dwhitney** [comment]
thanks!
