### ISSUE TITLE
Improve the documentation structure of the Dhall module

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1490]
The `Dhall` module has become quite large. It would be nice if it would be easier to navigate.

**Comment by Gabriel439** [comment]
Does https://github.com/dhall-lang/dhall-haskell/pull/2193 fix this?

**Comment by sjakobi** [comment]
> Does #2193 fix this?

I think it's a great improvement. I can open a new issue if I find anything left that should be improved.
