### ISSUE TITLE
Root CA seems to be missing from the docker images

### ISSUE THREAD

**Issue by daddykotex** [dhall-lang/dhall-haskell#1491]
Hey,

Thanks for dhall, it's amazing and the project/community is great.

I was using the docker image for dhall until I ran into an issue.

Given the following file:

```
❯ cat test.dhall
let Map = https://prelude.dhall-lang.org/Map/Type

in 2

```

We get an unknown CA certificate:

```
❯ docker run -i dhallhaskell/dhall:1.27.0 dhall < test.dhall
dhall:
InternalException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa)))
```

I open the issue before a PR because I want to make sure I'm not the only one that has the issue and also because I'm still not comfortable with `nix` enough to fix that easily.

If you got any pointer to where I should head in order to write a fix for that, I'd be grateful and would probably be able to submit a PR.

I saw some docker shenanigans in `shared.nix` and I'll probably start from there.

**Comment by Gabriel439** [comment]
Fixed by #1493
