### ISSUE TITLE
escaping string fail on multiline Text for pattern similiar with string interpolation

### ISSUE THREAD

**Issue by DrSensor** [dhall-lang/dhall-haskell#1497]
this works fine on single line string
```haskell
{
  run = "cross build --target \${{ matrix.arch }} --release"
}
```
but it fail on multi line string
```haskell
{
  run = ''
    cross build --target \${{ matrix.arch }} --release
  ''
}
```

**Comment by DrSensor** [comment]
Ah, you are right! Thought it a bit weird 🤔
I guess this is not yet documented?

**Comment by sjakobi** [comment]
> I guess this is not yet documented?

Maybe it should be documented better. Where would you have expected to find documentation on this?

**Comment by DrSensor** [comment]
Most of the time when I begin to write dhall, I open the wiki with a lot of tab 😅. What I mostly visit is cheatsheet (also both prelude source code and gh-release page).

It would be nice if everything is in the dedicated website.

**Comment by sjakobi** [comment]
Thanks for the feedback @DrSensor. It's good to know how these resources are being used!

I have added an example of escaped interpolation to the `Text` section of https://github.com/dhall-lang/dhall-lang/wiki/Cheatsheet.

> even better, all information can be accessed offline

Note that you can make a local clone of the wiki with 

    git clone https://github.com/dhall-lang/dhall-lang.wiki.git

**Comment by DrSensor** [comment]
I already know that. I prefer offline media where I can read it on the mobile phone like pdf or [devdocs](https://devdocs.io)

**Comment by Gabriel439** [comment]
@DrSensor: Once Dhall gets 5000 stars we can suggest it for inclusion in DevDocs

**Comment by sjakobi** [comment]
@DrSensor: @Gabriel439 just made me aware of this document:

https://github.com/dhall-lang/dhall-lang/blob/master/standard/multiline.md

It might be interesting for you too!
