### ISSUE TITLE
Add dhall-lsp-server to brew

### ISSUE THREAD

**Issue by akshaymankar** [dhall-lang/dhall-haskell#1499]
Title says it, it would be great to be able to install `dhall-lsp-server` with `brew`.

**Comment by Gabriel439** [comment]
The pull request is up here: https://github.com/Homebrew/homebrew-core/pull/46098

**Comment by Gabriel439** [comment]
Alright, my second attempt is up here: https://github.com/Homebrew/homebrew-core/pull/48978

**Comment by sjakobi** [comment]
Looks like the second attempt was successful: https://formulae.brew.sh/formula/dhall-lsp-server :tada: 

Please re-open if there's more to do here!
