### ISSUE TITLE
Is there a undefined to make compiler happy

### ISSUE THREAD

**Issue by psibi** [dhall-lang/dhall-haskell#150]
Similar in spirit to Haskell's `undefined`...

**Comment by Gabriel439** [comment]
You can introduce a value of any type using a lambda.  For example:

```haskell
  λ(undefined : ∀(a : Type) → a)
→     let foo : Text = undefined Text
  
  in  let bar : List Integer = [ 1, undefined Integer, 2 ]
  
  in  { bar = bar, foo = foo }
```

Dhall has no trouble normalizing that, of course, because there's nothing to do :)

```haskell
  λ(undefined : ∀(a : Type) → a)
→ { bar = [ 1, undefined Integer, 2 ], foo = undefined Text }
```

**Comment by Gabriel439** [comment]
I'll go ahead and close this since I think that answers the original question.  Feel free to reopen if you still have questions
