### ISSUE TITLE
Marshalling functions without FromDhall

### ISSUE THREAD

**Issue by neongreen** [dhall-lang/dhall-haskell#1501]
I'd like to have a manual combinator for marshalling functions from Dhall. It exists inside of a `FromDhall` instance (https://hackage.haskell.org/package/dhall-1.27.0/docs/src/Dhall.html#line-1128), but is not exported.

**Comment by sjakobi** [comment]
Something like this?
```haskell
function :: Encoder a -> Decoder b -> Decoder (a -> b)
```

A PR would be welcome! :)

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1507
