### ISSUE TITLE
Way to import haskell expressions from dhall.

### ISSUE THREAD

**Issue by MaxOw** [dhall-lang/dhall-haskell#1502]
I need a way to insert an expression from haskell when interpreting a dhall file. That's probably not very clear so let me give you an example. Let say we have a haskell type:

```haskell
data SomeType = A | B | C
```

Now to use it in dhall we write something like:

```dhall
let SomeType = < A | B | C >
in SomeType.A
```

So what i need now is a way to get rid of this duplication. I know there is a way to do this with template haskell to derive that expression from dhall on compilation but I want haskell to be my source of truth. I know I could write that type to a file on startup but then I need to know where it will be written in relation to the interpreted file and it sort of feels icky. I could use env variables and set them on runtime but again: hacky. I've also thought of some other ways like wrapping an expression in lets or Injecting that type but that felt messy and I wasn't sure how viable so I've desisted for now.

My ideal solution would be something like the env thing but dedicated. I'm thinking something like runtime: import protocol? thingy... like:

```dhall
let SomeType = runtime:SomeType
in SomeType.A
```

And then in haskell there would be a configurable callback in `InputSettings` with type something like `Text -> Maybe Expr`

I'm also open to other solutions because it's very possible there is already an existing method to achieve this but I'm just too daft to see it.

**Comment by sjakobi** [comment]
Have you seen [the "Extending the language" section in the tutorial](http://hackage.haskell.org/package/dhall-1.27.0/docs/Dhall-Tutorial.html#g:23)?

The normalizer currently supports only custom functions though:

https://github.com/dhall-lang/dhall-haskell/blob/7ea5f6fa51dfe99f9008c3160a9cad7b6331a9cb/dhall/src/Dhall/Normalize.hs#L554

https://github.com/dhall-lang/dhall-haskell/blob/7ea5f6fa51dfe99f9008c3160a9cad7b6331a9cb/dhall/src/Dhall/Normalize.hs#L729

**Comment by MaxOw** [comment]
Yeah that was sort of one of my attempts at that but I've somehow failed. I think I've made a function that took a value and returned a type but I got back an error about dependent types. Now I think that maybe if I've made a function that takes a type ignores it and returns a type it would do what I want. I'm gonna try that now and report back, but that's still a bit hacky, but probably good enough if it works.

**Comment by sjakobi** [comment]
I wonder whether it might be a good idea to extend [`EvaluateSettings`](https://github.com/dhall-lang/dhall-haskell/blob/7ea5f6fa51dfe99f9008c3160a9cad7b6331a9cb/dhall/src/Dhall.hs#L335-L339) to allow variable substitutions that could be applied before type checking…

**Comment by MaxOw** [comment]
Yep, when I've started on this journey that was what I was hoping was already possible, so I just thought pish pash posh I implement it and it will be done... but it wasn't to be. Anyway if that was possible it would solve my problem so I'm very much for that, assuming it wont brake something. Anyways going back to the type level function that takes a dummy type idea above, I wasn't able to make it work (but maybe it's just that my kungfu isn't strong enough).

**Comment by MaxOw** [comment]
FYI: I do offer to implement changes needed if we decide what to do here. I'm guessing allowing variable substitutions would be the least intrusive option.

**Comment by Gabriel439** [comment]
@MaxOw: One thing that help me better understand is if you showed some example Dhall and Haskell pseudocode illustrating what Dhall code you'd like users to write and what Haskell code you'd like the DSL implementer to write

**Comment by MaxOw** [comment]
Well, assuming we go with the "allowing variable substitutions" idea, something like:

```haskell

data SomeType = A | B | C deriving (Show, Generic)
instance Interpret SomeType

main :: IO ()
main = do
    let ctx = Dhall.Context.empty
            & Dhall.Context.insert "Runtime/SomeType" (Expr.Const Expr.Type)

    let someTypeExpr = expected (auto @SomeType)
    let nrm = \case
          Var "Runtime/SomeType" -> Just (denote someTypeExpr)
          _ -> Nothing

    let inputSettings = defaultInputSettings
            & set normalizer (Just $ ReifiedNormalizer (pure . nrm))
            & set startingContext ctx
    res <- inputWithSettings inputSettings auto
              "let SomeType = Runtime/SomeType in SomeType.A"
    print (res :: SomeType)

```

Something like that? This is based on some attempts that I was doing, (and in version 1.24 of dhall at that) haven't compiled this and I'm not sure if this is even correct conceptually, but I think it should get through what I'm trying to do here.

So what I'm currently doing is having a Types.dhall file that duplicates all my haskell types in dhall. Now say I add a value to an enum (or some other sum type). I compile my code, run it and get a type error in dhall, so I have to make that same change to the dhall representation in Types.dhall. Granted this is only a quality of life improvement, but it's something that's definitely a pain and would be nice to have.

**Comment by Gabriel439** [comment]
@MaxOw: What if there were a Dhall quasiquoter so that you could do something like this:

```haskell
input auto [dhall|let SomeType = ${expected (auto @SomeType)} in SomeType.A|]
```

**Comment by MaxOw** [comment]
Well that was only a minimal example, since that expression would be in a separate file loaded from disc, otherwise it wouldn't serve it purpose as a configuration. And I don't think this helps in that situation unless we could pass this expression as a type level function? But I don't think that is doable...

```haskell
input auto [dhall|(./Config.dhall) (${expected (auto @SomeType)})|]
```
And then the `Config.dhall`:

```dhall
∀(SomeType : Type) → SomeType.A
```
 
But this isn't a valid dhall I don't think right?

**Comment by MaxOw** [comment]
Ok, so I'm going to go with the "wrapping the thing in a let expression" idea that I was entertaining as a possible solution in the top post, for now:

```haskell
  ct <- readFile "Config.dhall"
  let ex = "let Runtime/SomeType = " <> pretty (expected (auto @SomeType)) <>
           " in " <> ct
  ret <- input auto ex
  print (ret :: SomeType)
```

Which is in a way the same solution as the one with extending the normalizer, where in that solution we say "behave as if you were inside a body of a let expression with that variable in context" in this solution we literally wrap the whole thing in a let expression. Mucking about with strings like that is a bit icky and it could give possibly confusing errors to the user so I would prefer a more proper solution, but if you don't believe that to be the case then you can close this issue since this technically works.

**Comment by Gabriel439** [comment]
@MaxOw: Note that if you really want a proper solution you can build the `Expr` AST and then use `Dhall.extract` directly on that so that there is no `Text` intermediate.  It's a bit more verbose but that is the robust solution

**Comment by Profpatsch** [comment]
Maybe I misunderstand the problem, but the new [“generate Haskell types from dhall types via TH”](https://github.com/dhall-lang/dhall-haskell/commit/b0280826790930d18a5498fb802120478fa11767#diff-a9729dccf50be61ce3d8c68c16f0fd50) feature looks related.
