### ISSUE TITLE
Type checker can loop forever

### ISSUE THREAD

**Issue by zyla** [dhall-lang/dhall-haskell#151]
When type checking the expression

```
let foo : (\(x : A) -> x x) (\(x : A) -> x x) = 1 in foo
```

the type checker loops forever.

The type annotation of this let-expression is the omega combinator of untyped lambda calculus, which reduces to itself. [Here](https://github.com/dhall-lang/dhall-haskell/blob/b21a3b8c0e6472372b00f8acee4b37557dd3557a/src/Dhall/TypeCheck.hs#L194) the type checker attempts to normalize it before type checking it, resulting in an infinite loop.

**Comment by zyla** [comment]
Another expression that makes the type checker diverge:

```
\(omega : ((\(x : A) -> x x) (\(x : A) -> x x))) -> omega 1
```

**Comment by Gabriel439** [comment]
Whoops!  Thank you for catching that.  I will fix this as soon as possible

**Comment by Gabriel439** [comment]
I have a pull request up with the fix here: https://github.com/dhall-lang/dhall-haskell/pull/153
