### ISSUE TITLE
dhall-lsp-server may show the wrong type on hover

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1510]
This type should actually be `Bool -> { home : Text, name : Text }`:

https://github.com/dhall-lang/dhall-haskell/blob/1b46f1885f25c16e369b3f455c3950e4837ac49f/dhall-lsp-server/tests/Main.hs#L40

There may be more bugs – ideally all the type information logic should have test coverage:

https://github.com/dhall-lang/dhall-haskell/blob/cc1814be9858f62e664b0d2114e711fd4431bd2c/dhall-lsp-server/src/Dhall/LSP/Backend/Typing.hs#L31-L72

**Comment by EggBaconAndSpam** [comment]
Eh, what is going on here? I'll have a look at it.

**Comment by EggBaconAndSpam** [comment]
Found the culprit:
https://github.com/dhall-lang/dhall-haskell/blob/cc176e1e93ed856ff2362ec275a68b2d4bbfba16/dhall/src/Dhall/Parser/Expression.hs#L218-L232

**Comment by EggBaconAndSpam** [comment]
Thanks for the bug report @sjakobi! This should have been caught by tests (yes, I know).
