### ISSUE TITLE
Support prettyprinter-1.5

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#1525]

**Comment by sjakobi** [comment]
This would be easier if https://github.com/haskell-nix/hnix/pull/522 were released, but maybe we should consider jailbreaking `hnix` to get #1422 and #1400 unstuck…

**Comment by sjakobi** [comment]
I've made an issue to request an `hnix` release or Hackage revision: https://github.com/haskell-nix/hnix/issues/524

**Comment by Gabriel439** [comment]
@sjakobi: You can jailbreak `hnix` on your branch in the meantime.  Supporting `prettyprinter-1.5` is something we have to do anyway before the next release so that every package except `dhall-nix` can remain on Stackage.

**Comment by sjakobi** [comment]
#1422 raised the lower bound to 1.5.1.
