### ISSUE TITLE
Add option to LSP to format with the ASCII character set

### ISSUE THREAD

**Issue by CLowcay** [dhall-lang/dhall-haskell#1529]
The dhall CLI has an option --ascii to format with ASCII characters rather than Unicode characters.  It would be nice if this option was also available when formatting via the LSP server.

**Comment by Gabriel439** [comment]
The main thing I want to check first before adding a command-line option is if the language server protocol supports a more idiomatic way to configure a setting like this within the protocol

**Comment by EggBaconAndSpam** [comment]
> The main thing I want to check first before adding a command-line option is if the language server protocol supports a more idiomatic way to configure a setting like this within the protocol

The protocol supports synchronising configuration between client and server, i.e. we can have 'first-class' options rather than having to deal with command line parameters.

Adding support for this to the client and server should be trivial &ndash; I'm working on it!

**Comment by Gabriel439** [comment]
Fixed by #1533
