### ISSUE TITLE
json-to-dhall and yaml-to-dhall should print the JSON path for errors

### ISSUE THREAD

**Issue by robbiemcmichael** [dhall-lang/dhall-haskell#1542]
When converting JSON/YAML files to a Dhall expression, it can be hard to tell where errors are for larger files. To take an example with `yaml-to-dhall`:

```dhall
{ a : { b : List Natural }
, c : { d : List Integer }
}
```

```yaml
a:
  b:
  - 10
  - 0.5
c:
  d:
  - 10
  - 0.5
```

```
$ yaml-to-dhall ./Type.dhall --file data.yaml


Error: Dhall type expression and YAML value do not match:

Expected Dhall type:
Natural

YAML:
0.5
```

It's hard to tell where the error is since we have `0.5` appear in the YAML file twice. It would be better to provide a path to the error:

```
Error in $.a.b[1]: Dhall type expression and YAML value do not match
```

----

There's a secondary question about whether it's worth printing the JSON/YAML value at all if we can print the path. If you make an error at the top level then it will print the entire JSON/YAML value for the file, which isn't particularly helpful for finding the error.

I would propose removing the code that prints the JSON/YAML value after the JSON path is exposed for errors. This also means we don't need to worry about adding a [`--censor` flag](https://github.com/dhall-lang/dhall-haskell/pull/1329) to hide these values.

**Comment by robbiemcmichael** [comment]
I had a quick look at doing this a while ago, but I needed to expose [`formatPath`](http://hackage.haskell.org/package/aeson-1.4.6.0/docs/Data-Aeson-Types.html#v:formatPath) from `aeson` for this to work. It's now in 1.4.6.0 which it the latest version, but not in a Stackage LTS release yet.

Once it's in an LTS release, are you happy to use very recent versions of packages or do try to avoid that? We can probably work around it using [`formatError`](http://hackage.haskell.org/package/aeson-1.4.6.0/docs/Data-Aeson-Internal.html#v:formatError) but that's an internal function so that may be even less desirable.

**Comment by sjakobi** [comment]
I wouldn't worry about using dependency versions that aren't in Stackage LTS yet – Stackage will catch up eventually.

What I'm slightly more concerned about is how we'd preserve this functionality if/once we translate YAML to Dhall directly, using HsYAML. A test would be very useful for this, but so far we don't have any tests for error messages. A proper golden-test setup (maybe based on [`tasty-silver`](http://hackage.haskell.org/package/tasty-silver)?) would be very useful for this!

**Comment by Gabriel439** [comment]
@sjakobi: I think it would still work even when converting directly from YAML.  Either way we will be descending through keys/arrays as we decode and we can keep track of the trail of breadcrumbs for how we got there and report that.

**Comment by joneshf** [comment]
It'd be nice to get the output in a standardized format, like [RFC6901](https://tools.ietf.org/html/rfc6901). The above example would change to:
```
Error in /a/b/1: Dhall type expression and YAML value do not match
```

Would that still work for the spirit of this request, or is the request explicitly to be in `aeson`s format?
