### ISSUE TITLE
Incorrect formatting of multi-line strings with leading whitespace

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1545]
Strings where the last line starts with whitespace are currently incorrectly formatted as multi-line strings:

```
$ echo '"\n\tx"' | dhall format
''

	x''
$ echo '"\n\tx"' | dhall format | dhall format
''

x''
```

```
$ echo '"\n x"' | dhall format
''

 x''
$ echo '"\n x"' | dhall format | dhall format
''

x''
```

I discovered this bug by running the very powerful formatting idempotence test while I was working on https://github.com/dhall-lang/dhall-haskell/pull/1543. @Gabriel439 pointed out that the underlying reason lies in the multi-line string dedentation logic specified in https://github.com/dhall-lang/dhall-lang/blob/master/standard/multiline.md#indentation.

This should be fixed by formatting such strings on a single line. I'm currently working on a patch.

**Comment by sjakobi** [comment]
@Gabriel439 Would you prefer to escape the leading whitespace here too, similarly to what you suggested in https://github.com/dhall-lang/dhall-haskell/pull/1543#issuecomment-554550934? E.g.

```
$ echo '"\n\tx"' | dhall format
''

${"\t"}x''
```

**Comment by Gabriel439** [comment]
@sjakobi: Yeah, that's probably the most straightforward solution

**Comment by sjakobi** [comment]
In case there are multiple whitespace characters at the beginning of the last line, I'd suggest that we escape all them in a single interpolation to highlight "the problem", e.g.

```
''

${" \t "}x''
```

Alternatively we could simply add `${""}` as a prefix:

```
''

${""} 	 x''
```

**Comment by Gabriel439** [comment]
@sjakobi: I'm fine with either of those two solutions.  `${""}` is probably simpler to implement, but escaping the entire prefix that we preserve is probably more clear to the user.  If I had to pick one maybe go with the latter (e.g. `${" \t "}x`)
