### ISSUE TITLE
Parser doesn't pass the new unicode escape sequence tests

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1548]
The parser needs to be fixed to pass the new tests for unicode escape sequences added in https://github.com/dhall-lang/dhall-lang/pull/802.

https://github.com/dhall-lang/dhall-haskell/blob/f18ec5f8e0145f8c77a3d59fedd8d0934c0e1bc0/dhall/src/Dhall/Parser/Expression.hs#L595-L618

@SiriusStarr since you seem to be intimately familiar with the topic, would you possibly be interested in making a PR?

**Comment by SiriusStarr** [comment]
> @SiriusStarr since you seem to be intimately familiar with the topic, would you possibly be interested in making a PR?

@sjakobi I feel personally attacked.  :grinning:  PR #1549 is up.

**Comment by Gabriel439** [comment]
Fixed by #1549
