### ISSUE TITLE
resolve --transitive-dependencies should preserve dependency order

### ISSUE THREAD

**Issue by retnuh** [dhall-lang/dhall-haskell#1551]
It would be nice if running `dhall resolve --transitive-dependencies` preserved the dependency order, so that when a file/url is printed out, we know that all it's dependencies have already been printed out.

This make it more useful for scripts that perform a freeze as part of a build/release process; we can just use `resolve` to get a list of files, in the correct freezing order.

**Comment by timbertson** [comment]
> * attempting to freeze transitive dependencies that you don't have permission to modify
> * freezing dependencies outside of your current project by mistake

For the latter, I've been using a dumb script that uses `find . -name '*.dhall'` to freeze everything under the current directory, which seems like a pretty reasonable boundary. For non-CLI usage you could try to detect VCS roots, pragmatically speaking `.git` would probably suffice for a while.

That doesn't help the former (no permission), but makes it fairly unlikely.

**Comment by ggilmore** [comment]
👍  For having `dhall freeze` natively handle this. 

In the meantime, I've written this bash script to handle freezing everything for https://github.com/sourcegraph/deploy-sourcegraph-dhall

```bash
#!/usr/bin/env bash

set -euo pipefail

DHALL_FILE="$1"

DEPENDENCIES=()

mapfile -t DEPENDENCIES < <(dhall resolve --no-cache --transitive-dependencies --file "${DHALL_FILE}")

for dependency in "${DEPENDENCIES[@]}"; do
  DEPENDENCY_FILE=$(cut -d' ' -f1 <<<"$dependency")
  if test -f "$DEPENDENCY_FILE" && [[ "$DEPENDENCY_FILE" =~ \.dhall$ ]]; then

    echo "${DEPENDENCY_FILE}"

    dhall freeze --all --inplace "${DEPENDENCY_FILE}"
  fi
done

```

It's a bit hacky, but it handles the edge cases for ignoring remote imports and non-dhall dependencies.

**Comment by ari-becker** [comment]
@timbertson @ggilmore to make sure that freeze handles the deepest folders first, we use the following (note: we only freeze our `package.dhall` files):

```bash
deepest_level=$(find . -name 'package.dhall' | sed 's/[^\/]//g' | awk '{ print length }' | sort | tail -n 1)
for depth in $(seq $deepest_level -1 1) ; do
  while IFS= read -r -d '' package_dhall ; do
    dhall freeze --cache --all --inplace $package_dhall
  done < <(find . -mindepth $depth -maxdepth $depth -name 'package.dhall' -print0)
done
```
Hope this helps (it's certainly not intuitive to people who aren't familiar with bash)

**Comment by Gabriel439** [comment]
The fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1880
