### ISSUE TITLE
Compile empty association list to object rather than list?

### ISSUE THREAD

**Issue by wbadart** [dhall-lang/dhall-haskell#1559]
Right now, unless `--noMaps` is specified, we expect `dhall-to-json` and `dhall-to-yaml` to compile values of type `List { mapKey = t, mapValue = u }` to objects. This works when the list is populated, but it seems that whatever process transforms non-empty association lists to objects is skipped for empty ones, so you end up with a different type in the compiled file. For example:

    $ dhall-to-json --version
    1.5.0

    $ dhall-to-json <<< '[{ mapKey = "foo", mapValue = "bar" }]'
    {
      "foo": "bar"
    }

    $ dhall-to-json <<< '[] : List { mapKey : Text, mapValue : Text }'
    []

Expected:

    $ dhall-to-json <<< '[] : List { mapKey : Text, mapValue : Text }'
    {}

If this is actually the desired behavior, please let me know! But if it is, I think it would still make sense to add this behavior as an option (maybe add a command line flag like `--transformEmptyAssocs` or something).

There are definitely practical applications of this new behavior. In my case, I'm compiling a docker compose configuration where I represent services and networks and such as association lists, e.g.

    { services = [
      { mapKey = "my_service"
      , mapValue = Service::
        { image = "dhallhaskell/dhall-json"
        , ports = [ "8000:80" ]
        }
      } ]
    , networks = [
      { mapKey = "my_net", mapValue = Network.default } ]
    }
      
==>

    services:
      my_service:
        image: "dhallhaskell/dhall-json"
        ports: [ "8000:80" ]
    networks:
      my_net:
        driver: overlay

In my case, if no, say, networks have been specified, it needs to be an object rather than a list, or docker will reject it:

    networks: {}

I have a work-around using `Optional`, but the ergonomics are **dramatically** better if I can allow `networks = [] : List { mapKey = Text, mapValue = Network.Type }` to be empty.

**Comment by sjakobi** [comment]
Thanks for the report! Looks like a regression back from https://github.com/dhall-lang/dhall-haskell/commit/0ee6ce6f6fd2afe9d227fa9d58a3e61fced33c21.

**Comment by wbadart** [comment]
Glad to hear my intuition on that behavior was on track. Thanks for the quick turnaround!
