### ISSUE TITLE
Implicit version of ‘input’

### ISSUE THREAD

**Issue by Icelandjack** [dhall-lang/dhall-haskell#156]
It would be good to have an implicit version of `input`

```haskell
inputImplicit :: Interpret a => Text -> IO a
inputImplicit = input auto
```

to let users express the type they are decoding with an explicit annotation (but without the use of `auto`) or by passing it as a type argument without any value-level witnesses.

The latter agrees with the use of current `input`

```haskell
    x <- inputImpl @Example "./config"
    print x
```

It would also be nice to have a name for the generic type former, so you can us them for subexpressions of types (`myPair genericType genericType`)

```haskell
genericType :: (Generic ty, GenericInterpret (Rep ty)) => Type ty
genericType = to <$> evalState (genericAutoWith defaultInterpretOptions) 1
```

**Comment by Gabriel439** [comment]
Note that this only really benefits the user if the name is short.  Otherwise, it's not much shorter than:

```haskell
x <- input @Example auto "./config
```

**Comment by Gabriel439** [comment]
However, I like the idea of exporting a `genericType` and I will add that
