### ISSUE TITLE
Serialize a Haskell value as Dhall?

### ISSUE THREAD

**Issue by dhess** [dhall-lang/dhall-haskell#157]
Is there a general way to serialize a Haskell value as Dhall-formatted Text?

I'm using Dhall to configure a program. By default, the program looks for a config in a particular filesystem location, and if it doesn't exist, I want to write a default config there. This would be helpful on the first run for bootstrapping a configuration, especially in cases where the configuration is non-trivial.

I can just define a raw Text value in the program whose contents are valid Dhall and write that to a file, but it'd be much nicer to define a default Haskell value and serialize that, so that I don't have to keep the Haskell type (and/or default values) in sync with the Text value.

**Comment by Gabriel439** [comment]
Yes.  You can use the `Inject` class to convert a Haskell value to the corresponding Dhall expression:

https://hackage.haskell.org/package/dhall-1.6.0/docs/Dhall.html#t:Inject

... and then you can use `Dhall.Core.pretty` to render that value to the file's contents

Like the `Interpret` class, you can derive `Inject` for user-defined types

**Comment by Gabriel439** [comment]
I should clarify that what you want is the `embed` field from the `InputType` that `inject` returns:

```haskell
embed inject yourHaskellValue
```

**Comment by dhess** [comment]
Perfect! I was missing the part about combining `embed` with `inject`.
