### ISSUE TITLE
Improve LSP experience outside VSCode

### ISSUE THREAD

**Issue by jvanbruegge** [dhall-lang/dhall-haskell#1587]
I am currently trying the LSP and sadly the diagnostics are unhelpful at best and annoying at worst. For example, I forgot to add `.Type` to an imported expression. This is the error I got:
![grafik](https://user-images.githubusercontent.com/1529052/70275090-b6179000-17ad-11ea-99c0-fb310805894a.png)
This looks like it is just the normal command line error squeezed into one line. When I run the interpreter in a command line window, the information I actually needed to see my mistake was at the very bottom:
![grafik](https://user-images.githubusercontent.com/1529052/70275251-0f7fbf00-17ae-11ea-99cc-5241f204197a.png)
(On a side note, I don't see the use in the huge output on the cli too but there I can simply ignore it)

On the annoying side are a ton of parse errors à la `Unexpected end of input, expected ...`. Also those errors somehow persist until I save the file again.

**Comment by Gabriel439** [comment]
@jvanbruegge: I'm seeing something very different when I get a type error, although I'm testing against `master`.  However, I don't expect it to look too different from the last release:

![Language Server](https://user-images.githubusercontent.com/1313787/70289310-34ae0680-1789-11ea-975b-a1f0817d3ab2.gif)

**Comment by jvanbruegge** [comment]
No, you are seeing the same thing, but in VSCode you can scroll over that huge chunk of text. The vim client does not have scrolling

**Comment by Gabriel439** [comment]
@jvanbruegge: Oh, I didn't even realize that the Dhall language server worked at all with Vim!

I know that in principle a language server should be able to support any editor that supports the language server protocol, but one issue that @EggBaconAndSpam ran into while designing the language server was that in practice language servers still requires some editor-side "glue" so we focused primarily on ironing out integration issues with VSCode.

In order to help you with your configuration I'm going to need as much detail on the following so I can reproduce your setup:

* Editor (e.g. `vim` or `nvim`, including version)
* Language server client plugin (e.g. `coc.nvim`, including version)
* Any relevant `vimrc` settings

I probably won't be able to help that much (since I'm not really an expert on customizing `vim`), but I'll do what I can

**Comment by jvanbruegge** [comment]
I use `nvim` version `0.4.3` with [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim).
The relevant config is:
```
let g:LanguageClient_serverCommands = {
    \ 'dhall': ['dhall-lsp-server']
    \ }
```
My full configuration can be found [in my dotfiles repo](https://github.com/jvanbruegge/dotfiles)

**Comment by jvanbruegge** [comment]
From what I can tell what does not work is configuration (the language server seems to ignore the `didConfigurationChange` event), and that the error messages are too huge to reasonably display them

**Comment by jvanbruegge** [comment]
Oh, yeah for some reason hints and error do not necessarily show up at the correct spot, for example `unused let binding` is always shown at some earlier binding

**Comment by jvanbruegge** [comment]
On the plus side, import completion and autocomplete works (albeit when working with dhall-kubernetes, autocomplete takes about 5 seconds to show up)

**Comment by Gabriel439** [comment]
I'm just documenting here that this also requires installing:

```
Plug 'vmchale/dhall-vim'
```

... in case somebody else makes the same mistake I did

**Comment by Gabriel439** [comment]
@jvanbruegge: `LanguageClient#explainErrorAtPoint` appears to do what you want.  If you call that then it provides the corresponding multiline display, like this:

![Screen Shot 2019-12-08 at 10 55 04 AM](https://user-images.githubusercontent.com/1313787/70394350-440b9a80-19a9-11ea-8ffa-236ebbf6dd99.png)


See: https://github.com/autozimu/LanguageClient-neovim/issues/35#issuecomment-414191276

**Comment by jvanbruegge** [comment]
Yes, but wouldnt it be better to just remove that huge chunk of unneccesary text?

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1604

Here is what the full diagnostic message looks like now in `nvim`:

![Screen Shot 2019-12-10 at 8 51 48 PM](https://user-images.githubusercontent.com/1313787/70592519-f0f33c80-1b8e-11ea-80b0-0361242cfe36.png)

**Comment by jvanbruegge** [comment]
nice

**Comment by Gabriel439** [comment]
As a side note, this change also removes the terminal escape codes around the "Error:" in the error message, too
