### ISSUE TITLE
dhall-to-yaml does not support Foo::{} syntax

### ISSUE THREAD

**Issue by jvanbruegge** [dhall-lang/dhall-haskell#1589]
Which is kind of sad because that's what the readme of `dhall-kubernetes` claims:
![grafik](https://user-images.githubusercontent.com/1529052/70283739-8c1c9880-17c2-11ea-8ee0-66f439a3a1d9.png)
When I run `dhall-to-yaml` on a file that the interpreter accepts, I get this error:
![grafik](https://user-images.githubusercontent.com/1529052/70283973-b53d2900-17c2-11ea-8715-50deb2e3487f.png)

This is with the newest version of `dhall-to-yaml` (1.4.1)

**Comment by Gabriel439** [comment]
@jvanbruegge: The latest version of `dhall-to-yaml` is version 1.5.0

**Comment by jvanbruegge** [comment]
Ok, got confused by the `CHANGELOG` that listed 1.4.1 as the newest version (and some other changes as coming in the next version).
Installed the newly released 1.6.0 and worked like a charm
