### ISSUE TITLE
dhall resolve should allow header exclusion

### ISSUE THREAD

**Issue by thebritican** [dhall-lang/dhall-haskell#1602]
When using `dhall resolve` to provide a dependency graph, the output provides the headers used to fetch remote content.

We fetch from a private repo, which requires interpolating the GitHub token into an authorization header from an environment variable. We don't want that value exposed in the dependency graph, especially if we want to commit that graph to the repo for documentation purposes.

Should we add a `--exclude-headers` option for this purpose? Open to better ideas :)

**Comment by thebritican** [comment]
Sounds good to me. Would very much improve the output graph 😄

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1603

**Comment by thebritican** [comment]
thanks for the very quick turnaround!

**Comment by Gabriel439** [comment]
@thebritican: You're welcome! 🙂
