### ISSUE TITLE
Less than great error message

### ISSUE THREAD

**Issue by aleator** [dhall-lang/dhall-haskell#161]
Given the expression `{f=1} // {g=2,,}` dhall produces the following error message:

```
Error: Invalid input

(stdin):1:7: error: expected: "''",
    "(", "+", "-", ".", ":", "\"",
    built-in value, double,
    end of input, import, integer,
    label, list literal, natural,
    operator, record literal,
    record type, union literal,
    union type
{f=1} // {g=2,,}
      ^

```
Notice the position of the caret at 1:7 which is in the middle of operator `//`, which is nowhere close to where the actual issue is. This error message problem is actually rather bad when you consider that the second record could be dozens of lines long.

What I would've expected is along the lines of
```
Error: Invalid input

(stdin):1:15: error: expected: "}",
    label
{g=2,,}
     ^
```
Also, extra comma doesn't seem to be the only thing to trigger this.

**Comment by Gabriel439** [comment]
This should be fixed in the latest version of Dhall on Hackage (1.7.0).  I tried your example on that version and the error message is almost exactly what you expected:

```
$ dhall <<< '{f=1} // {g=2,,}'

Error: Invalid input

(stdin):1:15: error: expected: label,
    whitespace
{f=1} // {g=2,,} 
```

**Comment by aleator** [comment]
Awesome! I hadn't noticed the new version before filing the bug.
