### ISSUE TITLE
Dhall for connfiguring Haskell applications

### ISSUE THREAD

**Issue by shinzui** [dhall-lang/dhall-haskell#1616]
I am investigating using Dhall to configure a Haskell `cloud-native` app that has a complex configuration. I can't figure out how to make Dhall the source of truth of my config and still have proper types referenced in my Haskell application. I found `staticDhallExpression`, but that does not provide nice types for the app. 

Are there any plans to have a TH function to generate Haskell data types from Dhall?

**Comment by sjakobi** [comment]
> Are there any plans to have a TH function to generate Haskell data types from Dhall?

AFAIK, no.

What's currently well-supported is to define your configuration types in Haskell and to type-check your Dhall config against the corresponding Dhall types during decoding.

**Comment by shinzui** [comment]
> What's currently well-supported is to define your configuration types in Haskell and to type-check your Dhall config against the corresponding Dhall types during decoding.

Wouldn't that result in a lot of duplication?

**Comment by sjakobi** [comment]
> Wouldn't that result in a lot of duplication?

Not if you keep the Dhall types implicit (and derived from the Haskell types), I believe.

I don't have a lot of experience _using_ the marshalling functionality though. I'm also not sure whether I really understand your problem. Some more details might be helpful…

**Comment by shinzui** [comment]
Let's say I have a simple config in Dhall that I want to use in my Haskell app. 

```dhall
let Environment = < Production | Staging | Development | Test >

let GcpConfig = { subscription : Text, topic : Text, projectId : Text }

let Configuration = { gcpConfig : GcpConfig, environment : Environment }

in  { gcpConfig =
        { subscription = "sub", topic = "topic", projectId = "project" }
    , environment =
        Environment.Production
    }

```

Now, I want to have my Haskell app read this config and use it. To do that currently, I need to duplicate the types in Haskell (unless I'm missing something).

```haskell
import           Dhall (FromDhall, Generic, Text, ToDhall, auto, detailed,
                        input)

data GcpConfig = GcpConfig {
subscription :: Text,
topic        :: Text,
projectId    :: Text
                           }
                           deriving (Generic, Show)

data Environment = Production | Staging | Development | Test
                           deriving (Generic, Show)

data Configuration = Configuration {
gcpConfig   :: GcpConfig ,
environment :: Environment

                                   }
                           deriving (Generic, Show)

instance FromDhall GcpConfig
instance ToDhall GcpConfig
instance FromDhall Environment
instance ToDhall Environment
instance FromDhall Configuration
instance ToDhall Configuration
```

My question is, how can I derive the `GcpConfig`, `Environment`, and `Configuration`, so I don't have to duplicate them.

**Comment by sjakobi** [comment]
In principle, you can get the Dhall type from the `expected` field of the [`Decoder`](http://hackage.haskell.org/package/dhall-1.28.0/docs/Dhall.html#t:Decoder) (which you can generate via `FromDhall`).

In the case of the `GcpConfig` and `Configuration` record types, it's not obvious to me why you need the types at all. For union types, I agree that a convenient way to generate them, seems useful.

**Comment by shinzui** [comment]
> In the case of the GcpConfig and Configuration record types, it's not obvious to me why you need the types at all. 

I included the simplest example I can think of to illustrate my problem, but the configuration is going to be quite complicated, so please don't focus on the example. My goal is to use Dhall to create a DSL that every microservice can use to configure itself. Being able to derive the Haskell types will make the task more straightforward.

**Comment by sjakobi** [comment]
You may want to look at how [`dhall-kubernetes`](https://github.com/dhall-lang/dhall-kubernetes) generates its types then.

**Comment by Gabriel439** [comment]
@sjakobi: I think what @shinzui wants is for Dhall to be something like how protocol buffers (or other IDLs) works, where Dhall is the IDL and then some executable generates language-specific bindings to the Dhall types

**Comment by shinzui** [comment]
> I think what @shinzui wants is for Dhall to be something like how protocol buffers (or other IDLs) works, where Dhall is the IDL and then some executable generates language-specific bindings to the Dhall types

Yes. In the case of Haskell, it would be preferable to have a TH function to generate the bindings instead of having the code-generation done by a separate executable.

**Comment by Gabriel439** [comment]
The fix for this is up here: https://github.com/dhall-lang/dhall-haskell/pull/1620

**Comment by shinzui** [comment]
#1620 looks good. I'll give it a try as soon as it's merged.
