### ISSUE TITLE
Support absolute imports

### ISSUE THREAD

**Issue by azuzunaga** [dhall-lang/dhall-haskell#1632]
When using  VSCode with the extension `vscode-dhall-lsp-server` an error with the text `Error: Missing file ...` shows up whenever using imports from the root dir. Expected behavior is that absolute imports are resolved correctly.

**Comment by sjakobi** [comment]
Thanks for the report!

Can you check that you can import the same file via the CLI? E.g.

```
$ echo '/x/y/z' | dhall resolve
```

**Comment by azuzunaga** [comment]
Thanks for the response! Good question. I can import the file from the root directory, but not from the directory with the file doing the import. Does that make sense?

So in `.` I can import './x/z/y', but let's say the error I see is in a file in `./a/b/c`, so doing the CLI import from `./a/b/c` for file `./x/y/z` fails.

Maybe there is a configuration flag I'm missing (like in node, where you can set the source directory)?

**Comment by sjakobi** [comment]
Hm, I don't quite understand what you're saying. I wonder whether the syntax for absolute imports is a problem.

Say your `pwd` is `/home/me` and contains a file `foo`. Then you should be able to import that file both as

`./foo` (relative import)

and as

`/home/me/foo` (absolute import)

and e.g.

    assert : ./foo as Text === /home/me/foo as Text

should typecheck.

**Comment by azuzunaga** [comment]
Let me try to explain better:

A file `foo` is in `./a/b/c/d`, and the file it is trying to import, `bar`, is in `./z/x/y`, however, when trying to import `bar` from `foo` as an absolute import (`./z/x/y/bar`), the path that gets resolved is `./a/b/c/d/z/x/y/bar`.

Does that make more sense?

**Comment by sjakobi** [comment]
Ah, right. `a/b/c/d/foo` should import `../../../../z/x/y/bar` then.

**Comment by azuzunaga** [comment]
Thanks @sjakobi! The project I'm working on uses the absolute import for `bar` from `foo`, so I guess I'm going to try to understand a bit better how that is working on my end. I'll reopen the issue if it makes sense to do so. Thanks again!

**Comment by Gabriel439** [comment]
@azuzunaga: Note that `./z/x/y/bar` is not an absolute import because of the initial `.`.  If you were to change it to `/z/x/y/bar` then it would be an absolute import
