### ISSUE TITLE
`to-directory-tree` doesn't create subdirectories

### ISSUE THREAD

**Issue by timbertson** [dhall-lang/dhall-haskell#1633]
aside: thanks for `for-directory-tree`, I'm very excited to use it :D

```
$ echo '{ a = "hello" }' | dhall to-directory-tree --output issue
$ cat issue/a
hello

$ echo '{ `a/b` = "hello" }' | dhall to-directory-tree --output issue
dhall: issue/a/b: openFile: inappropriate type (Not a directory)
```

If I `mkdir -p issue/a` first it works, but that's obviously inconvenient.

While I'm at it, my initial assumption was that `to-directory-tree` would take a map, instead of a record literal. That seems like it could be more flexible (because the keys can be programmatically generated too), and would also remove the need to support `Optional Text` (you could just filter out the unwanted items from the map). Should I make a separate issue for that, or does it intentionally not support maps?

**Comment by sjakobi** [comment]
@timbertson Instead of

```
$ echo '{ `a/b` = "hello" }' | dhall to-directory-tree --output issue
```

you can use

```
$ echo '{ a = { b = "hello" } }' | dhall to-directory-tree --output issue
```

Does that work for you?

**Comment by Profpatsch** [comment]
We should disallow `/` in the keys for that and tell the user that they should use nested records instead.

**Comment by Gabriel439** [comment]
Yeah, I would be fine with changing the `to-directory-tree` command to disallow `/` in the keys

**Comment by timbertson** [comment]
Oh, I was kind of relying on that actually. I am combining a number of
files from multiple places, and (for example) a couple of unrelated files
both belong in `scripts/` (one for docker, one for Travis). Having to pluck
those out from each place and put them into a record makes it hard to
combine multiple file sets.

**Comment by timbertson** [comment]
Sure. It may be that I can use `/\` to do everything I need, it just may be fragile when multiple things come into play (recursive merges _and_ overrides).

The basic idea is that I want to package up some common boilerplate, and reference it (via remote import) from many git repos. So (greatly) simplified I might have a `Travis.dhall` module which provides:

```
{
, `.travis.yaml` = "TODO"
, `script/lint.sh` = "TODO"
}
```

The `script/lint.sh` path would be referenced in .travis.yaml, so the user of this module shouldn't be responsible for choosing where that file goes.

Then say I've got a `Docker.dhall` module which provides:

```
{
, `Dockerfile` = "TODO"
, `script/compile.sh` = "TODO"
}
```

Again, the script path is used by the Dockerfile, so it should all be under control of this module.

To bring together the final set, I was doing `./Travis.dhall // ./Docker.dhall // { ... extra files as a record literal }`

I believe I can use nested records and `/\`. But thinking ahead, I expect I might want some default provided files (for convenience) which some users may wish to override or opt out of. I _could_ do that with, say:

```
{
, `Dockerfile` = "TODO"
, script = {
  , `compile.sh` = "TODO"
  , `optionalStuff.sh` = Some Text "TODO"
  }
}
```

Which then makes it quite difficult to combine _and_ override:
```
let dockerStuff =
  let base = ./Docker.dhall
  in
  base // { script = base.script // { `optionalStuff.sh` = None Text } }

in
(./Travis.dhall /\ dockerStuff) // { ... extra files as a record literal }
```

So it all seems possible, but:
 - Having to manually merge multiple levels with `//` to override is awkward
 - Knowing when to use `//` vs `/\` is not obvious (using `/\` when you want to override will at least give you an error, but doing the opposite will result in silently omitting files in any overridden subdirectory (`script/` in this case))

Flat records with directory-separated paths makes all this much simpler, because the data structure is flat. I can see how it's awkward to have two representations for the same thing though. So perhaps this is just another use case for https://github.com/dhall-lang/dhall-lang/issues/448 or https://github.com/dhall-lang/dhall-lang/issues/340

**Comment by sjakobi** [comment]
Thanks for the great explanation!

> * Having to manually merge multiple levels with `//` to override is awkward

Indeed. [Lenses](https://github.com/dhall-lang/dhall-lang/issues/754#issuecomment-574455857) should eventually make this easier but they're not here yet.

> * Knowing when to use `//` vs `/\` is not obvious (using `/\` when you want to override will at least give you an error, but doing the opposite will result in silently omitting files in any overridden subdirectory (`script/` in this case))

Fair point. IMHO it's generally good to start with `/\`, and to use `//` only when fields must be overridden. You could also give [record completions](http://hackage.haskell.org/package/dhall-1.29.0/docs/Dhall-Tutorial.html#g:12) a try.

> I can see how it's awkward to have two representations for the same thing though.

Yes, I think that would make things more complicate down the road.

I think you should give nested records a try for now. If that turns out to be too inergonomic or cause other problems, please report back, and we'll try to find a solution.

**Comment by timbertson** [comment]
Yeah, I'll give that a try. I hopefully won't actually need overrides much
or at all in the end anyway. Thanks for the discussion. Should I leave this
open (and/or rename) to track "disallow keys with a slash in them"?

**Comment by Gabriel439** [comment]
@timbertson: For what it's worth, I think we might be able to support deep overrides after all and I have a comment related to that here: https://github.com/dhall-lang/dhall-lang/issues/754#issuecomment-575947214

**Comment by bfrk** [comment]
@timbertson wrote:
> While I'm at it, my initial assumption was that `to-directory-tree` would take a map, instead of a record literal. That seems like it could be more flexible (because the keys can be programmatically generated too), and would also remove the need to support `Optional Text` (you could just filter out the unwanted items from the map). Should I make a separate issue for that, or does it intentionally not support maps?

+1 from me. I was just going to open an issue to request this feature.

**Comment by sjakobi** [comment]
@timbertson, @bfrk By "map" you mean this type, right?

```dhall
List { mapKey : Text, mapValue : Text }
```

**Comment by bfrk** [comment]
Yup. Also known as https://prelude.dhall-lang.org/Map/Type

**Comment by harris-chris** [comment]
This is a very useful feature, but I seem to be hitting a bit of a limitation:
- if you're passing in a record, the keys are set at the type level, so you can't have an arbitrary or programmatically defined number of files/directories at any given level of your structure
- but if you're passing in a fileMap, then every item in the list of the fileMap has to have the same type, therefore every branch of the directory structure has to have the same depth
I have a function which would ideally generate a config folder which looks a bit like this:
```
config
|
| -> sub-config-1
|         |
|         | -> _x many files_
|
| -> sub-config-2
          | 
          | -> sub-config-2-1
                    |
                    | -> _y many files_
```
where x and y vary across different calls of the function. I don't think this is possible from a single `dhall to-directory-tree call` because of the limitation above. Up until now I've been calling the function multiple times but this is quite slow (it takes a number of minutes to generate all the config).

**Comment by Gabriella439** [comment]
@harris-chris: Do you have a specific Dhall type in mind that would represent your desired directory tree?  The reason I ask is that I can extend `dhall to-directory-tree` to support additional Dhall types for this purpose

**Comment by harris-chris** [comment]
> @harris-chris: Do you have a specific Dhall type in mind that would represent your desired directory tree? The reason I ask is that I can extend `dhall to-directory-tree` to support additional Dhall types for this purpose

Thanks for the response. I'm sure you'd have a better idea than I, but I can't really see a particularly good solution there, at least not without a heterogenous list type. If `dhall to-directory-tree` accepted a `fileMap` in the following format then that would also work:
```
[ 
    { mapKey = "config/sub-config-1/file1", mapValue = "file 1 contents" }
    , { mapKey = "config/sub-config-2/sub-config-2-1/file2", mapValue = "file 2 contents" }
]
```
However I'd agree with the comments above, that that approach is a bit clunky compared to having nested records.

For the real-life situation I have here, I've just contrived the structure of the config files to have the same depth across the board, which is a perfectly fine work-around.

**Comment by Gabriella439** [comment]
What if `dhall to-directory-tree` were to support `Prelude.JSON.Type`?  Would that work for you?

**Comment by harris-chris** [comment]
That sounds like it would be a convenient solution, yes. So am I right in thinking that from bash I'd do something like, say:
```
$ dhall to-directory-tree --output my-directory-tree | dhall-to-json "(./file-containing-a-normal-record-expression.dhall)"
```

**Comment by Gabriella439** [comment]
What I mean is that the input would be a Dhall expression of this type:

https://store.dhall-lang.org/Prelude-v21.1.0/JSON/Type.dhall.html

… but you could create a value of that type using `json-to-dhall` if you wanted to

**Comment by harris-chris** [comment]
Right, of course. Yes, that would work well.

**Comment by harris-chris** [comment]
Hello - another observation about this feature - is there a particular reason that it can't be used to create empy folders? For example, 
```
dhall to-directory-tree <<< "[ { mapKey = \"empty_folder\", mapValue = [] : List { mapKey : Text, mapValue : Text } } ]" --output testing
```
is an invalid expression for `to-directory-tree`. Setting `mapValue` to `None` will create an empty `testing` folder, but with no `empty_folder` sub-folder.

**Comment by harris-chris** [comment]
Thank you, this does seem like a viable work-around.
