### ISSUE TITLE
Allow single quotes (') in double quote strings

### ISSUE THREAD

**Issue by aleator** [dhall-lang/dhall-haskell#164]
I think the following is a bug in dhall 1.7.0:

```
(stdin):74:82: error: expected: "${",
    "''", "''${", "'''", "\n",
    "\r\n", "\t"
<o fill out few easy survey questions. (If you really don't want to, go to the
                                                         ^
```

This error appears inside `''`-quoted string.

My understanding of the tutorial is that one should be able to use single quotes inside doubly-single-quoted string since the tutorial does not explain how to quote them.

**Comment by Gabriel439** [comment]
Yeah, this is a bug in the implementation (it wasn't following the language standard correctly).  I'll fix it
