### ISSUE TITLE
parser error using double followed by another value

### ISSUE THREAD

**Issue by gbwey** [dhall-lang/dhall-haskell#1646]
I am getting an error when using a Double followed by any other value

```
let f = \(d : Double) -> \(i : Integer) -> {=} in f 3.1 -1

Error: Invalid input
(input):1:57:
  |
1 | let f = \(d : Double) -> \(i : Integer) -> {=} in f 3.1 -1
  |                                                         ^
unexpected '-'
expecting ->, :, end of input, operator, or whitespace

```
this works:
let f = \(d : Double) -> \(i : Integer) -> {=} in f (3.1) -1

**Comment by sjakobi** [comment]
Interesting!

Since the problem seems to be related to the `Double` parser, I wonder whether the bug is somewhere in the `parsers` library, which we rely on:

https://github.com/dhall-lang/dhall-haskell/blob/6ccf08d6fb28ee35cf9e938cdce225e65ea84df6/dhall/src/Dhall/Parser/Token.hs#L191-L195

http://hackage.haskell.org/package/parsers-0.12.10/docs/Text-Parser-Token.html#v:double

**Comment by gbwey** [comment]
I replaced double with my own simpler version and the error went away.
I also noticed that the documentation explicitly mentions "This parser does NOT swallow trailing whitespace" for a number of methods (eg decimal) but not for double. 

To get around this parsers provides Unspaced but Dhall uses someSpace = ... which probably conflicts.

```
instance TokenParsing m => TokenParsing (Unspaced m) where
  someSpace = empty
```

**Comment by sjakobi** [comment]
Hm, this might be worth bringing up at https://github.com/ekmett/parsers/issues!?

**Comment by gbwey** [comment]
My only hesitation is that the api for parsers does have this support but it is all or nothing. Ie you have to commit to dealing with trailing spaces up front or not.
Maybe we could get around this by using Text.Megaparsec.Char.Lexer.float instead? 
However, I am not sure if it will match the requirements of parsers:double or more importantly the dhall spec. What do you think?

**Comment by sjakobi** [comment]
> Maybe we could get around this by using Text.Megaparsec.Char.Lexer.float instead?

Yes, that looks good. Would you care to make a PR? The testsuite includes the acceptance tests for the Dhall standard, so if it passes, it's probably fine.

See https://github.com/dhall-lang/dhall-lang/blob/8cf71d94bd63710faae018aac0920b937b977b11/standard/dhall.abnf#L475-L490 for the spec.

**Comment by Gabriel439** [comment]
I have a fix up here: https://github.com/dhall-lang/dhall-haskell/pull/1647
