### ISSUE TITLE
dhall-to-json 1.6.1 doesn't support JSON.Type from Prelude v13.0.0

### ISSUE THREAD

**Issue by akshaymankar** [dhall-lang/dhall-haskell#1665]
Sample failing code:
```
let Prelude =
      https://prelude.dhall-lang.org/v13.0.0/package.dhall sha256:4aa8581954f7734d09b7b21fddbf5d8df901a44b54b4ef26ea71db92de0b1a12

in  Prelude.JSON.string "string"
```

```
$ dhall-to-json --file example.dhall

Error: Cannot translate to JSON

Explanation: Only primitive values, records, unions, ❰List❱s, and ❰Optional❱
values can be translated from Dhall to JSON

The following Dhall expression could not be translated to JSON:

↳   λ(_ : Type)
  → λ ( _
      : { array : List _ → _@1
        , bool : Bool → _@1
        , double : Double → _@1
        , integer : Integer → _@1
        , null : _
        , object : List { mapKey : Text, mapValue : _ } → _@1
        , string : Text → _@1
        }
      )
  → _.string "string"

```

This however works with `dhall-to-json` installed from here: https://hydra.dhall-lang.org/build/51355. Is this already fixed? And should the dhall-haskell release say that `dhall-to-json` doesn't in fact work with `Prelude-v13.0.0`?

**Comment by sjakobi** [comment]
I believe Gabriel fixed this already in https://github.com/dhall-lang/dhall-haskell/commit/d0c73e6a0c77da89f9e9b9312cccfdf2b02813b9.

**Comment by Gabriel439** [comment]
Yeah, this was fixed in https://github.com/dhall-lang/dhall-haskell/pull/1631 and there will be a new release soon (once https://github.com/dhall-lang/dhall-lang/pull/908 is merged)
