### ISSUE TITLE
yaml-to-dhall error pasing keys with . dot

### ISSUE THREAD

**Issue by fkowal** [dhall-lang/dhall-haskell#1667]
test.yaml 
```yaml
key.value: "test"
```

this fails with the above yaml
```
yaml-to-dhall '{ key : { value : Text} }' --file ./test.yaml

Error: Key(s) key.value present in the YAML object but not in the expected Dhall record type. This is not allowed unless you enable the --records-loose flag:

Expected Dhall type:
{ key : { value : Text } }

YAML:
key.value: test
```

works fine if the yaml uses a different "formatting":
```
key:
   value: "test"
```

**Comment by sjakobi** [comment]
I wasn't aware that

> ```yaml
> key.value: "test"
> ```

and 


> ```yaml
> key:
>    value: "test"
> ```

are equivalent in YAML. The former is a mapping containing with a single key `key.value`, the latter is a mapping with a single key `key` that contains another mapping.

Are there YAML dialects that have a dotted-field syntax similar to TOML or Dhall v14?

**Comment by fkowal** [comment]
https://github.com/toml-lang/toml#keys toml keys section has a similar example as the one above

as i am not sure sure about dhall v14
but the output of yaml-to-dhall for second example 
```bash
yaml-to-dhall '{ key : { value : Text} }' --file ./test.yaml
{ key.value = "test" } <- gives this output
```

so i would yes both dialects seem to treat the . dot syntax the same way

i know that x.y.z is a common shortcut syntax used in spring boot yaml's
and that's why i am assuming that both represent the same thing

in general as far as i can tell
```
key.value1: v1
key.value2: v2

--
key:
  value1: v1
  value2: v2
```
are equivalent

**Comment by sjakobi** [comment]
Well the obvious translation from

```yaml
x.y: z
```

…to Dhall would be

```dhall
{ `x.y` = "z" }
```

But if there's a lot of demand for interpreting it as

```dhall
{ x = { y = "z" } }
```

…we could probably add an option.

Supporting a lot of non-standard YAML tricks seems like a bit of a maintenance hassle, so I wonder whether you could alternatively use some kind of YAML preprocessor that translates

```yaml
x.y: z
```

…to

```yaml
x:
  y: z
```

**Comment by Gabriel439** [comment]
@fkowal: It's not safe for us to implement what you suggest.  There are almost certainly current users depending on the old behavior of interpreting dots as part of the label name and making this change would break their configuration files.

It's also not standards-compliant, either.  YAML doesn't supported the dotted syntax for nested fields like Cue/TOML/Dhall do.

**Comment by fkowal** [comment]
@Gabriel439 of course I understand

just wanted to bring this to your attention. I was thinking that this might have slipped through the parser's edge-cases. I can't really tell if it's a part of the standard or not.

it's not a blocking issue I was able to rewrite the yaml x.y.z to x:y:z which fixed my use-case

It only makes sense to support this format if it's a part of the standard and I am trying to read the yaml.org docs but feels like looking at Egyptian pictograms.

Feel free to close this issue
