### ISSUE TITLE
makeHaskellTypeFromUnion does not create types for nested unions

### ISSUE THREAD

**Issue by anttih** [dhall-lang/dhall-haskell#1668]
I just tried to use `makeHaskellTypeFromUnion` and realised that it is less useful than I initially thought because I cannot create a Haskell type for a Dhall type which contains a nested union.

```
Dhall.TH.makeHaskellTypeFromUnion "Top" "< Nested : < First | Second > >"
```

Am I correct that this is not possible? If this is indeed the case then I think we should document this a bit more clearly.

**Comment by Gabriel439** [comment]
@anttih: Actually, the thing you want is merged into `master` and will be available in the next release.  See: https://github.com/dhall-lang/dhall-haskell/pull/1664

Basically, given these Dhall definitions:

```dhall
-- ./Top.dhall
< Nested : ./Inner.dhall >
```

```dhall
-- ./Inner.dhall
< First | Second >
```

... then you'll be able to write:

```dhall
Dhall.TH.makeHaskellTypes
    [ MultipleConstructors "Top" "./Top.dhall"
    , MultipleConstructors "Inner" "./Inner.dhall"
    ]
```

... and it should generate this Haskell code:

```haskell
data Top = Nested Inner

data Inner = First | Second
```

**Comment by anttih** [comment]
Wonderful!
