### ISSUE TITLE
`dhall --help` does not include `--inplace` option

### ISSUE THREAD

**Issue by note** [dhall-lang/dhall-haskell#1670]
`dhall --help | grep inplace` returns nothing, checked with dhall `1.29.0`

It should be included as it's an option for `freeze` and `format`.

I would be happy to take care of that. If I felt more familiar with haskell I would just open a PR but since I am not I opened an issue so it will not slip through.

**Comment by sjakobi** [comment]
`dhall freeze --help` and `dhall format --help` include the `--inplace` option.

Is it unusual that subcommand-specific options are not included at the top-level?

**Comment by note** [comment]
@sjakobi you're right it's there. I cannot answer your question but probably subcommand level is enough.

Sorry for the trouble. Feel free to close the issue.

**Comment by sjakobi** [comment]
No worries @note!

My impression is that the `--help` output is pretty conventional in this regard, but maybe that's just because I'm used to it.

If more people are confused about it, we should probably do something about it, but for now I'll optimistically close this.

**Comment by sjakobi** [comment]
For reference, here's a `optparse-applicative` ticket for including subcommand docs in the the top-level `--help` output: https://github.com/pcapriotti/optparse-applicative/issues/175.
