### ISSUE TITLE
Dhall format converts hexadecimal to decimal

### ISSUE THREAD

**Issue by blitz** [dhall-lang/dhall-haskell#1671]
I'm really glad that Dhall supports hexadecimal now! :) That being said, the formatter ruins the fun by automatically converting them back to decimal:

```sh
% echo 0x802000 | dhall format
8396800
```

I personally find this very surprising. Any chance this gets fixed or at least becomes configurable?

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1674

**Comment by blitz** [comment]
@Gabriel439 Thanks for the amazingly fast response! :champagne:

**Comment by Gabriel439** [comment]
@blitz: You're welcome! 🙂
