### ISSUE TITLE
[Dhall.TH] Derive instances automatically

### ISSUE THREAD

**Issue by srid** [dhall-lang/dhall-haskell#1679]
If `makeHaskellTypes` generated these instances automatically, that would be handy (and `StandaloneDeriving` need not be enabled).

```haskell
makeHaskellTypes
  [ SingleConstructor "Config" "Config" "./src-dhall/Config.dhall"
  ]

deriving instance Generic Config
deriving instance FromDhall Config
```

At minimum `Generic` and `FromDhall` is required to be able to parse the files using `input`. But we might want to generate other instances, like `Show`, as well.

**Comment by Gabriel439** [comment]
I have a fix up which derives `Generic`/`FromDhall`/`ToDhall` for now: https://github.com/dhall-lang/dhall-haskell/pull/1682
