### ISSUE TITLE
Dhall excessive memory consumption with couple of imports

### ISSUE THREAD

**Issue by naglalakk** [dhall-lang/dhall-haskell#1691]
System info:
OS: macOS Mojave, version 10.14.6
ghc-version: 8.6.5
cabal-version: 3.0.0.0

Hi. I'm wondering what newbie mistake I might be doing. If I try to import this into Haskell the memory keeps going up until I have to manually kill the process. This is my config file.
I expect some delay since it is actually a lot to deserialize but this seems off. 

The config file
```
{ name = "Notification App"
, generate = 
    { pages = [
        { pageName = "Home"
        , url = Some "/"
        , htmlElements = [
            { tag = "h1"
            , text = Some "Welcome to the notification page"
            , class = None Text
            , style = Some "text-align:center"
            },
            { tag = "div"
            , text = None Text
            , class = (Some "notification-container")
            , style = None Text
            }]
        }]
    , services = [
        { serviceName = "notification-service"
        , version = Some "1"
        , serviceConfig = Some
          { port = Some "8080"
          , plugin = Some "servant"
          }
        , endpoints = 
            [{ endpoint = "notifications"
            , dataModel = "notifications"
            , methods   = 
              [ "GET"
              , "POST"
              , "PUT"
              , "PATCH"
              , "DELETE"
              ]
            , filters   = [ "desc" ]
            }]
        , serviceModels = [
            { modelName = "Notification"
            , identifier = "notifications"
            , modelConfig = Some
              { enableSearch = True
              , searchEngine = Some "elasticsearch"
              }
            , fields = [
                { fieldName  = "content"
                , fieldType  = "text"
                , default    = None Text
                , null 	     = True 
                },
                { fieldName  = "created_at"
                , fieldType  = "date"
                , default    = Some "now"
                , null       = False
                }]
            }]
        }]
    }
} : ./../../dhall/Application.dhall
```

Imagine all the sections in this config have definitions but they are within Application. 
Application is a nested record that looks like this

```
{ name : Text
, generate :
  { pages : List ./Page.dhall
  , services : List ./Service.dhall
  }
}
```

Haskell code is
```
{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE OverloadedStrings #-}

import Dhall

import Cherry.Application       (Application)

main :: IO ()
main = do
    x <- input auto "./test/files/one.dhall"
    print (x :: Application)
```
Some questions that might help 

**How do you declare types?**

I add them to a file without any further declaration like so
```
-- ./user.dhall
{ id : Natural
, username : Text
}
```

**How do you declare nested data structure?**

I use let and in like so
```
let ModelField =
  { fieldName : Text
  }
in Model
  { fields : List ModelField
  }
```

**Comment by sjakobi** [comment]
Is `Application` recursive in some way? In that case you might be running into https://github.com/dhall-lang/dhall-haskell/issues/1660.

Regarding your questions: Both type definitions look fine to me.

**Comment by sjakobi** [comment]
Since you're hinting at an issue with imports, can you still reproduce the issue when the config doesn't use imports? You can use `dhall resolve` to produce a version where any imports are inlined.

**Comment by naglalakk** [comment]
Thank you for a quick reply @sjakobi. I think I see now why this was happening. I did indeed have a recursive field. I had removed it from the dhall file but not from the Haskell data type. Now i get mismatch errors but at least it's not halting anymore. Going to get it to match and see if it runs before confirming this.

**Comment by naglalakk** [comment]
Yes confirmed. This takes no time to execute now. It was the recursive data type in my Haskell code. Closing this now. Thank you so much for a quick respone @sjakobi

**Comment by sjakobi** [comment]
You're welcome, @naglalakk! :)

I hope we can arrange to at least produce a proper error for similar cases soon!
