### ISSUE TITLE
Add dhall-lsp-server to Stackage

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1697]
I'm just recording this task:

The latest `dhall-lsp-server` release is incompatible with the latest `haskell-lsp`. Once we have release that includes https://github.com/dhall-lang/dhall-haskell/pull/1684, we can add `dhall-lsp-server` to Stackage.

**Comment by sjakobi** [comment]
PR for Stackage: https://github.com/commercialhaskell/stackage/pull/5283

**Comment by Gabriel439** [comment]
Closing as fixed since the linked PR was merged
