### ISSUE TITLE
dhall to-directory-tree: treat dynamic maps as directories

### ISSUE THREAD

**Issue by bfrk** [dhall-lang/dhall-haskell#1704]
This feature would be even more useful if dynamic maps would be interpreted as directories in the same way as records are. See https://github.com/dhall-lang/dhall-haskell/issues/1633#issuecomment-598325109

**Comment by bfrk** [comment]
This could be generalised by adding a built-in function to the languager that converts a record to a dynamic map. Or one could go yet anotehr step further and add a generic function that reflects any type to the value level.

**Comment by sjakobi** [comment]
> This could be generalised by adding a built-in function to the languager that converts a record to a dynamic map.

Do you mean `toMap`?

Or maybe I'm misunderstanding what you mean by "dynamic map". Are you referring to

    List { mapKey : Text, mapValue : Text }

?

**Comment by bfrk** [comment]
Sorry. What I referred to as a "generalization" is already there, thanks for pointing me to `toMap`. But that doesn't help here, because we would need conversion in the other direction.

**Comment by Gabriel439** [comment]
The fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1705
