### ISSUE TITLE
Github action to setup and install dhall

### ISSUE THREAD

**Issue by craig-day** [dhall-lang/dhall-haskell#1718]
I'm not sure if this is the best place, but I figured I would start here. 

Just wanted to make you aware of a Github action I put together to install dhall and dhall-json and make the executables available for further actions. https://github.com/craig-day/setup-dhall

I did this, because previously I was using the `setup-haskell` option, which required running `cabal update` and then `cabal install dhall`. Since cabal had no packge information, it would fetch everything from scratch and took about 10 minutes to run the action to install a specific version of dhall. 

If it's of interest to you, I think it could be worth having the action under the `dhall-lang` organization and submitting the action to the official actions marketplaces. 

Thanks for making the install so easy! I hope others find this useful.

**Comment by Gabriel439** [comment]
@craig-day: Yeah, I think this is a great idea!  I can add you to the organization so that you can set things up

**Comment by craig-day** [comment]
Awesome. Thanks @Gabriel439. A few questions on how you think we can handle this nicely: 

- Should I fork the repo into dhall-lang, or change the owner? I think change owner, but wanted to verify.
- The license currently for v2 is MIT. Would you like me to change it to BSD-3 to match dhall and release v3?

**Comment by Gabriel439** [comment]
@craig-day: I think changing the owner will probably work better

Yeah, if you can change the license to match it will be easier

**Comment by craig-day** [comment]
Repo moved with updated license. Thanks for the quick response @Gabriel439 !

**Comment by Gabriel439** [comment]
@craig-day: You're welcome, and thank you for contributing this 🙂
