### ISSUE TITLE
Decoder contract

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1722]
#1711 raised my attention to this contract that I somehow hadn't been aware of before.

https://github.com/dhall-lang/dhall-haskell/blob/0c4b59a02591b65f2076b801e9b5a11d2b2e5596/dhall/src/Dhall.hs#L265-L300

If I understand this contract correctly, we have at least two `Decoder`s that break it:

* https://github.com/dhall-lang/dhall-haskell/blob/0c4b59a02591b65f2076b801e9b5a11d2b2e5596/dhall/src/Dhall.hs#L939-L940
* https://github.com/dhall-lang/dhall-haskell/blob/0c4b59a02591b65f2076b801e9b5a11d2b2e5596/dhall/src/Dhall.hs#L968-L971

We also use these `Decoder`s in the instances for `Set` and `HashSet`.

I've also suggested defining contract-breaking `Decoder`s to @SiriusStarr before…

What's the reasoning behind this contract?

If we want to keep this contract, we should document it in the haddocks for `Decoder`.

**Comment by Gabriel439** [comment]
@sjakobi: That contract was created before we started adding support for custom decoders with post-marshaling validation checks.  I think it's fine to remove the contract or update it to reflect the new use cases for custom decoders.

**Comment by sjakobi** [comment]
> if an expression's type matches the `expected` type then the `extract` function must not fail with a type error.

I think I had simply overlooked the `with a type error` bit. The contract does seem to allow `extract` to fail with a non-type error. Maybe we could add a sentence like

> `extract` may fail for other reasons though.
