### ISSUE TITLE
dhall format desugars record puns

### ISSUE THREAD

**Issue by ari-becker** [dhall-lang/dhall-haskell#1728]
In `1.31.0`,

```dhall
let Foo = { foo = "hi" } in { Foo }
```
`dhall format` adjusts this to:
```dhall
let Foo = { foo = "hi" } in { Foo = Foo }
```
which, accordingly, causes `dhall lint --check` to fail when the pun syntax is used.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1729

**Comment by amesgen** [comment]
What about record completions? `prettyRecordEntry` is different in `prettyRecordLit` and `prettyCompletionLit`.

Unformatted:
```dhall
let T = { Type = { x : Text }, default = {=} } let x = "lul" in T::{ x }
```

Formatted:
```dhall
let T = { Type = { x : Text }, default = {=} } let x = "lul" in T::{ x = x }
```

**Comment by sjakobi** [comment]
Good catch, @amesgen! :)

Would you be interested in fixing this in a PR?
