### ISSUE TITLE
Is `InputNormalizer` intentionally hidden?

### ISSUE THREAD

**Issue by trskop** [dhall-lang/dhall-haskell#1734]
Sorry if this was mentioned somewhere, or if the new behaviour of `autoWith` is somehow obvious, but reading the ChangeLog hadn't provided with me with the answer I was looking for.

I tried to migrate some of my non-trivial code to 1.31 and hiding `InputNormalizer` prevented me from using manual instances. For for most of the code I don't need the parametrisation and the rest can  use the combinator approach. What surprised me the most is that even the type of `InputNormalizer` is hidden, which prevented me from using `InstanceSigs` for cases when type classes were still a viable option.

What I would like to know is what is the idea behind hiding so much information?

Thanks

**Comment by Gabriel439** [comment]
@trskop: It was a mistake and it is fixed in https://github.com/dhall-lang/dhall-haskell/pull/1727

I plan to cut a new release soon

**Comment by trskop** [comment]
Thanks @Gabriel439! Please, let me know if I can help somehow.

**Comment by Gabriel439** [comment]
@trskop: There's nothing you need to do.  We're already starting the process to cut a new release: https://github.com/dhall-lang/dhall-haskell/pull/1735
