### ISSUE TITLE
Detect `toMap` in `dhall format`

### ISSUE THREAD

**Issue by Nadrieril** [dhall-lang/dhall-haskell#1744]
I'm working with a big `Prelude.JSON.Type` value that I converted from yaml. There are arrays of `mapKey` and `mapValue` all over the place and it's making it hard to read and annoying to convert to proper dhall record by hand. Could `dhall format` detect those and use `toMap` instead when relevant?

**Comment by sjakobi** [comment]
I think that's something that `dhall lint` could do, and that `yaml-to-dhall` and `json-to-dhall` should probably do by default.

I'm not sure whether `dhall format` should perform such refactorings – so far it's limited to applying syntactic sugar like e.g. record puns.

**Comment by Nadrieril** [comment]
I'm happy with `dhall lint` doing it, as long as I don't have to do it by hand

**Comment by Gabriel439** [comment]
I really like this idea

Actually, we could go a step further and have `yaml-to-dhall` also emit `toMap`, too

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1745
