### ISSUE TITLE
`dhall format` messes up precedence of `with`

### ISSUE THREAD

**Issue by Nadrieril** [dhall-lang/dhall-haskell#1747]
If I run dhall format on the following:
```dhall
let Foo =
        Bar
        with default = (Bar.default ⫽ { bar = 0 })
```
I get
```dhall
let Foo =
        Bar
        with default = Bar.default ⫽ { bar = 0 }
```
Which is parsed as
```dhall
let Foo =
        (Bar
        with default = Bar.default) ⫽ { bar = 0 }
```
Which is a very different expression.

To be fair I agree with dhall format that `with` should have lower precedence, probably more akin to `let`. It's on my todo-list of planned changes to the standard

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1748
