### ISSUE TITLE
GADT support: serializing to (and unserializing from) Dhall?

### ISSUE THREAD

**Issue by mx00s** [dhall-lang/dhall-haskell#1753]
## Motivation

GADTs are useful for modeling several domains, and pure Dhall supports types reminiscent of GADTs, e.g. [this grammar](https://gitlab.com/mx00s/dhall-cpeg/-/blob/master/examples/grammar.dhall). However, by design, pure Dhall is computationally limited. To work around that I want to deserialize such expressions into a more powerful language, e.g. Haskell, do some computation, and serialize the result as a Dhall expression of the expected type. More specifically, I'd like to develop a type-safe parser-generator which supports representing all inputs and outputs as Dhall expressions and types.

## Current blocker

The following compiles and prints `< L : Integer | R : Bool >.R True` as expected.

```haskell
{-# LANGUAGE DeriveAnyClass    #-}
{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE GADTs             #-}

import Dhall
import Dhall.Pretty

data BasicGADT a b where
  L :: a -> BasicGADT a b
  R :: b -> BasicGADT a b
  -- X :: BasicGADT a b -> BasicGADT a b
  deriving (Generic, ToDhall)

-- instance (FromDhall a, FromDhall b) => FromDhall (BasicGADT a b)

ppDhall :: ToDhall a => a -> IO ()
ppDhall = print . prettyExpr . embed inject

main :: IO ()
main = ppDhall (R True :: BasicGADT Integer Bool)
```

However, uncommenting the `X` constructor and re-running seemingly causes an infinite loop:

```
$ timeout 10m cabal new-run dhall-gadt-demo
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - dhall-fun-0.1.0.0 (exe:dhall-gadt-demo) (file main.hs changed)
Preprocessing executable 'dhall-gadt-demo' for dhall-fun-0.1.0.0..
Building executable 'dhall-gadt-demo' for dhall-fun-0.1.0.0..
[1 of 1] Compiling Main             ( main.hs, /tmp/dhall-fun/dist-newstyle/build/x86_64-linux/ghc-8.6
.5/dhall-fun-0.1.0.0/x/dhall-gadt-demo/build/dhall-gadt-demo/dhall-gadt-demo-tmp/Main.o )
Linking /tmp/dhall-fun/dist-newstyle/build/x86_64-linux/ghc-8.6.5/dhall-fun-0.1.0.0/x/dhall-gadt-demo/
build/dhall-gadt-demo/dhall-gadt-demo ...
$
```

Memory appears to be the primary bottleneck. The computer I'm using has 32GB.

**Comment by mx00s** [comment]
I ran it again without the 10m timeout:

```
$ \time ./dist-newstyle/build/x86_64-linux/ghc-8.6.5/dhall-fun-0.1.0.0/x/
dhall-gadt-demo/build/dhall-gadt-demo/dhall-gadt-demo
Command terminated by signal 9
259.38user 83.19system 12:03.54elapsed 47%CPU (0avgtext+0avgdata 30753768maxresident)k
73239240inputs+0outputs (2013360major+27609698minor)pagefaults 0swaps
```

I'm pretty sure the OOM killer crashed it.

**Comment by Gabriel439** [comment]
@mx00s: I believe this is the same issue as: https://github.com/dhall-lang/dhall-haskell/issues/1660

Dhall does not yet support deriving `ToDhall`/`FromDhall` for recursive types.  Currently, only `Fix` is supported, so you can derive a `FromDhall` instance for `BasicGADT` using `Fix` as an intermediate type, like this:

```haskell
{-# LANGUAGE DeriveAnyClass     #-}
{-# LANGUAGE DeriveTraversable  #-}
{-# LANGUAGE DeriveGeneric      #-}
{-# LANGUAGE GADTs              #-}
{-# LANGUAGE KindSignatures     #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE TemplateHaskell    #-}
{-# LANGUAGE TypeApplications   #-}
{-# LANGUAGE TypeFamilies       #-}

import GHC.Generics (Generic)
import Dhall (FromDhall(..), ToDhall)

import qualified Data.Fix                 as Fix
import qualified Data.Functor.Foldable    as Foldable
import qualified Data.Functor.Foldable.TH as TH
import qualified Dhall
import qualified Dhall.Pretty

data BasicGADT a b where
  L :: a -> BasicGADT a b
  R :: b -> BasicGADT a b
  X :: BasicGADT a b -> BasicGADT a b
  deriving (Generic, ToDhall)

TH.makeBaseFunctor ''BasicGADT

deriving instance Generic (BasicGADTF a b c)
deriving instance (FromDhall a, FromDhall b, FromDhall c) => FromDhall (BasicGADTF a b c)

instance (FromDhall a, FromDhall b) => FromDhall (BasicGADT a b) where
    autoWith = fmap (fmap convert) autoWith
      where
        convert = Fix.cata Foldable.embed

main :: IO ()
main = do
    print (Dhall.Pretty.prettyExpr (Dhall.expected (Dhall.auto @(BasicGADT Integer Bool))))
```

... although currently `Fix` only has support for `FromDhall` (but I can fix that; it's an oversight)

Alternatively, you can hand-write the `FromDhall`/`ToDhall` instances, which will probably lead to a cleaner expected Dhall type.  The type printed by the above program is:

```dhall
  ∀(result : Type)
→ ∀(Make : < LF : Integer | RF : Bool | XF : result > → result)
→ result
```

... which adds an "F" to all constructor names (because it goes through the `Fix (BasicGADTF a b)` intermediate type) and also uses a sum type.  If you hand-write the instance you can get something that is probably closer to what you wanted:

```dhall
  ∀(BasicGADT : Type)
→ ∀(L : Integer → BasicGADT)
→ ∀(R : Bool → BasicGADT)
→ ∀(X : BasicGADT → BasicGADT)
→ result
```

Fixing the derived instance for directly-recursive types is more tricky (and see #1660 for more details)

**Comment by mx00s** [comment]
Wow, thanks for the quick, detailed response.

The hand-written approach is indeed closer to what I want. It's good to know about the `Fix` approach too.

I'll close this in favor of the issue you linked.

**Comment by Gabriel439** [comment]
@mx00s: You're welcome! :slightly_smiling_face:
