### ISSUE TITLE
Hackage documentation does not exist for dhall-nix

### ISSUE THREAD

**Issue by turion** [dhall-lang/dhall-haskell#1756]
This link is broken: https://hackage.haskell.org/package/dhall-nix-1.1.13/docs/Dhall-Nix.html

**Comment by turion** [comment]
It is linked from `dhall-nix/README.md`.

**Comment by sjakobi** [comment]
Thanks for the report. As Hackage's docs builder [reports](http://hackage.haskell.org/package/dhall-nix-1.1.13/reports/3), the underlying issue is in `hnix`: https://github.com/haskell-nix/hnix/issues/538

**Comment by Gabriel439** [comment]
I will close this in favor of tracking the issue in https://github.com/haskell-nix/hnix/issues/538
