### ISSUE TITLE
dhall-to-nix: add `--omit-null` flag (or `--preserve-null`)

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-haskell#1764]
```
> echo "{ foo = None Text }" | dhall-to-json
{}

> echo "{ foo = None Text }" | dhall-to-json --preserve-null
{
  "foo": null
}

> echo "{ foo = None Text }" | dhall-to-nix
{ foo = null; }

> echo "{ foo = None Text }" | dhall-to-nix --omit-null
Invalid option `--omit-null'

Usage: dhall-to-nix [--version]

ExitFailure 1
```

It would be great if `dhall-to-nix` had a similar behaviour to `dhall-json`.

For consistency, we could omit `None` fields by default and have a `--preserve-null` field like with the `dhall-to-json`.

**Comment by Gabriel439** [comment]
@Profpatsch: I would prefer that this is done on the Nix side.  It wouldn't be too difficult to write a Nix function that post-processes the output of `dhallToNix` to recursively filter out `null`s

**Comment by Profpatsch** [comment]
That’s indeed a better approach.
