### ISSUE TITLE
Help message for `--check` flag is wrong for `dhall freeze` (and somewhat for `lint`)

### ISSUE THREAD

**Issue by SiriusStarr** [dhall-lang/dhall-haskell#1768]
Running `dhall freeze --help` returns
```
Available options:
  --check                  Only check if the input is formatted
```
but the `--check` flag isn't checking "if the input is formatted" in this case but rather if imports have been frozen correctly.  Similarly `dhall lint --help` has the same message (carried over from `dhall format`), which is more apt in that case, but still linting is more than just formatting.  Ideally, the explanation of the `--check` flag would be different for the three commands, though it might not be worth the effort to change?

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1771
