### ISSUE TITLE
Move marshalling code in own module namespace

### ISSUE THREAD

**Issue by mmhat** [dhall-lang/dhall-haskell#1786]
The `Dhall` module is somewhat huge and I hereby propose to split it. Since most of the code deals with marshalling I think that would be a good point to start:

- `Dhall.Marshal.Decode`
  Decoding stuff goes here
- `Dhall.Marshal.Decode.Generic`
  Generic decoding stuff goes here (`GenericFromDhall` + instances)
- `Dhall.Marshal.Decode.Instances`
  Builtin instances for decoding go here
- `Dhall.Marshal.Encode`
  Encoding stuff goes here
- `Dhall.Marshal.Encode.Generic`
  Generic encoding stuff goes here (`GenericToDhall` + instances)
- `Dhall.Marshal.Encode.Instances`
  Builtin instances for encoding go here

I think this would improve the hackabilty of the `Dhall` module a lot. The `Dhall` module should reexport those modules.

**Comment by Gabriel439** [comment]
@mmhat: Yeah, that's fine with me as long as the `Dhall` module still re-exports the functionality
