### ISSUE TITLE
Will not build: Spurious prettyprinter.nix in release.nix

### ISSUE THREAD

**Issue by daig** [dhall-lang/dhall-haskell#179]
The `release.nix` is overriding `prettyprinter` with some local `prettyprinter.nix` which does not exist. Is this override intentional and missing, or is it a leftover that can be removed? It seems to build ok by simply removing that override line, but I haven't checked extensively for subtle bugs.

**Comment by Gabriel439** [comment]
Yeah, that line was something I mistakenly checked in and doesn't belong there.  I will remove it

**Comment by daig** [comment]
Ahh you beat me to the PR ;)
Thanks for the quick fix

**Comment by Gabriel439** [comment]
You're welcome! :)
