### ISSUE TITLE
Freeze error that does not seem right (unknown situation)

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#1794]
I have experienced the following:
```
λ ~ → dhall freeze <<< 'http://stash.cirb.lan/projects/CICD/repos/dhall/raw/openshift/package.dhall'
dhall: 
Error: Remote host not found
URL: http://stash.cirb.lan/projects/CICD/repos/dhall/raw/openshift/package.dhall

λ ~ → curl -sI http://stash.cirb.lan/projects/CICD/repos/dhall/raw/openshift/package.dhall | head -n 1
HTTP/1.1 200
 
λ ~ → dhall version
1.32.0
```
Totally puzzled, someone on the team suggests to remove the cache (~/.cache/dhall). And indeed it solves the problem.

I have no idea what went wrong but share the problem in case it helps to discover an hidden bug.

**Comment by Gabriel439** [comment]
@PierreR: Were you able to reproduce the connection failure more than once before you deleted the cache?  The "Remote host not found" error message means in this case that the interpreter was unable to open a connection to the server at the time, which can be a transient error if the server is temporarily unavailable.

As far as I know, the only thing that changes when you delete the cache is that the interpreter will make more HTTP(S) requests (in order to repopulate the cache).

It's also not clear that this is an error with `dhall freeze`.  Did you try interpreting that import using the vanilla `dhall` command?

**Comment by PierreR** [comment]
@Gabriel439  Thanks for your reply.

Actually trying this again I have just realized the fix has nothing to do with the removal of the cache. That seems to be pure coïncidence.

It is actually failing again right now. With the freeze command but also with a simple import. The only way I have managed to make it work is by replacing the dns with the IP address. 

I guess I have one the dns server that takes too much time to respond ...

**Comment by Gabriel439** [comment]
@PierreR: There might still be something work fixing here.  Perhaps we could retry requests that fail on that specific error?

**Comment by PierreR** [comment]
Yep sure, `curl` seems to handle it alright.

**Comment by Gabriel439** [comment]
@PierreR: Do you know what `curl` does different?  The next time this happens to you, could you try running `curl` with `--verbose` to see how it recovers?

**Comment by sjakobi** [comment]
For reference, there's a handy [`retry` package](http://hackage.haskell.org/package/retry), that we could use here.

**Comment by PierreR** [comment]
As soon as I can I try to come up with an strace of both `curl` and `dhall freeze` to investigate this further

**Comment by sjakobi** [comment]
The proper place to add the retry logic would probably be here:

https://github.com/dhall-lang/dhall-haskell/blob/bfb2a1e044bdf1f106c090ed4cc8503bcfbe3f69/dhall/ghc-src/Dhall/Import/HTTP.hs#L273-L292

(and (maybe less importantly) for GHCJS [here](https://github.com/dhall-lang/dhall-haskell/blob/bfb2a1e044bdf1f106c090ed4cc8503bcfbe3f69/dhall/ghcjs-src/Dhall/Import/HTTP.hs#L31-L46))

We could look at other [`retry` users](https://packdeps.haskellers.com/reverse/retry) for some guidance on which exceptions we should retry after.

**Comment by Gabriel439** [comment]
@sjakobi: Retrying on `ConnectionFailure` would probably be enough to solve the original problem since that's the constructor that corresponds to the "Remote host not found" message

**Comment by PierreR** [comment]
In case it is helpful here is the output of `curl --verbose`
```
→ curl -sI --verbose  http://stash.cirb.lan/projects/CICD/repos/dhall/raw/openshift/package.dhall
*   Trying 192.168.xx.171:80...
* TCP_NODELAY set
* Connected to stash.cirb.lan (192.168.xx.171) port 80 (#0)
> HEAD /projects/CICD/repos/dhall/raw/openshift/package.dhall HTTP/1.1
> Host: stash.cirb.lan
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 
HTTP/1.1 200 
< Server: nginx/1.14.0
Server: nginx/1.14.0
< Date: Wed, 27 May 2020 14:41:49 GMT
Date: Wed, 27 May 2020 14:41:49 GMT
< Content-Type: text/plain;charset=UTF-8
Content-Type: text/plain;charset=UTF-8
< Content-Length: 159
Content-Length: 159
< Connection: keep-alive
Connection: keep-alive
< X-AREQUESTID: @3L43YJx1001x12609622x0
X-AREQUESTID: @3L43YJx1001x12609622x0
< X-ASEN: SEN-2972700
X-ASEN: SEN-2972700
< x-xss-protection: 1; mode=block
x-xss-protection: 1; mode=block
< x-frame-options: SAMEORIGIN
x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
x-content-type-options: nosniff
< Pragma: no-cache
Pragma: no-cache
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Cache-Control: no-cache
Cache-Control: no-cache
< Cache-Control: no-store
Cache-Control: no-store
< Content-Disposition: inline; filename="package.dhall"; filename*=UTF-8''package.dhall
Content-Disposition: inline; filename="package.dhall"; filename*=UTF-8''package.dhall

< 
* Connection #0 to host stash.cirb.lan left intact

→ dhall <<< 'http://stash.cirb.lan/projects/CICD/repos/dhall/raw/openshift/package.dhall' 
dhall: 
Error: Remote host not found

URL: http://stash.cirb.lan/projects/CICD/repos/dhall/raw/openshift/package.dhall

```
The message from dhall is coming very quickly.

**Comment by PierreR** [comment]
strace output for dhall is (I am just replacing some digits with 'xx' for security reasons):
```
socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 0
bind(0, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
sendto(0, "\16\35\1\0\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\1\0\1", 32, MSG_NOSIGNAL, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.xx.244")}, 16) = 32
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=0, ptr=NULL}} ---
rt_sigreturn({mask=[]})                 = 32
sendto(0, "\16\35\1\0\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\1\0\1", 32, MSG_NOSIGNAL, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.28.xy.10")}, 16) = 32
sendto(0, "\16\35\1\0\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\1\0\1", 32, MSG_NOSIGNAL, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.1.1")}, 16) = 32
sendto(0, "\17\22\1\0\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\xx\0\1", 32, MSG_NOSIGNAL, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.xx.244")}, 16) = 32
sendto(0, "\17\22\1\0\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\xx\0\1", 32, MSG_NOSIGNAL, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.28.xy.10")}, 16) = 32
sendto(0, "\17\22\1\0\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\xx\0\1", 32, MSG_NOSIGNAL, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.1.1")}, 16) = 32
poll([{fd=0, events=POLLIN}], 1, 3000)  = 1 ([{fd=0, revents=POLLIN}])
recvfrom(0, "\16\35\201\203\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\1\0\1", 512, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.1.1")}, [16]) = 32
recvfrom(0, 0x7ffe8830f8a8, 512, 0, 0x7ffe8830f350, [16]) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=0, events=POLLIN}], 1, 2994)  = 1 ([{fd=0, revents=POLLIN}])
recvfrom(0, "\17\22\201\203\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\xx\0\1", 512, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.1.1")}, [16]) = 32
close(0)                                = 0
select(0, 0x7ffe883141c0, 0x7ffe88314240, NULL, {tv_sec=0, tv_usec=0}) = 0 (Timeout)
select(0, 0x7ffe883141c0, 0x7ffe88314240, NULL, {tv_sec=0, tv_usec=0}) = 0 (Timeout)
ioctl(1, TIOCGWINSZ, {ws_row=52, ws_col=239, ws_xpixel=0, ws_ypixel=0}) = 0
writev(2, [{iov_base="dhall: ", iov_len=7}, {iov_base=NULL, iov_len=0}], 2dhall: ) = 7
writev(2, [{iov_base="", iov_len=0}, {iov_base="\n\33[1;31mError\33[0m: Remote host n"..., iov_len=123}], 2
Error: Remote host not found
```
dig would anwer this:
```
;; ANSWER SECTION:
stash.cirb.lan.		1506	IN	A	192.168.xx.171

;; Query time: 12 msec
;; SERVER: 192.168.xx.244#53(192.168.xx.244)
```
Not sure what's going on but stracing curl wouldn't even mentionned the dns ip servers from /etc/resolv.conf

**Comment by Gabriel439** [comment]
This makes me believe that our error reporting may be hiding the true cause of the failure.  The `ConnectionFailure` constructor contains a `SomeException` that contains more detailed information but we currently don't display it, so the first step might be to just include that.

From looking through the `http-client` codebase, it looks like the only place that throws a `ConnectionFailure` exception is here:

https://github.com/snoyberg/http-client/blob/c1c6ffa9e7bf3556f8577b12fc2ccb3e92b080a4/http-client/Network/HTTP/Client/Manager.hs#L235-L269

... so I'm trying to reverse engineer what might be going wrong

**Comment by Gabriel439** [comment]
@PierreR: Could you also include an `strace` of a successful `dhall` import, too?

**Comment by Gabriel439** [comment]
@PierreR: This looks like a DNS resolution failure of some form as the `strace` output indicates that the `dhall` executable only made TCP requests to port 53 to various DNS servers.  There might be something different in how Haskell's `http-client` package performs DNS resolution compared to `curl`

**Comment by PierreR** [comment]
@Gabriel439  Yep it is definitely a DNS resolution problem. The only way to make it work is to use the IP

Note that I succeed to ping all the DNS servers without any perceptive sluggishness

```
→ strace dhall <<< ' http://192.168.xx.171/projects/CICD/repos/dhall/raw/openshift/package.dhall'
execve("/nix/store/sprv0kjs0zgsn2vbxxmapwsf4p7hgx01-source/bin/dhall", ["dhall"], 0x7ffce8b3e840 /* 142 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x11ce398)      = 0
set_tid_address(0x11ce3d0)              = 1413
brk(NULL)                               = 0x1a5b000
brk(0x1a5c000)                          = 0x1a5c000
brk(0x1a5f000)                          = 0x1a5f000
brk(0x1a62000)                          = 0x1a62000
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=0, tv_nsec=549029}) = 0
sysinfo({uptime=26514, loads=[21088, 11328, 6432], totalram=9398968320, freeram=6696329216, sharedram=40755200, bufferram=223211520, totalswap=0, freeswap=0, procs=399, totalhigh=0, freehigh=0, mem_unit=1}) = 0
mmap(0x4200000000, 1099512676352, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x4200000000
madvise(0x4200000000, 1099512676352, MADV_DONTNEED) = 0
madvise(0x4200000000, 1099512676352, MADV_DONTDUMP) = 0
mmap(0x4200000000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x4200000000
madvise(0x4200000000, 1048576, MADV_WILLNEED) = 0
madvise(0x4200000000, 1048576, MADV_DODUMP) = 0
mmap(0x4200100000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x4200100000
madvise(0x4200100000, 1048576, MADV_WILLNEED) = 0
madvise(0x4200100000, 1048576, MADV_DODUMP) = 0
brk(0x1a65000)                          = 0x1a65000
brk(0x1a68000)                          = 0x1a68000
brk(0x1a6b000)                          = 0x1a6b000
timer_create(CLOCK_MONOTONIC, {sigev_signo=SIGVTALRM, sigev_notify=SIGEV_SIGNAL}, [0]) = 0
rt_sigprocmask(SIG_UNBLOCK, [RT_1 RT_2], NULL, 8) = 0
rt_sigaction(SIGVTALRM, {sa_handler=0xd38580, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0xdbe821}, NULL, 8) = 0
timer_settime(0, 0, {it_interval={tv_sec=0, tv_nsec=10000000}, it_value={tv_sec=0, tv_nsec=10000000}}, NULL) = 0
rt_sigaction(SIGINT, {sa_handler=0xd4c610, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xdbe821}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGINT, NULL, {sa_handler=0xd4c610, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xdbe821}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0xd4c610, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xdbe821}, NULL, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=0xd4c580, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xdbe821}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=0xd4c5f0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xdbe821}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTSTP, {sa_handler=0xd4c630, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xdbe821}, NULL, 8) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=0, tv_nsec=1012513}) = 0
rt_sigprocmask(SIG_BLOCK, [INT], [], 8) = 0
rt_sigaction(SIGINT, {sa_handler=0xd4c6b0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESETHAND|SA_SIGINFO, sa_restorer=0xdbe821}, NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
stat("/home/vagrant/.cache/dhall", {st_mode=S_IFDIR|0755, st_size=274432, ...}) = 0
stat("/home/vagrant/.cache/dhall", {st_mode=S_IFDIR|0755, st_size=274432, ...}) = 0
access("/home/vagrant/.cache/dhall", R_OK) = 0
access("/home/vagrant/.cache/dhall", W_OK) = 0
access("/home/vagrant/.cache/dhall", X_OK) = 0
stat("/home/vagrant/.cache/dhall-haskell", {st_mode=S_IFDIR|0755, st_size=380928, ...}) = 0
stat("/home/vagrant/.cache/dhall-haskell", {st_mode=S_IFDIR|0755, st_size=380928, ...}) = 0
access("/home/vagrant/.cache/dhall-haskell", R_OK) = 0
access("/home/vagrant/.cache/dhall-haskell", W_OK) = 0
access("/home/vagrant/.cache/dhall-haskell", X_OK) = 0
ioctl(0, TIOCGWINSZ, 0x7ffe88b70330)    = -1 ENOTTY (Inappropriate ioctl for device)
fstat(0, {st_mode=S_IFREG|0600, st_size=77, ...}) = 0
fstat(0, {st_mode=S_IFREG|0600, st_size=77, ...}) = 0
lseek(0, 0, SEEK_CUR)                   = 0
ioctl(0, TIOCGWINSZ, 0x7ffe88b70330)    = -1 ENOTTY (Inappropriate ioctl for device)
poll([{fd=0, events=POLLIN}], 1, 0)     = 1 ([{fd=0, revents=POLLIN}])
read(0, " http://192.168.xx.171/projects/"..., 8192) = 77
poll([{fd=0, events=POLLIN}], 1, 0)     = 1 ([{fd=0, revents=POLLIN}])
read(0, "", 8192)                       = 0
close(0)  
```

**Comment by PierreR** [comment]
@Gabriel439 also the curl strace output looks quite different (I believe it is using linux lib under the hood). I don't even see the IP of my DNS server from /etc/resolv.conf in the strace of curl.

**Comment by Gabriel439** [comment]
So it looks like the error must be originating from `Network.Socket.getAddrInfo`.  That means we might be able to narrow the reproduction down to the following GHCi session:

```
Prelude> import Network.Socket
Prelude Network.Socket> getAddrInfo (Just defaultHints{ addrFlags = [ AI_ADDRCONFIG ], addrSocketType = Stream }) (Just "stash.cirb.lan") (Just "53")
```

Could you try running that command and seeing if you can reproduce the failure?  If you can, it might provide a more detailed explanation of why DNS resolution failed.

**Comment by PierreR** [comment]
@Gabriel439  As an extra note this python script works fine:
```
→ cat test.py 
import socket
print(socket.gethostbyname('stash.cirb.lan'))
```
I will try the haskell one.

**Comment by Gabriel439** [comment]
@PierreR: Whoops, the port should be "80", not "53":

```haskell
Prelude Network.Socket> getAddrInfo (Just defaultHints{ addrFlags = [ AI_ADDRCONFIG ], addrSocketType = Stream }) (Just "stash.cirb.lan") (Just "80")
```

**Comment by PierreR** [comment]
@Gabriel439 it works in ghci

**Comment by Gabriel439** [comment]
@PierreR: Could you get an `strace` of `dhall` successfully resolving an import (e.g. for `example.com`)?

Also, do you happen to have any proxies in your network environment?

**Comment by PierreR** [comment]
@Gabriel439 I am using a linux vm. I have just tried it on the Windows host (fresh cache ...) and it works fine there ...

**Comment by PierreR** [comment]
@Gabriel439  it won't work with
```
→ dhall <<< 'https://example.com as Text'                                                                                                                                                                                                  
dhall: 
Error: Remote host not found

URL: https://example.com/
```

**Comment by Gabriel439** [comment]
@PierreR: How were the two `dhall` executables obtained (inside the Linux VM vs. the Windows host)?

**Comment by PierreR** [comment]
I don't  believe I can successfully resolving any import with dhall on the linux vm. I am using a VPN (but that's also the case with the window host).

This might be relevant. I am using a nixos vm under vitualbox. I use the static binary that I fetch directly into the nix store using this kind of trick:
```
let
  version = "1.32.0";
  path = fetchTarball {
    url = "https://github.com/dhall-lang/dhall-haskell/releases/download/${version}/dhall-${version}-x86_64-linux.tar.bz2";
    sha256 = "11syan5l53lvg98hj9nfjn4anm05klqsw83gb75jmcz8h8948vy3";
  };
in
{
  inherit version path;
}
```
I am not using `autoPatchelfHook`.

**Comment by PierreR** [comment]
@Gabriel439 On windows, I have downloaded the static binary, unzip, and then use "git bash here" to get a terminal.

**Comment by Gabriel439** [comment]
@PierreR: When you performed the `ghci` test commands, was that inside the Linux VM?

**Comment by PierreR** [comment]
@Gabriel439 Yes with `nix-shell -p  'haskellPackages.ghcWithPackages(p: with p; [network])' `

**Comment by PierreR** [comment]
I am trying with the dhall version from nixpkgs but it is only 1.24.1 and I have the following exception (not sure what's wrong here)
```
→ dhall <<< 'https://example.com as Text'                                                                                                                                                                                                  1 ↵

Error: Invalid input

(stdin):1:8:
  |
1 | https://example.com as Text
  |        ^
unexpected '/'
expecting expression or whitespace
```

**Comment by Gabriel439** [comment]
@PierreR: Older versions of Dhall don't support importing from a bare domain, so you'd have to do something like https://example.com/index.html

However, I think I have a slightly better idea of what is going on based on the `strace` collected from the failing session.  The key lines are these ones, which I've grouped for clarity:

```
sendto(0, "\16\35\1\0\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\1\0\1", 32, MSG_NOSIGNAL, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.xx.244")}, 16) = 32
sendto(0, "\16\35\1\0\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\1\0\1", 32, MSG_NOSIGNAL, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.28.xy.10")}, 16) = 32
sendto(0, "\16\35\1\0\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\1\0\1", 32, MSG_NOSIGNAL, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.1.1")}, 16) = 32

sendto(0, "\17\22\1\0\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\xx\0\1", 32, MSG_NOSIGNAL, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.xx.244")}, 16) = 32
sendto(0, "\17\22\1\0\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\xx\0\1", 32, MSG_NOSIGNAL, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("172.28.xy.10")}, 16) = 32
sendto(0, "\17\22\1\0\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\xx\0\1", 32, MSG_NOSIGNAL, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.1.1")}, 16) = 32

recvfrom(0, "\16\35\201\203\0\1\0\0\0\0\0\0\5stash\4cirb\3lan\0\0\1\0\1", 512, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.1.1")}, [16]) = 32
recvfrom(0, 0x7ffe8830f8a8, 512, 0, 0x7ffe8830f350, [16]) = -1 EAGAIN (Resource temporarily unavailable)
```

The high-level description of those lines is:

* The DNS client queries `192.168.xx.244:53` for the IP address of `stash.cirb.lan`
* The DNS client queries `172.28.xy.10:53` for the IP address of `stash.cirb.lan`
* The DNS client queries `192.168.1.1:53` for the IP address of `stash.cirb.lan`

* The DNS client queries `192.168.xx.244:53` *again* for the IP address of `stash.cirb.lan`
* The DNS client queries `172.28.xy.10:53` *again* for the IP address of `stash.cirb.lan`
* The DNS client queries `192.168.1.1:53` *again* for the IP address of `stash.cirb.lan`

* The DNS server at `192.168.1.1:53` replies with a non-zero Rcode (11), meaning that the request failed

I suspect that the DNS server at `192.168.1.1:53` is a local DNS server for the virtual machine network (perhaps one managed by `vagrant`), which explains why you can't reproduce when testing outside of the VM on Windows.

It's not clear to me why the DNS server at `192.168.1.1:53` is failing to service the request.  It is a little bit weird that the Haskell DNS client is duplicating the requests for the same domain, but that shouldn't be disallowed or cause a DNS server to misbehave.

I will wager at this point that this is probably an issue with the local DNS server running on the VM network and my guess is that `curl` doesn't reproduce this problem because it is using a DNS client that is more tolerant of failed DNS requests than the Haskell client.

**Comment by PierreR** [comment]
@Gabriel439  Thanks for the detail explanation. I guess `192.168.1.1:53` is indeed the default gateway of the virtualbox vm. 

I have tried to add `8.8.8.8` to the /etc/resolv.conf inside the vm and I was not too surprised to see that `dhall <<< 'https://example.com as Text' ` starts to work just fine.

What I find a bit surprising `dhall hash <<< http://stash.cirb.lan/projects/CICD/repos/dhall/raw/openshift/package.dhall` also works now ...

Hopefully this solution will go on working. I don't quite understand why but hey that's ok by me ;-)

Thanks you so much for the time, trouble, patience giving me hints toward a (hopefully working in the long run) solution.

**Comment by Gabriel439** [comment]
@PierreR: You're welcome!  No trouble at all 🙂
