### ISSUE TITLE
*-to-dhall: generate auto-completed record using a --schemas file

### ISSUE THREAD

**Issue by sbrunk** [dhall-lang/dhall-haskell#1796]
I'm trying to convert a bunch of kubernetes resources (currently generated via helm) to dhall/dhall-kubernetes.

Given the existing resources, using `yaml-to-dhall` as described  by @Gabriel439 in this [SO answer](https://stackoverflow.com/questions/61010406/is-it-possible-to-get-a-kubernetes-object-in-json-or-yaml-with-all-optional-fiel) seems like a promising approach to bootstrap the conversion.

But, as also explained in that answer, *`yaml-to-dhall` doesn't yet take advantage of support for default values*. This means that the generated dhall file contains `None` for all optional values not set in the original yaml. It makes the imported definitions quite large and somewhat convoluted.

So I wonder if it would be feasible to add an option to `yaml-to-dhall` to omit unset fields in the generated dhall definition?

**Comment by german1608** [comment]
If I understand your suggestion, you're saying that `yaml-to-dhall` could have a flag like `--omit-null` for example, to omit those files.

The only thing I see is that the generated dhall definition doesn't have the type provided by, in that SO Answer, Deployment.dhall and won't be compatible with that since the absence of a field in a dhall record isn't the same as if that field is `None` there.

```
Welcome to the Dhall v1.32.0 REPL! Type :help for more information.
⊢ ./schema.dhall 

{ o : Optional Natural }

⊢ {} : ./schema.dhall 

Error: Expression doesn't match annotation

- { … : … }
+ Type

1│ {} : ./schema.dhall

(input):1:1
⊢ { o = None Natural} : ./schema.dhall 

{ o = None Natural }

⊢ { o = Some 1} : ./schema.dhall 

{ o = Some 1 }

⊢ { o = Some 1 } : ./schema.dhall 

{ o = Some 1 }```

So yes I think it will be possible but you'll lose backwards compatibility between generated dhall and original type

**Comment by sbrunk** [comment]
Oh I see. I've just started with dhall and I'm still in the process of figuring it out.

So I guess what I'm **actually** looking for is for the generated dhall records to be typed w.r.t to `kubernetes.Deployment.Type` from Deployment.dhall in that case.

I guess that's not possible (yet)?

In that case something like `--omit-null` would still be helpful in a partially manual conversion process as it would remove a lot of noise.

**Comment by Gabriel439** [comment]
@sbrunk: Yeah, I've been wanting to do something similar for a while.  I believe it should be possible since for any Dhall record in the tree of records we can check the type and see if it matches a known type for a record completion schema and use that.

**Comment by TristanCacqueray** [comment]
To better understand the issue, is this the goal: ?

```
$ yaml-to-dhall --omit-null '{ a : Bool, b : Optional Bool }' <<< 'a: true' 
{ a = True }
```

Or should it be:

```
$ yaml-to-dhall './recordSchema.dhall' <<< 'a: true'
recordSchema::{ a = True }
```

where recordSchema is a `{ Type = ... , default = ... }` record?

**Comment by Gabriel439** [comment]
@TristanCacqueray: The user experience I was thinking of was that one could optionally give `yaml-to-dhall` a record of schemas (i.e. one field per schema), and then `yaml-to-dhall` would find all occurrences of each schema and use them.

In other words, if `./schemas.dhall` had the following contents:

```dhall
{ Person = { Type = { name : Text, alive : Bool }, default = { alive = True } }
}
```

... and you ran:

```bash
$ yaml-to-dhall --schemas ./schemas.dhall <<< '{ name = "John", age = True }'
```

... then it would output:

```
let schemas = ./schemas.dhall

in  schemas.Person::{ name = "John" }
```

**Comment by sbrunk** [comment]
@TristanCacqueray Yes the conversion to the right types given a record of schemas is what I was looking for. I've renamed the issue (borrowing the title of your PR) to make it more clear.

I guess omitting defaults as shown in the example of @Gabriel439 above is also nice for a more concise output. But that could be added later.

**Comment by TristanCacqueray** [comment]
Thank you for the details, I am looking forward improving the PR to at least work with the simplest case, perhaps by next week.
