### ISSUE TITLE
Labels that are keywords should be quoted

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1805]
```
$ echo '{ `if` = 0 }' | dhall
{ if = 0 }
```

`if` (unquoted) is not a valid label.

`Some` will need special treatment: Only when used as a record label can it remain unquoted.

**Comment by sjakobi** [comment]
Actually `Some` seems to be handled correctly:

```
$ echo 'let `Some` = 3 in 0' | dhall format
let `Some` = 3 in 0
```

`if` too, when used in a `let`-binding:

```
$ echo 'let `if` = 3 in 0' | dhall format
let `if` = 3 in 0
```

So maybe the issue is actually limited to record labels?!

**Comment by german1608** [comment]
@sjakobi I can take a look at that later or tomorrow, It doesn't seems
complicated to fix

**Comment by sjakobi** [comment]
Sounds great, @german1608! :)
