### ISSUE TITLE
Error while trying to use the -zsh-completion-script

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#1827]
I am probably doing something wrong but I have not been able to make zsh completion work:

```
λ ~ → nix-shell -p dhall --run zsh
λ ~ → echo $0
zsh
λ ~ → source <(dhall            --zsh-completion-script dhall)
/proc/self/fd/11:compadd:24: can only be called from completion function
```
I have also tried to put this line in ` shellHook ` but then I have got:

```
/dev/fd/63: line 26: print: command not found
/dev/fd/63: line 27: compadd: command not foun
```

PS:  The bash completion script is working fine.

Thanks for your help.

**Comment by Gabriel439** [comment]
Apparently we're not loading the `zsh` completion correctly.  `zsh` is not designed to `source` completion scripts.  I'll have a fix up later today.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1829

**Comment by PierreR** [comment]
@Gabriel439 Thanks. 

Do you know if there is a way to reload zsh with the completion enabled without launching a new one with `zsh -i` ? 

Unlike `nix-shell`, `direnv` is using the shell of the user. Creating a new one seems to cause problems with `direnv`.

If I just remove the line `zsh -i` I don't get any completion.

**Comment by PierreR** [comment]
I guess this is more a direnv issue than anything else:
https://github.com/direnv/direnv/issues/443

**Comment by Gabriel439** [comment]
@PierreR: There is not a way to avoid the `zsh -i` when using `nix-shell`, because `nix-shell` switches the shell to `bash`, regardless of what the original shell was.  I think it might be worth making a request upstream to have `nix-shell` support shells other than `bash`

**Comment by PierreR** [comment]
@Gabriel439 sure but that's not the case with `direnv`. `direnv` is going to read `shell.nix` and keep the user shell (zsh for me).

At this point I really believe it is more a direnv problem than anything else. 

I believe your fix is quite valid for nix-shell usage in general.

I will probably try to fix this by creating a `dhall` nix derivation (or will upload _dhall in my .zsh). I even might go with bash instead.

Thanks for your help !

**Comment by Gabriel439** [comment]
@PierreR: You're welcome! 🙂
