### ISSUE TITLE
dhall lint always change the timestamp of the file

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#1828]
While trying to an extra hook in `.pre-commit-config.yaml`, I have reliazed that `dhall lint` always changes the timestamp even if the file hasn't been changed by the linter.

This is annoying  because I wanted to add another hook that generates yaml with `dhall-to-yaml`. Because the timestamp is changed, `make` will always re-generate everything (a process that takes minutes).

Is there a way to improve this ? 

I have tried to use `dhall lint --check`. Is it meant to be called like this ? 

```
dhall lint --check <<< './openshift/examples/cron1.dhall'
```
Whatever error I introduce in `cron1.dhall` the return code is always `0`.

**Comment by PierreR** [comment]
After looking in the source code, I have figured out that this would work:
`dhall lint --inplace ./openshift/examples/cron1.dhall --check`

Still I would expect `dhall lint/format` to let the file update timestamp at rest when no modification is introduced.

**Comment by sjakobi** [comment]
Sounds reasonable to me. Would you mind preparing a PR, @PierreR? Please include `freeze` too!

**Comment by PierreR** [comment]
@sjakobi I could try a PR but I have to admit my haskell is a bit rusty at the moment ;-) 

I see what I can do. It is probably going to take a while on my side for the PR but anyway this is nothing urgent on the matter.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1830
