### ISSUE TITLE
[Question] How to get the type error if my config file fails to parse (alternative import)?

### ISSUE THREAD

**Issue by zzat** [dhall-lang/dhall-haskell#1832]
If I have a config like:
`./myconfig.dhall ? 1`

It returns `1` if `myconfig.dhall` fails to typecheck. I'd like to get the type error if `myconfig.dhall` fails to parse and default to `1` only if the file is missing. How can I achieve it?

**Comment by sjakobi** [comment]
Is this a question about possibilities with `dhall-haskell` or about the Dhall language?

Within the Dhall language, I think this is impossible. Both failure modes are just indistinguishable failures during import resolution.

**Comment by Gabriel439** [comment]
@zzat: A similar concern was brought up in: https://github.com/dhall-lang/dhall-lang/issues/975

If you want, we can make that other issue the central one for fixing `?` to not fallback on type errors

**Comment by mageshb** [comment]
@Gabriel439 It would be great to fix ```?``` to not fall back on type errors as it may silently go against the user intention without getting notified.

**Comment by Gabriel439** [comment]
I'll close this in favor of https://github.com/dhall-lang/dhall-lang/issues/975 to track this issue, then
