### ISSUE TITLE
dhall-nix: Please, bump dependency HNix to 0.8.0 or stabilize in Nixpkgs

### ISSUE THREAD

**Issue by Anton-Latukha** [dhall-lang/dhall-haskell#1838]
<details><summary>Current Nixpkgs DHall-Nix Nix build tail:</summary>
<p>

```
Configuring dhall-nix-1.1.14...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1022:20 in Cabal-3.0.1.0:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:475:12 in Cabal-3.0.1.0:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.0.1.0:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.0.1.0:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.0.1.0:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.0.1.0:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing or private dependencies:
dhall >=1.31 && <1.33, hnix ==0.7.*

builder for '/nix/store/qsikazg9k94wxif0y2j4a6ck813d4jaf-dhall-nix-1.1.14.drv' failed with exit code 1
```
</details>

`HNix 0.8.0`: Breaking change, `NAtom` type (& module) - received an `NURI Text` data constructor.

---

Soon we would probably release minor fix, fixing Hackage documentation.

---

Sorry in advance. There seen, and would be many breakage changes and so - major versions. Probably a lot.
But since the project is far from working state - I think those breakages would be/is no biggy. And since the project does not work - now is the best time to do needed breakages as soon as they can be done, and the only time we can and should do them, since the project does not work really and even still somewhat far from being cleaned-up into shape.

---

If something - we can stabilize the DHall-Nix on some HNix version by creating a separate HNix version in Nixpkgs.

**Comment by Gabriel439** [comment]
@Anton-Latukha: Don't worry.  We don't mind if there are breaking changes to `hnix`.  We can accommodate the API changes; just do what you feel is necessary.  One of the benefits of Haskell is that it's easy to detect and fix any type errors 🙂

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1841

**Comment by Anton-Latukha** [comment]
Thank you, forgot to close the report.
