### ISSUE TITLE
LSP - Unused binding should have targeted highlighting

### ISSUE THREAD

**Issue by drewolson** [dhall-lang/dhall-haskell#1847]
I've been really enjoying using my editor's integration with the dhall LSP (vim + coc). However, the linter seems to be overzealous in highlighting my code when there is an unused binding. All of the code in the file is highlighted rather than the specific unused binding. I've attached a screenshot.

![dhall-lint](https://user-images.githubusercontent.com/3536/84449903-54c8f180-ac14-11ea-9961-67b25e28c9d1.png)

Thanks!

**Comment by Gabriel439** [comment]
I have a fix up here: https://github.com/dhall-lang/dhall-haskell/pull/1854
