### ISSUE TITLE
Dhall tuples?

### ISSUE THREAD

**Issue by robertjlooby** [dhall-lang/dhall-haskell#185]
Does Dhall allow tuples? There's an instance of [`Interpret`](https://hackage.haskell.org/package/dhall-1.8.1/docs/Dhall.html#t:Interpret) for them and it type checks fine, but it fails to parse what I would expect them to look like:

```haskell
Prelude> :set -XOverloadedStrings
Prelude> import Dhall
Prelude Dhall> let t = input auto "(1, 2.3)" :: IO (Integer, Double)
Prelude Dhall> t
*** Exception:
Error: Invalid input

(input):1:3: error: expected: "!=",
    "#", "&&", "(", ")", "*", "+",
    "++", ".", "//", "/\\", ":",
    "==", "||", "∧", "⫽",
    built-in expression, digit,
    double literal, import,
    integer literal, label,
    list literal, natural literal,
    record type or literal,
    text literal,
    union type or literal
(1, 2.3)<EOF>
  ^
Prelude Dhall>
```

**Comment by Gabriel439** [comment]
The `Interpret` instance for 2-tuples expects a Dhall record with two fields named `_1` and `_2`, so this will work:

```haskell
>>> input auto "{ _1 = 1, _2 = 2.3 }" :: IO (Integer, Double)
(1,2.3)
```

Dhall supports anonymous records, but not tuples.  The `Interpret` instance for tuples was added primarily for ease of integration with Haskell code

**Comment by robertjlooby** [comment]
Thank you!

**Comment by Gabriel439** [comment]
You're welcome! ☺
