### ISSUE TITLE
Dhall format / freeze should skip writing identical file

### ISSUE THREAD

**Issue by timbertson** [dhall-lang/dhall-haskell#1855]
This is just a bit of an inconvenience, in that `vim` complains if I don't reload a changed file before saving. When it's _actually_ changed that's what I want, but `dhall format` writes files even when they're identical.

**Comment by Gabriel439** [comment]
This was fixed in https://github.com/dhall-lang/dhall-haskell/pull/1830 and just hasn't been released yet.  We will be cutting a new release in a few days

**Comment by timbertson** [comment]
Ah perfect, thanks!

**Comment by Gabriel439** [comment]
@timbertson: You're welcome! 🙂
