### ISSUE TITLE
[dhall-to-yaml] using --documents with one document

### ISSUE THREAD

**Issue by jfroche** [dhall-lang/dhall-haskell#1864]
Would it be possible for *dhall-to-yaml --documents* to generate yaml prefixed by document separator (`---`) even if we generate a single document.

We aggregate generated yaml files produced by dhall-to-yaml (using argocd) and miss the separation between each files.

We would have something like this:

```
$ dhall-to-yaml --documents <<< '["foo"]'
---
foo
$ dhall-to-yaml --documents <<< '"foo"'
---
foo
$ dhall-to-yaml --documents <<< '["foo", "bar"]'
---
foo
---
bar
```

Thank you for all the nice work done in this project, it really really helps us !

**Comment by Gabriel439** [comment]
@jfroche: Yeah, this seems reasonable to me!  I will have a fix up later today

**Comment by Gabriel439** [comment]
First pull request up here: https://github.com/clovyr/aeson-yaml/pull/6

**Comment by Gabriel439** [comment]
Second pull request is up here: https://github.com/dhall-lang/dhall-haskell/pull/1865

**Comment by sjakobi** [comment]
This seems to be fixed now.

**Comment by jfroche** [comment]
Hello @Gabriel439 , it occurs to me only now that the implementation does not match completely with my first comment in this issue:
```
$ dhall-to-yaml --documents <<< '"foo"'
---
foo
```
is (still) not working with the new implementation. And returns:
```
$ dhall-to-yaml --documents <<< '"foo"'
foo
```
Is this intended ?

Our usecase is we are running gitops with argocd to deploy on OpenShift. dhall generates the yaml and argocd is running something like `cat folder/*.yaml | kubectl apply -f -`. If all yaml documents are not correctly separated using `---`, it fails.
We are using this workaround 
```
%.yaml: %.dhall
        dhall-to-yaml --documents --file $< --output $@
        sed -i '1s/^/---\n/' $@
```
but we would prefer not to have to do this sed.

**Comment by Gabriel439** [comment]
@jfroche: How did you obtain or build the `dhall-to-yaml` executable?

To provide some context: `dhall-to-yaml` (from the `dhall-json` package) will only produce the correct behavior if built against the latest version of its `aeson-yaml` dependency.  The release binaries we supply should be built in this way (and if they are not, then that's a bug).

Also, if you use `dhall-to-yaml-ng` (from the `dhall-yaml` package) then it will produce the behavior you expect, too.

**Comment by jfroche** [comment]
we download it from the releases:
```
$ curl -L https://github.com/dhall-lang/dhall-haskell/releases/download/1.34.0/dhall-json-1.7.1-x86_64-linux.tar.bz2 | tar -xj
$ bin/dhall-to-yaml --documents <<< '"foo"'
foo
```

**Comment by jfroche** [comment]
forgot the ping in previous comment @Gabriel439 
I tried to find out why the aeson-yaml dependency would not be correct in that release even though cabal in dhall-json is referencing the correct version range but can't see why

**Comment by Gabriel439** [comment]
@jfroche: Alright, I think I figured out the problem.  It is using the correct version of `aeson-yaml`, but it only adds document headers if the input is a `List`:

```bash
$ dhall-to-yaml --documents <<< '[1]'
---
1

$ dhall-to-yaml --documents <<< 1
1
```

**Comment by Gabriel439** [comment]
@jfroche: Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1977
