### ISSUE TITLE
No instance for (Interpret Int)

### ISSUE THREAD

**Issue by bitc** [dhall-lang/dhall-haskell#187]
Dhall version 1.8.1 from Hackage.

I am new to Dhall and likely am doing something wrong.

I modified the example, changing `foo` from `Integer` to `Int`:

```haskell
data Example = Example { foo :: Int, bar :: Vector Double }
    deriving (Generic, Show)

instance Interpret Example
```

But I get an error:

```
    * No instance for (Interpret Int)
        arising from a use of `Dhall.$dmautoWith'
    * In the expression: Dhall.$dmautoWith @Example
      In an equation for `autoWith':
          autoWith = Dhall.$dmautoWith @Example
      In the instance declaration for `Interpret Example'

```

**Comment by bitc** [comment]
Also getting the same error when trying to use `String` (`No instance for (Interpret Char)`)

**Comment by Gabriel439** [comment]
It will work if you change `Int` to `Integer`

The Haskell API for `dhall` intentionally omits the `Interpret` instance for `Int` because it is a lossy conversion: Dhall `Integer`s have unlimited precision whereas the Haskell `Int` type is limited to one machine word.  You can decode into a Haskell `Integer`, though, because that is unlimited precision

**Comment by bitc** [comment]
Thanks for the reply. If I understood correctly, then dhall can be used to load a file containing the config of my program, as a better replacement for json/yaml, or one of the other haskell config file parsers. These all support loading data directly into an "Int" type. This is useful since real world programs usually use "Int" rather than "Integer".

With dhall it seems that I'd need to use an intermediate data structure that uses Integers, and then convert that to my real data structure that uses Ints. This feels to me like too much unnecessary boilerplate.

Can't dhall just throw a runtime error if it tries to load a config containing a value that is out of range of "Int"?

Also what about String?

Thank you

**Comment by Gabriel439** [comment]
I can definitely add support for `String` since it's a loss-less conversion from `Text`

The reason I prefer to avoid potentially failing conversions is because I want people to be able to do ahead-of-time validation of configuration files by type-checking them using the `dhall` executable.  I want to provide users with the guarantee that if the configuration file validates then their program will successfully marshal the configuration file without errors.

**Comment by Profpatsch** [comment]
> This is useful since real world programs usually use "Int" rather than "Integer".

I certainly hope they do not! Why would you want to risk overflows in your internal model?
If you think you need Ints in your program, it is a good idea to manually try the conversion and show a domain-specific error when it fails.

**Comment by Gabriel439** [comment]
Actually, it looks like there is not a good way to provide an `Interpret` instance for `String`.  Doing so would require also providing an `Interpret` instance for `Char`, which wouldn't work

**Comment by ocharles** [comment]
@Gabriel439 Well, your typical solution there would be to have `Interpret` have `interpretList`. Is marshalling `Char` to a one-element `String` problematic?

**Comment by Gabriel439** [comment]
Yeah, that was already assuming an additional `interpretList` method to deal with the special case of `String`

The objection was more to marshaling `Char`.  Note that `Interpret` is about marshaling values from Dhall to haskell, so an `Interpret` instance for `Char` would require converting Dhall `Text` to a Haskell `Char`, which is a partial conversion with the same issues as marshaling `Integer` to `Int`.

**Comment by ocharles** [comment]
Oh yes, of course - that's the direction it's partial in.

**Comment by ocharles** [comment]
@Gabriel439 What about an overlapping instance for `[Char]`? I just ran into this exact problem trying to derive a `Type` for https://hackage.haskell.org/package/Cabal-2.0.1.1/docs/Distribution-System.html#t:OS.

**Comment by Gabriel439** [comment]
@ocharles: Alright.  I'd accept a pull request to add that

**Comment by Gabriel439** [comment]
I will go ahead and close this given that there is now a `Interpret` instance for `String`, which was added in: https://github.com/dhall-lang/dhall-haskell/commit/0e7d620fa8cf334fc3d28263c96d656e3a95575d

I'm unlikely to add an `Interpret` instance  for `Int`, though, for the reasons I mentioned above
