### ISSUE TITLE
[DOC] dhall-yaml ng features

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#1872]
It would be nice if the README from `dhall-yaml` specifies what features makes it `ng`.

It is kind of easy to remember that we keep `dhall-to-yaml` from `dhall-json` for licencing matters.
On the other hand I always kind of forget why I should care about `dhall-to-yaml-ng`

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1874

**Comment by PierreR** [comment]
@Gabriel439 Thanks for the quick fix up !

**Comment by Gabriel439** [comment]
@PierreR: You're welcome! :slightly_smiling_face:
