### ISSUE TITLE
Can't use a function call on LHS of `with`

### ISSUE THREAD

**Issue by timbertson** [dhall-lang/dhall-haskell#1884]
Not sure if this is a dhall-haskell bug or in the spec, but I can't get `with` to work on anything other than a variable reference or record literal, and that seems strange:

```dhall
-- scratch.dhall
let Make = \(T: Type) -> { Type = { a: T },  default = {=} }

in
(Make Natural) with default = { a = 2 }
```

```
$ dhall --file scratch.dhall
dhall:
Error: Invalid input

scratch.dhall:22:16:
   |
22 | (Make Natural) with default = { a = 2 }
   |                ^
unexpected 'w'
expecting ->, :, end of input, or whitespace
```

**Comment by sjakobi** [comment]
Strange indeed. I can reproduce this with `v1.33.1`, but I have no idea what might be wrong.

**Comment by sjakobi** [comment]
After taking a look at the [grammar](https://github.com/dhall-lang/dhall-lang/blob/0c899ab31fdb857f535fe9f5b37f981271824a65/standard/dhall.abnf), I think this might indeed be a problem with the spec:

```
with-expression =
    import-expression 1*(whsp1 with whsp1 with-clause)

import-expression = import / completion-expression

completion-expression =
    selector-expression [ whsp complete whsp selector-expression ]

selector-expression = primitive-expression *(whsp "." whsp selector)
```

But `(Make Natural)` isn't a `primitive-expression`. It's an `application-expression` within parentheses.

(Where's the rule for these parentheses BTW?)

So I think this ought to be moved to the `dhall-lang` repo.

**Comment by sjakobi** [comment]
Oops. Nope.

```
primitive-expression =
    ...

    ; "( e )"
    / "(" complete-expression ")"
```

There are the parentheses and `(Make Natural)` is a `primitive-expression` alright.

Must be a bug in the parser then.

**Comment by sjakobi** [comment]
This appears to be a regression introduced in https://github.com/dhall-lang/dhall-haskell/commit/eb895bc538e8a2307d81a841f1f042ed6dbf8b80.

I suspect this line is problematic:

https://github.com/dhall-lang/dhall-haskell/blob/89ab09583ca50377517ee2f0740420e9b8487a93/dhall/src/Dhall/Parser/Expression.hs#L288

I'll try to prepare a fix.

**Comment by sjakobi** [comment]
So it's not as simple as just removing that line. In that case we unexpectedly parse [`tests/parser/failure/unit/WithPrecedence2.dhall`](https://github.com/dhall-lang/dhall-lang/blob/0c899ab31fdb857f535fe9f5b37f981271824a65/tests/parser/failure/unit/WithPrecedence2.dhall).

**Comment by sjakobi** [comment]
https://github.com/dhall-lang/dhall-haskell/pull/1770#discussion_r419022486 explains the approach taken in eb895bc.

This is the relevant code:

https://github.com/dhall-lang/dhall-haskell/blob/89ab09583ca50377517ee2f0740420e9b8487a93/dhall/src/Dhall/Parser/Expression.hs#L243-L399

This seems to be the relevant idea from the explanation:

> If that fails, then attempt to parse the remainder of a with expression, but only if the operator expression was the same as the import expression

I wonder whether we could just compare source locations instead of checking the `Expr` constructor in order to determine whether it's an operator expression or not…

**Comment by sjakobi** [comment]
This patch results in the same test failure:

```diff
--- a/dhall/src/Dhall/Parser/Expression.hs
+++ b/dhall/src/Dhall/Parser/Expression.hs
@@ -271,22 +271,10 @@ parsers embedded = Parsers {..}
                         _ -> return (Annot a b)
 
             let alternative4C = do
-                    case shallowDenote a of
-                        Equivalent{}   -> empty
-                        ImportAlt{}    -> empty
-                        BoolOr{}       -> empty
-                        NaturalPlus{}  -> empty
-                        TextAppend{}   -> empty
-                        ListAppend{}   -> empty
-                        BoolAnd{}      -> empty
-                        Combine{}      -> empty
-                        Prefer{}       -> empty
-                        CombineTypes{} -> empty
-                        NaturalTimes{} -> empty
-                        BoolEQ{}       -> empty
-                        BoolNE{}       -> empty
-                        App{}          -> empty
-                        _              -> return ()
+                    case (a0, a) of
+                        (Note (Src l0 r0 _ ) _, Note (Src l1 r1 _) _)
+                            | l0 == l1 && r0 == r1 -> return ()
+                        _ -> empty
 
                     bs <- many (do
                         try (whitespace *> _with *> nonemptyWhitespace)
```

I suspect the real problem is that we can't tell whether `a0` is just an import expression or a full application expression.

**Comment by sjakobi** [comment]
I'll try tagging the result of `applicationExpression` to say whether it's just an import expression or not.

**Comment by sjakobi** [comment]
I've pushed an attempted fix to https://github.com/dhall-lang/dhall-haskell/pull/1889. Unfortunately it breaks >200 tests. ;)

I suspect I still don't have the full picture on this issue.

I'll take another look at this during the weekend.

**Comment by sjakobi** [comment]
After a few more tweaks, #1889 seems to fix this properly.
