### ISSUE TITLE
Haddocks for dhall-json are missing

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1887]
Hackage's docs builder failed to produce Haddocks for http://hackage.haskell.org/package/dhall-json-1.7.0 due to a now-fixed disk-space issue (https://mail.haskell.org/pipermail/libraries/2020-June/030639.html).

@Gabriel439 If you give me upload permissions I can do a manual docs upload. My Hackage handle is the usual `sjakobi`.

**Comment by Gabriel439** [comment]
@sjakobi: I just added you 🙂

**Comment by sjakobi** [comment]
@Gabriel439 I believe you added me as a maintainer of `dhall` but not for `dhall-json`:

http://hackage.haskell.org/package/dhall-json/maintainers/

While you're at it, you could also add me for `dhall-lsp-server`, `dhall-yaml`, `dhall-nix`, and `dhall-bash`, too! :)

**Comment by Gabriel439** [comment]
@sjakobi: Alright, I added you to all of them

**Comment by sjakobi** [comment]
Thanks, @Gabriel439! :)

I've uploaded the previously missing docs for `dhall-json`, `dhall-yaml` and `dhall-lsp-server`.

**Comment by Gabriel439** [comment]
@sjakobi: Thank you! 🙂
