### ISSUE TITLE
Humble request for a new release 1.33.2

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#1888]
I would love a release with b293dc & 89ab09 if it is not too much trouble.

We are about to go in production in 3 weeks so it would help.

I dare to ask because I believe nothing big have been introduced since 1.33 and maybe some other issues could be squashed in.

If it is too much trouble (or bad timing), please close the issue, it is not critical.

Cheers ! Thanks again for all the work on Dhall.

**Comment by Gabriel439** [comment]
@PierreR: We release on a roughly monthly schedule, mainly to reduce version churn for our reverse dependencies.  Usually the only reasons we cut a new release early are:

* We need to release a fix for a bug that is severe enough to blacklist prior affected releases

* We need to cut a release to support a new dependency on Stackage that can't be handled with a revision

**Comment by PierreR** [comment]
@Gabriel439 that makes sense.
