### ISSUE TITLE
Annotate MissingFile exception with absolute path

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-haskell#189]
```
↳ ../imports/Prelude; 

Error: Missing file
```

I suggest adding the absolute filepath it tried to stat, this should help debugging complex setups.
Not sure if that were a security risk in some cases, though.

**Comment by Gabriel439** [comment]
There's no security risk if you return the canonicalized path which Dhall already stores internally.  In other words if you had `../foo/bar → ./baz` then the canonicalized path would be `../foo/baz`.  Would that be alright?

**Comment by Gabriel439** [comment]
I'll mark this closed since the corresponding pull request is merged
