### ISSUE TITLE
YAML strings value are quoted differently if the first character is a number 

### ISSUE THREAD

**Issue by TristanCacqueray** [dhall-lang/dhall-haskell#1894]
In version `1.31.1`, this expression:

```dhall
[ { checksum = "72b6ae7b4ed0" }
, { checksum = "e3c1b309d920" } ]
```

Is YAML rendered as:

```yaml
- checksum: "72b6ae7b4ed0"
- checksum: e3c1b309d920
```

This looks a bit odd. Should we always quote single word string value?

**Comment by TristanCacqueray** [comment]
Another oddity is:

```dhall
{ ip = "127.0.0.1", net = "127.0.0.1/8" }
```

Which is YAML rendered as:

```yaml
ip: '127.0.0.1'
net: "127.0.0.1/8"
```

**Comment by Gabriel439** [comment]
@TristanCacqueray: These are likely questions for `aeson-yaml`.  For example, the relevant line of code for the first difference is:

https://github.com/clovyr/aeson-yaml/blob/fdaabaf78bfb74e53e185f3ca01588290b61850c/src/Data/Aeson/Yaml.hs#L141

**Comment by TristanCacqueray** [comment]
@Gabriel439 thanks, I asked the question there.

**Comment by Gabriel439** [comment]
@TristanCacqueray: Thank you! 🙂
