### ISSUE TITLE
dhall-docs release

### ISSUE THREAD

**Issue by german1608** [dhall-lang/dhall-haskell#1900]
Do we need to follow a procedure to release dhall-docs?

From my POV, it looks like we need to:

* Add `dhall-docs` to release.sh
* Update `.travis.yml` for GitHub releases

**Comment by german1608** [comment]
cc: @Gabriel439

**Comment by Gabriel439** [comment]
@german1608: Yeah, those steps plus also updating `appveyor.yml`, too

**Comment by Gabriel439** [comment]
@german1608: I can perform the release process for just `dhall-docs` tonight if you don't object

**Comment by german1608** [comment]
@Gabriel439 that would be awesome! Thanks!

**Comment by Gabriel439** [comment]
@german1608: Alright, `dhall-docs` is up on Hackage now: https://hackage.haskell.org/package/dhall-docs
