### ISSUE TITLE
Make pre-built binaries for macOS available in Nix

### ISSUE THREAD

**Issue by tssm** [dhall-lang/dhall-haskell#1907]
It's possible to install pre-build binaries in Linux using Nix. It would be nice to be able to do the same in macOS.

**Comment by Gabriel439** [comment]
@tssm: By prebuilt do you mean cached using cachix?

The reason I ask is because the current pre-built binaries for Linux use the work described in this ticket in order to ensure that the built executable is fully statically linked:

https://github.com/NixOS/nixpkgs/issues/43795

... but as far as I know that only works on Linux.  If we were to build them using Nix on OS X they would require including the entire closure since they wouldn't be fully statically linked

**Comment by tssm** [comment]
I see. Is it possible to build them on macOS using Nix (and hopefully nix-darwin)? I tried following the Linux guide but I'm stuck

**Comment by Gabriel439** [comment]
@tssm: This repository provides instructions for building Dhall packages using Nix here:

https://github.com/dhall-lang/dhall-haskell#nix

Those instructions should also work on OS X

**Comment by Gabriel439** [comment]
Closing, as I believe the question was answered.  Feel free to reopen if you have additional questions

**Comment by tssm** [comment]
Sorry for the delay, I'm back on this. I already tried that, but I get

```
building '/nix/store/c7zhlb8yh8bisj8bk5s9mhbp85v5hr7y-remove-references-to.drv'...
copying path '/nix/store/bsj4x4c56xis5wyb652klg6x3i840jyd-aws-sdk-cpp-1.4.82' from 'https://cache.nixos.org'...
dyld: Library not loaded: /usr/lib/system/libsystem_network.dylib
  Referenced from: /nix/store/2cqdl7qvk9skzag962v9y2a3ga3sm699-Libsystem-osx-10.11.6/lib/libSystem.B.dylib
  Reason: image not found
builder for '/nix/store/c7zhlb8yh8bisj8bk5s9mhbp85v5hr7y-remove-references-to.drv' failed due to signal 6 (Abort trap: 6)
```

when I execute `nix-build` with and without the `--pure` flag. That's why I thought binary caches would be easier.

Not sure if I should re-open the ticket though, there may be something wrong in my macOS set-up, but I don't know where to start

**Comment by Gabriel439** [comment]
@tssm: Oh, I recognize that issue.  The build fails on newer versions of OS X because it is using an older version of Nixpkgs (mainly to support building static Linux executables)

**Comment by tssm** [comment]
@Gabriel439 apparently I missed it somehow, but `dhall-lsp-server` is available in Nixpkgs. Not sure if it wasn't building on macOS or I completely overlooked it, but I installed it today and seems to be working without problems.

Thanks for all your attention here!

**Comment by Gabriel439** [comment]
@tssm: You're welcome! 🙂
