### ISSUE TITLE
dhall-docs can't generate documentation for dhall-kubernetes

### ISSUE THREAD

**Issue by german1608** [dhall-lang/dhall-haskell#1971]
The error is the following:
```
dhall-docs: user error (File name too long)
```
That error messages seemed unknown from me to be from `dhall-docs`, so I searched that error string on all third party packages and I've found that the error is from a (bad use) of the `tar` package:

https://github.com/haskell/tar/blob/bde33fe580881f011ba5b91e9c23631877fa09ef/Codec/Archive/Tar/Types.hs#L393-L402

**Comment by german1608** [comment]
FWIW: The longest file path on `dhall-kubernetes` is:

    defaults/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionCondition.dhall.html

...with a length of 115 characters

**Comment by german1608** [comment]
After running:
```haskell
Codec.Archive.Tar.Entry.toTarPath False
    "defaults/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionCondition.dhall.html"
```

I get that error

**Comment by sjakobi** [comment]
What's the `dhall-docs` command that results in the error?

**Comment by Gabriel439** [comment]
Apparently the maximum path length for tar archives is 100 characters.  One way we can work around this is by replacing each file name with the hash of the file name, since we don't actually care what the file name is so long as different file names produce different archive hashes.

**Comment by german1608** [comment]
> What's the `dhall-docs` command that results in the error?

```bash
dhall-docs --input ${PATH_TO_DHALL_KUBERNETES}
```
