### ISSUE TITLE
dhall-docs linux binary is missing from the 1.34.0 release assets 

### ISSUE THREAD

**Issue by TristanCacqueray** [dhall-lang/dhall-haskell#1975]
It seems like only windows and macos tarball are published for dhall-docs in the latest release. Is there a reason why Linux is not included?

**Comment by Gabriel439** [comment]
@TristanCacqueray: Yeah, this is a known issue that I'm currently fixing.  Basically, once I fix the failing build on https://github.com/dhall-lang/dhall-haskell/pull/1972 then I can go back and also publish the Linux binary for `dhall-docs`

**Comment by Gabriel439** [comment]
So the fix to this was large enough that I won't be able to easily backport it to the last release, but I will ensure that we publish the `dhall-docs` Linux binary for the upcoming release, which will be in a few days.

**Comment by TristanCacqueray** [comment]
That's good to hear, it's ok to skip the backport, running `cabal install dhall-docs` worked for me. Thanks!

**Comment by Gabriel439** [comment]
@TristanCacqueray: You're welcome! 🙂

**Comment by TristanCacqueray** [comment]
dhall-docs linux binary is published for the 1.35.0 release, thanks!

**Comment by Gabriel439** [comment]
@TristanCacqueray: You're welcome! 🙂
