### ISSUE TITLE
Advice for updating `Expr` AST in the context of `dhall-docs` & `dhall format`

### ISSUE THREAD

**Issue by german1608** [dhall-lang/dhall-haskell#1986]
The JTD (jump to definition) feature needs to be able to get the source position of a token to get the exact jump location, and in order to do so, I've been updating the `Expr` AST to add more `Maybe Src` in places where I need them.

I'm currently working to add support for JTD in record fields, and I need to modify the following constructors to get more `SourcePos`es

* `Field`
* `RecordLit`

`RecordLit` does already preserve the prefix whitespace of the label, but I need to record the suffix. On `Field` we do not record anything, and what I need to preserve is:

```dhall
e . {- here -} x {- and here -}
```

_but_ I was thinking that to help `dhall format` we could also preserve the following:

```dhall
{- A -} e {- B -} . {- C -} x {- D -}
```

(note that I'm not sure if recording `A` is possible and I'm 100% sure that preserving `B` is really difficult because our limitation with suffix whitespace on expressions)

So this issue is to get some recommendations and advice from you about doing work that could benefit several features at the same time:

* Should I focus only on what I need for `dhall-docs`?
* Should I try to do changes that favour as much features as we can although:
    1. Those features won't be implemented right now (PRs on `dhall format` are not so frequent, for instance)
    2. `dhall-docs` doesn't really need those changes right away?

Note that although I specify the `Field` case, the same question can be applied on any other context on this repository (or on any project)

**Comment by german1608** [comment]
(off-topic on the main purpose of this issue, but preserving the whitespace that `dhall-docs` needs on `Field` would allow users to write code like this:

```dhall
a
  .b -- foo
  .c -- bar
  .d -- baz
```

which will be cool to preserve from `dhall format`)

**Comment by Gabriel439** [comment]
@german1608: I would focus on what is needed for `dhall-docs`

**Comment by sjakobi** [comment]
> @german1608: I would focus on what is needed for `dhall-docs`

Agreed!

I'm very happy to see work on this extension of JTD, BTW! :)

**Comment by german1608** [comment]
Thanks for your suggestions. I've taken them in the develop of #1991, so I'm closing this issue now

**Comment by Gabriel439** [comment]
@german1608: You're welcome! 🙂
