### ISSUE TITLE
dhall completion does not return record fields

### ISSUE THREAD

**Issue by nickhs** [dhall-lang/dhall-haskell#1992]
Love Dhall, and love the work that's going into the LSP implementation. One thing I find odd is that the completion doesn't return record names currently. Concretely I'd expect:

```dhall
let Config = { name : Text, age : Natural }

in { name = "alice", a<complete here> } : Config
```

to offer `age` as a completion option. I don't believe that's currently happening - though LSP returns all the other bound variables and reserved keywords in that context.

**Comment by Gabriel439** [comment]
@nickhs: Yeah, this is not yet implemented, although there was an initial attempt along those lines in https://github.com/dhall-lang/dhall-haskell/pull/1621

It should be possible, though, as that attempt got pretty close

**Comment by nickhs** [comment]
Cool! Right now I have to keep open the dhall types and file I'm editing when working on large projects (eg kubernetes) so I can understand what's possible for each record/field. If I could have the lang server inform me what objects could make sense when hitting ctrl+space at a point that would be the dream.

It looks like #1621 is trying to get to that more holistically than my desire to add record fields to the completion. I'm happy to close this out as a dupe of #1615?

**Comment by Gabriel439** [comment]
@nickhs: Yeah, we can use #1651 to track this.  Thank you for reporting, though! :slightly_smiling_face:
