### ISSUE TITLE
Issue with pretty printing empty list

### ISSUE THREAD

**Issue by zzat** [dhall-lang/dhall-haskell#1996]
When I try to use the output generated by `ppExpr` for an empty list, it throws an error. Sample usecase:

```
ppExpr (With (RecordLit (fromList [("field",ListLit Nothing (fromList [TextLit (Chunks [] "foo")]))])) ("field" :| []) (ListLit (Just (App List Text)) (fromList [])))
```
Output:
```
"{ field = [ \"foo\" ] } with field = [] : List Text"
```
Trying this out with dhall executable throws:
```
Error: An empty list requires a type annotation

1│                                    []

```
When I manually wrap the list and type annotation with parenthesis, it works:
```
{ field = [ "foo" ] } with field = ([] : List Text)
```
I couldn't find a way to add parenthesis in the AST. Is there any way I can fix this?

**Comment by sjakobi** [comment]
What is `ppExpr`?

**Comment by zzat** [comment]
It just calls the `prettyExpr` function

```
ppExpr :: Expr Void Import -> String
ppExpr = show . prettyExpr
```

**Comment by sjakobi** [comment]
Which version of `dhall` are you using?

**Comment by zzat** [comment]
It is `1.31.1`

**Comment by sjakobi** [comment]
Can you try again with the latest version? I think there have been a few related changes since.

**Comment by zzat** [comment]
Yeah seems like that is fixed. Thanks!

**Comment by sjakobi** [comment]
You're welcome, @zzat! :)
