### ISSUE TITLE
Unexpected dhall format around `toMap`

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#1999]
Given this file:
```
let oc = env:OC

let nsp = "openshift-config"

let local_users =
      oc.Secret::{
      , name = "htpass-users"
      , metadata = oc.core.ObjectMeta::{
        , annotations = Some
            ( toMap
                { description =
                    "Secret containing local user bcrypt hash passwords"
                }
            )
        }
      , data = Some
          (toMap { htpasswd = ./local-accounts.passwd.base64 as Text })
      }

in  [ oc.makeSecret nsp local_users ]
```

dhall format is forcing `( toMap` for the first occurence but `(toMap` for the second.

I believe this makes no sense for the end user.

I guess it has something to do with the decision to force the line break so I am expecting to close this issue right away - unless there is an easy fix to make white spaces "behave" consistently around keywords.

As a note on that matter I believe I have read somewhere @ocharles was against such a kind of format engine that doesn't preserve the user decision to end the line.  I can't find the link anymore but I have to say I am wholeheartedly with him on that subject ;-)

I have found the dhall formatter doing too much changes of questionable merit (sorry for the rambling).

**Comment by Gabriel439** [comment]
@PierreR: As far as I can tell this is a bit challenging to fix, so this is low priority for me to address

What's going on here is that the formatter tries to ensure that everything is aligned to an even number of columns, so when formatting a multi-line expression wrapped in parentheses it inserts an obligatory space after the open parenthesis.  I believe fixing the following token to begin immediately after the parentheses would require tighter coupling of the pretty-printer logic

**Comment by sjakobi** [comment]
Here is a more reduced example:

```
[ f (g x)
, f
    ( g
        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    )
]
```

Personally, I don't think that the space between the `(` and the function (`g`) is very surprising when the expression is broken over multiple lines, and changing that wouldn't be worth a big increase in pretty-printer complexity IMHO.



> As a note on that matter I believe I have read somewhere @ocharles was against such a kind of format engine that doesn't preserve the user decision to end the line. I can't find the link anymore but I have to say I am wholeheartedly with him on that subject ;-)

You're probably referring to https://github.com/dhall-lang/dhall-haskell/issues/244 and/or https://github.com/dhall-lang/dhall-haskell/issues/1496.

**Comment by PierreR** [comment]
@sjakobi thanks so much for the link. Indeed the `Vonderhaar` style pretty-printer is what I was looking for. 

I agree spending works on this does not worth it even more so knowing a change of pretty printer might actually happen one day.
