### ISSUE TITLE
Newline is not whitespace

### ISSUE THREAD

**Issue by ttuegel** [dhall-lang/dhall-haskell#200]
The documentation says,
```
Dhall is whitespace-insensitive, so feel free to format things over multiple lines or indent in any way that you please.
```
However, the parser does not treat `\n` as whitespace, so this is not true. For example,
```
let foo = "foo" in let bar = "bar" in foo ++ bar
```
is a fine expression, but replacing some spaces with newlines is a parse error:
```
let foo = "foo" in
let bar = "bar" in
foo ++ bar
```
because it parses as
```
let foo = "foo" inlet bar = "bar" infoo ++ bar
```
This would seem to be highly-sensitive to whitespace, unless `\n` is not considered whitespace. That is VERY surprising; I think most people would consider `\n` to be whitespace.

1. Is this the intended parser behavior?
2. If this is intended, can I convince you to change it so that `\n` is treated as whitespace?
3. If I cannot convince you to change it, what is the rationale?

**Comment by ttuegel** [comment]
This is my mistake; I was doing something embarrassingly foolish with my input. My sincerest apologies!

**Comment by Gabriel439** [comment]
No problem at all 🙂
