### ISSUE TITLE
`dhall resolve --transitive-dependencies` doesn't return imports' imports

### ISSUE THREAD

**Issue by german1608** [dhall-lang/dhall-haskell#2004]
```
$ dhall resolve --transitive-dependencies --file dhall/dhall-lang/Prelude/package.dhall
./dhall/dhall-lang/Prelude/Bool/package.dhall sha256:7ee950e7c2142be5923f76d00263e536b71d96cb9c190d7743c1679501ddeb0a
./dhall/dhall-lang/Prelude/Double/package.dhall sha256:b8d20ab3216083622ae371fb42a6732bc67bb2d66e84989c8ddba7556a336cf7
./dhall/dhall-lang/Prelude/Function/package.dhall sha256:6d17cf0fd4fabe1737fb117f87c04b8ff82b299915a5b673c0a543b134b8fffe
./dhall/dhall-lang/Prelude/Integer/package.dhall sha256:d1a572ca3a764781496847e4921d7d9a881c18ffcfac6ae28d0e5299066938a0
./dhall/dhall-lang/Prelude/List/package.dhall sha256:547cd881988c6c5e3673ae80491224158e93a4627690db0196cb5efbbf00d2ba
./dhall/dhall-lang/Prelude/Location/package.dhall sha256:0eb4e4a60814018009c720f6820aaa13cf9491eb1b09afb7b832039c6ee4d470
./dhall/dhall-lang/Prelude/Map/package.dhall sha256:598e9c76103b2686fbbda6cc30078f9e60dd846d9eaf155d0149cf0ae06c21c5
./dhall/dhall-lang/Prelude/Monoid sha256:26fafa098600ef7a54ef9dba5ada416bbbdd21df1af306c052420c61553ad4af
./dhall/dhall-lang/Prelude/Natural/package.dhall sha256:ee9ed2b28a417ed4e9a0c284801b928bf91b3fbdc1a68616347678c1821f1ddf
./dhall/dhall-lang/Prelude/Optional/package.dhall sha256:4324b2bf84ded40f67485f14355e4cb7b237a8f173e713c791ec44cebebc552c
./dhall/dhall-lang/Prelude/JSON/package.dhall sha256:79dfc281a05bc7b78f927e0da0c274ee5709b1c55c9e5f59499cb28e9d6f3ec0
./dhall/dhall-lang/Prelude/Text/package.dhall sha256:819a967038fbf6f28cc289fa2651e42835f70b326210c86e51acf48f46f913d8
./dhall/dhall-lang/Prelude/XML/package.dhall sha256:137e7b106b2e9743970e5d37b21a165f2e40f56ab593a4dd10605c9acd686fc6
```

I expected that other imports such as `Prelude/Bool/and`, for example, would be listed here too because I believed of the `transitive` on `--transitive-dependencies`. I'm not sure if this is the expected behavior, though, and wouldn't mind closing the issue if that's the case

Also, from the `--transitive-dependencies` description:

> List transitive import dependencies in post-order

isn't post-order the reverse order in the source code?

**Comment by Gabriel439** [comment]
@german1608: It only prints dependencies that were actually resolved.  You might have to use the `--no-cache` flag or set `XDG_CACHE_HOME=/var/empty` if you want the full list.

**Comment by Gabriel439** [comment]
@german1608: Also, if this is for `dhall-docs`, then you might want to study and/or upstream the logic that `dhall-nixpkgs` uses to find transitive dependencies:

https://github.com/dhall-lang/dhall-haskell/blob/4b4669cf8ababa5cadb3f972821ff8ff20d8d0fe/dhall-nixpkgs/Main.hs#L295-L359

**Comment by german1608** [comment]
@Gabriel439: Thanks for the resource!

**Comment by Gabriel439** [comment]
@german1608: You're welcome! 🙂

**Comment by PierreR** [comment]
@Gabriel439 @vmchale could the above recipe be relevant for `shake-dhall` (https://github.com/vmchale/shake-dhall)  ?

**Comment by vmchale** [comment]
Definitely!

**Comment by sjakobi** [comment]
> Also, from the `--transitive-dependencies` description:
> 
> > List transitive import dependencies in post-order
> 
> isn't post-order the reverse order in the source code?

If I compare the description of post-order at https://en.wikipedia.org/wiki/Tree_traversal#Post-order,_LRN with the output of

```
$ dhall resolve --no-cache --transitive-dependencies --file dhall/dhall-lang/Prelude/package.dhall
```

it seems to match.

Closing since it looks like there's nothing left to do here!
