### ISSUE TITLE
Swap out the HTTP Manager 

### ISSUE THREAD

**Issue by amesgen** [dhall-lang/dhall-haskell#2022]
Right now, dhall-haskell uses the `Manager` from http-client-tls to resolve remote imports by default. It can be disabled, but I don't see an easy way to provide a different `Manager` (maybe an `IO Manager` is better for laziness), especially without depending on `http-client-tls` (maybe a new flag is necessary). This might be desirable if
 - one only needs plain HTTP imports (probably rare),
 - one does already depend on another dependency providing a TLS-enabled `Manager` (http-client-openssl), or
 - one has security considerations (see e.g. [here](https://github.com/vincenthz/hs-tls/issues/117) or [here](https://github.com/haskell-crypto/cryptonite/issues/330)).

I am happy to create a PR if the direction is clear, though it might take some time.

**Comment by Gabriel439** [comment]
@amesgen: Yeah, it's definitely possible.  We already do something similar for GHCJS support.  The basic idea is that you add a Cabal configure flag and then the package can conditionally depend on `http-client-tls` depending on what that flag is set to.

However, generally I'd recommend first seeing if the upstream issues can be resolved first, but if you submit a PR to add this I won't reject it.
