### ISSUE TITLE
dhall-openapi.cabal won't 'cabal build"

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#2026]
From all the cabal files, the one from `dhall-openapi` does not seem to work

It fails with:
```
[nix-shell:~/projects/hub/dhall-haskell/dhall-openapi]$ cabal build
cabal: No targets given and there is no package in the current directory. Use
the target 'all' for all packages in the project or specify packages or
components by name or location. See 'cabal build --help' for more details on
target options.
```

```
[nix-shell:~/projects/hub/dhall-haskell/dhall-openapi]$ cabal --version
cabal-install version 3.2.0.0
compiled using version 3.2.0.0 of the Cabal library 
```

I have been trying to understand why but have failed so far ;-)

**Comment by PierreR** [comment]
Hum, `cabal build all` works ...

**Comment by Gabriel439** [comment]
@PierreR: Just out of curiosity, could you try adding `./dhall-openapi` to this file: https://github.com/dhall-lang/dhall-haskell/blob/master/cabal.project

… and then try again?  I suspect that the `cabal.project` file in the root directory might be confusing Cabal

Another thing to try is `cabal build dhall-openapi`
