### ISSUE TITLE
Dhall format of plain record produces operator (/\) merge  

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#2032]
This must be the most surprising `dhall format` I have encountered so far ;-)
```
  { kafka.keystore.p12 = "fgfg"
  , kafka.properties = "ds="
  , kafka.truststore.jks = "L3UzKzdRQUdsFBQ9"
  }
```
->
```
{ kafka =
      { keystore.p12 = "fgfg" }
    ∧ { properties = "ds=" }
    ∧ { truststore.jks = "L3UzKzdRQUdsFBQ9" }
}

```

**Comment by sjakobi** [comment]
Nice catch! :+1:

**Comment by sjakobi** [comment]
The expected output is

```
{ kafka.keystore.p12 = "fgfg"
, kafka.properties = "ds="
, kafka.truststore.jks = "L3UzKzdRQUdsFBQ9"
}
```

right?!

**Comment by PierreR** [comment]
Anything less intrusive would do ;-) 

I first believe only `dhall lint` would go that far but I was quite surprised even `dhall format` was doing this kind of transformation.

**Comment by sjakobi** [comment]
Actually

```
{ kafka =
    { keystore.p12 = "fgfg"
    , properties = "ds="
    , truststore.jks = "L3UzKzdRQUdsFBQ9"
    }
}
```

would also seem reasonable to me. I think that might have been the intention of the current formatting code, but the explicit `/\`s look like a bug.

**Comment by PierreR** [comment]
Sure I would not mind the second option. I have no real preference.

**Comment by Gabriel439** [comment]
Yeah, this is an unintended consequence of how we desugar chained accessors at parse time.  I believe the way we can fix this is the same way we handle other syntactic sugar: "resugar" at pretty-printing time.

**Comment by Gabriel439** [comment]
@sjakobi: Also, my plan is to resugar as the first expected output you suggested:

```dhall
{ kafka.keystore.p12 = "fgfg"
, kafka.properties = "ds="
, kafka.truststore.jks = "L3UzKzdRQUdsFBQ9"
}
```

… since that preserves the user's original intention.  If the user wanted the latter expected output they can always explicitly author the code that way and the formatter would preserve that, too.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2037
