### ISSUE TITLE
Command line:  file path completion

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#2033]
This might looks like a detail but it comes to a surprise that `dhall` command supports completions (which is 🎉) but on the other hand file name are not completed (for instance dhall type --file TABTAB).

The later behaviour is really uncommon on a linux terminal.

Is this something that could be fixed easily ?

**Comment by Gabriel439** [comment]
@PierreR: Yeah, I'm fairly confident that this can be fixed.  The main thing I need to know is how you obtained/install `dhall`, since that can affect how the completions are provided

**Comment by ggilmore** [comment]
I install dhall via https://github.com/aaaaninja/asdf-dhall

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2034
