### ISSUE TITLE
Misleading parse error on missing comma in a record

### ISSUE THREAD

**Issue by akshaymankar** [dhall-lang/dhall-haskell#2035]
When I run:
```
dhall <<< 'foo bar::{a = 1 b = 2}'
```

I get this error:
```
dhall:
Error: Invalid input

(input):1:5:
  |
1 | foo bar::{a = 1 b = 2}
  |     ^
unexpected 'b'
expecting ->, :, end of input, keyword, operator, or whitespace
```

Here clearly a `,` is missing in the record. It is not very clear when the expression is bigger and spans multiple lines. It would be nice if the parser could try harder to find the problem :smile:

**Comment by sjakobi** [comment]
I believe this is another instance of https://github.com/dhall-lang/dhall-haskell/issues/1592.

**Comment by akshaymankar** [comment]
Yeah, looks like it. I will close this one, thanks.

**Comment by winitzki** [comment]
With https://github.com/dhall-lang/dhall-haskell/pull/2836 there will be this message:

```dhall
⊢ foo bar::{a = 1 b = 2}

Error: Invalid input

(input):1:19:
  |
1 | foo bar::{a = 1 b = 2}
  |                   ^
Missing ',' in record literal
```
