### ISSUE TITLE
Add an entry to scoop

### ISSUE THREAD

**Issue by ursi** [dhall-lang/dhall-haskell#2036]
I just found about about [scoop](https://scoop.sh), and I'm really liking it. However, I just noticed it doesn't have dhall.

**Comment by Gabriel439** [comment]
@ursi: I'd be fine creating an initial manifest if other people could take care of keeping it up to date

**Comment by Gabriel439** [comment]
I have a pull request up to add `dhall` to scoop here: https://github.com/ScoopInstaller/Main/pull/1546

**Comment by Gabriel439** [comment]
Fixed by https://github.com/ScoopInstaller/Main/pull/1546
