### ISSUE TITLE
dhall format removes required parentheses before with expressions

### ISSUE THREAD

**Issue by JohannesRudolph** [dhall-lang/dhall-haskell#2047]
Take this example

```dhall
let x = ({ foo = 1 } ∧ { bar = 2 })
  with bar = 3 
  with foo = 4 
in x
```

Using 
```text
dhall --version
1.35.0
```

This prints just fine

```
dhall --file test.dhall
{ bar = 3, foo = 4 }
```

But after running dhall format on it, it removes the parentheses around the union of the `foo` and `bar` records, leading to an error with the following `with` expressions.

```
dhall format --inplace test.dhall && dhall --file test.dhall
dhall: 
Error: Invalid input

test.dhall:1:35:
  |
1 | let x = { foo = 1 } ∧ { bar = 2 } with bar = 3 with foo = 4 in x
  |                                   ^^
unexpected "wi"
expecting ->, :, keyword, or whitespace
```

This is a bit of a bummer because we quite heavily rely on auto-formatting and have a decent number of places that rely on a similar coding pattern. I feel that dhall format should never alter code in a way that alters its semantic (or breaks the parser).

**Comment by sjakobi** [comment]
Thanks for the report!

Fix is up in https://github.com/dhall-lang/dhall-haskell/pull/2048.
