### ISSUE TITLE
Get source position of errors without parsing the error message

### ISSUE THREAD

**Issue by kenranunderscore** [dhall-lang/dhall-haskell#2057]
Our web application contains a text editor component where the user may enter some Dhall configuration code. We send this to the (Haskell/servant) server to "validate" it.
Now the `Dhall.inputWithSettings` function and others return `IO` and throw an exception I can catch to get the resulting error message which includes (among others) the line and column positions of the actual error. I wonder whether I can get this information without catching an exception on `input...` and extracting it from the error message.

I had a look at the `Dhall.Parser` module where I can use `exprFromText` to at least get some information about syntactic errors by leveraging `megaparsec`. But then I don't see how I can re-use the resulting `Expr` to validate "the rest". It seems like I still have to either use some form of `input` to find, for instance, type errors, or re-implement some more internal functions.

Is there an easier way to do this that I'm not seeing? Thanks!

**Comment by Gabriel439** [comment]
@kenranunderscore: You can essentially do what the `input` functions are doing under the hood if you split out the steps.  In other words, something like:

```haskell
example text = do
    parsedExpression <- case Dhall.Parser.exprFromText "(stdin)" text of
        Left parseError -> do
            … {- Extract line and column numbers from `parseError` -}
            fail "Urk!"
        Right expression ->
            return parsedExpression

    resolvedExpression <- Dhall.Import.load parsedExpression

    _typeOfExpression <- Dhall.Core.throws (Dhall.TypeCheck.typeOf resolvedExpression)

    let normalizedExpression = Dhall.Core.normalize resolvedExpression

    return normalizedExpression
```

At the moment there currently isn't a utility in the `Dhall` module that starts from an already-parsed expression, though.

**Comment by sjakobi** [comment]
Closing since the question seems to have been answered.

Please re-open if there's anything left to do here!
