### ISSUE TITLE
dhall-docs README: Link to Prelude docs is broken

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#2058]
https://github.com/dhall-lang/dhall-haskell/tree/master/dhall-docs#features includes a link to https://hydra.dhall-lang.org/job/dhall-haskell/master/generate-dhall-docs/latest/download/1/docs which currently produces a 404 for me.

![image](https://user-images.githubusercontent.com/3664523/94808130-ebeacc80-03f0-11eb-96a6-f829b7499273.png)

@german1608 Any ideas?

**Comment by german1608** [comment]
@sjakobi no idea, maybe hydra garbage collected that link? I dont have a lot of expertise on nix, though.

**Comment by german1608** [comment]
Probably @Gabriel439 has better intuition of what is going on
