### ISSUE TITLE
Provide a download progress indicator?

### ISSUE THREAD

**Issue by arianvp** [dhall-lang/dhall-haskell#2062]
Dhall can take a very long time importing projects like `dhall-kubernetes`. It would be nice if it printed a progress bar to stderr during evaluation

**Comment by Gabriel439** [comment]
I'm closing this in favor of https://github.com/dhall-lang/dhall-haskell/issues/1511

The main reason I'm not implementing a progress bar (yet) is because I think we can get this much faster, to the point where a progress bar is not necessary
