### ISSUE TITLE
Docs markdown parser too sensitive to underscore

### ISSUE THREAD

**Issue by craig-day** [dhall-lang/dhall-haskell#2065]
It seems that the documentation parser is too sensitive to the markdown text formatting characters. Not sure if the dhall docs parser is doing this, or some other markdown library, but it would be nice to not see a warning for even a single underscore.

```
Warning
/path/to/file.dhall:1:15:
  |
1 | Usage: my_library gem
  |          ^
'_' should be in left- or right- flanking position
The original non-markdown text will be pasted in the documentation
```

**Comment by german1608** [comment]
Hi, @craig-day! Thanks for your submission.

The problem here is from the markdown parser dependency, [mmark](https://github.com/mmark-md/mmark), which uses [commonmark](https://commonmark.org): a more strict specification of markdown

But after I googled, I found this

https://stackoverflow.com/questions/35827838/how-to-show-underscores-symbol-in-markdown

It looks like you need to escape the `_` by writing `\_`:

```
Usage: my\_library gem
```

**Comment by craig-day** [comment]
Yeah, I can escape them but it feels wrong. Thanks much for the links.

After some further reading of the commonmark spec, it actually appears that this is wrong. It explicitly states that emphasis or strong can only be opened or closed by a flanking character, and that any non-flanking underscore or asterisk is treated as a literal. 

This is illustrated this with examples [359](https://spec.commonmark.org/0.29/#example-359) and [360](https://spec.commonmark.org/0.29/#example-360). 

![Screen Shot 2020-10-10 at 12 06 00 PM](https://user-images.githubusercontent.com/6731804/95663091-00198280-0af1-11eb-9ba9-c9304a090d4a.png)

So, I suppose what I'm really asking is can those warnings be silenced in the way dhall-docs uses the libraries, or should I go open an issue with mmark or commonmark to see about removing those as warnings?

**Comment by german1608** [comment]
Good research.

It's better to upstream that fix on the mmark repository. `dhall-docs` should not worry about detecting the type of error from mmark (and in fact it is not possible).

What we can try is to check if this issue has been solved in a newer version before submitting it. I can check that tomorrow, if you are not in a hurry

**Comment by craig-day** [comment]
Definitely not in a hurry. Any help is much appreciated, thanks!

**Comment by craig-day** [comment]
Taking a look at mmark, it seems that this is a result as a design simplification choice. Reading through the [Differences in inline parsing](https://github.com/mmark-md/mmark#differences-in-inline-parsing) section of their readme talks about the complications of the emphasis and strong rules. I might open an issue with them to see if we can at least make assertions on pairs of these characters, but if you can check for an updated version before I do that, that would be greatly appreciated.

**Comment by Gabriel439** [comment]
@craig-day: We're currently using `mmark-0.0.7.1` (the last version is `0.0.7.2`), and it looks like the only thing that changed in `0.0.7.2` is building against `megaparsec-8.0.0`, so I believe we're using essentially the latest version of `mmark`'s markdown parsing algorithm.

**Comment by craig-day** [comment]
Thanks @german1608 and @Gabriel439 , I'll see if I can get the behavior addressed upstream. Feel free to close the issue here if you'd like, since the dhall docs generator can't do much about it.

**Comment by Gabriel439** [comment]
Alright, then I'll go ahead and close this.  Thank you for reporting this!
