### ISSUE TITLE
"Multiple declarations" errors in Haskell using makeHaskellTypes with MultipleConstructors

### ISSUE THREAD

**Issue by joefiorini** [dhall-lang/dhall-haskell#2066]
I'm working on a project where I have unions that reference other types in the same file. Here is an example of some Dhall types that will exhibit the problem I'm having:

```dhall
let Bar = { baz : Integer }
let Foo = { foo : Integer, bar : Bar }
let Qux = < Foo : Foo | Bar : Bar >
in { Foo, Bar, Qux }
```
When I try to convert these to Haskell types using `Dhall.TH` I get a bunch of "Multiple declarations" errors from Haskell because (I'm assuming) it's replacing `Qux`s reference to `Bar` with the actual type of `Bar` (probably some sort of normalization logic?) Here is the Haskell code I'm using to bring them in:

```haskell
#!/usr/bin/env nix-shell
#! nix-shell -I nixpkgs="channel:nixpkgs-unstable" --keep LANG --keep LC_ALL --keep NIX_CONF_DIR
#! nix-shell --pure -i "runghc" --packages ghcid "haskellPackages.ghcWithPackages (pkgs: [ pkgs.turtle pkgs.dhall ])" -p git -p glibcLocales

{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}

import Dhall
import Dhall.TH
import Data.Text (Text)
import qualified Data.Text as T
--import DhallCode


makeHaskellTypes
  [ SingleConstructor "Bar" "Bar" "(./test-types.dhall).Bar"
  , SingleConstructor "Foo" "Foo" "(./test-types.dhall).Foo"
  , MultipleConstructors "Qux" "(./test-types.dhall).Qux"
  ]

foo' = Foo {
  foo = 1
, bar = Bar {
    baz = 2
  }
}

deriving instance Show Foo
deriving instance Show Bar

main = do
  putStrLn $ show foo'
```
When I run it I get the following errors from Haskell:

```
test-interp.hs:21:1: error:
    Multiple declarations of ‘bar’
    Declared at: test-interp.hs:21:1
                 test-interp.hs:21:1
   |
21 | makeHaskellTypes
   | ^^^^^^^^^^^^^^^^...

test-interp.hs:21:1: error:
    Multiple declarations of ‘foo’
    Declared at: test-interp.hs:21:1
                 test-interp.hs:21:1
   |
21 | makeHaskellTypes
   | ^^^^^^^^^^^^^^^^...

test-interp.hs:21:1: error:
    Multiple declarations of ‘baz’
    Declared at: test-interp.hs:21:1
                 test-interp.hs:21:1
   |
21 | makeHaskellTypes
   | ^^^^^^^^^^^^^^^^...
```

If I don't try to convert `Qux` then `Foo` and `Bar` both get pulled in just fine, but then I have to create and maintain a separate `Qux` type in Haskell manually, which breaks the "single source of truth in Dhall" idea that @Gabriel439 has recommended.

This smells like a bug to me, since the `SingleConstructor` version doesn't conflict when both types reference `Bar`. Or am I doing something wrong?

**Comment by Gabriel439** [comment]
@joefiorini: I believe what is happening is that the Template Haskell code is generating the following Haskell code:

```haskell
data Bar = Bar { baz :: Integer }

data Foo = Foo { foo :: Integer, bar :: Bar }

data Qux = Foo { foo :: Integer, bar :: Bar } | Bar { baz :: Integer }
```

... and I'm guessing you expected it to generate the following code:

```haskell
data Bar = Bar { baz :: Integer }

data Foo = Foo { foo :: Integer, bar :: Bar }

data Qux = Foo Foo | Bar Bar
```

The reason why the code generation behaves this way is because the type deduplication logic only checks the types of the fields to see if each field can be replaced with a reference to another Haskell type (which is why the `bar` fields correctly contain references to the `Bar` type).  However, it doesn't check if the set of fields as a whole can be replaced with a single anonymous field.  That can be fixed, though, if that's the behavior you desire.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2070

**Comment by Gabriel439** [comment]
@joefiorini: You're welcome! 🙂
