### ISSUE TITLE
Better error messages with record types mismatching

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#207]
I'm currently at the following:

```
ou or the interpreter annotated this expression:                               
                                                                                
↳ { benchmarks = [] : List { main-is : Text, name : Text }, executables = [{ build-dependencies = [{ package = "base" }], main-is = "Main.hs", name = "dhall-to-cabal" }], foreign-libraries = [] : List { name : Text, type : < Shared : {} > }, library = [] : Optional { build-dependencies : List { package : Text }, name : Optional Text }, package = { name = "dhall-to-cabal", version = [+0, +1, +0] }, source-repos = [] : List {}, tests = [] : List { build-dependencies : List { package : Text }, main-is : Text, name : Text }, x-fields = [] : List { _1 : Text, _2 : Text } }                                                                
                                                                                
... with this type or kind:                                                     
                                                                                
↳ { benchmarks : List { main-is : Text, name : Text }, executables : List { build-dependencies : List { package : Text }, main-is : Text, name : Text }, foreign-libraries : List { name : Text, type : < Shared : {} > }, library : Optional { build-dependencies : List { package : Text }, name : Text }, package : { name : Text, version : List Natural }, source-repos : List {}, tests : List { build-dependencies : List { package : Text }, main-is : Text, name : Text }, x-fields : List { _1 : Text, _2 : Text } }                                                                
                                                                                
... but the inferred type or kind of the expression is actually:                
                                                                                
↳ { benchmarks : List { main-is : Text, name : Text }, executables : List { build-dependencies : List { package : Text }, main-is : Text, name : Text }, foreign-libraries : List { name : Text, type : < Shared : {} > }, library : Optional { build-dependencies : List { package : Text }, name : Optional Text }, package : { name : Text, version : List Natural }, source-repos : List {}, tests : List { build-dependencies : List { package : Text }, main-is : Text, name : Text }, x-fields : List { _1 : Text, _2 : Text } }                                                                

────────────────────────────────────────────────────────────────────────────────

{ benchmarks        = [] : List { main-is : Text, name : Text }
, executables       =
    [ { build-dependencies = [ { package = "base" } ]
      , main-is            = "Main.hs"
      , name               = "dhall-to-cabal"
      }
    ]
, foreign-libraries = [] : List { name : Text, type : < Shared : {} > }
, library           =
    [] : Optional
         { build-dependencies : List { package : Text }, name : Optional Text }
, package           = { name = "dhall-to-cabal", version = [ +0, +1, +0 ] }
, source-repos      = [] : List {}
, tests             =
    [] : List
         { build-dependencies : List { package : Text }
         , main-is            : Text
         , name               : Text
         }
, x-fields          = [] : List { _1 : Text, _2 : Text }
}
 : { benchmarks : List { main-is : Text, name : Text }, executables : List { build-dependencies : List { package : Text }, main-is : Text, name : Text }, foreign-libraries : List { name : Text, type : < Shared : {} > }, library : Optional { build-dependencies : List { package : Text }, name : Text }, package : { name : Text, version : List Natural }, source-repos : List {}, tests : List { build-dependencies : List { package : Text }, main-is : Text, name : Text }, x-fields : List { _1 : Text, _2 : Text } }
```

This error just makes me freeze.

We should recurse into the types as much as we can and show a minimal diff.

**Comment by Gabriel439** [comment]
Yeah, this seems reasonable to me.  I just haven't gotten around to this yet.  One thing that can be decided here ahead of the code changes is what the user experience should look like (i.e. how to render the "path" to the two sub-expressions that differ)

**Comment by aleator** [comment]
I have a small program that takes two dhall record types and removes all identical fields and adds an ellipsis to the prettyprinted result if anything was removed. Makes things bit easier to read. Perhaps 
 a similar thing could be done when emitting the current type error?

**Comment by ocharles** [comment]
That is the kind of thing we want, definitely. Could you share the output - maybe using the above type error?

**Comment by Gabriel439** [comment]
I forgot to mention that I already have a branch that does most of this:

https://github.com/dhall-lang/dhall-haskell/compare/gabriel/diff

Here is an example output from that branch:

```
$ dhall
  { foo = 1, bar = { baz = "ABC", qux = True }, xyzzy = [ 2.0, 3.0 ] }
: { foo : Integer, bar : { baz : Text, qux : Natural, xyzzy : List Double } }
<Ctrl-D>

Use "dhall --explain" for detailed errors

Error: Expression doesn't match annotation

{ + xyzzy : …
,   bar : { - xyzzy : …
          ,   qux : - Natural
                    + Bool
          , …
          }
, …
}

{ foo = 1
, bar = { baz = "ABC"
        , qux = True
        }
, xyzzy = [ 2.0, 3.0 ]
} : { foo : Integer, bar : { baz : Text, qux : Natural, xyzzy : List Double } }

(stdin):1:1
```

However, it still needs additional work because it doesn't descend into lambdas or function types, yet.

**Comment by ocharles** [comment]
Oh, neat! I was going to do this at ZuriHac, I guess I'll have to find something else ;)

**Comment by aleator** [comment]
Well, mine doesn't recurse either, but UI-wise I think it would be actually better to print out both elided types instead of +/-. For example:

    Expected: { foo : Integer, bar : { baz : Text, qux : Natural, xyzzy : List Double } 
    Got: { foo : Integer, bar : { baz : Text, qux : Bool}, xyzzy : List Double } }

would render as:

    Expected: { ... , bar : { ... , qux : Natural , xyzzy : List Double ... } ... } 
    Got:          { ... , bar : { ... qux : Bool ... }, xyzzy : List Double ... } }

Comparing two things requires bit more effort, but might be less strange than +/- and it is more clear what gets elided.

I would expect that most common case is that there is actually just a single field that is wrong and the message is rather short. Except, of course, in the case where a completely wrong type of record is used making all the fields wrong. That might need a special case message.

**Comment by ocharles** [comment]
I think +/- is going to scale much better to bigger error messages. I think we can use some ANSI colour on the error too, highlighting the - in red and the + in green. (with a - Got + Expected) at the top to clarify what you should be looking for.

**Comment by aleator** [comment]
Well, I would be extremely happy regardless of how this is done if it is done :)

**Comment by ocharles** [comment]
Just wanted to mention that this is a little more important now that we have ordered fields - you can no longer just diff the two types (after using `dhall-format`) unless you get lucky that they are in the same order.

**Comment by Gabriel439** [comment]
@ocharles: This is getting really close to complete.  For example, I just took the `dhall-to-cabal.dhall` and gave a type annotation that was slightly wrong in a few places, which produces the following output:

```
$ dist/build/dhall/dhall <<< '../dhall-to-cabal/dhall-to-cabal.dhall : ./type.dhall'

Use "dhall --explain" for detailed errors

Error: Expression doesn't match annotation

{ - license2 : …
, + license : …
,   library : …
              (   ∀(… : { arch :   ∀(… : < S390 : - Bool
                                                  + {}
                                         | …
                                         > 
                                   )
                                 → …
                        , …
                        } 
                  )
                → { build-tools : …
                                  { - version2 : …
                                  , + version : …
                                  , …
                                  } 
                  , default-extensions : …
                                         < - NamedWildCards2 : …
                                         | - UnboxedSums : …
                                         | + DataKinds : …
                                         | + NamedWildCards : …
                                         | …
                                         > 
                  , …
                  } 
              )
, …
} 

../dhall-to-cabal/dhall-to-cabal.dhall : ./type.dhall

(stdin):1:1
```

Note that the diff is actually backwards, but I'll fix that.

You can test drive it using this branch:

https://github.com/dhall-lang/dhall-haskell/tree/gabriel/diff

I estimate about 1 more week before it's ready (but possibly a month before it's on hackage just due to pacing non-Stackage-related releases)

**Comment by Gabriel439** [comment]
Alright, I have a pull request up with support for diffs:

https://github.com/dhall-lang/dhall-haskell/pull/336

These diffs are not only used in type errors but also allow you to
diff arbitrary Dhall expressions via the Haskell API
