### ISSUE TITLE
Print details for ConnectionTimeout errors

### ISSUE THREAD

**Issue by rautenrieth-da** [dhall-lang/dhall-haskell#2075]
I am facing an issue where `dhall type --file` fails with ConnectionTimeout errors, while the same command works on the same input file on other machines.

I have a file `prelude.dhall` with the following content:
```
let Prelude =
      https://prelude.dhall-lang.org/v17.0.0/package.dhall sha256:10db3c919c25e9046833df897a8ffe2701dc390fa0893d958c3430524be5a43e

in  { Prelude }
```

I have tried deleting my cache, verifying that I can access the prelude URL with `curl` (and also manually in my browser), and then type checking the file:
```
$ rm -rf ~/.cache/dhall
$ rm -rf  ~/.cache/dhall-haskell/
$ curl --silent https://prelude.dhall-lang.org/v17.0.0/package.dhall | shasum
aced19a48239c016a45978d0acfac7456f4d40a5
$ dhall type --file prelude.dhall
dhall: 
ConnectionTimeout
$ ls -l ~/.cache/dhall
total 0
$ ls -l ~/.cache/dhall-haskell
total 0
```

Would it be possible to add some more information to the `ConnectionTimeout` error? Such as, what import failed to resolve? Also, replacing the prelude URL by a non-existing URL results in the same dhall connection timeout after 30sec, even though the server immediately replies with a 404 error when using `curl`.

**Comment by Gabriel439** [comment]
The fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2082
