### ISSUE TITLE
dhall-nixpkgs Unsupported domain error

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#2090]
We have had to re-generate `dhall-kubernetes` to minimize the effect of  #1890 . We are using an internal SCM to host it (it doesn't make sense to make it public).

Unfortunately when we try to use `dhall-to-nixpkgs` we received this error message:

```
Error: Unsupported domain

This tool currently only translates the following domains into Nix dependencies:

* raw.githubusercontent.com
* prelude.dhall-lang.org

One of the Dhall project's dependencies:

↳ http://stash.lan/projects/OC/repos/dhall-openshift/raw/package.dhall?at=0z7d64944e30334fdfaf4149775bafaa14a8df58

... used the following unexpected domain:

↳ stash.lan

If you would like to support a new domain for Dhall dependencies, please open an
issue here:

↳ https://github.com/dhall-lang/dhall-haskell/issues
```

Is there a way to add internal domains to nixpkgs ?

Not sure if it is a proper use case for `dhall-nixpkgs` but I was hoping to mitigate [this issue](https://discourse.dhall-lang.org/t/how-to-clear-cache/376/8?u=pierrer).

**Comment by PierreR** [comment]
This is minor annoyance. I can always clone the internal repo on github (it is not something that is going to change often).

I will close the issue as it might not be relevant enough.

**Comment by Gabriel439** [comment]
@PierreR: Also, note that `dhall-to-nixpkgs` is only a convenience for generating Nix code.  You can also author the equivalent code by hand if it's stable.  It's not yet documented (because I'm blocked on upstream code reviews)
