### ISSUE TITLE
Could Dhall.Type have X as a type parameter?

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#210]
I may be using Dhall incorrectly, but here's what I'm doing.

`dhall-to-cabal` essentially works by taking a Dhall expression, type-checking it and then walking the normalized expression to generate a Cabal `PackageDescription`. I'm mostly doing this by using lots of little `Type`s and then composing them, to use `extract` and `expected`. (Let's ignore Generics for now.)

This works well, until I start introducing some global functions. One such function I'm introducing is:

```
majorVersionBound : List Natural -> VersionRange
```

My plan was to use `normalizeWith` to turn `App "majorVersionBound" components` into `Embed VersionRange`. While this is fine, I then can no longer `extract` from the result, because `extract` fixes me to `Embed X`. It seems that this could really be a type parameter, and most combinators could universally quantify over this.

What do you think? Thanks for being so responsive through my barrage of questions today.

**Comment by Gabriel439** [comment]
Yeah, don't worry :)

There's no specific reason why that type parameter needs to be `X`.  Feel free to generalize it

**Comment by ocharles** [comment]
I mean the `X` in the type of `extract` in https://hackage.haskell.org/package/dhall-1.8.2/docs/Dhall.html#t:Type - unless you mean "feel free to generalize it in a pull request" :)

**Comment by ocharles** [comment]
FWIW, you can see what I butted my head up against in https://github.com/ocharles/dhall-to-cabal/commit/3317c963a1571f999ab86ee9f18a862aa7353b65. I ended up copying `Type` locally, just so I could replace `X`. That meant copying `vector` and `maybe` over... Something doesn't feel quite right!

**Comment by Gabriel439** [comment]
Yeah, I meant to feel free to make a pull request to give it the type you need

**Comment by Gabriel439** [comment]
Marking this "good first issue" since once you identify the type you need for `extract` it should easy to change the library to generalize the type

**Comment by ocharles** [comment]
Closing as per discussion in the associated PR.
