### ISSUE TITLE
dhall-docs release tarball has manpage, but only on MacOS

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-haskell#2104]
We stumbled over this inconsistency in easy-dhall-nix: https://github.com/justinwoo/easy-dhall-nix/pull/40

```
 still some files remaining!
.
./share
./share/man
./share/man/man1
./share/man/man1/dhall-docs.1
strip is /nix/store/l5707pca91sq99fd5fq4x84302zssyjj-cctools-binutils-darwin-949.0.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/qyngk0jnlqz2mj4fzags73n093ki94j1-dhall-lsp-simple/bin
patching script interpreter paths in /nix/store/qyngk0jnlqz2mj4fzags73n093ki94j1-dhall-lsp-simple
builder for '/nix/store/pczvnl48x0qa7qhf3cnzvjyzvl4nx561-dhall-docs-simple.drv' failed with exit code 1
```

Apparently, dhall-docs comes distributed with a manpage, but *only on MacOS*.

Another problem is that the `share` directory is on the *bottom of the tarball*, which makes extracting the tarball complicated with nix; it would be great if release tarballs had a parent directory named after the tool.

**Comment by Profpatsch** [comment]
I noticed that the `dhall` has the same, the manpages are only in the MacOS release.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2111
