### ISSUE TITLE
possible `with` performance regression in 1.36.0 release

### ISSUE THREAD

**Issue by ggilmore** [dhall-lang/dhall-haskell#2105]
Related https://github.com/dhall-lang/dhall-haskell/issues/1960

When I run `dhall` against a file with a lot of chained `with` statements, dhall `1.36.0` seems to choke while dhall `1.35.0` executes the file quickly. 

I've created a reproduction repository here: https://github.com/ggilmore/dhall-performance-regression-example-with

Run `dhall 1.35.0` with `dhall --file=src/fast-1.35.0/fast.dhall` - see that the command executes quickly

Run `dhall 1.36.0` with `dhall --file=src/slow-1.36.0/slow.dhall` - see that the command never terminates

**Comment by Gabriel439** [comment]
Yeah, I'm pretty sure I know what went wrong here.  The regression is likely due to https://github.com/dhall-lang/dhall-haskell/pull/2055 and I believe I can fix it by using an optimization similar to the one we used back when `with` was syntactic sugar.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2112
