### ISSUE TITLE
Frozen imports that include `using` of an import fail integrity checks. 

### ISSUE THREAD

**Issue by craig-day** [dhall-lang/dhall-haskell#2113]
I've setup an example of this and put the explanation in the readme in this repo: https://github.com/craig-day/dhall-freeze-demo

There are 4 commits in that repo that show each of the three stages. Hopefully it all makes sense! 

I'll try to summarize here as well: 

Freezing an import that leverages the `using` directive to set headers will cause integrity check failures because the formatting removes parens causing the checksum to be applied to the wrong value. 

Consider this import: 

```dhall
let Prelude = https://raw.githubusercontent.com/dhall-lang/dhall-lang/v19.0.0/Prelude/package.dhall using ./github-headers.dhall
```

That works fine on its own. Now if I freeze that import using `freeze --all`, it becomes this: 

```dhall
let Prelude =
      https://raw.githubusercontent.com/dhall-lang/dhall-lang/v19.0.0/Prelude/package.dhall using ./github-headers.dhall sha256:eb693342eb769f782174157eba9b5924cf8ac6793897fc36a31ccbd6f56dafe2
```

which now causes an integrity check failure and it appears to be because that checksum is the value for the prelude remote import, but is being interpreted as the value for the local `./github-headers.dhall` file. 

If I simply wrap the local file usage in parens, it succeeds: 

```dhall
let Prelude =
      https://raw.githubusercontent.com/dhall-lang/dhall-lang/v19.0.0/Prelude/package.dhall using (./github-headers.dhall) sha256:eb693342eb769f782174157eba9b5924cf8ac6793897fc36a31ccbd6f56dafe2
```

**Comment by Gabriel439** [comment]
This is the same issue as https://github.com/dhall-lang/dhall-haskell/issues/1672 which will take some time to fix

**Comment by craig-day** [comment]
Ah, sorry for the duplicate! Feel free to close this if you'd like. I'm happy to track the other one.

**Comment by Gabriel439** [comment]
No worries!  Then I'll close this in favor of #1672.
