### ISSUE TITLE
A more advanced "go" function

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#213]
Right now we have `input` which is fairly useful, but the moment you have to supply custom typing contexts and normalizers, the difficulty significantly rises. What do you think about an "advanced" convenience function that:

* Takes a typing context, and uses it while resolving imports
* Takes a `Normalizer` to use `normalizeWith`

I feel like this when paired with `input` is a good 90% of use cases.

**Comment by Gabriel439** [comment]
Yeah, I think that's a reasonable addition to the API.  Feel free to submit a pull request
