### ISSUE TITLE
A variant of `load` that takes a Context (but does not require a loading function).

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#214]
Right now, we have 

```haskell
load :: Expr Src Path -> IO (Expr Src X)
loadWith :: MonadCatch m => (Path -> m (Expr Src Path)) -> Context (Expr Src X) -> Expr Src Path -> m (Expr Src X)
```

The first is no good if you need a custom typing context. The latter is quite a jump up, as now I have to find something to plug into the first argument. There is `exprFromPath`, but now I have to create a `Manager` which means a dependency on `httpClient`, an `import`, the creation of a `Manager`, and then finally I can build what I want - though I always have to pay for the construction of the `Manager`.

Perhaps we could have a `loadWithContext` that doesn't require the loading function to be supplied.

**Comment by Gabriel439** [comment]
Yeah, sounds good to me

As a general rule of thumb, I'm pretty permissive about additions to the Haskell API.  The only thing I really review for is tasteful naming.  Just submit a pull request with the change you have in mind and I'll review it

**Comment by ocharles** [comment]
Good to know :) Just saving myself some cycles to avoid going down a path that results in rejection (which is equally understandable!)
