### ISSUE TITLE
dhall-json: lower bound too generous

### ISSUE THREAD

**Issue by JackKelly-Bellroy** [dhall-lang/dhall-haskell#2146]
`dhall-json-1.7.5` has changes to support `dhall-1.38.0`. `dhall-1.38.0` introduces [breaking changes](https://hackage.haskell.org/package/dhall-1.38.0/changelog) but `dhall-json` has not raised the lower bound.

Reproduction: `cabal v2-repl -b 'dhall == 1.36.0' -b 'dhall-json == 1.7.5' -j`

Snippet:
```
src/Dhall/JSON.hs:503:9: error:
    • The constructor ‘Core.Lam’ should have 2 arguments, but has been given 3
```

Suggest: raise lower bound on `dhall-json` and publish metadata revision to Hackage.

**Comment by sjakobi** [comment]
Thanks for the report! There are a few more packages affected in the same way. https://github.com/dhall-lang/dhall-haskell/pull/2147 should fix this.
