### ISSUE TITLE
dhall-docs man pages on linux should be in share/man1/

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-haskell#2161]
https://github.com/dhall-lang/dhall-haskell/pull/2111 added the docs manpage to the tarball, but 

```
./share/man/dhall-docs.1
```

should be

```
./share/man/man1/dhall-docs.1
```

cc @Gabriel439

**Comment by Profpatsch** [comment]
Same for `./share/man/dhall.1`

**Comment by sjakobi** [comment]
@Profpatsch Could you clarify which directory would be correct? In the issue title you mention `share/man1/`, but in the description you mention `share/man/man1`.

Maybe simply open a PR if it's easy to fix.
