### ISSUE TITLE
dhall-to-yaml takes unreasonably long to process a simple file

### ISSUE THREAD

**Issue by jsynacek** [dhall-lang/dhall-haskell#2167]
```
$ nix-shell -p dhall-json
```
```
$  dhall-to-yaml --version
1.7.5
```
```
$ cat dhall-to-yaml-timeout.dhall 
let Map = https://prelude.dhall-lang.org/Map/Type
in
toMap { something = "Slow" }
```
```
$ time dhall-to-yaml < dhall-to-yaml-timeout.dhall
something: Slow

real	0m1.093s
user	0m0.069s
sys	0m0.017s
```
Running `dhall-to-yaml` in a loop which processes many files is simply too slow. The slowdown is caused by declaring `Map` to be taken from the URL.

Let me know if you need more information.

**Comment by sjakobi** [comment]
Thanks for the report, @jsynacek!

I think this ultimately boils down to `prelude.dhall-lang.org` being rather slow. A good way to tell is that `dhall resolve` is just as slow as `dhall-to-yaml` in this case:

```
$ /usr/bin/time dhall-to-yaml < dhall-to-yaml-timeout.dhall 
something: Slow
0.04user 0.00system 0:00.88elapsed 6%CPU (0avgtext+0avgdata 32636maxresident)k
0inputs+0outputs (0major+3371minor)pagefaults 0swaps
$ /usr/bin/time dhall resolve < dhall-to-yaml-timeout.dhall
let Map = \(_ : Type) -> \(_ : Type) -> List { mapKey : _@1, mapValue : _ }

in  toMap { something = "Slow" }
0.04user 0.02system 0:00.88elapsed 7%CPU (0avgtext+0avgdata 32004maxresident)k
0inputs+0outputs (0major+3274minor)pagefaults 0swaps
```

The best way to work around this is to `freeze` these slow imports:

```
$ cat dhall-to-yaml-timeout.dhall | dhall freeze > frozen.dhall
$ /usr/bin/time dhall-to-yaml < frozen.dhall 
something: Slow
0.00user 0.00system 0:00.00elapsed 100%CPU (0avgtext+0avgdata 12900maxresident)k
0inputs+0outputs (0major+572minor)pagefaults 0swaps
```

You can find more info about freezing at https://docs.dhall-lang.org/tutorials/Language-Tour.html#installing-packages.

Regarding speeding up import resolution, see the thread at  https://github.com/dhall-lang/dhall-haskell/issues/1511#issuecomment-550408308.

**Comment by jsynacek** [comment]
Thank you for the quick response, I'll try the freeze feature.

What I would like to add is that if you have multiple files (let's say ten) that import dhall expressions from a URL and you run `dhall-to-yaml` in a loop, they all get processed with pretty much the same timeout. The timeouts are so regular and consistent that I even think that this is a bug. I'm not sure where it would be, though. I even thought that the loop had a `sleep` in it.

**Comment by sjakobi** [comment]
I'll close this issue, since I don't see any indication that something unexpected is happening here.

If you disagree, please supply more information, for example an `strace` profile.
