### ISSUE TITLE
dhall-toml package

### ISSUE THREAD

**Issue by cahilfil** [dhall-lang/dhall-haskell#2168]
Hello, I'm Yunus! I'm interested in the [Dhall bindings to TOML](https://summer.haskell.org/ideas.html#dhall-toml) project for GSoC 2021, and I had some initial questions about it. (I hope this is a good place to ask them.)

**Comment by Gabriel439** [comment]
@cahilfil: I'd recommend either https://discourse.dhall-lang.org/ or the issue tracker for the Haskell repository (https://github.com/dhall-lang/dhall-haskell/issues) to discuss this since it's sort of a Haskell-specific project.

**Comment by sjakobi** [comment]
@Gabriel439 This issue is already on the `dhall-haskell` issue tracker! ;)

**Comment by cahilfil** [comment]
@sjakobi Yes. That was what I was just going to say :)

@Gabriel439 I'm sorry. I actually prematurely clicked the 'Comment' button on my previous comment. I will ask my questions here in the next hour or so. Sorry about that.

**Comment by Gabriel439** [comment]
Whoops!  For some reason I thought this was the dhall-lang repository 🙂

**Comment by cahilfil** [comment]
I've looked into `dhall-yaml`  a bit, and as far as I understand, it makes use of [HsYAML](https://hackage.haskell.org/package/HsYAML-0.2.1.0/docs/Data-YAML.html) both to convert to and to convert from `Aeson.Value` and then uses `dhall-json` to handle the rest.

Since TOML is even more closer to JSON than YAML, it seems like a similar approach for TOML would be reasonable. I guess the main issue here is that there is no library that exactly does this -- at least I couldn't find any.
- There is [tomland](https://github.com/kowainik/tomland), which supports TOML 0.5.0 and provides some primitive functions, from which you can describe bidirectional converters from/to Haskell datatypes to TOML . At a first glance, this seemed quite nice to me, but If I'm not mistaken their DSL is not quite powerful to describe a converter to/from `Aeson.Value`. To make use of its parser and pretty-printer, maybe we could define functions that convert their intermediate AST to/from `Aeson.Value`. I'm not sure this is a good idea though, both because they might change their AST in the future and also because it might be simpler to do it directly. 
- There is also [htoml](https://github.com/cies/htoml). This one might be more useful because their AST is an instance of the ToJSON typeclass, so we could use it for the TOML->Dhall direction, but the downside here is it only supports TOML 0.4.0, and it doesn't have a pretty-printer. 

In general, do you have any other suggestions for things I should look into or any other ideas? I'm sure I'm missing something.
Also, apart from `data-json` and `data-yaml`, is there any other resources I can look into, while preparing the project proposal?
Lastly, can I e-mail my draft proposal?

**Comment by Gabriel439** [comment]
@cahilfil: We could go through `Aeson.Value` as an initial intermediate solution, but in the long run I would prefer a direct conversion between TOML and Dhall for a few reasons:

* First, the `Value` type doesn't preserve field ordering, so there is information loss when going through that intermediate

  Note: I haven't yet checked if the TOML packages do preserve field ordering, though

* Second, it would incur an unnecessary dependency on `aeson` / `dhall-json`

I think if you've already studied `dhall-json` and `dhall-yaml` then you should be good to go, since I expect the TOML support for Dhall to follow the same structure as those two projects.

**Comment by sjakobi** [comment]
Closing, since @ear7h  got the GSoC slot and is working on `dhall-toml`.
