### ISSUE TITLE
Support for nested inlining in dhall-to-yaml

### ISSUE THREAD

**Issue by Pr0Ger** [dhall-lang/dhall-haskell#2171]
Hi! I want to implement binding for [Drone CI pipelines](https://docs.drone.io/yaml/docker/#the-pipeline-object). TLDR: top level object is either secret or pipeline (type is stored in `kind` attribute). There are few types of pipelines (type is stored in `type` field), one of them is `docker`

In yaml it will look like this:
```yaml
kind: pipeline
type: docker
name: pipeline_name
...
---
kind: secret
...
```

My first attempt to define this looks like this:

```dhall
let Nesting = < Inline | Nested : Text >

let Pipeline = < docker : { name : Text } >

let Resource =
      < secret : {}
      | pipeline : { field : Text, nesting : Nesting, contents : Pipeline }
      >

in  { field = "kind"
    , nesting = Nesting.Inline
    , contents =
        Resource.pipeline
          { field = "type"
          , nesting = Nesting.Inline
          , contents = Pipeline.docker { name = "pipeline_name" }
          }
    }
```

Obviously this is not working since these three-field-records are not unfolding recursive. My question is how to properly implement binding for this yaml structure? My first thought was to add all pipeline types directly to `Resource` union, but this will not work since all of them should have `pipeline` type.
Another idea is to make `Pipeline` as a union from different record type (e.g. `DockerPipeline`) where `type` is populated from record defaults.
Is this the best approach for this task or is there a more canonical way to this?

**Comment by Gabriel439** [comment]
@Pr0Ger: Rather than using the `Nesting` support of `dhall-to-yaml`, what I think would work best is to split this into two steps:

* First define the Dhall types in the "obvious" way (that doesn't necessarily match the YAML that Drone CI expects)

  In other words, something like:

  ```dhall
  let Pipeline = < docker : { name : Text } >

  let Resource = < secret : {} | pipeline : Pipeline >
  ```

* Then have your package provide a `render` function or something similar which converts that simpler representation to to `Prelude.JSON.Type`

  ```dhall
  let JSON = https://prelude.dhall-lang.org/v20.1.0/JSON/package.dhall

  let Pipeline = < docker : { name : Text } >

  let Resource = < secret : {} | pipeline : Pipeline >

  let render
      : Resource → JSON.Type
      = λ(resource : Resource) →
          merge
            { secret =
                λ(args : {}) → JSON.object (toMap { kind = JSON.string "secret" })
            , pipeline =
                λ(pipeline : Pipeline) →
                  merge
                    { docker =
                        λ(args : { name : Text }) →
                          JSON.object
                            ( toMap
                                { kind = JSON.string "pipeline"
                                , type = JSON.string "docker"
                                , name = JSON.string args.name
                                }
                            )
                    }
                    pipeline
            }
            resource

  in  render
  ```

If you're not familiar with the `Prelude.JSON.Type` representation, then this section of the Dhall manual explains it a bit:

* [How to convert an existing YAML configuration file to Dhall](https://github.com/Gabriel439/dhall-manual/blob/develop/manuscript/01-YamlToDhall.md)

**Comment by Pr0Ger** [comment]
@Gabriel439 Thanks for the suggestion! 
One more question about this approach: whose responsibility is to call `render` method? Should it be called directly from `.drone.dhall` file (so this file will be usable as-is with dhall-to-yaml) or this file should only contain an expression with the list of simple records and converter plugin for Drone CI should create new expression using this file as an argument for render function?

**Comment by Gabriel439** [comment]
@Pr0Ger: It could work either way, but if I had to pick one I'd suggest having the end user call the `render` method themselves, that way it will be easier for the Drone Dhall bindings to evolve/migrate things if the schema changes.  If you bake the `render` function into the Drone CI plugin then it might entail creating multiple versions of the Dhall plugin for each new version of the Drone CI schema.

**Comment by Pr0Ger** [comment]
@Gabriel439 Thanks for sharing your insight, sounds reasonable to me.

I'll close this issue since there is no need to change anything in compiler
