### ISSUE TITLE
Remote imports fail on OSX when `security` executable is not on PATH

### ISSUE THREAD

**Issue by timbertson** [dhall-lang/dhall-haskell#2178]
As the title says, on OSX, when running with a `$PATH` that doesn't include `/usr/bin`, remote imports fail because the `security` program can't be found.

```
$ echo 'http://example.com/dhall' | env -u PATH `which dhall`
dhall: security: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

This is... kind of a dumb thing to do, it's down to the interactions of some seemingly reasonable choices:

 - I'm trying to use https://github.com/humphrej/rules_dhall/ in bazel, and bazel's sandbox runs with `PATH` completely unset
 - I'm using `bazel` from a nix shell (because I try to do most things in a nix shell ;) )

When bazel uses the system bash, the problem is hidden because of how PATH gets defaulted:

```
$ env -u PATH /bin/bash -c 'echo $PATH'
/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.

$ env -u PATH /nix/store/w8cqc6lfdrszpjkpmfs16yl237dp08p8-bash/bin/bash -c 'echo $PATH'
/nix/store/rq1inyhyr4gddgc5gxdid38iwn7769d7-bash-4.4-p23/bin:/nix/store/9h82w3pdqvvd417vvshzwpm292357k0k-coreutils-8.32/bin:/nix/store/j2wmzhyxb4j53djl1clbp913f5l9zpjb-findutils-4.7.0/bin:/nix/store/j18z8yxv34hp4llgdgkdbbsgad6l3dqc-gawk-5.1.0/bin:/nix/store/blvrpmrrcx022hw1w7kil8mg80vnk01a-gnugrep-3.6/bin:/nix/store/g684dnb2i9pxckk9r6najb6in94sp10p-gnutar-1.32/bin:/nix/store/ri6cpdgd2k0snspqb2mqzxx8zr3h9pr2-gnused-4.8/bin:/nix/store/mrfxjp41fj2m0wa5hwhmdb1y7wbbmrmb-gzip-1.10/bin:/nix/store/zvf8xwmm6ywimjbcralz73ydb6d4n6ng-which-2.21/bin:/nix/store/286vwj23yrjqir75zyx8873a9gs1qjfi-unzip-6.0/bin:/nix/store/wrp2659yjr5zbfmly6qc6r4nxkibh72i-file-5.39/bin:/nix/store/fqdifvrgq9ran7wgrhkbly441xc7s832-zip-3.0/bin
```

I assume nix's version has all the normal POSIX things, but not the magical `/usr/bin/security` binary.

Checking the binaries, I see that the official dhall binary doesn't have a hardcoded `security` path, but dhall from nixpkgs does:

```
$ strings /nix/store/l1n6800dgb5x1sw6s0nvr2garsq0x893-dhall-1.38.0/bin/dhall | grep security
/usr/bin/security

# extracted from https://github.com/dhall-lang/dhall-haskell/releases/download/1.38.0/dhall-1.38.0-x86_64-macos.tar.bz2
$ strings bin/dhall | grep security
security
```

(the bazel rules use the official binary from github)

Now that I know what the difference is, I found the following nix-specific patch to the `x509-system` haskell package:

https://github.com/NixOS/nixpkgs/blob/3f5b404980d7521dabe6923a289a9382b58340a9/pkgs/development/haskell-modules/configuration-nix.nix#L147-L165

...which affects this source code:

https://github.com/vincenthz/hs-certificate/blob/7041244d0dd3946d96af66611b2760d2478e055f/x509-system/System/X509/MacOS.hs#L22

## So what's the fix?

Hardcoding `/usr/bin/security` in the upstream haskell library does feel hacky, because it could change. Finding its location at compile-time is similarly fragile (might not work when distributing that binary across OSX versions).

Perhaps the most practical fix is to alter the existing wrappers in `rules_dhall` to ensure `/usr/bin` is on `$PATH`. Unsetting PATH as bazel does is a weird enough use case that maybe it warrants this very specific hack. Thoughts?

**Comment by sjakobi** [comment]
I'm not familiar with the OS X platform, but it sounds like this should be fixed upstream, e.g. in `x509-system`. If someone would create a PR to fix that library, we can use that fork to build the OS X binaries.

**Comment by timbertson** [comment]
Closing this since there's nothing `dhall-haskell` can here, this was just a good place to put my investigation notes ;). I haven't pushed this upstream to x509-system
