### ISSUE TITLE
Move to travis-ci.com ?

### ISSUE THREAD

**Issue by mmhat** [dhall-lang/dhall-haskell#2197]
From travis.org:

> Please be aware travis-ci.org will be shutting down by end of May 2021. Please consider migrating to travis-ci.com.

**Comment by mmhat** [comment]
Doing a bit of research revealed the following:

Apparently one gets 10000 Credits/month with the "Free" plan. One minute MacOSX build time costs 50 Credits which leaves us with 200 minutes/month build time. IMHO this won't fit our needs. I see two options:

1. Upgrade to another plan.
2. Migrate away from Travis.

Thoughts?

**Comment by mmhat** [comment]
Judging from [this](https://travis-ci.community/t/org-com-migration-unexpectedly-comes-with-a-plan-change-for-oss-what-exactly-is-the-new-deal/10567/35) other projects are hit by this as well. Some posts are really devastating.
For the record: [Announcement blog post](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)

@Gabriel439 I guess it was you who set up the CI initially? What are your ideas on that?

**Comment by Gabriel439** [comment]
@mmhat: I don't have any particular attachment to Travis CI.  The only reason we still kept it around was to build executables for Mac, but we can probably do that with GitHub actions now

**Comment by sjakobi** [comment]
CC @f-f who had introduced the Mac executable building in #1101, in case he has any thoughts on this issue.

**Comment by mmhat** [comment]
I started some development on the [this](https://github.com/dhall-lang/dhall-haskell/tree/2197-github-actions). So far the results look promising. Have a look at the "Actions" tab :)

**Comment by mmhat** [comment]
While working on this I stumbled upon [the following line](https://github.com/dhall-lang/dhall-haskell/blob/68da43454d41785beee94ab722b060665aa79cce/appveyor.yml#L60) in our AppVeyor configuration:

> Enable when issue with path-separators tests on windows is resolved

@german1608, can you clarify which issue that line is referring to? Is it still an issue or got it resolved?

**Comment by mmhat** [comment]
Is there any particular reason why we don't want the stack.yaml.lock file to be checked in? The [documentation](https://docs.haskellstack.org/en/stable/lock_files/) suggests that it should be.
@ejconlon @jneira What was the motivitation behind the inclusion in the .gitignore file?

**Comment by sjakobi** [comment]
> Is there any particular reason why we don't want the stack.yaml.lock file to be checked in? The [documentation](https://docs.haskellstack.org/en/stable/lock_files/) suggests that it should be.

@mmhat I'm not sure we need this level of reproducibility. I'd expect that main thing that we'd get from tracking the stack lock files is inflated commit diffs.

**Comment by mmhat** [comment]
@sjakobi It is rather about cachability: The way how actions/cache works is that you commit to a key for your cache once. After a successful build that cache gets populated and never updated again. To work around outdated caches it is common to do something like this:
```
key: ${{ hashFile(some lock file here) }}
```

If that file changes a new cache is created and the old one will be deleted if not accessed for one week.
The best explanation I found is in [this](https://markkarpov.com/post/github-actions-for-haskell-ci.html#cache) blog post.
There are [some examples](https://github.com/actions/cache/blob/main/examples.md#haskell---cabal) in the official documentation but the one for Haskell is unfortunately not the best one. IMHO it is better  to look at the ones of the other languages listed there.

The problem regarding commit diffs is understandable; I will try to work around that, i.e. look for a way to get decent caching without that file.

**Comment by sjakobi** [comment]
How about simply using the `stack.yaml` as the cache key file?

Do note though that CI times are usually dominated by the Hydra build, so optimizing the GA build probably isn't too important.

If tracking the `stack.yaml.lock` has clear advantages, I wouldn't be opposed to doing that either.

**Comment by mmhat** [comment]
@sjakobi I went for hash of stack.yaml as a key after I figured out that there is no way to generate the stack.yaml.lock without a `stack setup`. I'm aware of the Hydra being the bottleneck here but I guess it was nice if some CI job provides a faster feedback for the developer.

BTW: Is there a way to speed up the Hydra builds? What are the limitations there?

**Comment by mmhat** [comment]
Ok, I managed to port most of our CI code to GHA. Two (probably related) problems remain:

- Test failures of the following packages on Windows: [dhall](https://github.com/dhall-lang/dhall-haskell/runs/2697241061?check_suite_focus=true), [dhall-docs](https://github.com/dhall-lang/dhall-haskell/runs/2697241107?check_suite_focus=true) and [dhall-json](https://github.com/dhall-lang/dhall-haskell/runs/2697241129?check_suite_focus=true). In all cases the golden tests fail.
- [dhall-yaml](https://github.com/dhall-lang/dhall-haskell/runs/2697241186?check_suite_focus=true) fails on Windows due to wrong line endings.

I will try to resolve those issues in the next days; Any ideas on how to fix them are of course highly appreciated :)

**Comment by mmhat** [comment]
Closing since https://github.com/dhall-lang/dhall-haskell/pull/2199 got merged.
