### ISSUE TITLE
Sort "let-imports" with "dhall lint"

### ISSUE THREAD

**Issue by denizdogan** [dhall-lang/dhall-haskell#2204]
I like to keep my "external let expressions", i.e. "imports", at the top of each file where they're being used. It would be nice if `dhall lint` could fix that automatically.

Example:

```
let x = "foo"
let List/concat = https://prelude.dhall-lang.org/List/concat.dhall
```

->

```
let List/concat = https://prelude.dhall-lang.org/List/concat.dhall

let x = "foo"
```

**Comment by Gabriel439** [comment]
The fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2205
