### ISSUE TITLE
Some possible contributions from my `Dhall.Extra` module

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#221]
I have the following in `Dhall.Extra` - would any of this be useful in Dhall? I think `pair` and `list` should be uncontroversial, `string` a bit more controversial, and `makeRecord`/`makeUnion` might be a bit specific.

```haskell
{-# language ApplicativeDo #-}
{-# language GADTs #-}
{-# language GeneralizedNewtypeDeriving #-}
{-# language OverloadedStrings #-}
{-# language RecordWildCards #-}
{-# language TypeApplications #-}

module Dhall.Extra
  ( RecordBuilder
  , emptyRecord
  , keyValue
  , list
  , makeRecord
  , makeUnion
  , pair
  , string
  , validateType
  )
  where

import Control.Applicative ( Const(..) )
import Control.Monad ( guard, join )
import Control.Monad.Trans.Reader ( Reader, reader, runReader )
import Data.Foldable ( toList )
import Data.Functor.Compose ( Compose(..) )
import Data.Functor.Product ( Product(..) )

import qualified Data.Map as Map
import qualified Data.Text.Lazy as LazyText
import qualified Dhall
import qualified Dhall.Core as Dhall ( Expr )
import qualified Dhall.Core as Expr ( Expr(..) )
import qualified Dhall.Parser
import qualified Dhall.TypeCheck 



string :: Dhall.Type String
string =
  LazyText.unpack <$> Dhall.lazyText



pair :: Dhall.Type a -> Dhall.Type b -> Dhall.Type ( a, b )
pair l r =
  makeRecord $ (,) <$> keyValue "_1" l <*> keyValue "_2" r



list :: Dhall.Type a -> Dhall.Type [a]
list t =
  toList <$> Dhall.vector t



newtype RecordBuilder a =
  RecordBuilder
    ( Product
        ( Const
            ( Map.Map
                LazyText.Text
                ( Dhall.Expr Dhall.Parser.Src Dhall.TypeCheck.X )
            )
        )
        ( Compose
            ( Reader
                ( Dhall.Expr Dhall.Parser.Src Dhall.TypeCheck.X )
            )
            Maybe
        )
        a
    )
  deriving (Functor, Applicative)



makeRecord :: RecordBuilder a -> Dhall.Type a
makeRecord ( RecordBuilder ( Pair ( Const fields ) ( Compose extractF ) ) ) =
  let
    extract =
      runReader extractF

    expected =
      Expr.Record fields

  in Dhall.Type { .. }



keyValue :: LazyText.Text -> Dhall.Type a -> RecordBuilder a
keyValue key valueType =
  let
    extract expr = do
      Expr.RecordLit fields <-
        return expr

      Map.lookup key fields >>= Dhall.extract valueType

  in
    RecordBuilder
      ( Pair
          ( Const ( Map.singleton key ( Dhall.expected valueType ) ) )
          ( Compose ( reader extract ) )
      )



emptyRecord :: Dhall.Type ()
emptyRecord =
  let
    extract expr = do
      Expr.RecordLit fields <-
        return expr

      guard ( Map.null fields )

    expected =
      Expr.Record Map.empty
      
  in Dhall.Type { .. }



makeUnion :: Map.Map LazyText.Text ( Dhall.Type a ) -> Dhall.Type a
makeUnion alts =
  let
    extract expr = do
      Expr.UnionLit ctor v _ <-
        return expr

      t <-
        Map.lookup ctor alts

      Dhall.extract t v

    expected =
      Expr.Union ( Dhall.expected <$> alts )

  in Dhall.Type { .. }



validateType :: Dhall.Type ( Maybe a ) -> Dhall.Type a
validateType a =
  a { Dhall.extract = join . Dhall.extract a }
```

**Comment by Gabriel439** [comment]
I think `string`, `list`, `pair`, and `emptyRecord` (perhaps renamed to `unit`) make sense to add.  For the other ones I think the more friendly user interface is to have the user define a polymorphic record type, derive `Generic`/`Interpret`, and then specialize `auto` to that type

**Comment by ocharles** [comment]
Right, I can't do that because I don't own the data type, so introducing any `Interpret` instances would be orphan. I'll get those other four bundled up into a PR thuogh.

**Comment by Gabriel439** [comment]
Does the type you have in mind derive `Generic`, though?  The reason I ask is that `master` has a recently added `genericAuto` function (not yet on Hackage) which you can use when you can't derive `Interpret` for the desired type

https://github.com/dhall-lang/dhall-haskell/blob/master/src/Dhall.hs#L505

**Comment by ocharles** [comment]
Yes, that bit isn't the problem - the problem is that the fields of that record themselves don't have `Interpret` instances, nor do I own those types :disappointed:

**Comment by Gabriel439** [comment]
Then you'll probably have to do something similar to what you would for the worst case scenario with `aeson`: define a parallel hierarchy of types that you derive `Interpret` for and then convert that to the desired hierarchy of types.

**Comment by ocharles** [comment]
I don't see it as much better than just writing everything out by hand. If
I understand what you're suggesting, it would be newtyping all the types
and then doing loads of unwraps.

**Comment by Gabriel439** [comment]
Yeah, I mean `aeson` has the same limitation in the worst case, too (For example, suppose that you want some `Double` deep in the hierarchy to be rendered in a different way) .  I'm just saying that the generics+type-class approach has this fundamental worst-case scenario that you always have to be prepared for.
