### ISSUE TITLE
Require whitespace before with

### ISSUE THREAD

**Issue by travisbrown** [dhall-lang/dhall-haskell#2212]
The [grammar](https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L799) currently requires whitespace before `with`:

```
with-expression =
    import-expression 1*(whsp1 with whsp1 with-clause)
```

I'm following this in Dhall for Java, but noticed that the Haskell implementation doesn't match the standard:

```dhall
$ dhall <<< "{=}with foo = 0with bar = 1"
{ bar = 1, foo = 0 }
```
This seems to me like a bug on the dhall-haskell side, not in the grammar, but I'm happy to open an issue over at dhall-lang if anyone disagrees.

**Comment by Gabriel439** [comment]
Fixed by #2213
