### ISSUE TITLE
Users cannot omit fields of a record.

### ISSUE THREAD

**Issue by vmchale** [dhall-lang/dhall-haskell#225]
I quite like Dhall from what I've seen so far. However, one of the pain points I noticed (compared to TOML) is that the user cannot simply omit a field of a record. If library authors were able to make values of type `Maybe Text` and have these omitted when writing the actual configuration, it would be much easier for users down the line.

Thanks for all the work on this language! I'm using it in a [project](https://github.com/vmchale/atspkg) and am excited to see where it goes :)

**Comment by ocharles** [comment]
As `Optional` is actually part of the core language this feels like it *might* be possible. Don't hold me to that, though :smile:

**Comment by ocharles** [comment]
I should note that this is possible, in a sense, using the current version of Dhall. What changes here is that you can no longer provide a canonical type of the expression that your users give you. The process is essentially:

* Read `Text`
* Parse a Dhall 'Expr`
* Resolve imports
* Type check the result - only to make sure it is well formed
* Turn the `Expr` into whatever type you need by walking through it.

It's in the last step that you can start to do things like:

```haskell
case expr of
  RecordLit fields -> do
    myFoo <-
      case Map.lookup "foo" fields of
        Just fooExpr -> Just <$>_ fooExpr
        Nothing -> return Nothing
```

Does that make sense?

**Comment by Gabriel439** [comment]
Yeah, the main issue here is that you would no longer be able to infer a canonical type for a expression

I recommend instead providing a record where all the `Optional` fields are empty that you can then override that using `//`, like this:

```
    let defaults = { bar = [] : Optional Bool, foo = [] : Optional Text }

in  defaults ⫽ { bar = [ True ] : Optional Bool, baz = 1 }
```

**Comment by ocharles** [comment]
I've opened https://github.com/ocharles/dhall-to-cabal/issues/12 to continue that discussion, rather than hijack @vmchale's original question.

**Comment by vmchale** [comment]
Great, thanks! This should work well enough for now :)
