### ISSUE TITLE
Invalid character escaping produces confusing error

### ISSUE THREAD

**Issue by southerntofu** [dhall-lang/dhall-haskell#2264]
# Problem

Invalid escaped character such as `\-` or `\e` crashes the dhall parser, producing a useless error message:

```
Error: Invalid input

(input):1:14:
  |
1 | { a = "foo", b = "\e" }
  |              ^
unexpected 'b'
expecting whitespace or }
```

This confusing error, though not for the same reason, is the same as the one described in #2200.

# Reproducing

A simple entry `{ b = "\e" }` produces a useful error message with indication of what went wrong and where:

```
Error: Invalid input

(input):1:9:
  |
1 | { b = "\e" }
  |         ^
unexpected 'e'
expecting ", $, /, \, b, f, n, r, t, or u
```

However, making the structure slightly more complex (`{ a = "foo", b = "\e" }`) produces the `unexpected 'b'` error which is unergonomic. Telling me b is unexpected leads me to believe my error is located *before* b is declared, instead of pointing out the actual error.

# Expected behavior

```
Error: Invalid input

(input):1:20:
  |
1 | { a = "foo", b = "\e" }
  |                    ^
unexpected 'e'
expecting ", $, /, \, b, f, n, r, t, or u
```

**Comment by sjakobi** [comment]
Thanks for the report! I think we can track this in #2200. In https://github.com/dhall-lang/dhall-haskell/issues/1592 there's some discussion on how we can fix these terrible parser error messages.

**Comment by winitzki** [comment]
With https://github.com/dhall-lang/dhall-haskell/pull/2836 there will be this message:
```dhall
⊢ { a = "foo", b = "\e" }

Error: Invalid input

(input):1:20:
  |
1 | { a = "foo", b = "\e" }
  |                    ^
Invalid escape sequence
```
