### ISSUE TITLE
Extra comma in struct produces confusing error

### ISSUE THREAD

**Issue by southerntofu** [dhall-lang/dhall-haskell#2265]
# Problem

If a substructure has an extra comma inside, and there was another key/value before that declaration, the same useless error (though for different reasons) as in #2200 and #2264.

# How to reproduce

The simplest case to reproduce is `{ a = "a", b = { a = "foo",, } }`, which produces the following error message:

```
Error: Invalid input

(input):1:12:
  |
1 | { a = "a", b = { a = "foo",, } }
  |            ^
unexpected 'b'
expecting whitespace or }
```

# Expected behavior

Simpler cases are handled well, for example `{ a = "foo",, }` or `{ a = { a = "foo",, } }` produce the following helpful error message:

```
Error: Invalid input

(input):1:19:
  |
1 | { a = { a = "foo",, } }
  |                   ^
unexpected ','
expecting whitespace or }
```

**Comment by sjakobi** [comment]
Thanks for this report, too! I think we can track this in #2200. In #1592 there's some discussion on how we can fix these terrible parser error messages.

**Comment by Gabriel439** [comment]
Closing in favor of #2200
