### ISSUE TITLE
Encoding composite record to dhall

### ISSUE THREAD

**Issue by locallycompact** [dhall-lang/dhall-haskell#2266]
Hi, I've been trying to get dhall to play with [composite](https://hackage.haskell.org/package/composite-base), an extension to vinyl with type level field names.

I tried to roughly mimic the internal generic functions in Dhall's internals, but I'm stuck on a couple of holes that seem to expect internal functions.

```
  instance D.ToDhall (Record '[]) where
    injectWith = pure (D.Encoder {..})
      where
        embed _ = RecordLit mempty
        declared = Record mempty

  instance (KnownSymbol s, D.ToDhall (Record xs), D.ToDhall x) => D.ToDhall (Record (s :-> x ': xs)) where
    injectWith = do
      let f :: s :-> x
          f = undefined
      let name = valName f
      let D.Encoder embedL declaredL = D.inject
      let D.Encoder embedR declaredR = D.inject
      let embed (s :*: xs) = RecordLit (Dhall.Map.insert name (Dhall.Core.makeRecordField (embedL $ s)) mapR)
            where
              mapR = _ $ embedR xs
      let declared = Record (Dhall.Map.insert name (Dhall.Core.makeRecordField (declaredL)) mapR)
            where
              mapR = _ declaredR
      pure (D.Encoder {..})
```

I've pushed this [here](https://github.com/locallycompact/composite-dhall/blob/master/src/Lib.hs) for now. I did try generics to begin with but I think I'd encounter the same problem without access to the internals. I'd appreciate any direction you can give on how to solve this.

**Comment by Gabriel439** [comment]
It sounds like the internal function you need is [unsafeExpectRecordLit](https://hackage.haskell.org/package/dhall-1.39.0/docs/src/Dhall.Marshal.Internal.html#unsafeExpectRecordLit), although you can still define that function yourself even if it's not exposed from the API

**Comment by locallycompact** [comment]
Ok, thanks. Just checking there wasn't a way to do it through the API. I'll give that a shot.

**Comment by locallycompact** [comment]
This seems to work and I've published it here: https://hackage.haskell.org/package/composite-dhall
