### ISSUE TITLE
`dhall format` removes required parentheses in freezed import statement using headers

### ISSUE THREAD

**Issue by jgeerds** [dhall-lang/dhall-haskell#2273]
This issue is related to #441. The parentheses around `./headers.dhall` are required to make the code unambiguous. Unfortunately, the `format` command removes the parenthesis resulting that the expression no longer works 

```
let MyPackage = https://server.test/package.dhall using (./headers.dhall) sha256:03a6e298ff140d430cea8b387fad886ce9f5bee24622c7d1102115cc08ed9cf8
```

```
dhall: 
↳ ./test.dhall
  ↳ ./headers.dhall
  sha256:03a6e298ff140d430cea8b387fad886ce9f5bee24622c7d1102115cc08ed9cf8

Error: Import integrity check failed

Expected hash:

↳ 03a6e298ff140d430cea8b387fad886ce9f5bee24622c7d1102115cc08ed9cf8

Actual hash:

↳ f251a7ed8ae08f533a11033e164afc73da09e65997a3f77d2345e34e42ea0f13


2│                                                                                                   ./headers.dhall
3│         sha256:03a6e298ff140d430cea8b387fad886ce9f5bee24622c7d1102115cc08ed9cf8

```

**Comment by sjakobi** [comment]
I think this is related to https://github.com/dhall-lang/dhall-haskell/issues/1925#issuecomment-660668039. (Maybe @Gabriel439 can check!)

I suspect that there's no easy fix. I suggest that you workaround the issue by moving the headers import into a `let`-binding:

```dhall
let headers = ./headers.dhall

let MyPackage = https://server.test/package.dhall using headers sha256:03a6e298ff140d430cea8b387fad886ce9f5bee24622c7d1102115cc08ed9cf8
```

**Comment by Gabriel439** [comment]
Actually, I think this is easy to fix.  I believe all we have to do is to always parenthesize the argument to the `using` keyword.  That was actually part of the original plan outlined here:

https://github.com/dhall-lang/dhall-lang/pull/171

… which I just had never gotten around to following up on.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2280
