### ISSUE TITLE
`FromDhall`/`ToDhall` for types from `time`?

### ISSUE THREAD

**Issue by amesgen** [dhall-lang/dhall-haskell#2286]
I am not sure whether this has been discussed before, but what about implementing `FromDhall`/`ToDhall` for various types from `time`, like `Day`, `TimeOfDay`, `LocalTime`, `ZonedTime`, `UTCTime`, now with #2247?

**Comment by Gabriel439** [comment]
Whoops, this is an oversight on my part!  Yeah, this is a great idea and it should be easy for me to add

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2294

**Comment by amesgen** [comment]
Thanks for the instances for `Day`, `TimeOfDay` and `TimeZone`! I created #2300 to also add instances for `LocalTime`/`ZonedTime`/`UTCTime` (if that is desired).

**Comment by georgefst** [comment]
Would you consider also adding `DayOfWeek` (as the obvious 7-element enum)? I've found this useful in some projects.

**Comment by Gabriel439** [comment]
@georgefst: I opened a PR to add isntance for `DayOfWeek`: https://github.com/dhall-lang/dhall-haskell/pull/2413
