### ISSUE TITLE
Is this a bug in the type checker with dependent types? `∀(x: Type) → x`

### ISSUE THREAD

**Issue by winitzki** [dhall-lang/dhall-haskell#2296]
I tried but failed to define the `Void` type in `dhall`. In the process, I found the following disturbing code that suggests to me that there might be a bug in `dhall`'s type checker. I hope I am wrong, but then there is a confusion to be resolved.

The document [How-to-translate-recursive-code-to-Dhall.html](https://docs.dhall-lang.org/howtos/How-to-translate-recursive-code-to-Dhall.html) describes how to define recursive types via the Church encoding. In a similar way, the following code defines a recursive type isomorphic to `Natural`:

```haskell
let N: Type = ∀(x: Type) → ∀(y: Optional x → x) → x
```

This is the Church encoding of the form `∀x. (1 + x → x) → x`.

Now, one can define values of type `N` that correspond to naturals. A typical value of type `N` will be a function of the form:

```haskell
let number2: N = \(x: Type) → \(y: Optional x → x) → y(Some (y (Some (y (None x)))))  -- natural number 2
```

 But I can also define a weird-looking value (`n` below) that returns a `Type`:

```haskell
$ dhall repl
Welcome to the Dhall v1.40.0 REPL! Type :help for more information.
⊢ :let N: Type = ∀(x: Type) → ∀(y: Optional x → x) → x

N : Type

⊢ :let n: N = \(x: Type) → \(y: Optional x → x)  → x    -- ignore `y` and just return `x`

n : ∀(x : Type) → ∀(y : Optional x → x) → Type

⊢ :let number0: N = \(x: Type) → \(y: Optional x → x) → y (None x)     -- this is a Church-encoded "zero"

number0 : ∀(x : Type) → ∀(y : Optional x → x) → x
```

But actually I expected `n` to be invalid and only `number0` be valid. Is this a bug in `dhall`?

Even if I am wrong, only one of `n` and `number0` should be accepted as valid. But `dhall` accepts both.

Note that `dhall` says `n` has type `∀(x : Type) → ∀(y : Optional x → x) → Type` but `number0` has type `∀(x : Type) → ∀(y : Optional x → x) → x`.

So, `n` is a function that, when applied to its two curried arguments, will eventually return a `Type`, while `number0`  is a function that, when applied to arguments, will eventually return a _value_ of type `x`. But a value of type `x` cannot be itself a `Type` because we have `x : Type`. How can _both_ `n` and `number0` be accepted as valid values of type `N`? 

What does the last `→ x` mean in the type declaration of the type `N`:
```haskell
∀(x: Type) → ∀(y: Optional x → x) → x
```
Does the last `x` mean that the function’s return value is a _value_ of type `x`, or does it mean that the function’s return value is the type `x` itself? It must be one or the other, not both. And yet `dhall` accepts both as valid. Is this a bug or a feature?

As a result of this, the following code fails to define the `Void` type:

```haskell
let Void: Type = ∀(x : Type) → x     -- I expect this to mean the type (∀x. x), which is void.
let void: Void = \(x: Type) → x      -- but dhall accepts this as a value of type Void.
```

Here the last `x` is again interpreted as being a `Type` rather than as a value of type `x`.

**Comment by winitzki** [comment]
@Gabriel439  That's great, I'm very much relieved to know that the typechecker is working correctly and it's just a minor bug with the REPL. So, the `Void` type can be defined by `∀(x: Type) → x`.

**Comment by Gabriel439** [comment]
Yeah, the `Void` type in Dhall is `∀(a : Type) → a`.  As a side note, you might also be interested in this: https://docs.dhall-lang.org/howtos/How-to-type-check-and-normalize-incomplete-code.html

**Comment by Gabriel439** [comment]
Oh, also `<>` can be used as the `Void` type, too, because it's isomorphic to `∀(a : Type) → a`:

```dhall
let forward
      : (∀(a : Type) → a) → <>
      = λ(void : ∀(a : Type) → a) → void <>

let backward
      : <> → (∀(a : Type) → a)
      = λ(void : <>) → λ(a : Type) → merge {=} void : a

in  { forward, backward }
```

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2297
