### ISSUE TITLE
Recursive data types cause an inifiite loop

### ISSUE THREAD

**Issue by vmchale** [dhall-lang/dhall-haskell#231]
Haskell file (compiler with `ghc -O Example.hs` and GHC 8.2.2:

```haskell
{-# LANGUAGE DeriveAnyClass    #-}
{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE OverloadedStrings #-}

import           Dhall

main :: IO ()
main = do
    x <- input auto "./example.dhall"
    print (x :: Tree Text)

data Tree a = Leaf a | Branch [Tree a]
    deriving (Show, Generic, Interpret)
```

Dhall file (version 1.8.2 is installed):

```
let ex =
  {
  }

in ex
```

Running `./Example` yields an infinite loop. 

Thanks again!

**Comment by Gabriel439** [comment]
Known issue: https://github.com/dhall-lang/dhall-lang/issues/3#issuecomment-331679595

This is a limitation of the way `GHC.Generics` encodes recursive data types.  The only way you can marshal user-defined datatypes into Haskell is to hand-write the `Interpret` instance

**Comment by vmchale** [comment]
Ah okay. I'll close this in favor of that one then.
