### ISSUE TITLE
dhallToNix errors with "Remote host not found" if Prelude is imported

### ISSUE THREAD

**Issue by ereslibre** [dhall-lang/dhall-haskell#2310]
I am using `dhallToNix` in a nix expression:

https://github.com/ereslibre/dhall-to-nix-test/blob/924757a2e5aabc5ae5f39ddd7b1144e9101dd624/oi.nix#L7

If this `dhall` file includes the `Prelude`, when I try to build the derivation, I get a `Remote host not found` error:

```
~/dhalltonix-test main » make
nix-build oi.nix
building '/nix/store/rj2lnm3mkdk16g5hhfn0z9c5cyd4i77w-dhall-compiled.nix.drv'...


Error: Remote host not found

URL: https://prelude.dhall-lang.org/v20.2.0/package.dhall

error: builder for '/nix/store/rj2lnm3mkdk16g5hhfn0z9c5cyd4i77w-dhall-compiled.nix.drv' failed with exit code 1
(use '--show-trace' to show detailed location information)
make: *** [Makefile:3: default] Error 100
```

I am a bit lost on how to start debugging this issue to understand what is going on. I created a repo for reproducing this issue: https://github.com/ereslibre/dhall-to-nix-test. A `make` will reproduce the issue. If the `Prelude` is removed from the dhall file in:

https://github.com/ereslibre/dhall-to-nix-test/blob/924757a2e5aabc5ae5f39ddd7b1144e9101dd624/dhall/versions.dhall#L1-L2

Then, the build succeeds:

```
~/dhalltonix-test main* » make
nix-build oi.nix
/nix/store/kwv5d2m22hli4wz3kkbiz7mw0mff686v-oi-20.09.0-alpha21
```

I would be grateful if you can point to something I might be missing or misunderstanding. If this is an issue with dhallToNix I would also be interested in helping fix it.

Thanks for dhall! 💯

**Comment by ereslibre** [comment]
I just pushed a new commit on the reproducer repository. When running the `cli` Makefile target -- which uses the `dhall-to-nix` CLI --, it works as expected.

```
~/dhall-to-nix-test main » make cli
nix-shell --pure --run ''dhall-to-nix <<< ./dhall/versions.dhall''
{ oneinfraVersion = "20.09.0-alpha21"; }
```

**Comment by Gabriel439** [comment]
My guess is that this is due to the `sandbox` setting (which is `true` by default on Linux).  Sandboxed builds cannot make HTTP requests by default

**Comment by ereslibre** [comment]
Thanks a lot, you are right. `nix-build --no-sandbox oi.nix` does not report this error. Closing.

**Comment by Gabriel439** [comment]
You're welcome! 😄
