### ISSUE TITLE
Hydra sometimes runs out of memory while building `dhall`

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#2313]
Recent examples:

* https://github.com/dhall-lang/dhall-haskell/pull/2236#issuecomment-926987181
* https://github.com/dhall-lang/dhall-haskell/pull/2312, with error:
  ```
  [11 of 47] Compiling Dhall.Syntax     ( src/Dhall/Syntax.hs, dist/build/Dhall/Syntax.o, dist/build/Dhall/Syntax.dyn_o )
  /nix/store/qdf49mvm79r83n9c9s7pkmmjqwhrw8jv-stdenv-linux/setup: line 1316: 3376277 Killed                  ./Setup build
  builder for '/nix/store/80snyp1ffix7ls7ayjjwxs0sqw1d3fqi-dhall-1.40.1.drv' failed with exit code 137
  ```

If `Dhall.Syntax` turns out to trigger this problem frequently, we could try to split that module in order to reduce the burden on GHC.

**Comment by Gabriel439** [comment]
Yeah, we should probably split it into one module per type at this point since it's getting large

**Comment by sjakobi** [comment]
It just happened again in https://github.com/dhall-lang/dhall-haskell/pull/2314. `Dhall.Syntax` indeed seems to be the problem.

**Comment by sjakobi** [comment]
I've implemented some relatively simple refactorings in #2317. Unfortunately the effect is rather unsatisfactory so far. I think the lowest maximum residency I saw was 1099MB (down from the initial 1128MB), but one of the last changes must have somehow negated these (tiny) improvements, so I'm now measuring 1138MB:

```
<<ghc: 123205423920 bytes, 4286 GCs, 174184726/464036480 avg/max bytes residency (27 samples), 1138M in use, 0.000 INIT (0.000 elapsed), 68.056 MUT (71.126 elapsed), 21.036 GC (21.061 elapsed) :ghc>>
```

There are a few more things that can be extracted without causing dependency cycles. However my suspicion is that the main GHC perf challenges are the derived instances of `Expr` and its components like `RecordField`. The relevant GHC tickets are https://gitlab.haskell.org/ghc/ghc/-/issues/5642 and https://gitlab.haskell.org/ghc/ghc/-/issues/9557. The main workaround I'm aware of is to write instances by hand. Are there any other tricks?

**Comment by sjakobi** [comment]
> This is why I think there needs to be one module per type (e.g. `Dhall.Syntax.{Expr,Binding,RecordField}`), because that would split up the derived instances

This will involve adding `.hs-boot` files, but I'll give it a try.

**Comment by mmhat** [comment]
I gave it a shot and split the `Dhall.Syntax` module in https://github.com/mmhat/dhall-haskell/tree/2313-split-syntax.
The stats are a bit better:
> <<ghc: 122937302272 bytes, 4432 GCs, 155520507/323993592 avg/max bytes residency (25 samples), 886M in use, 0.000 INIT (0.000 elapsed), 64.175 MUT (66.527 elapsed), 16.362 GC (16.380 elapsed) :ghc>>

I am however not sure if that is the right way to tackle this problem: As @sjakobi pointed out the main problem is (most likely) the huge sum type `Expr` and its `Generic` instance. I think a better solution would be to move the builtins to own types like:
```haskell
-- Dhall.Synax.Builtin.List

data ListExpr s a
    = List
    | ListLit ...
    | ListAppend ...
    | ListBuild
    ...

-- Dhall.Syntax

import qualified Dhall.Syntax.Builtin.List

data Expr s a
    ...
    | ListExpr (Dhall.Syntax.Builtin.List.ListExpr s a)
    ...

-- Pattern synonyms for backwards compatibility
pattern List = ListExpr Dhall.Syntax.Builtin.List
pattern ListLit mtype list = ListExpr (Dhall.Syntax.Builtin.ListLit mtype list)
```

@Gabriella439 @sjakobi What do you think?

**Comment by sjakobi** [comment]
> I gave it a shot and split the `Dhall.Syntax` module in https://github.com/mmhat/dhall-haskell/tree/2313-split-syntax. The stats are a bit better:
> 
> > <<ghc: 122937302272 bytes, 4432 GCs, 155520507/323993592 avg/max bytes residency (25 samples), 886M in use, 0.000 INIT (0.000 elapsed), 64.175 MUT (66.527 elapsed), 16.362 GC (16.380 elapsed) :ghc>>

Wow, thanks for pushing through! :star_struck:

Admittedly I'm not a big fan of `.hs-boot` files, but if they can fix the OOM issue, I'm in favour of accepting that change.

> I think a better solution would be to move the builtins to own types [...]

Yeah, that might make a bigger difference. But I think that splitting `Expr` may result in its own maintainability setbacks and possibly performance regressions (e.g. due to additional pointer chasing). I'd suggest that we merge your existing patch and look into splitting `Expr` if the the OOM issue persists or reappears.

**Comment by Gabriella439** [comment]
Sorry for the late reply.  I'm in favor of any of the proposed fixes, and I very much support factoring out builtins into a separate type (even if that's a breaking Haskell API change)

**Comment by mmhat** [comment]
Thanks for the feedback! Although I think it would be good to move the builtins to a separate type I share the concerns of @sjakobi. I drafted the solution I [mentioned](https://github.com/dhall-lang/dhall-haskell/issues/2313#issuecomment-1229426709) in https://github.com/mmhat/dhall-haskell/tree/2313-split-syntax-2 but I didn't run the benchmarks yet. The space usage on this branch is however a bit disappointing:
> <<ghc: 121471591392 bytes, 1798 GCs, 166505914/376001360 avg/max bytes residency (20 samples), 1056M in use, 0.001 INIT (0.001 elapsed), 66.141 MUT (69.108 elapsed), 16.217 GC (16.261 elapsed) :ghc>>

I think we should go with the previous approach (I can prepare a PR for the first branch throughout the next week.) first as suggested; At least for now. If we decide to move the builtins to an own type anyway we can do it on top of that.
