### ISSUE TITLE
Specific doctest test is unreliable

### ISSUE THREAD

**Issue by hololeap** [dhall-lang/dhall-haskell#2323]
This particular doctest relies on the inner [`HashMap`][1] to return the same ordering every time:

https://github.com/dhall-lang/dhall-haskell/blob/d561b77d051b1653e596cd38f9ac3c0a52ad2401/dhall-toml/src/Dhall/DhallToToml.hs#L218-L219

I hit this running the test suite on my system:
```
./setup test --show-details=streaming
Running 2 test suites...
Test suite doctest: RUNNING...
/var/tmp/portage/dev-util/dhall-toml-1.0.0/work/dhall-toml-1.0.0/src/Dhall/DhallToToml.hs:218: failure in expression `toml'
expected: Right (TOML {tomlPairs = fromList [("foo" :| [],Integer 1),("bar" :| [],Text "ABC")], tomlTables = fromList [], tomlTableArrays = fromList []})
 but got: Right (TOML {tomlPairs = fromList [("bar" :| [],Text "ABC"),("foo" :| [],Integer 1)], tomlTables = fromList [], tomlTableArrays = fromList []})
                                               ^

Examples: 8  Tried: 7  Errors: 0  Failures: 1
Test suite doctest: FAIL
Test suite logged to: dist/test/dhall-toml-1.0.0-doctest.log
```

[1]: https://hackage.haskell.org/package/tomland-1.3.3.0/docs/Toml-Type-TOML.html#t:TOML

**Comment by sjakobi** [comment]
I think this test provides good documentation independently of the exact order of elements in `tomlPairs`. As a test for correctness, I think it's pretty unimportant.

So ideally, we'd somehow keep the example while disabling it for `doctest`. Does `doctest` provide a way to  skip specific examples? Maybe insert a zero-width space in the `>>>` prefix?! Or be explicit and turn the `>>>` into a `>`.

**Comment by Gabriel439** [comment]
I believe https://github.com/dhall-lang/dhall-haskell/pull/2325 should fix it.  Could you give that branch a try and see if it resolves the problem for you?
