### ISSUE TITLE
Haddocks for `dhall-toml` are missing on Hackage

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#2324]
See https://hackage.haskell.org/package/dhall-toml-1.0.0.

In https://github.com/haskell/hackage-server/issues/988 I've figured out that the build fails due to an issue in `tomland`. Until that's fixed, we should probably upload the docs directly.

**Comment by sjakobi** [comment]
I hope that https://github.com/kowainik/tomland/pull/392 will fix the build issue with `tomland`.

**Comment by Gabriel439** [comment]
I manually uploaded the documentation for `dhall-toml`
