### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by joneshf** [dhall-lang/dhall-haskell#235]
Congrats on 1.9.0! Can we get a tag for 1.9.0 so the binaries get built?

More generally, is there something we can do to automate the creation of tags/binaries? Is there a different process that fits in better with how releases are made?

**Comment by Gabriel439** [comment]
Yeah, I just created tags for both `dhall` and `dhall-json`

You could probably automate it based on the revision name.  I always title the revisions for releases something like `Version X → Y`

**Comment by ocharles** [comment]
I just updated the 1.9 tag information on GitHub to provide the Changelog. No change on the Git side of things, just a heads-up!

**Comment by Gabriel439** [comment]
@ocharles: Oh yeah, good idea.  Thanks! :)

**Comment by ocharles** [comment]
I think this can be closed now, right?

**Comment by joneshf** [comment]
I'm unsure. I think the issue might be mis-titled.

Ultimately, I'd like to have binaries available for each version. I don't really care how that happens. But CI has moved from Travis to Hydra and I'm unsure if that's happening now. Is it happening? If so, where do the binaries end up? If not, what's the story for it to get there?

**Comment by Gabriel439** [comment]
So right now I'm working on being able to serve fully static binaries from Hydra (i.e. no Nix dependency).  I'm still preserving the Travis logic for now so that we can publish releases with that if necessary until then

**Comment by joneshf** [comment]
Per https://github.com/dhall-lang/dhall-lang/issues/192#issuecomment-406872743, I think this issue is resolved.
