### ISSUE TITLE
dhall-to-json: should --pretty vs --compact change the type of numbers in the output?

### ISSUE THREAD

**Issue by mikeantonacci** [dhall-lang/dhall-haskell#2351]
Minimal (contrived) example:

```bash
$ echo '{"n":2123234787847813783278587}' | json-to-dhall | dhall --annotate
{ n = 2123234787847813783278587 } : { n : Natural }
$ echo '{"n":2123234787847813783278587}' | json-to-dhall | dhall --annotate | dhall-to-json --compact
{"n":2123234787847813783278587}
$ echo '{"n":2123234787847813783278587}' | json-to-dhall | dhall --annotate | dhall-to-json --pretty
{
  "n": 2.123234787847813783278587e24
}
```
This creates a situation where I could serialize something to JSON from Python containing a large `int`, convert it to Dhall and see that it becomes a `Natural` and everything is fine, and then if I run `dhall-to-json` I may get back something that looks like a `float` and loses precision when I deserialize depending on whether I pretty-printed the output or not:
```python
>>> import json
>>> json.dumps({"n":2123234787847813783278587})
'{"n": 2123234787847813783278587}'
>>> json.loads('{"n":2123234787847813783278587}')
{'n': 2123234787847813783278587}
>>> json.loads('''{
...   "n": 2.123234787847813783278587e24
... }''')
{'n': 2.1232347878478138e+24}
```

**Comment by Gabriel439** [comment]
Whoops!  The scientific notation for large numbers is unintentional.  Fortunately, we can fix it since the JSON pretty-printing library we're using lets us disable that behavior

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2352
