### ISSUE TITLE
dhall-to-toml: No proper CLI

### ISSUE THREAD

**Issue by amesgen** [dhall-lang/dhall-haskell#2353]
The usual stuff provided by optparse-applicative (`--version`, `--help`, input/output as file/stdin/stdout) is missing from `dhall-to-toml` and `toml-to-dhall`. 

This should be easy to add, but maybe there could even be some shared code for the various `dhall-someformat` projects?

**Comment by sjakobi** [comment]
Yes, proper CLIs would be very nice to have!

> This should be easy to add, but maybe there could even be some shared code for the various `dhall-someformat` projects?

The various option parsers do have things in common, but they also have a lot of differences. I suspect that it might be easiest to keep them separate. AFAIK this hasn't caused us much maintenance hassle so far.
