### ISSUE TITLE
Import function with dynamic number of arguments

### ISSUE THREAD

**Issue by mainrs** [dhall-lang/dhall-haskell#2357]
I have a similar configuration to how `flake.nix` files work. I have a set of inputs that the config exports. These consists of data that I have to ask the user (in Haskell).
The configuration also exports a function (called `output`) that accepts that input data and returns its configuration.

I know how to implement this for a fixed number of arguments. I can simply load the `output` function using its signature and interpret it. But how can I do this if the number of `inputs` can be anything? Configuration A might only need two datapoints from the user, configuration B might need seven.

Thanks for your help!

```nix
let 
  inputs = {
    name = { type = "text"; message = "What is your name?"; };
    age = { type = "number"; message = "What is your age?"; };
  };
  outputs = \(name: String, age: Int) -> "${name} is ${toString age} years old!");
in {
  inputs = inputs;
  output = output;
}
```

**Comment by Gabriel439** [comment]
I assume that you're asking what the Dhall type would be for a flake like this for use with `dhall-to-nix`

As far as I know, there is not a universal Dhall type that you could use for all possible flakes.  It would be a different Dhall type for each flake

**Comment by mainrs** [comment]
> I assume that you're asking what the Dhall type would be for a flake like this for use with dhall-to-nix

No. It basically boils down to me having a similar structure. The `inputs` set is a mapping of `Text -> Question` and `output` is a function that takes as many arguments as are defined in `inputs`. Here ([nopaste.ml](https://nopaste.ml/#XQAAAQC5BQAAAAAAAAAW4Hz4IB+ACOUSXJYsTWO67c6t3JgZL7QVqEnNnAAP5Y4xYeONfMRwPp5K3BdYoUFa1vQuaUNa9MrOwzv5jIX8wZbsEwCvE/59j3/ZbF8gMxZQ9JfwIRolyTh35ZlwP4BS2MWDcN84/Rc/RgsWhR84MB50Us1ifvdvEPG6YOk2rbcRoaWNGtXGa0iiaA2MQatB12KgoEih5GW6WG8AbENnY+TYgHgH/uGuEXjynCCQzE3GRkn+KVv3rKY7kIYijhXnqNu9OlmluXtzXxNpexEfJvfuEyI+GUT29mC2W/G6bHuMbws41CzZQxjfd0tdT6OaYxP6yq07xKB2pcK2mDfIAjH/fVjLdyubrCZ0CIigr//8LobFFilb5Wa+ZhqtVMpFJbGvdQYgKMgfcdeAtf0VuZe9wRRXIvrp8jBvZ5WUtvOww2LB9AzbmxsIp56m6BvxRd6S27RWkLMcxBEbxzEN4cn92p8FeDGIx0iX33P6apnZ9s/2zflhVuv4zxGDC75hU4p31/kRUR7jBX/v+/ylyGHn/NM5nSj1Sbzw0UvYRll0uSPA6HwY4G+6dLfyWentoO4YKCyd4NFAZJnQ/DDkmX33emu281Mzg6Pzcp9xn85s4cJXeLWBjLtsRBTDlnKEseoh45NdHA5GJHaRPMvGUg5xL5hNViEDcHvM1KnrOygXMm2hQStTWuaeDkKxEl1QrzVhDZ4wavQUeadRWNeuFbsWGPcpi1JiOrv63mNJ4ibN8ZouWR6dF+baXBgYVTkuQL+zm9Z4SsoFRRgpdYMjvNhRrAWLIkf8tLHB6XyZQGhm8jM41N90XAvjKDIcYDloH6Tu5jOpOMhoqJWU9hfCmHbGpE3QuV4rrljaCYNdFxYN5v/6Pk0Q)) is an example. I hope that this clarifies it!

**Comment by Gabriel439** [comment]
Ah, I get what you're trying to do now.  I think the way I would approach that is like this:

```dhall
let DefaultOption = < Neither | No | Yes >

in

λ(choicePrompt : { message : Text, choices : List Text } → Text) →

λ(confirmPrompt : { message : Text, defaultOption : DefaultOption } → Bool) →

λ(textPrompt : { message : Text, allowEmpty : Bool } → Text) →

let Wizard = λ(a : Type) → { inputs : a, output : a → Text }

let example
    : Wizard { name : Text, iceCream : Bool }
    = { inputs =
        { name =
            textPrompt
              { message = "What is your name?"
              , allowEmpty = False
              }
        , iceCream =
            confirmPrompt
              { message = "Do you want ice cream?"
              , defaultOption = DefaultOption.Yes
              }
        }
      , output =
          λ(inputs : { name : Text, iceCream : Bool }) →
            let suffix =
                  if    inputs.iceCream
                  then  " and you want ice cream"
                  else  ""

            in  "Your name is ${inputs.name}${suffix}"
      }

in  example
```

The key trick here is "assuming" the existence of built-in functions that prompt the user for input (e.g. `choicePrompt` / `confirmPrompt` / `textPrompt`).  In Dhall you can introduce such assumptions as lambdas since Dhall can interpret under lambdas abstractly.  Alternatively, you could extend the interpreter to add those built-in prompt functions by the following the instructions here: https://docs.dhall-lang.org/howtos/How-to-add-a-new-built-in-function.html

**Comment by Gabriel439** [comment]
Actually, going a step further, if you extended the interpreter to add those built-in prompt functions then you wouldn't even need the `Wizard` type.  You could just write this:


```dhall
let DefaultOption = < Neither | No | Yes >
in

λ(choicePrompt : { message : Text, choices : List Text } → Text) →
λ(confirmPrompt : { message : Text, defaultOption : DefaultOption } → Bool) →
λ(textPrompt : { message : Text, allowEmpty : Bool } → Text) →

let name =
      textPrompt { message = "What is your name?", allowEmpty = False }

let iceCream = confirmPrompt
        { message = "Do you want ice cream?"
        , defaultOption = DefaultOption.Yes
        }

let suffix = if iceCream then " and you want ice cream" else ""

in  "Your name is ${name}${suffix}"
```

**Comment by mainrs** [comment]
@Gabriel439 First off, thanks for helping me out! I am still experimenting around with `dhall`. I want to use it for custom project template generation and I thought that it might actually fit the use-case quite good!

Would expanding the interpreter allow for composition of inputs? It's quite hacky right now how I "implemented" it, but I can reference the inputs of other generators and compose them. It seems like that wouldn't be possible when using a builtin function that actually returns the value directly. Maybe there is another way to compose in this scenario that I am not seeing right now.

Example of composition:

```dhall
-- generator-base exports this input
let inputs
    : T.Inputs
    = toMap
        { project-name =
            P.Question.TextPrompt
              P.CreateTextPrompt::{ message = "Project name?" }
        , project-description =
            P.Question.TextPrompt
              P.CreateTextPrompt::{ message = "Project description?" }
        }
```

```dhall
-- generator-rust imports it and uses it.
let GenBase = ../generator-base/template.dhall
let T = ../dhall-api/Types.dhall

let baseInputs
    : T.Inputs
    = List/unpackOptionals
        T.Input
        [ List/index 0 T.Input GenBase.inputs
        , List/index 1 T.Input GenBase.inputs
        ]
let rustInputs
    : T.Inputs
    = toMap
        { project-type =
            P.Question.ChoicePrompt
              { message = "Project type?", choices = [ "Binary", "Library" ] }
        }
let inputs = List/concat T.Input [ baseInputs, rustInputs ]
```

Super ugly right now, but it is the first try. This comes super handy when using generators for nix flakes, licenses, gitignore files and the like.

**Comment by Gabriel439** [comment]
The idea I'm going for here is that if you were to add built-in functions for each type of prompt then you wouldn't need generators at all (and therefore you wouldn't need to be able to compose generators).  See the second generator-free example I posted here: https://github.com/dhall-lang/dhall-haskell/issues/2357#issuecomment-1003189454

**Comment by mainrs** [comment]
Thank you very much! I think I came up with something based on your second suggestion that should work out!

I'd like to contribute back to `dhall`. I'll try to resolve https://github.com/dhall-lang/dhall-lang/issues/1256 first. I'd also like to contribute to the standard. But I couldn't really find a `how-to` guide on how that is done. Are there resources that I missed?

**Comment by Gabriel439** [comment]
There's not a guide, but probably the most useful existing resources are to study prior pull request to extend the language, such as:

* https://github.com/dhall-lang/dhall-lang/commit/8d22f9f563ffd94a60d23938f4b2c9cc972c2395#diff-fe6d3468cf5c74d8ec2a95b40f2e05338c37a4202f8fad692d2b64a9cf9b468a
* https://github.com/dhall-lang/dhall-lang/commit/16160eb447f06fcd69bf6b386970ea929f84438c#diff-fe6d3468cf5c74d8ec2a95b40f2e05338c37a4202f8fad692d2b64a9cf9b468a

… and also to read the beginning of the main `README` for the standard:

* https://github.com/dhall-lang/dhall-lang/tree/master/standard#semantics

**Comment by mainrs** [comment]
Thank you!

**Comment by Gabriel439** [comment]
You're welcome! 🙂
