### ISSUE TITLE
`dhall format` removes shebang

### ISSUE THREAD

**Issue by SiriusStarr** [dhall-lang/dhall-haskell#2361]
dhall-lang/dhall-lang#1158 added support for leading shebangs in Dhall files, but `dhall format` currently removes them.  Probably related to #145, but this is arguably "worse"/more pressing, since the shebang actually serves a functional purpose and is not merely documentation.

**Comment by Gabriel439** [comment]
Fix up here: https://github.com/dhall-lang/dhall-haskell/pull/2364
