### ISSUE TITLE
Does Dhall render times that are in timezones on the western hemisphere correctly?

### ISSUE THREAD

**Issue by isaacsanders** [dhall-lang/dhall-haskell#2368]
I entered the following time `04:00:00-04:00` in the Dhall front page, and it rendered `"04:00:00--4:00"`.

The double `-` doesn't seem correct to me, but I could be wrong.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2379
