### ISSUE TITLE
dhall-nix: 1.6 release of hnix implemented more `builtins`

### ISSUE THREAD

**Issue by Anton-Latukha** [dhall-lang/dhall-haskell#2369]
Additionally to `99` functions implemented & existing for several last releases, there are several new function implementations from [`builtins`](https://nixos.org/manual/nix/stable/expressions/builtins.html):
* `isPath`
* `unsafeDiscardOutputDependency`
* `ceil` (rounding)
* `floor` (rounding)
* `hashFile`
* `groupBy` 

Do not know if that is relevant in the projects functionality/scope, just thought that this detail of the release is worth notifying here.

**Comment by Gabriel439** [comment]
It doesn't affect `dhall-nix`, since it only uses `hnix` for pretty-printing Nix syntax trees
