### ISSUE TITLE
text-2.0 support

### ISSUE THREAD

**Issue by SiriusStarr** [dhall-lang/dhall-haskell#2370]
Currently, it looks `text-2.0` cannot be used with Dhall due to the dependency on `text-manipulate`, which makes use of internal text modules and is [broken with text 2.0](https://github.com/brendanhay/text-manipulate/issues/6) (and as such will likely require considerable work to make compatible with 2.0).  `text-manipulate` seems to only be used in lightly in `Dhall.Deriving` (qualified as `Case` in the below snippet) https://github.com/dhall-lang/dhall-haskell/blob/2df2a5186270e5fcd7aa1848e119706df33dd7e6/dhall/src/Dhall/Deriving.hs#L153-L181

Since `text-2.0` is a pretty massive upgrade and `text-manipulate` is only used for trivial case conversion, it would perhaps be good to find an alternative dependency (or simply replace them inline); the fusion capabilities of the current dependency are the only non-trivial part of the functions, and they are presumably unnecessary for this particular use case.

**Comment by sjakobi** [comment]
`text-manipulate` has actually already been fixed upstream in https://github.com/brendanhay/text-manipulate/pull/5. I expect that it the fix will be released pretty soon – I've perceived the maintainer as pretty reliable so far.

**Comment by SiriusStarr** [comment]
Nvm, I am an idiot and somehow overlooked that despite staring at it for the last 15 minutes...

**Comment by sjakobi** [comment]
No worries, @SiriusStarr! ;)

**Comment by SiriusStarr** [comment]
Alas, my shame shall live on eternally as a closed issue.  :rofl:
