### ISSUE TITLE
Allow Comments To Be Emitted In Dhall's Output

### ISSUE THREAD

**Issue by Varriount** [dhall-lang/dhall-haskell#2375]
One of the things that makes me hesitant about using Dhall is how comments from input files are discarded when generating output files. I am concerned about the readability of the output files in cases where the input files may not be accessible, such as a user modifying a pregenerated configuration file, or when conducting troubleshooting on a specific machine/node. Ideally comments from input files would be preserved when generating output files, or at the very least, a mechanism would exist to inject specific comments in output files.

**Comment by sjakobi** [comment]
Is this about `dhall format` (see https://github.com/dhall-lang/dhall-haskell/issues/145) or about other functionality, e.g. normalization?

**Comment by Varriount** [comment]
> Is this about `dhall format` (see #145) or about other functionality, e.g. normalization?

This is more about the output of `dhall-to-json`, `dhall-to-yaml`, etc.

Given the example on dhal-lang.org:
```dhall
{- This is an example Dhall configuration file

   Can you spot the mistake?

   Fix the typo, then move onto the "Definitions"
   example
-}

{ home       = "/home/bill"
, privateKey = "/home/bill/.ssh/id_ed25519"
, publicKey  = "/home/blil/.ssh/id_ed25519.pub"
}
```
the output of `dhall-to-yaml --file test.dhall --output test.yaml` is
```
home: /home/bill
privateKey: /home/bill/.ssh/id_ed25519
publicKey: /home/blil/.ssh/id_ed25519.pub
```

This lacks the comments in the original file.

**Comment by Gabriel439** [comment]
Oh, we don't support comments in `dhall-to-yaml` *in general* (because that would be very difficult), but we could add support for the special case of preserving a comment at the beginning of the file.  Would that work for your use case?

**Comment by Varriount** [comment]
Not really. The goal is to ensure that no matter which version of a file is read, explanatory comments for parts of the configuration are seen.

I'm not sure how Dhall handles parsing (whether it has separate lexing/parsing phases, etc.), but the way I've seen this done in procedural languages using ASTs (Abstract Syntax Trees) is to either:
  - Parse comments as their own AST node. Code that doesn't care about comment nodes could either skip over them, or instruct the parser not to emit them (this is what [Go's parser does](https://github.com/golang/go/blob/master/src/cmd/gofmt/gofmt.go#L66)).
  - Attach comments as metadata to existing AST nodes - that is, when a comment is parsed, attach it to the last created node. I believe this is what [Python's `ruamel.yaml` module does](https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/events.py#l28). 

Either of these strategies makes comments available for tools which require them, such as formatters and translators.

**Comment by Gabriel439** [comment]
We do parse comments as a separate AST node (called `Note`).  The issue here is that `dhall-to-yaml` also does interpretation, and there's no easy way to preserve comments *in general* when interpreting the syntax tree.

For example, this is a valid input to `dhall-to-yaml`:

```dhall
let foo = λ(n : Natural) → {- A comment -} n + 1

in { x = foo 2 }
```

That comment would get lost by the interpreter.

We could add special cases to the interpreter to make a best effort to preserve comments, but currently we discard all comments as part of interpretation for performance reasons.

An intermediate solution we could do is check to see if the input is already normalized, and if not then we might be able to preserve comments when converting to YAML.

**Comment by Varriount** [comment]
I can understand why comments would be lost in that case, however I believe the majority of comments one would want to retain would either be "top-level" comments, or comments inside top-level structures.

> Currently we discard all comments as part of interpretation for performance reasons.

By "performance reasons", do you mean memory? Or CPU usage/processing time?

**Comment by Gabriel439** [comment]
CPU usage/processing time

**Comment by Varriount** [comment]
Huh, how does the addition of comments cause additional CPU usage during interpretation?

**Comment by rgrunbla** [comment]
I have another use-case for supporting comments: I use dhall-to-yaml to create cloud-init files, and such files are supposed to begin with `#cloud-config`. Having to add this after the yaml generation is only a minor annoyance, but still an annoyance. Having top-level comments being preserved would solve this small issue.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2410

**Comment by Varriount** [comment]
@Gabriel439 Does the fix preserve all comments, or only those at the very top of a Dhall file?

**Comment by Gabriel439** [comment]
Only those at the top of a Dhall file

**Comment by Varriount** [comment]
@Gabriella439 I wouldn't really call this PR "fulfilled" then. A proper fix would be to include *all* comments in Dhall's output.
