### ISSUE TITLE
Inconsistent handling of yaml reserved words

### ISSUE THREAD

**Issue by mrskug** [dhall-lang/dhall-haskell#2377]
dhall-to-yaml seems to not care about yaml reserved words when using a Text type.

Example: 
```bash 
dhall-to-json <<< '{ key = "KEY", value = "on"}'
```
```json
{
  "key": "KEY",
  "value": "on"
}
```
```bash
dhall-to-yaml <<< '{ key = "KEY", value = "on"}'
```
```yaml
key: KEY
value: on
```

Should not the yaml output be  `value: "on"` ?

**Comment by sjakobi** [comment]
Note that `on` is not a reserved word in YAML 1.2.

`dhall-to-yaml` has a `--quoted` option that you can use. Alternatively you can give `dhall-to-yaml-ng` a try, which quotes YAML 1.1 booleans:

```
$ echo '{ key = "KEY", value = "on"}' | dhall-to-yaml-ng 
key: KEY
value: 'on'
```

**Comment by sjakobi** [comment]
https://github.com/dhall-lang/dhall-haskell/issues/2275 was a similar issue BTW.

**Comment by mrskug** [comment]
Thanks for the help. This makes sense, what does not make sense though is why does `kubectl` parse yaml according to the 1.1 spec :thinking:.
