### ISSUE TITLE
Remove `system-filepath`/`system-fileio` dependencies

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-haskell#239]
`dhall` doesn't really need improved type safety for filepaths, so I don't mind getting rid of these dependencies (i.e. replace them with just `FilePath` from the `Prelude` and operations from the `filepath` library)

**Comment by PierreR** [comment]
Two little questions:

- Do you want to bring https://hackage.haskell.org/package/path-0.6.1 deps ?  If you don't what's the best way to get the parent directory from a FilePath ?
- How do we replace [collapse](https://github.com/dhall-lang/dhall-haskell/blob/master/src/Dhall/Import.hs#L481) (with `normalize`) ?

As a note, I am bit confused by the name of this [function](https://github.com/dhall-lang/dhall-haskell/blob/master/src/Dhall/Import.hs#L474)

**Comment by Gabriel439** [comment]
@PierreR: The `filepath` library contains utilities for working with `Prelude.FilePath`.  For example, `System.FilePath.takeDirectory` gives you the parent directory

Similarly, the analog of `Filesystem.Path.collapse` is `System.FilePath.normalise`

In English the `@` symbol is pronounced "at", which is why the function is called `removeAtFromFile`

**Comment by PierreR** [comment]
If I understand your comment correctly, `removeAtFromFile` assume that the input FilePath is a file and not a directory ? 
`removeAtFromFile` seems confusing because it does not remove `@` from a filepath, it just remove `@` is the filepath happens to be a be a path describing a filename which is exactly `@` ?

**Comment by Gabriel439** [comment]
Right.  It only removes the `@` if it is the last path component (i.e. the name of the file)

**Comment by PierreR** [comment]
To be clearer about my first comment I am wondering if `Filesystem.Path.parent` is the same as `System.FilePath.takeDirectory` in case of  `/foo/bar/baz/` ?

**Comment by Gabriel439** [comment]
So I just checked and they do not behave the same:

```
$ nix-shell --packages 'haskellPackages.ghcWithPackages (pkgs: [ pkgs.system-filepath pkgs.filepath ])'
$ ghci
Prelude> :set -XOverloadedStrings
Prelude> import qualified Filesystem.Path.CurrentOS
Prelude Filesystem.Path.CurrentOS> import qualified System.FilePath
Prelude Filesystem.Path.CurrentOS System.FilePath> Filesystem.Path.parent "/foo/bar/baz/"
FilePath "/foo/bar/"
Prelude Filesystem.Path.CurrentOS System.FilePath> System.FilePath.takeDirectory "/foo/bar/baz/"
"/foo/bar/baz"
```
