### ISSUE TITLE
`Failed to parse message header` with 1.1.1 build

### ISSUE THREAD

**Issue by chenrui333** [dhall-lang/dhall-haskell#2411]
I was trying to upgrade the homebrew formula to use the latest release, but ran into some test failure.

```
$ /opt/homebrew/Cellar/dhall-lsp-server/1.1.1/bin/dhall-lsp-server
"Content-Length: 152\r\n\r\n{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{\""processId\":88075,\"rootUri\":null,\"capabilities\":{},\"trace\":\"ver" bose\",\"workspaceFolders\":null}}\r\n"Failed to parse message header:
: string
 exiting 1 ...
```

Let me know if I can provide more info.

- relates to https://github.com/Homebrew/homebrew-core/pull/99071

**Comment by Gabriella439** [comment]
@chenrui333: I have a pull request up which I believe will fix this: https://github.com/Homebrew/homebrew-core/pull/102546

**Comment by Gabriella439** [comment]
Fixed by https://github.com/Homebrew/homebrew-core/pull/102546
