### ISSUE TITLE
dhall-nix Use z-encoding for nix symbol names

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-haskell#2425]
When trying to encode a function like 

```
\(Foo/Bar: Text) -> Foo/Bar
```

I get the nix code

```nix
Foo/Bar:
  Foo/Bar
```

which fails with the nix parsing error

```
error: syntax error, unexpected ':', expecting end of file

       at «string»:1:8:

            1| Foo/Bar:
             |        ^
```

… this is not good, because “namespaced” symbols like that are quite frequent in dhall code.

I would suggest using the [Z-Encoding scheme](https://hackage.haskell.org/package/zenc-0.1.2/docs/Text-Encoding-Z.html) that is also used by GHC to create nix symbols.

**Comment by Gabriella439** [comment]
You can escape identifiers using backticks, like this:

```dhall
λ(`Foo/Bar` : Text) → `Foo/Bar`
```

**Comment by Profpatsch** [comment]
Yeah, but the generated nix code is still not valid nix syntax, this generates

```
Foo/Bar:
  Foo/Bar
```
