### ISSUE TITLE
Create templates for error messages

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-haskell#243]
One thing that would help for creating independent Dhall implementations is if they could reuse the Haskell implementation's error messages.  This would be easy if the error messages were stored as template files that could be shared between projects and/or upstreamed into the parent `dhall-lang` project

Bonus points if [the templates are Dhall expressions](http://www.haskellforall.com/2017/06/dhall-is-now-template-engine.html)

**Comment by paulyoung** [comment]
@joneshf pointed me to @nanotech's Rust implementation which does something like this.

* Template files: https://github.com/nanotech/dhall-rs/tree/7fe85bcd1ddecf58814e35f02cab8ef652a1e9c2/src/errors
* Usage: https://github.com/nanotech/dhall-rs/blob/7fe85bcd1ddecf58814e35f02cab8ef652a1e9c2/src/typecheck.rs#L600-L616

**Comment by Gabriel439** [comment]
I'm going to close this out since I believe this might not be a good idea after all.

The main issue is that we'd like error messages to eventually be formatted entirely using the `prettyprinter` library instead of being manually formatted.  This would allows us to do things like
change the error messages to fit within a different number of columns or correctly enable/disable terminal highlighting within them.
