### ISSUE TITLE
[dhall-to-yaml-ng] args and usage problem

### ISSUE THREAD

**Issue by buzzerpuzzle** [dhall-lang/dhall-haskell#2442]
I'm investigating the dhall and like to adapt it to my project. 
However, I have go through the tutorial but still do not sure how to fulfill my goal.
The thing is that I hope I could create the dhall file and use it with different argument so that I could generate different yaml config file which could help me to further deploy on the system.
The most intuitive approach would be something like below.

```
dhall-to-yaml-ng --file test.dhall --value "test1" > test1.yaml
dhall-to-yaml-ng --file test.dhall --value "test2" > test2.yaml
....
```

There are few parts I do not know and hope anyone could help me with corresponding example that would be great!

1. How to passing the args or parameter from the command line?
   
   `dhall-to-yaml-ng --file test.dhall --value "test"`

2. How to read the args from dhall file? Is there any preserve word I could assign to specific variable like below.
   
   `let test = ${args.value}`

Reference
```
Usage: dhall-to-yaml-ng [[--explain] [--omit-empty | --preserve-null] 
                          [--documents] [--quoted] 
                          [[--key ARG] [--value ARG] | --no-maps] [--file FILE] 
                          [--output FILE] [--generated-comment] 
                          [--preserve-header] |
                          --version]

  Compile Dhall to YAML

Available options:
  -h,--help                Show this help text
  --explain                Explain error messages in detail
  --omit-empty             Omit record fields that are null or empty records
  --preserve-null          Preserve record fields that are null
  --documents              If given a Dhall list, output a document for every
                           element. Each document, including the first one, will
                           be preceded by "---", even if there is only one
                           document. If not given a list, output a single
                           document (as if it were a list of one element)
  --quoted                 Prevent from generating not quoted scalars
  --key ARG                Reserved key field name for association lists
                           (default: mapKey)
  --value ARG              Reserved value field name for association lists
                           (default: mapValue)
  --no-maps                Disable conversion of association lists to
                           homogeneous maps
  --file FILE              Read expression from a file instead of standard input
  --output FILE            Write YAML to a file instead of standard output
  --generated-comment      Include a comment header warning not to edit the
                           generated file
  --preserve-header        Translate any Dhall comment header to a YAML comment
                           header
  --version                Display version
```

**Comment by Gabriella439** [comment]
`dhall-to-yaml` accepts an arbitrary Dhall expression on standard input, so you can do this:

```ShellSession
$ dhall-to-yaml <<< './test.dhall { value = "test1" }'
```

… which will work if you make `./test.dhall` a function of a record:

```dhall
λ(args : { value : Text }) → …
```

**Comment by buzzerpuzzle** [comment]
Thanks for this input!
Any other way to pass args into the dhall file?
I feel like there is a way to pass and use it but do not sure how to do it.

Reference
```
  --key ARG                Reserved key field name for association lists
                           (default: mapKey)
  --value ARG              Reserved value field name for association lists
                           (default: mapValue)
```

**Comment by Gabriella439** [comment]
`--key` and `--value` are not for passing in arguments.  They are there so that users can override the `Map` type that `dhall-to-yaml` expects

To elaborate on that, currently `dhall-to-yaml` provides special support for recognizing association lists of the following type:

```dhall
List { mapKey : Text, mapValue : Text }
```

… and translating them to YAML dictionaries.  This type is the same thing as [`Prelude.Map.Type`](https://store.dhall-lang.org/Prelude-v21.1.0/Map/Type.dhall.html).

However, in rare circumstances the user may want to use records that have fields named `mapKey` or `mapValue` without colliding with that built-in support, so they can override it.

I'm pretty sure 0 users use this feature, but I believe that was the rationale for adding those command-line options originally.

**Comment by buzzerpuzzle** [comment]
I see!
Thanks for this clarification!
Also, I see there is yaml-to-dhall command but I do not sure how to install it...
I have use below command to enable it but unfortunately not working from my end.
```
brew install dhall
brew install dhall-yaml
```

**Comment by Gabriella439** [comment]
Hmmm. The `dhall-yaml` package should include `yaml-to-dhall`.  If not, then there was something wrong with how `dhall-yaml` was packaged for `brew`

**Comment by buzzerpuzzle** [comment]
I see!
One last question!
Is there anyway we could make dhall generated yaml with double quote on string?
Like specify on the dhall code?
```
original yaml: cmd: "/home/app/test.sh"
dhall generated yaml: cmd: /home/app/test.sh
```

**Comment by Gabriella439** [comment]
The closest thing we have is the `--quoted` option, but that generates single-quoted strings

**Comment by buzzerpuzzle** [comment]
I see!
I have pop out another question!
Is there any way we could have if condition in the function that if we pass parameter with true, it would come with specific config and if that is not, it would not comes with this config.

```
dhall-to-yaml-ng <<< './test-service.dhall {test = True}'

{
    a: "123"
    b: "test"
}

dhall-to-yaml-ng <<< './test-service.dhall {test = False}'

{
    a: "123"
}
```

**Comment by buzzerpuzzle** [comment]
![Screen Shot 2022-08-31 at 10 43 25 AM](https://user-images.githubusercontent.com/1564157/187744571-460ae081-bc30-484e-9131-226e5fc20c17.png)
```
 learning-dhall % dhall-to-yaml-ng <<< './function.dhall {value = True}'

↳ ./function.dhall

Error: ❰if❱ branches must have matching types

- { … = … } (a record)
+ { … : … } (a record type)

4│                                       if True then {
5│ 	test1 = c
6│ } else {
7│ 	test2 = b
8│ }

/Users/len.lin/Projects/learning-dhall/function.dhall:4:39

1│ ./function.dhall
```

**Comment by Gabriella439** [comment]
You can't return two different types of values from an `if` expression.  However, for the former example, you can unify the two branches by using an `Optional` value, like this:

```dhall
λ(args : { test : Bool }) →
  { a = "123", b = if args.test then Some "test" else None Text }
```

**Comment by buzzerpuzzle** [comment]
I try to install the latest version `dhall-yaml-1.2.11-x86_64-Linux.tar.bz2` and looks like that required version `GLIBC_2.29' not found.
Do you have any suggestion for the version is Debian GLIBC 2.28-10+deb10u1?

**Comment by buzzerpuzzle** [comment]
The reason for that question is that I can not find the corresponding package from the repo.

```
apt-get install dhall
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dhall
```

**Comment by Gabriella439** [comment]
I'll mark this issue closed as I believe it's been answered
