### ISSUE TITLE
Windows CI failure in `Dhall.DirectoryTree`

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#2452]
See https://github.com/dhall-lang/dhall-haskell/actions/runs/3138921448/jobs/5098786985#step:5:3517.

This seems related to https://github.com/dhall-lang/dhall-haskell/pull/2437. Could you possibly take a look, @mmhat?

**Comment by mmhat** [comment]
I am on it.

**Comment by Gabriella439** [comment]
Just to clarify: does this only affect Windows?

**Comment by mmhat** [comment]
@Gabriella439 Yes, Unix systems are fine. The issue is caused by some missing types in the `unix-compat` package. It should ultimately be solved there and what I am trying here is to find a decent workaround.

**Comment by mmhat** [comment]
Also setting permissions does not work as expected on Windows: https://github.com/mmhat/dhall-haskell/actions/runs/3147765869/jobs/5117585580
I will disable setting permissions on Windows for now.
