### ISSUE TITLE
Problem with space character in URL import.

### ISSUE THREAD

**Issue by 1chb** [dhall-lang/dhall-haskell#2467]
A URL with a space encoded as `%20` is changed to `%2520` so the URL misses its target. Maybe there is no coincident that the `%` character has ASCII code 0x25. To reproduce:

```
> dhall repl
Welcome to the Dhall v1.41.2 REPL! Type :help for more information.
⊢ https://github.com/dhall-lang/dhall-haskell/blob/master/dhall/examples/fi%20le.dhall

Error: Remote file not found

HTTP status code: 404

URL: https://github.com/dhall-lang/dhall-haskell/blob/master/dhall/examples/fi%2520le.dhall
```

**Comment by sjakobi** [comment]
Can you provide a reproducer with an import that is actually supposed to work?

https://github.com/dhall-lang/dhall-haskell/blob/master/dhall/examples/fi%20le.dhall doesn't exist so it's no surprise the import fails.

**Comment by 1chb** [comment]
Of course:
A file without space works:
`https://github.com/1chb/dhall/blob/main/file.dhall as Text`

But not this one:
`https://github.com/1chb/dhall/blob/main/the%20file.dhall as Text`

Note that `%20` is changed to `%2520`. I think I understand why. When Dhall sees the `%` in the URL, which is a special token that needs to be escaped, it changes it to `%25` (hex 25 is the ASCII code for `%`).

I was thinking that maybe this is not a bug, but a feature so I don't have to escape my special tokens myself. However, it is not very usable because if I have a file: `the%file.dhall`, I can't import it like so:
```
https://github.com/1chb/dhall/blob/main/the%file.dhall as Text

Error: Invalid input

(input):1:7:
  |
1 | https://github.com/1chb/dhall/blob/main/the%file.dhall as Text
  |       ^^
unexpected "//"
expecting whitespace
```
Dhall's parser doesn't recognize a `%` without two following hex digits, but if I have a file `the%20file.dhall`, it can actually be imported with:
`https://github.com/1chb/dhall/blob/main/the%20file.dhall as Text`

But how do I import the other two?

**Comment by Gabriella439** [comment]
Yeah, so according to the language standard the Haskell implementation is non-standard-conforming.  What should have happened is that an import of the form `https://github.com/1chb/dhall/blob/main/the%20file.dhall` should have been resolved as-is without percent-encoding the `%20`.

See also:

- https://docs.dhall-lang.org/howtos/migrations/Deprecation-of-quoted-paths-in-URLs.html
- https://github.com/dhall-lang/dhall-lang/issues/581

So the fix here is to change the Haskell implementation to conform to the standard.

**Comment by Gabriella439** [comment]
The fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2505
