### ISSUE TITLE
`as Location` doesn't return `Missing`

### ISSUE THREAD

**Issue by mode89** [dhall-lang/dhall-haskell#2477]
Hi there :)

When doing the following:
```
let someLocation = "/some/missing/file" as Location
```
the value saved in `someLocation` is always `Local "/some/missing/file"`. Shouldn't it be `Missing` when the file doesn't exist?

I ran this code on `dhall` of version `1.41.1`.

**Comment by MonoidMusician** [comment]
The `Missing` value of `Location` represents the `missing` keyword, which is an import that always fails in Dhall. The `as Location` import is not meant to represent the state of your filesystem at the time you run Dhall.

**Comment by Gabriella439** [comment]
Basically, `as Location` doesn't actually perform any `IO`.  It just reifies within the language what Dhall would have resolved

**Comment by mode89** [comment]
Oh, I see. Thank you for the explanation :)
