### ISSUE TITLE
How is https://store.dhall-lang.org/ generated?

### ISSUE THREAD

**Issue by locallycompact** [dhall-lang/dhall-haskell#2492]
Hi. I can generate docs for an individual package but how is the homepage for the full package set with all versions at https://store.dhall-lang.org/ generated?

**Comment by Gabriella439** [comment]
the code for all the websites is here:

https://github.com/dhall-lang/dhall-lang/tree/master/nixops

… and the code for generating https://store.dhall-lang.org is here:

https://github.com/dhall-lang/dhall-lang/blob/master/nixops/store.nix

**Comment by locallycompact** [comment]
Thanks. I was able to put something together. https://store.horizon-haskell.net/
