### ISSUE TITLE
No documentation for accessing nested unions

### ISSUE THREAD

**Issue by scarf005** [dhall-lang/dhall-haskell#2523]
```dhall
let CD
    : Type
    = < C | D >

let Flat
    : Type
    = < A : Text | CD : < C | D > >

let a
    : Flat
    = Flat.A "A"

let c
    : Flat
    = Flat.CD CD.C

let d
    : Flat
    = Flat.CD.C
      ~~~~~~~~~ Error: Not a record or a union

let e
    : Flat
    = Flat.CD <C | D>.C

in  { a, c, d, e }
```
I'm very lost in how to access `C` inside `Flat`. I've read through [language tour](https://docs.dhall-lang.org/tutorials/Language-Tour.html#unions) and [searched documentation](https://docs.dhall-lang.org/search.html?q=union&check_keywords=yes&area=default) but none of the articles mention how to access nested union.
- https://docs.dhall-lang.org/references/Built-in-types.html?highlight=union
- https://docs.dhall-lang.org/discussions/Core-language-features.html?highlight=union
- https://docs.dhall-lang.org/howtos/Cheatsheet.html?highlight=union
- https://docs.dhall-lang.org/tutorials/Language-Tour.html?highlight=union

**Comment by Gabriella439** [comment]
There isn't a way to do what you want for expression `d`.  You have do something like you already did in expressions `c` or `e`

**Comment by scarf005** [comment]
thanks for the clarification. however, it may be hard for beginners to come up with solution `c` or `e`. therefore, i'm interested in adding examples for nested unions. should i add the guide for all of these four?

> [docs.dhall-lang.org/references/Built-in-types.html?highlight=union](https://docs.dhall-lang.org/references/Built-in-types.html?highlight=union)
    [docs.dhall-lang.org/discussions/Core-language-features.html?highlight=union](https://docs.dhall-lang.org/discussions/Core-language-features.html?highlight=union)
    [docs.dhall-lang.org/howtos/Cheatsheet.html?highlight=union](https://docs.dhall-lang.org/howtos/Cheatsheet.html?highlight=union)
    [docs.dhall-lang.org/tutorials/Language-Tour.html?highlight=union](https://docs.dhall-lang.org/tutorials/Language-Tour.html?highlight=union)

**Comment by Gabriella439** [comment]
I think it would only make sense to mention this in the language tour

**Comment by scarf005** [comment]
alright. I'll open a PR shortly after. would there be anything else i should consider?
