### ISSUE TITLE
Support request for `aeson` 2.2 in `dhall`

### ISSUE THREAD

**Issue by peterbecich** [dhall-lang/dhall-haskell#2535]
Current upper bound in `dhall.cabal` is < 2.2: https://github.com/dhall-lang/dhall-haskell/blob/main/dhall/dhall.cabal#L208

This would make it easier to build `dhall` with `aeson_2_2_0_0` on NixPkgs: https://search.nixos.org/packages?channel=unstable&show=haskellPackages.aeson_2_2_0_0&from=0&size=50&sort=relevance&type=packages&query=aeson_2

Thank you

**Comment by kukimik** [comment]
Looks like #2542 fixed this.

**Comment by Gabriella439** [comment]
Ah, good catch!  I'll go ahead and close this, then.
