### ISSUE TITLE
[Question] Update records

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#254]
What's the idiomatic way to update a record ?

I am trying to write a function of the like where the record is huger:

```
λ(conf : {repos : List Text ) → {repos = conf.repos # ["newstuff"]} 
```

**Comment by ocharles** [comment]
I think you want the "prefer" operator.

```
λ(conf : {repos : List Text, a : A, b : B, c : C, ... ) → conf // { repos = conf..repos # [ "newstuff" }
```

Is that what you mean?

**Comment by PierreR** [comment]
Oh my yes, it is. I need more coffee ;-)
Thanks
