### ISSUE TITLE
Report imports

### ISSUE THREAD

**Issue by bgohla** [dhall-lang/dhall-haskell#2575]
Is there a way for Dhall to report which files are imported?

This would be very handy when writing Makefiles.

E.g., 
```
dhall imports <<< "{ foo = ./bar.dhall, baz = ./words.txt as Text, boom = https://example.com/package/dhall }"
```
should answer with 

```
./bar.dhall
./words.txt
```

**Comment by Gabriella439** [comment]
Sorry, for the late reply, but there is a way to do this!  The `dhall resolve` subcommand has a few flags related to this and the one you're probably interested in is `--immediate-dependencies`:

```ShellSession
$ dhall resolve --immediate-dependencies <<< "{ foo = ./bar.dhall, baz = ./words.txt as Text, boom = https://example.com/package/dhall }"
./bar.dhall
./words.txt as Text
https://example.com/package/dhall
```

**Comment by bgohla** [comment]
Wow, very nice. (In hindsight, it is in the command line help, if you know where to look :shrug:)

Thanks @Gabriella439 for the reply.
