### ISSUE TITLE
Add semantic annotations to the pretty printer

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#258]
Now that `dhall-to-cabal` has `--print-type` and friends, I'd like that printing to have syntax highlighting. To do this, I need access to semantic annotations in the pretty printed `Doc`. Would you be open to have `pretty` changed in `Dhall.Core` to something Dhall-specific that returns `Doc DhallAnnotation` (name open to suggestions). `data DhallAnnotation = Keyword | Paren | Equals | Colon | Type`, or something like that.

**Comment by Gabriel439** [comment]
Yeah, definitely!

Also, in general I've been meaning to obsolete the `Builder` / `Buildable` interface to rendering Dhall values since the `prettyprinter` interface subsumes it now and is fast enough

**Comment by ocharles** [comment]
Cool. I'll get on a pull request for the former. The latter might be best in a separate branch.

**Comment by ocharles** [comment]
Semantic annotations and syntax highlighting has been added :rainbow:
