### ISSUE TITLE
LSP does not handle STextDocumentDidClose

### ISSUE THREAD

**Issue by ShrykeWindgrace** [dhall-lang/dhall-haskell#2612]
Hi!

I see the following error in vscode's window for dhall's lsp output:
```
lsp:no handler for:  STextDocumentDidClose
```
I run on windows with
```console
PS> dhall-lsp-server --version
1.1.3
PS> code --version
1.94.2
```
The plugin for vscode: "Dhall LSP Server v0.0.4"

I'll see if I can make PR with a fix.

**Comment by mmhat** [comment]
Fixed in #2613; Closing.
