### ISSUE TITLE
Make `--pretty` the default and only rendering behavior

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-haskell#284]
I've considered removing the `--pretty` option from the `dhall` executable and just always enabling pretty-printing.  Would anybody object to that?

**Comment by PierreR** [comment]
Maybe leaving an option like `--raw` to make it possible to by-pass the pretty printer when it gets annoying  ?

**Comment by Gabriel439** [comment]
Also, I might split `--no-pretty` into `--no-highlight` and `--no-format`.  `--pretty` was added before we had syntax highlighting so it might make sense to tease apart those two features now

**Comment by ocharles** [comment]
Oh, of course. I'm fine with `--no-pretty` - `--no-highlight` I think you can get by just piping through `cat`, but maybe that's a bit subtle. Doesn't hurt to have an option.

**Comment by Gabriel439** [comment]
I'm still inclined to removing the command line option altogether (i.e. always format the output and continue to do auto-detection for syntax highlighting).  The reason I'm not that concerned about always formatting the output is that it still tries to be compact wherever possible so I doubt it will ever annoy people to format the result.  For example:

```bash
$ dhall --pretty <<< 'let x = [1, 1] in let y = [x, x] in let z = [y, y] in let a = [z, z] in [a, a]'
List (List (List (List (List Integer))))

[ [ [ [ [ 1, 1 ], [ 1, 1 ] ], [ [ 1, 1 ], [ 1, 1 ] ] ]
  , [ [ [ 1, 1 ], [ 1, 1 ] ], [ [ 1, 1 ], [ 1, 1 ] ] ]
  ]
, [ [ [ [ 1, 1 ], [ 1, 1 ] ], [ [ 1, 1 ], [ 1, 1 ] ] ]
  , [ [ [ 1, 1 ], [ 1, 1 ] ], [ [ 1, 1 ], [ 1, 1 ] ] ]
  ]
]
```

I think a person would be more likely to be annoyed if we didn't format the result if it exceeded 80 columns

Also, it still does the right thing if you assign the output to a variable since it will concatenate the lines and Dhall is whitespace insensitive:

```bash
$ FOO=$(dhall --pretty <<< 'let x = [1, 1] in let y = [x, x] in let z = [y, y] in let a = [z, z] in [a, a]')
List (List (List (List (List Integer))))

$ echo $FOO
[ [ [ [ [ 1, 1 ], [ 1, 1 ] ], [ [ 1, 1 ], [ 1, 1 ] ] ] , [ [ [ 1, 1 ], [ 1, 1 ] ], [ [ 1, 1 ], [ 1, 1 ] ] ] ] , [ [ [ [ 1, 1 ], [ 1, 1 ] ], [ [ 1, 1 ], [ 1, 1 ] ] ] , [ [ [ 1, 1 ], [ 1, 1 ] ], [ [ 1, 1 ], [ 1, 1 ] ] ] ] ]
```

... so we don't really need to worry about fitting in one line for Bash scripting purposes

**Comment by PierreR** [comment]
Personally as long as there is an option to remove highlighting that's quite alright. Always formatting the output sounds like a good idea.
