### ISSUE TITLE
Scala library

### ISSUE THREAD

**Issue by missingfaktor** [dhall-lang/dhall-haskell#29]
@amarpotghan and I have decided to give this a shot. 🙂 Project URL: https://github.com/missingfaktor/dhall-scala

**Comment by Gabriel439** [comment]
Nice!  This is really exciting :)

**Comment by f-f** [comment]
@ocharles this is actually already mentioned [in dhall-lang's README](https://github.com/dhall-lang/dhall-lang#language-bindings), so I'd say we can close this
