### ISSUE TITLE
Split tests/Examples.hs out into separate A/B.dhall files

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#290]
I'm starting to implement normalization for `dhall.js`, but the normalization test folder moves pretty fast - it's either essentially `Natural/show`, and then suddenly in `remoteSystems` we have to basically have a complete normalizer. It would be helper to implementers to be able to take smaller steps - especially with `subst` and `shift`. Examples.hs seems to contain a good set of smaller normalization steps.

**Comment by ocharles** [comment]
I now see most of these use imports, so I guess that needs to be standardised first. It might also be worth moving this test information into `dhall-lang` and use a submodule (or imports! :smile: )

**Comment by Gabriel439** [comment]
Yeah, I agree these standard compliance tests belong in the `dhall-lang` projects.  I'm just trying to decide how to ensure that it doesn't get out of sync.  One possibility I've considered is turning `dhall-lang` into a mono-repo (which would also simplify maintenance of the downstream `dhall-*` projects, too)
