### ISSUE TITLE
Tutorial: Dead Link

### ISSUE THREAD

**Issue by FintanH** [dhall-lang/dhall-haskell#295]
Hey, I'm going through the tutorial, which is amazing by the way!

Unfortunately, I came across a [dead link](https://github.com/dhall-lang/dhall-haskell/blob/master/src/Dhall/Tutorial.hs#L419) at the beginning. It's this one https://ipfs.io/ipfs/QmVf6hhTCXc9y2pRvhUmLk3AZYEgjeAz5PNwjt1GBYqsVB

Thanks!

**Comment by Gabriel439** [comment]
This should be fixed now.  I have a pull request up to prevent this from recurring here: https://github.com/dhall-lang/dhall-lang/pull/102

**Comment by FintanH** [comment]
Awesome! Thanks for the quick response + fix @Gabriel439 😄

**Comment by Gabriel439** [comment]
You're welcome! :)
