### ISSUE TITLE
Question: User defined types

### ISSUE THREAD

**Issue by FintanH** [dhall-lang/dhall-haskell#297]
I'm spinning my wheels on how to implement a `NonEmpty` and starting off with defining `head` in Dhall.

My implementation is as follow:
`NonEmpty/NonEmpty`:
```
   let NonEmpty
       = \(a : Type)
      -> \(h : a)
      -> \(t : List a)
      -> { head = h, tail = t}
in NonEmpty
```

`NonEmpty/head`:
```
   let NonEmpty = ./NonEmpty
in let head : forall (a : Type) -> NonEmpty a -> a
       = \(a : Type)
      -> \(xs : NonEmpty a)
      -> xs.head
in head
```

if I try compile `NonEmpty/head` I get the following error:
```
↳ ./NonEmpty/head 

a : Type
xs : (λ(a : Type) → λ(h : a) → λ(t : List a) → { head = h, tail = t }) a

Error: Not a record

xs.head

NonEmpty/head:5:10
````

I've tried this a couple of ways but it's either `Not a record` or I can't use it in the type signature. Which I guess makes sense, because when I look at `List` it's `Type -> Type`. Which is definitely not what I have here with `NonEmpty`. Is what I'm doing possible in Dhall or am I just going about it the wrong way?

**Comment by Gabriel439** [comment]
I believe this is what you want:

```haskell
let NonEmpty = λ(a : Type) → { head : a, tail : List a }
in  NonEmpty
```

**Comment by Gabriel439** [comment]
And the matching definitions for `head` and `tail` would be:

```haskell
let head : ./NonEmpty a → a = λ(x : ./NonEmpty a) → x.head
in  head
```

```haskell
let tail : ./NonEmpty a → List a = λ(x : ./NonEmpty a) → x.tail
in  tail
```

... although they are a bit superfluous since you can use the `.head` and `.tail` field accessors directly

**Comment by FintanH** [comment]
Yes! Thank you so much! I realise it's a bit contrived but it was something that seemed simple enough that I didn't seem to know how to do :)

Expect some documentation PRs because I feel like this is something that should definitely be explore in your tutorial! 😄

**Comment by Gabriel439** [comment]
Yeah, documentation improvements are definitely welcome! :)

**Comment by FintanH** [comment]
Also for reference, I it was the following for `head` (the polymorphic type was missing):

```
let head : forall (a : Type) -> ./NonEmpty a → a = \(a : Type) -> λ(x : ./NonEmpty a) → x.head
in  head
```

P.S. I love the idea of documenting out our functional stuff better so we can rid ourselves of our documentation stigma. I have a proposal for LambdaConf around this topic so fingers crossed :) Dhall has been fun to play with and I look forward to using it more!
