### ISSUE TITLE
Error message seems wrong.

### ISSUE THREAD

**Issue by guaraqe** [dhall-lang/dhall-haskell#299]
I am using `dhall-1.9.1`, commit 7f29209ffd423bdce1bf03ea87003db8637c544a.

I am playing with fixed points, and defined lists using them. By using `dhall --explain`, I get the following error:

```dhall
You tried to invoke the following function:                                     
                                                                                
↳ Fixer                                                                
                                                                                
... which expects an argument of type or kind:                                  
                                                                                
↳ < Nil : {} | Cons : { fst : a, snd : FixI (λ(b : Type) → < Nil : {} | Cons : { fst : a, snd : b } >) } > 
                                                                                
... on the following argument:                                                  
                                                                                
↳ < Nil = {=} | Cons : { fst : a, snd : FixI (λ(b : Type) → < Nil : {} | Cons : { fst : a, snd : b } >) } > 
                                                                                
... which has a different type or kind:                                         
                                                                                
↳ < Cons : { fst : a, snd : FixI (λ(b : Type) → < Nil : {} | Cons : { fst : a, snd : b } >) } | Nil : {} > 
```

These lines seem very strange for me, as it seems that there is only a change in the order of the arguments of the union type. The code that gives such error is the following.

```dhall
-- Equivalent to Fix in Haskell
let
  Fix : (Type → Type) → Type =
    λ(f : Type → Type) →
    ∀(FixI : (Type → Type) → Type) →
    ∀(Fixer : f (FixI f) → FixI f) →
    FixI f

-- Functor that generates linked lists
in let
  LListF : Type → Type → Type =
    λ(a : Type) →
    λ(b : Type) →
    < Nil : {} | Cons : { fst : a, snd : b } >

-- Lists defined as fixed points
in let
  LList : Type → Type =
    λ(a : Type) →
    Fix (LListF a)

-- Polymorphic empty list
in let
  nil : ∀(a : Type) → LList a =
    λ(a : Type) →
    λ(FixI : (Type → Type) → Type) →
    let
      LListI = FixI (LListF a)
    in
-- Offending expression
      λ(Fixer : LListF a LListI → LListI) →
      Fixer < Nil = {=} | Cons : { fst : a, snd : LListI } >
in
  nil
```

I am unable to understand if this a problem in my code or in `dhall`.

Thanks!

**Comment by Gabriel439** [comment]
The reason why is that the type being compared has an anonymous function:

```haskell
< Cons : { fst : a, snd : FixI (λ(b : Type) → < Nil : {} | Cons : { fst : a, snd : b } >) } | Nil : {} >
                                ↑
```

... and Dhall's builtin judgmental equality does not check for equality of anonymous functions since it's undecidable in general for any type system that is a superset of System F.

**Comment by guaraqe** [comment]
Thanks for your answer!

Still, the message seem very strange for someone that reads it, since the compiler does not recognize two terms that are visibly identical as such. Is it possible to use some kind of structural equality for these situations, where type terms are compared in their internal representation, in a way that covers this case at least?

Otherwise, would it be possible to have an error message that indicates this limitation on the language? I would not be surprised if others faced the same situation.

Thank you!

**Comment by Gabriel439** [comment]
Yeah, it's possible.  The only issue here is that it requires some work to redesign the error messages so that they can explain intermediate reasons for type-checking failing.  I'll probably first wait to see if other people run into the same issue and if it's a larger problem then I'll redesign the errors

**Comment by Gabriel439** [comment]
Actually, looking at this more closely, it may be possible to do what you want.  I was just checking the standard and it does require the behavior that you requested:

https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#equivalence

Specifically, functions are supposed to count as equal if they are α-equivalent and β-equivalent, so this falls under the Haskell implementation of Dhall not matching the standard.  So I take back my previous comment and the real issue is that the Haskell implementation needs to follow the spec.

**Comment by guaraqe** [comment]
In this case, I am glad this was helpful! If there is something small where I can help just tell me.

**Comment by Gabriel439** [comment]
I have a pull request to fix this in #307.  I've also verified that the `dhall` executable on that branch handles your example correctly:

```
$ dhall
-- Equivalent to Fix in Haskell
let
  Fix : (Type → Type) → Type =
    λ(f : Type → Type) →
    ∀(FixI : (Type → Type) → Type) →
    ∀(Fixer : f (FixI f) → FixI f) →
    FixI f

-- Functor that generates linked lists
in let
  LListF : Type → Type → Type =
    λ(a : Type) →
    λ(b : Type) →
    < Nil : {} | Cons : { fst : a, snd : b } >

-- Lists defined as fixed points
in let
  LList : Type → Type =
    λ(a : Type) →
    Fix (LListF a)

-- Polymorphic empty list
in let
  nil : ∀(a : Type) → LList a =
    λ(a : Type) →
    λ(FixI : (Type → Type) → Type) →
    let
      LListI = FixI (LListF a)
    in
-- Offending expression
      λ(Fixer : LListF a LListI → LListI) →
      Fixer < Nil = {=} | Cons : { fst : a, snd : LListI } >
in
  nil
<Ctrl-D>
  ∀(a : Type)
→ ∀(FixI : (Type → Type) → Type)
→ ∀ ( Fixer
    :   < Nil :
            {}
        | Cons :
            { fst :
                a
            , snd :
                FixI (λ(b : Type) → < Nil : {} | Cons : { fst : a, snd : b } >)
            }
        >
      → FixI (λ(b : Type) → < Nil : {} | Cons : { fst : a, snd : b } >)
    )
→ FixI (λ(b : Type) → < Nil : {} | Cons : { fst : a, snd : b } >)

  λ(a : Type)
→ λ(FixI : (Type → Type) → Type)
→ λ ( Fixer
    :   < Nil :
            {}
        | Cons :
            { fst :
                a
            , snd :
                FixI (λ(b : Type) → < Nil : {} | Cons : { fst : a, snd : b } >)
            }
        >
      → FixI (λ(b : Type) → < Nil : {} | Cons : { fst : a, snd : b } >)
    )
→ Fixer
  < Nil =
      {=}
  | Cons :
      { fst :
          a
      , snd :
          FixI (λ(b : Type) → < Nil : {} | Cons : { fst : a, snd : b } >)
      }
  >
```

**Comment by guaraqe** [comment]
I just tested it here and I confirm it works well for my case. Thanks!

**Comment by Gabriel439** [comment]
You're welcome! :)
