### ISSUE TITLE
Dependency 'cryptohash' is deprecated

### ISSUE THREAD

**Issue by chris-martin** [dhall-lang/dhall-haskell#305]
[`cryptohash`](https://hackage.haskell.org/package/cryptohash) recommends not using this library anymore, and switching to `cryptonite`. Is there a particular reason dhall should be using this old package?

https://github.com/dhall-lang/dhall-haskell/blob/6b56aa5a0f8eea4189b408566b9dfc473c1a22ff/dhall.cabal#L105

**Comment by Gabriel439** [comment]
There is no good reason why Dhall is using `cryptohash` (I don't even remember why I picked it).  I'm more than happy to switch to `cryptonite`
