### ISSUE TITLE
dhall --only-imports

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#314]
What do you think about adding the ability for the `dhall` executable to only resolve imports? I was going to work on `dhall.js` now that there are lots of normalization examples, but I can't actually do that because they all use imports. I'm going to have to remove the imports from those files, and while I can write something easily that will do this, I wonder if it's a feature for `dhall`.

**Comment by Gabriel439** [comment]
Yeah, that seems reasonable.  My only suggestion is to perhaps name this flag `--resolve`

**Comment by ocharles** [comment]
Yep, didn't have a good suggestion for the name. Resolve sounds good

**Comment by sellout** [comment]
Is this fixed by #352?

**Comment by Gabriel439** [comment]
Yes.  The `dhall resolve` subcommand now does exactly this
