### ISSUE TITLE
Should type/term restrictions be loosened?

### ISSUE THREAD

**Issue by aleator** [dhall-lang/dhall-haskell#327]
Allowing records to carry fields of type `Type` allows you to write

     ((\(x:Bool) -> if x then {t=Natural} else {t=Bool}) True).t

Which is nearly equivalent to

    ((\(x:Bool) -> if x then Natural else Bool) True)

Latter is forbidden by dhall, but the first one isn't. Also, doesn't this push dhall to different edge in the lambda cube?

**Comment by Gabriel439** [comment]
Yeah, I would like to lift the requirement on `if` expressions to permit the latter expression.  That restriction on `if` expressions is just a legacy design decision.  It should be permitted for exactly the reason you've shown.

However, I want to point out that even though the former expression type-checks it does not imply support for dependent types.  For example, if you try to do this, the compiler will still reject the expression:

```
$ dhall
λ(x : Bool) → (if x then { t = Natural } else { t = Bool }).t
^D
Use "dhall --explain" for detailed errors

Error: No dependent types

λ(x : Bool) → (if x then { t = Natural } else { t = Bool }).t

(stdin):1:1
```

Note that I am considering adding back the third edge of the lambda cube (dependent types) now that the equivalence check is more robust, but that's still orthogonal to whether or not `if` expressions can return types or not.

**Comment by Gabriel439** [comment]
See https://github.com/dhall-lang/dhall-lang/pull/119 for the change to the standard to support this

**Comment by Gabriel439** [comment]
So after some more thought the conclusion I came to was actually to go in the other direction and fix the type-checking judgment for records with type-valued fields in https://github.com/dhall-lang/dhall-lang/pull/120

**Comment by aleator** [comment]
Although I'm bit sad about not being able to do semi dependent types this decision is probably better for dhall as configuration language.
