### ISSUE TITLE
Strange output for dhall --explain with errors in windows console

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-haskell#339]
Hi, i am trying dhall in windows 7 and the option `--explain` generates a weird output, in dos console and powershell:
```
C:\>echo Tru | dhall --explain


←[1;31mError←[0m: Unbound variable

Explanation: Expressions can only reference previously introduced (i.e. "bound")

variables that are still "in scope"


For example, the following valid expressions introduce a "bound" variable named
ÔØ░xÔØ▒:





    ÔöîÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÉ

    Ôöé ╬╗(x : Bool) ÔåÆ x Ôöé  Anonymous functions introduce "bound" variables

    ÔööÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÿ

        Ôçº

        This is the bound variable
....
```
Same for dhall-repl:
```
C:\>dhall-repl
⊢ Tru

←[1;31mError←[0m: Unbound variable

Tru

(interactive):1:1
```
I 've installed dhall from master (922e20e6ab1a36c99c9914ffc0e6b26e353c1e78) using stack-1.6.5
Thanks in advance

**Comment by Gabriel439** [comment]
That looks like a UTF8 encoding issue.  Could you try wrapping the `main` in `dhall/Main.hs` with `System.IO.withCP65001` (from the `code-page` library):

https://hackage.haskell.org/package/code-page-0.1.3/docs/System-IO-CodePage.html#v:withCP65001

**Comment by jneira** [comment]
Hi, i forgot the default code page for windows console is not unicode. Setting the code page to 65001 in the console itself, the program outputs is better:
```
PS C:\Users\Javier\dev\lang\eta\dhall\dhall-haskell> chcp
Página de códigos activa: 65001
PS C:\Users\Javier\dev\lang\eta\dhall\dhall-haskell> echo Tru | stack exec dhall -- --expla
in


[1;31mError[0m: Unbound variable

Explanation: Expressions can only reference previously introduced (i.e. "bound")
variables that are still "in scope"

For example, the following valid expressions introduce a "bound" variable named
❰x❱:


    ┌─────────────────┐
    │ λ(x : Bool) → x │  Anonymous functions introduce "bound" variables
    └─────────────────┘
        ⇧
        This is the bound variable


    ┌─────────────────┐
    │ let x = 1 in x  │  ❰let❱ expressions introduce "bound" variables
    └─────────────────┘
          ⇧
          This is the bound variable
...
```
* ⇧ and ❰ are not displayed correctly, i suppose the default font (Lucida Console) doesn't have the mapping for those unicode chars.
* In any case i think we can close the issue so the output is pretty close to *nix one, thanks a lot!

**Comment by jneira** [comment]
With `DejaVu Sans Mono` font ⇧ and ❰ are displayed correctly!

**Comment by tankorsmash** [comment]
![image](https://github.com/dhall-lang/dhall-haskell/assets/1312390/692a6253-f165-4e84-9fef-0e685e2bfd1d)

I get the same output on Powershell Windows 10 and dhall-1.42.0-x86_64-Windows

**Comment by tankorsmash** [comment]
Oh found an [SO](https://stackoverflow.com/a/69150127/541208) post whic fixes it:

```ps1
$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = 
New-Object System.Text.UTF8Encoding``` fixes it
