### ISSUE TITLE
Sum types produce empty backtick quoting

### ISSUE THREAD

**Issue by srid** [dhall-lang/dhall-haskell#346]
This looks like a bug to me. Dhall's `embed . inject` when applied a sum type like the following:

```
data Amount
  = Debit Scientific
  | Credit Scientific
  deriving (Generic, Show)
```

produces this:

```
amount = < Debit = { `` = 5.45 } > 
```

I don't think this right, because those backtick pairs seem to be invalid Dhall syntax. dhall-format doesn't recognize it:

```
Error: Invalid input

(stdin):1:109: error: unspecified
    error
<y = "Internet", amount = < Debit = { `` = 5.45 } > }, { transactiondate = "02>
```

I'm using dhall  at rev 7d7b8590b5ef82598bbf36e146a0c4c20e4dec04

**Comment by srid** [comment]
Looking at Dhall's union type representation, it should have produced `< Debit = 5.45 >`.

**Comment by Gabriel439** [comment]
Actually, what it should have produced was this:

```haskell
< Debit = 5.45 | Credit : Double >
```

There are three issues to address here:

*   The `Credit` alternative was missing from the union

    I'm pretty sure I've found out the cause of this and can fix it

*   The `5.45` is being wrapped in a record

    It should be just `5.45`, not a record with one field whose value is `5.45`

    I'm still looking into what caused this

*   The record has a field with the wrong name

    I believe this is might be because you are using a non-standard `constructorModifier` in the `InjectOptions` which is causing this because I get a field named `_1` when I try to reproduce this:

    ```haskell
    $ git checkout 7d7b8590b5ef82598bbf36e146a0c4c20e4dec04
    $ cabal repl lib:dhall
    >>> :set -XDeriveGeneric
    >>> :set -XDeriveAnyClass
    >>> data Amount = Debit Scientific | Credit Scientific deriving (Show, Generic, Inject, Interpret)
    >>> Dhall.Core.pretty (embed inject (Debit 5.45))
    "< Debit = { _1 = 5.45 } >"
    ```

    `_1` is the expected name of this field (although there shouldn't be a record at all if this were working correctly)

**Comment by Gabriel439** [comment]
Actually, I forgot that the expected result is actually:

```haskell
< Debit = { _1 = 5.45 } | Credit : { _1 : Double } >
```

This is because the Dhall encoding of Haskell's sum types is supposed to wrap the contents of each constructor in an obligatory record.  So there are actually only two issues here:

* The missing `Credit` alternative

* The missing `_1` field name (which I think might still be due to custom options on your end)

**Comment by Gabriel439** [comment]
The fix for the first issue is up here: https://github.com/dhall-lang/dhall-haskell/pull/348

**Comment by srid** [comment]
> I believe this is might be because you are using a non-standard constructorModifier in the InjectOptions

That sounds about right. FTR, I'm using:

```
interpretOptions :: InterpretOptions
interpretOptions = defaultInterpretOptions { fieldModifier = f }
  where
    f = TL.toLower . TL.dropWhile (not . isUpper)
```

**Comment by Gabriel439** [comment]
Yeah, that would explain why the label disappears since `isUpper` returns `False` for every character in `_1`

**Comment by srid** [comment]
> The missing _1 field name (which I think might still be due to custom options on your end)

Fixed it using:

```haskell
interpretOptions :: InterpretOptions
interpretOptions = defaultInterpretOptions { fieldModifier = f }
  where
    f "_1" = "_1"
    f x = TL.toLower . TL.dropWhile (not . isUpper) $ x
```

I'll test your PR now.

**Comment by rprije** [comment]
> Actually, I forgot that the expected result is actually:
> 
> ```haskell
> < Debit = { _1 = 5.45 } | Credit : { _1 : Double } >
> ```
> 
> This is because the Dhall encoding of Haskell's sum types is supposed to wrap the contents of each constructor in an obligatory record.

I just ran into this and found it surprising. What's the reason it needs to be wrapped in a record and is there a way to have a Haskell sum type like this work with a basic `< Debit = Double | Credit : Double >.Debit 5.45` ?

**Comment by rprije** [comment]
I just found [this comment](https://github.com/dhall-lang/dhall-haskell/issues/357#issuecomment-381152852) which offers a little more explanation and says a hand-written union instance is needed.

Is it possible to change the derived interpret instance to cater for haskell sum types that do not wrap a record?

**Comment by Gabriel439** [comment]
@rprije: Sorry for the delayed response.  Yes, I plan to change the `Generic`-derived `Inject`/`Interpret` instance to remove the superfluous record wrappers for constructors with one fields.  It will most likely be ready by version 1.27 at the current rate of progress.

**Comment by Gabriel439** [comment]
Alright, the fix to simplify one-field constructors is up here: https://github.com/dhall-lang/dhall-haskell/pull/1315
