### ISSUE TITLE
Add `dhall --type` option.

### ISSUE THREAD

**Issue by sellout** [dhall-lang/dhall-haskell#349]
In psibi/dhall-mode#7, I’ve made it possible to display the type of the file in the header line in Emacs. Currently I do
```sh
dhall --plain <<< $file 2>&1 >/dev/null
```
to capture the type, but I think that also does a bunch of other normalization work that I’m throwing away. It’d be great if it were possible to only do what’s necessary to get the type out, and to make it a bit less complicated to do so – ideally outputting the type on stdout, and the errors remaining on stderr.

**Comment by Gabriel439** [comment]
Yeah, I've been meaning to add optional sub-commands to Dhall to capture individual phases of the pipeline (i.e. `dhall type`, `dhall normalize`, `dhall resolve`, etc.).  I'll take a stab at this

**Comment by sellout** [comment]
For my own use case, I’m fine with that, as I want to basically show a one-line “sketch” of the type while editing, so avoiding resolution and normalization can often help with that.
