### ISSUE TITLE
Escaping of `${` with double-single-quotes doesn't appear to work

### ISSUE THREAD

**Issue by deepfire** [dhall-lang/dhall-haskell#356]
Following https://hackage.haskell.org/package/dhall-1.12.0/docs/Dhall-Tutorial.html#g:9, I would have expected the following to evaluate without error:

```
$ dhall
"''${A}"

Use "dhall --explain" for detailed errors

Error: Unbound variable

A

(stdin):1:6
```

**Comment by ocharles** [comment]
I wrote on IRC:

16:14 <ocharles> deepfire: that syntax is for single quoted strings, not double quoted
16:14 <ocharles> I think '''${A}' should work
16:14 <ocharles> or "\${A}"
16:14 <ocharles> see https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L133 and https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L207

**Comment by Gabriel439** [comment]
Yes, that is correct.  To escape in a double-quoted string you use `\${` instead of `''${`

**Comment by deepfire** [comment]
Thank you, @ocharles, I was indeed misreading the doc.
