### ISSUE TITLE
[Question] Interpret a Data.List.NonEmpty

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#361]
Hi,

What would be the idiomatic way to construct a record with an Haskell Data.List.NonEmpty field ?

I currently have a record with a List field and then convert manually with `fromList` but I was wondering about something a bit nicer.

Cheers,

**Comment by Gabriel439** [comment]
You can do this by adding an `Interpret` instance for `NonEmpty` that expects a Dhall value of type:

```haskell
{ head : a, tail : List a }
```

**Comment by PierreR** [comment]
I have users that aren't that technical. I don't believe I can ask them to write such a complex Dhall value for the purpose. I am currently  using a simple Dhall List.

It is more or less ok. It still a bit weird not to be able to hide the type from the user when it is hard to provide a default value for List.

I don't know how much sense it makes but it would be useful to be able to include the expected expression type at the top of a dhall configuration (something like `./type as TYPE`) and then be able to let a non-technical user to fill in the blank.

**Comment by ocharles** [comment]
I'm having a hard time following what this issue is asking for (in the last comment). @PierreR could you clarify if this issue is still important to you, and if so - what could be improved or added on Dhall's side?

**Comment by Gabriel439** [comment]
I think it's on me to close this since I was the one who reopened it :slightly_smiling_face:
