### ISSUE TITLE
Dhall.Tutorial: Linked `True` value doesn't finish loading

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#363]
This link which is referenced in `Dhall.Tutorial` never finishes loading for me: https://ipfs.io/ipfs/QmVf6hhTCXc9y2pRvhUmLk3AZYEgjeAz5PNwjt1GBYqsVB

**Comment by Gabriel439** [comment]
Try now.  The machine that mirrors that file became unresponsive and I just restarted it

**Comment by sjakobi** [comment]
Oh, it finally did finish loading now, after about half an hour.

**Comment by sjakobi** [comment]
Thanks!

**Comment by Gabriel439** [comment]
You're welcome, and thank you for reporting this!
