### ISSUE TITLE
Variable record keys

### ISSUE THREAD

**Issue by blast-hardcheese** [dhall-lang/dhall-haskell#374]
In attempting to produce desired JSON output with maximal code reuse I came across the following problem:

```
let server1 = { id = 1, name = "foo" } in
let server5 = { id = 5, name = "bar" } in
{
  ${server1.name} = server1,
  ${server5.name} = server5
}
```

This is necessary to avoid duplication, as the same `name` will need to be string interpolated into JSON-pointer-style paths (`#/servers/${server1.name}/foo`) in the target runtime (Terraform).

Reading through the parser, it doesn't seem as though this is currently a supported feature. Do you have any suggestions on where to start if I were to add this feature?

**Comment by Gabriel439** [comment]
Could you reopen this issue against the https://github.com/dhall-lang/dhall-lang/ repository?  That's for discussions about the Dhall language standard (independent of any specific implementations) whereas this repository is for issues specific to the Haskell implementation.  I have some ideas for how to do this, but I'd like to relocate the discussion there first

**Comment by blast-hardcheese** [comment]
OK, understood.

**Comment by blast-hardcheese** [comment]
https://github.com/dhall-lang/dhall-lang/issues/135
