### ISSUE TITLE
Prelude/package.dhall: Field mismatch because Monoid is a type

### ISSUE THREAD

**Issue by w3rs** [dhall-lang/dhall-haskell#378]
$ dhall --explain <<< https://ipfs.io/ipfs/QmdtKd5Q7tebdo6rXfZed4kN6DXmErRQHJ4PsNCtca9GbB/Prelude/package.dhall 

↳ https://ipfs.io/ipfs/QmdtKd5Q7tebdo6rXfZed4kN6DXmErRQHJ4PsNCtca9GbB/Prelude/package.dhall 

Error: Field mismatch

(...)
                                                                                
You provided a record with a field named:                                       
                                                                                
↳ Monoid                                                                
                                                                                
... whose value was:                                                            
                                                                                
↳ let Monoid : ∀(m : Type) → Type = λ(m : Type) → List m → m in Monoid                                                                
                                                                                
... which is a type whereas another field named:                      
                                                                                
↳ Bool                                                                
                                                                                
... whose value was:                                                            
                                                                                
↳ { ... }                                                                
                                                                                
... is a term, which does not match                                  

───────────────

{ `Bool` =
    ./Bool/package.dhall 
, `Double` =
    ./Double/package.dhall 
, `Integer` =
    ./Integer/package.dhall 
, `List` =
    ./List/package.dhall 
, Monoid =
    ./Monoid 
, `Natural` =
    ./Natural/package.dhall 
, `Optional` =
    ./Optional/package.dhall 
, `Text` =
    ./Text/package.dhall 
}

https://ipfs.io/ipfs/QmdtKd5Q7tebdo6rXfZed4kN6DXmErRQHJ4PsNCtca9GbB/Prelude/package.dhall:1:1

**Comment by w3rs** [comment]
This is with dhall 1.13.1

**Comment by Gabriel439** [comment]
Yeah, I forgot to distribute the latest version of the Prelude, which has the `Monoid` field removed for exactly this reason.  I will fix this soon (hopefully tonight)

**Comment by Gabriel439** [comment]
In the meantime you can import https://raw.githubusercontent.com/dhall-lang/dhall-haskell/master/Prelude/package.dhall which is the more recent version of the Prelude with this issue fixed

**Comment by w3rs** [comment]
Thanks. Feel free to close the issue then.
