### ISSUE TITLE
alpha normalization bug

### ISSUE THREAD

**Issue by sellout** [dhall-lang/dhall-haskell#391]
The following expression fails to normalize:
```dhall
    let Foo = λ(b : Type) → < Bar : {} | Baz : b >

in    λ(a : Type)
    → λ(f : {} → a)
    → λ(ts : Foo a)
    → merge { Bar = λ(a : {}) → f a, Baz = λ(arg : a) → arg } ts
```
It _seems_ to be because in the handlers for `merge`, `Bar` introduces a new `a` and `Baz` uses the `a` from the surrounding function. If I change either handler (e.g., `Bar = f` or `Bar = λ(z : {}) → f z`), it normalizes fine.

I first mentioned this in #362, but this includes a minimal example. For some reason, I only ran into this before when I tried normalizing import-by-import, but once I got down to this minimal case, it failed without that change as well.

The error is
```
a : Type
f : {} → a
ts : < Bar : {} | Baz : a >

Error: Handlers should have the same output type

…@- 1
  + 0

merge { Bar = λ(a : {}) → f a, Baz = λ(arg : a) → arg } ts
```

**Comment by FintanH** [comment]
So I played around with this. The issue seems to actually be the scoping of `λ(a : {})`

The following _does_ normalize:
```
    let Foo = λ(b : Type) → < Bar : {} | Baz : b >

in    λ(a : Type)
    → λ(f : {} → a)
    → λ(ts : Foo a)
    → merge { Bar = λ(x : {}) → f x, Baz = λ(arg : a) → arg } ts
```

**Comment by sellout** [comment]
Oh! I _think_, judging by this type diff,
```
…@- 1
  + 0
```
… are those numbers the De Bruijn indices? And it’s actually expecting them to be the same, rather than referring to the same variable. So, since the first case introduces a new `a`, the outer `a` has index 1, and in the second case, the outer `a` is the only one, so it has index 0. So the alpha conversion is correct, but equality checker for types is too naïve.

**Comment by sellout** [comment]
As an aside, I think it would be nice if De Bruijned vars printed in a way that made it a bit clearer what they are. I thought the output was buggy as a result of the bug – I didn’t interpret it as De Bruijns at all.

Like, if it’s possible to not rename vars to `_`, maybe it could look like
```
…@- a₁
  + a₀
```
(which I stole from your own style – I appreciate the Unicode alternative to primes!)

**Comment by FintanH** [comment]
Ya I think you're right. It seems more obvious in the error message that I see with version `1.11.1` now that you mention it:

```
The handler for the ❰Bar❱ alternative has this output type:          
                                                                                
↳ a@1                                                                
                                                                                
... but the handler for the ❰Baz❱ alternative has this output type instead:
                                                                                
↳ a   
```

**Comment by sellout** [comment]
So, I used that to shrink it a bit further:
```dhall
    let Foo = < Bar : {} | Baz : {} >

in    λ(a : Type)
    → λ(f : {} → a)
    → λ(ts : Foo)
    → merge { Bar = λ(a : {}) → f a, Baz = f } ts
```
but some interesting changes … if I change the last line so that both branches have the same variable (and supposedly the same De Bruijn indices)
```dhall
    → merge { Bar = λ(a : {}) → f a, Baz = λ(a : {}) → f a } ts
```
I get a different error
```
a : Type
f : {} → a
ts : < Bar : {} | Baz : {} >

Error: Unbound variable

λ(ts : Foo)
    → merge { Bar = λ(a : {}) → f a, Baz = λ(a : {}) → f a } ts
```
and if I change the parameter name for `Baz`,
```dhall
    → merge { Bar = λ(a : {}) → f a, Baz = λ(b : {}) → f b } ts
```
I’m back to the original error (as I’d expect).

But I’m really surprised the case where they both use the same function doesn’t work.

**Comment by Gabriel439** [comment]
This is actually due to the type-checking judgment for `merge` and the Haskell.  Actually, according to the specification your code should be rejected:

```

Γ ⊢ t :⇥ { y : ∀(x : A₀) → T₀, ts… }
Γ ⊢ u :⇥ < y : A₁ | us… >
Γ ⊢ (merge { ts… } < us… > : T₁) : T₂
A₀ ≡ A₁
T₀ ≡ T₁
────────────────────────────────────  ; `x` not free in `T₀`
Γ ⊢ (merge t u : T₁) : T₁
```

The key part is the `x not free in T₀` bit

I actually don't remember why that restriction was necessary (I'm still in the process of reverse engineering the rationale) and I'm not even sure the specification is correct.

**Comment by Gabriel439** [comment]
Also, even if the specification were correct (which is still not certain), the Haskell implementation is not fastidiously following that part (otherwise you'd be getting a better error message)

**Comment by sellout** [comment]
Ok, I’ll have to dig into this later today, but I have a feeling that the reason it wasn’t rejected before minimization is because these variables existed in different files, and it was only by introducing the intermediate `normalization` step that that expectation broke.

But I am totally speculating now. The original case involved at least a dozen different files.

**Comment by Gabriel439** [comment]
I'm pretty sure that fixing the type-checking judgment for `merge` will fix your original larger example.  The reason why is that the specification for `merge` is not respecting α-equivalence of types and normalization can rename variables at the type-level to an α-equivalent type.

**Comment by Gabriel439** [comment]
Alright, I have a dirty branch which I believe is probably the correct fix, but I still need to reason through it more carefully.  Try this:

https://github.com/dhall-lang/dhall-haskell/compare/gabriel/issue_391

**Comment by sellout** [comment]
Yep – the original and the minimal case both work now. And the “Unbound variable” error mentioned in https://github.com/dhall-lang/dhall-haskell/issues/391#issuecomment-389540683 is also gone.

💯

**Comment by Gabriel439** [comment]
Alright, here is the matching change to the standard:

https://github.com/dhall-lang/dhall-lang/pull/156

**Comment by Gabriel439** [comment]
... and here is the pull request for the matching Haskell change:

https://github.com/dhall-lang/dhall-haskell/pull/394

I'll probably wait until the standard is updated (i.e. minimum 3-day review period) before merging the Haskell implementation.  I can delay cutting the 1.14.0 release until then

**Comment by sellout** [comment]
@aleator There have been three PRs merged that address parts of this issue (although there are still improvements to be had, I think). I’d be interested in hearing if master performs much better for you now.

**Comment by Gabriel439** [comment]
Note that there will be one more change to match the standardized import system.  Currently the import system uses a breadth-first import resolution algorithm, but the standard specifies a (much simpler) depth-first import resolution algorithm.  That may or may not improve things, too
