### ISSUE TITLE
dhall-format is a bit weird with big conditionals' indentation

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-haskell#397]
[This gist](https://gist.github.com/quasicomputational/b4b16130726f82b0fbd1ed6260d44340) has large, four-level deep conditional that's been through dhall-format, and I'm not sure I like what dhall-format has done to it. I guess that the `else` being less indented than the `if` and `then` is to make long chains of else-ifs readable, but it's confusing how the `then` and `else` branches wind up differently indented and I find myself getting quite lost and having to manually count `then`s and `else`s rather than relying on indentation.

**Comment by Gabriel439** [comment]
@quasicomputational: Could you give a sketch of how you would prefer it to be formatted?

**Comment by quasicomputational** [comment]
I think aligning the `then` with the corresponding `else` works. [Here's a gist with that done manually, and I think it's a lot less confusing.](https://gist.github.com/quasicomputational/2440ade8dc7d12c1ee8dd3731d476d04) Having the `if` indented like that still looks a little weird to me, but I think I could get used to that.

**Comment by quasicomputational** [comment]
Looks good, thanks!

**Comment by Gabriel439** [comment]
You're welcome!
