### ISSUE TITLE
Bad docs for Directory

### ISSUE THREAD

**Issue by andrewthad** [dhall-lang/dhall-haskell#399]
There is currently a haddock mistake in the docs for `Directory`.

**Comment by Gabriel439** [comment]
@andrewthad: Could you expand on that?  I'm not sure what you are referring to

**Comment by andrewthad** [comment]
In the docs, this is written:

```
In other words, the directory @/foo/bar/baz@ is encoded as
```

but haddock interprets the slashes as italics.

**Comment by Gabriel439** [comment]
Fix up here: https://github.com/dhall-lang/dhall-haskell/pull/401
