### ISSUE TITLE
Values that do not map cleanly to dhall types

### ISSUE THREAD

**Issue by andrewthad** [dhall-lang/dhall-haskell#400]
In my configuration files, I often need to store things like IPv4 addresses and MAC addresses. Dhall cannot faithfully represent either of these types (not in a way that isn't extremely verbose). I'm fine with just representing things like this as text, but the dhall library doesn't provide an out-of-the-box solution for marshalling text to a more structured type. Roughly, what I'm missing is something like this:

    mapMaybeType :: (a -> Either ErrorMessage b) -> Type a -> Type b

**Comment by Gabriel439** [comment]
I think this overlaps with https://github.com/dhall-lang/dhall-haskell/issues/387

**Comment by andrewthad** [comment]
Thanks for pointing that out. This is in fact the same issue. I had tried searching through the issue tracker for things like `Word8` and `RGB` that dhall doesn't represent accurately, but I didn't find that issue. I'm closing this in favor of that one.
