### ISSUE TITLE
Relative Path Error (dhall-1.14)

### ISSUE THREAD

**Issue by FintanH** [dhall-lang/dhall-haskell#402]
**Dhall Version 1.14**

I have a reproducible error here: https://github.com/FintanH/dhall-directory-error

There seems to be an issue with relative imports when running the command line compiler. The reproducible is in the README. But can give a quick overview here.

If I run:
```bash
cd Inner/Dir2
dhall <<< "./type"
```

I get back:
```
↳ ./type 
  ↳ ./../Dir3/type 
    ↳ ./Dir1/dir1 

Error: Missing file /Users/halpenny/Developer/dhall-directory-error/Inner/Dir2/Dir1/dir1
```

Where `Dir1` is in the root directory: `dhall-directory-error`, but the resolver thinks it should be searching in the current directory.

**Comment by Gabriel439** [comment]
Fix up here: https://github.com/dhall-lang/dhall-haskell/pull/403

Note that I need to also fix the standard before merging that since this is a specification bug, but you can use that branch for now

**Comment by FintanH** [comment]
Thanks @Gabriel439 that was quick! 😁

**Comment by Gabriel439** [comment]
You're welcome!  Sorry about the bug 😊

**Comment by FintanH** [comment]
No worries, that's the excitement of working bleeding edge 😉
