### ISSUE TITLE
Add a function to parse a file

### ISSUE THREAD

**Issue by gromakovsky** [dhall-lang/dhall-haskell#408]
I couldn't find a function which takes a `FilePath` and parses it.
If I have a file which I want to parse I have two options:
1. Read the contents of this file and pass it to `input`. This is bad for the reasons described in https://github.com/dhall-lang/dhall-lang/issues/68. Specifically, if the file is `a/b` and it contains `./c`, Dhall will try to import `$PWD/c`, not `a/c` as I would expect.
2. Pass `./<PATH>` to `input`. This solves the problem above, but it's a bit inconvenient, because one has to check whether the `<PATH>` is relative and also consider `~`. Also I am not sure whether it's really the right way to do what I want.

So having a function which does (2) would be convenient and one wouldn't have to think whether it's a proper way or not.

**Comment by Gabriel439** [comment]
@gromakovsky: Yeah, this seems reasonable to me.  Do you want to add such a function?  If not, I can add it.

Also, do you intend to use this as an alternative to `Dhall.input` or an alternative to `Dhall.Parser.exprFromText`?

**Comment by gromakovsky** [comment]
@Gabriel439 sorry for not replying, I was quite busy last week.
I'd like to add such a function, but only when I have more spare time, so if you or anyone else adds it before I do it, I won't be disappointed :)
I intend to use it as an alternative to `Dhall.input`, I didn't know about `Dhall.Parser.exprFromText`.
Now that I'm aware of `exprFromText`, I suppose it makes sense to also add a version of `exprFromText` which takes a `FilePath`, doesn't it?
Also, how would you name this function? Is `inputFromFile` a reasonable name? And a version of `exprFromText` can be called `exprFromFile` I guess.

**Comment by gilligan** [comment]
@Gabriel439 i'll take a stab at this one ;-}

**Comment by Gabriel439** [comment]
I'll close this as I believe it was fixed by #512, which introduced `inputFile`
