### ISSUE TITLE
Only accepting input from stdin makes relative imports awkward

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-haskell#409]
Because most of Dhall's executables only accept input from stdin, if the top-level Dhall file being interpreted has relative imports, you have to run the command from the input file's directory or else Dhall can't find the relative imports.

This is work-around-able today by setting the directory before running Dhall's programs, but this makes interactive use at the command line quite awkward.

Dhall's executables should accept a filename and resolve imports in the top-level input file relative to that.

**Comment by quasicomputational** [comment]
Oops, further poking around the issue tracker uncovered the `dhall <<< './some/input/file'` method. I learned something new today!

Since I don't seem to be the only one who didn't know that that was possible, I think that that's definitely worth putting in a cookbook somewhere.

**Comment by Gabriel439** [comment]
@quasicomputational: I'll keep this open to remind myself to put this in the FAQ section of the Dhall wiki

**Comment by Gabriel439** [comment]
Alright, there is an FAQ section describing this common issue and work-around here: https://github.com/dhall-lang/dhall-lang/wiki/Frequently-Asked-Questions-(FAQ)#imports-relative-to-my-top-level-file-are-not-working
