### ISSUE TITLE
Still possible to create records of mixed terms and types

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-haskell#410]
It's still possible to do this, but I think it will break as soon as you try to use it by accessing a field:

```
$ dhall-repl
⊢ { foo = 1 } // { bar = Natural }

{ bar = Natural, foo = 1 }

⊢ ({ foo = 1 } // { bar = Natural }).foo

Error: Field annotation mismatch
```

This is because the `Prefer` and `Merge` cases in `Dhall.TypeCheck` do not check to see if their left- and right-hand arguments are compatible. They don't need to check the whole of both, but only need to grab a single value from each and then compare those, and then rely on the inductive assumption that there isn't a type/term amalgamation.

**Comment by Gabriel439** [comment]
Yeah, that seems like a bug to me.  I need to check to see if it's a bug in the specification or the Haskell implementation

**Comment by Gabriel439** [comment]
Yeah, this is definitely a bug in the standard like you pointed out.  I will fix the standard

**Comment by Gabriel439** [comment]
Finally got around to this.  The fix to the standard is up here: https://github.com/dhall-lang/dhall-lang/pull/209

**Comment by f-f** [comment]
@Gabriel439 sorry if the question is naïve: why should we prevent mixing values and types in records? UX-wise it's pretty useful to have.

**Comment by Gabriel439** [comment]
@f-f: See: https://github.com/dhall-lang/dhall-lang/pull/120
