### ISSUE TITLE
Unclear parsing error when using an alias as type annotation on empty List

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-haskell#414]
Afaik empty lists require a type annotation, but it seems to break on aliased types.

Example:

```haskell
   let genericRecord = List { mapKey : Text, mapValue : Text }
in ([] : genericRecord)
```

Evaluating this returns:
```
Error: Invalid input

(stdin):2:6: error: expected: expression,
    whitespace
in ([] : genericRecord)
     ^
```

While writing down the type inplace works.
(that is: `([] : List { mapKey : Text, mapValue : Text })`)

Dhall version: `1.11.1`

**Comment by ocharles** [comment]
You have to do this: 

```
   let genericRecord = { mapKey : Text, mapValue : Text }
in ([] : List genericRecord)
```

I believe.

**Comment by PierreR** [comment]
Isn't the error message a bit confusing in this case ? For a while I could not figure out the relation between the title of the issue and the issue itself ;-)
👍 to add this in the FAQ

**Comment by f-f** [comment]
Added to the [FAQ](https://github.com/dhall-lang/dhall-lang/wiki/Frequently-Asked-Questions-(FAQ)), closing.

**Comment by ocharles** [comment]
I don't think the FAQ is sufficient to close this. It's a really understandable mistake to make, and getting a parse error about whitespace is not at all enlightening. You can only resolve the error if you know the grammar. I think the error message needs to be improved and this should be re-opened.

**Comment by f-f** [comment]
> I think the error message needs to be improved and this should be re-opened.

Agreed 👍

**Comment by Gabriel439** [comment]
@ocharles @f-f: Note that improving the error message requires a change to the language standard since `: List` is part of the grammar for empty list literals, so this issue might be more appropriate for the `dhall-lang` repository
