### ISSUE TITLE
`Data` instance for `Expr Src X`

### ISSUE THREAD

**Issue by sellout** [dhall-lang/dhall-haskell#416]
At work, many of our `Interpret` instances import Dhall files for the `expected` component of the `Type`, to avoid duplicating the types and ensure that our configs stay in sync with the interpreter.

In order to avoid a runtime dependency on the location of the configs (especially remote URLs), we use TemplateHaskell to resolve all the imports at compile time. However, since there’s no `Data` instance for `Expr`, we pretty-print the resolved AST and then re-interpret it at runtime (assuming that it has type checked and has no imports).

Having a `Data` instance should help us avoid the re-serialization / reparsing steps.

If this is deemed acceptable, I’m happy to take it on myself.

As an aside, I think the TH functions we have would make a good addition to the dhall-haskell library.

**Comment by Gabriel439** [comment]
Yeah, that's totally fine with me (both adding the `Data` instance and upstreaming any Template-Haskell utilities into the `dhall `package)
