### ISSUE TITLE
dhall should not allow fields with the same name in records

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-haskell#417]
* Actually dhall let you write records with fields sharing the same name:
```
>echo { a=1, a=2 } | dhall
{ a : Natural }

{ a = 2 }
```
* Same for record types:
```
>echo { a : Natural, a : Integer } | dhall
Type

{ a : Integer }
```

**Comment by ocharles** [comment]
Pretty sure this is a bug, as https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#records-1 suggests it shouldn't even type check.

**Comment by Gabriel439** [comment]
Yep, this is definitely a bug and violation of the spec

**Comment by Gabriel439** [comment]
Note that for simplicity I will probably reject duplicates at parse time rather than type-checking time, that way I don't have to change the type of the `Record`/`RecordLit`/`Union`/`UnionLit` constructors.  If that bothers people then I can do the proper fix

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/430
