### ISSUE TITLE
Debugging large expressions

### ISSUE THREAD

**Issue by michalrus** [dhall-lang/dhall-haskell#421]
With a relatively large configuration file, when I mess up types or names (Double instead of Int etc.), I’m getting:

```
Error: Expression doesn't match annotation

./config/test.config : { [large type of the expression] }

(input):1:1
```

… but I’m not told exactly *what* I did wrong (just `(input):1:1`).

How can I debug it efficiently?

**Comment by ocharles** [comment]
What Dhall version are you running? The latest version should show concise type differences.

**Comment by michalrus** [comment]
@ocharles, 1.8.2, oh, haha, so it’s pretty ancient.

Thank you! =)
