### ISSUE TITLE
diff command

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#431]
What do you think about teaching `dhall` a `diff` command? Given two Dhall expressions it would resolve/type-check/normalise both, and then print their differences.

**Comment by Gabriel439** [comment]
@ocharles: Yeah, the code to support that is already there in the `Dhall.Diff` module, which is what powers type diffs in error messages.  The main thing missing is that the logic to diff values is missing support for diffing lists and strings because that would entail adding new dependencies.

**Comment by basile-henry** [comment]
@Gabriel439 I would be interested in tackling this issue. Am I understanding correctly that we would want the output to be something like your [nix-diff](https://github.com/Gabriel439/nix-diff) tool?

**Comment by FintanH** [comment]
Should this be closed due to #442?

**Comment by basile-henry** [comment]
@FintanH There is a second part to this issue, which is to diff list and text values better. I am working on that and will open a second PR as soon as I have something that works! :smile:

**Comment by FintanH** [comment]
Ah sorry, I missed that!

**Comment by basile-henry** [comment]
With #455 merged, I think we can close this issue. There are still a few things that could be tweaked and improved in the diff command, but nothing mentioned in this issue.
