### ISSUE TITLE
Remove use of the `Buildable` class

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-haskell#440]
Dhall used to use `Buildable` for rendering expressions and now prefers the `Pretty` class.  We should migrate off of `Buildable` to use `Pretty` exclusively to simplify the code and remove the dependency on `text-format`

**Comment by bergmark** [comment]
@Gabriel439 c87e5d9 removed text-format. I guess the intention to drop `formatting`?

**Comment by Gabriel439** [comment]
@bergmark: Oops, yes.  I meant `formatting`

**Comment by Gabriel439** [comment]
To add some extra context to this:

The `Buildable` instance for `Expr` renders an expression in compact form (i.e. one big line).  You can get the same compact 1-line representation by using the `Pretty` instance if you specify an unbounded line length.

**Comment by ocharles** [comment]
Fixed in https://github.com/dhall-lang/dhall-haskell/pull/459
