### ISSUE TITLE
Beginner friendly hints in error messages for path format 

### ISSUE THREAD

**Issue by basile-henry** [dhall-lang/dhall-haskell#445]
If I write the following by mistake:

```sh
dhall <<< "Prelude/package.dhall"
```

Instead of:

```sh
dhall <<< "./Prelude/package.dhall"
```

The error message's `--explain` section doesn't really guide a user of Dhall in the right direction; they are not using the file path format correctly.

**Comment by Gabriel439** [comment]
Fix up here: https://github.com/dhall-lang/dhall-haskell/pull/472

**Comment by basile-henry** [comment]
Great, thanks! :smile:

**Comment by Gabriel439** [comment]
You're welcome! 🙂
