### ISSUE TITLE
Expressing a range of numbers

### ISSUE THREAD

**Issue by jchia** [dhall-lang/dhall-haskell#460]
In Haskell, we can write `[0,2..10]`, but not in Dhall. Can there be a way to concisely express simple numeric ranges?

**Comment by f-f** [comment]
Yes, you can use the `enumerate` function [from Prelude](https://github.com/dhall-lang/Prelude/blob/master/Natural/enumerate)

**Comment by Gabriel439** [comment]
@jchia: Note that if you need a variation on that function (i.e. starting from a different number or a step size other than `1`) then just let us know.  We're more than happy to add new utilities to the Prelude

**Comment by jchia** [comment]
@Gabriel439 Thanks. I'll have a better idea after I get more experience. At the very least, `map` combined with `enumerate` can achieve the same effect, albeit clunkily.
