### ISSUE TITLE
import unqualified

### ISSUE THREAD

**Issue by jchia** [dhall-lang/dhall-haskell#461]
Is there a way to do 'unqualified' imports? E.g. I want to import everything from the `Prelude/List` and use ``Prelude.`List`.length`` 'unqualified' as simply `length`, or at least without mentioning `Prelude`.

Among the examples in the tutorial, I only see those that import individual functions and the one that imports all of `Prelude` after which the functions are used 'qualified'. Both ways result in verbose code.

**Comment by jchia** [comment]
The best I could come up with was something like this:
```
let list = (https://raw.githubusercontent.com/dhall-lang/Prelude/master/package.dhall).`List`
in list.all
```

It seems circuitous to grab all of `Prelude` only to zoom in on `List`.

**Comment by Gabriel439** [comment]
This sounds similar to https://github.com/dhall-lang/dhall-lang/issues/74

**Comment by Gabriel439** [comment]
I'll close this out unless there is something different here than what is proposed in https://github.com/dhall-lang/dhall-lang/issues/74
