### ISSUE TITLE
Error using file import as parameter in type annotations for empty List or Optional

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-haskell#462]
Hi, not sure if this is a bug:
```
>type example.dhall
Integer

>echo [] : List ./example.dhall | dhall-1.14.0
List Integer

[] : List Integer

>echo [] : List ./example.dhall | dhall-3c05125

 Error : Invalid input

(stdin):1:11:
  |
1 | [] : List ./example.dhall
  |           ^
unexpected "./example.dhall <newline>"
expecting '(', built-in expression, double literal, integer literal, label, list
 literal, natural literal, record type or literal, text literal, union type or l
iteral, or whitespace

>echo +1 : ./example.dhall | dhall-3c05125
Integer

+1
```
Using the file import directly as type annotation works but no for `List`, `Optional`, etc.
Tested in windows 7

**Comment by ocharles** [comment]
Looks like it might have to be `[] : List (./example.dhall)` now? Does that work?

**Comment by jneira** [comment]
@ocharles it works with parenthesis! i am afraid that `dhall-to-cabal` has [several annotations without them](https://github.com/dhall-lang/dhall-to-cabal/blob/master/dhall/defaults/Package.dhall#L4) what will have to change (i've detected this hacking with dhall-to-cabal dhall files)

In any case closing this, thanks!

**Comment by jneira** [comment]
Non empty lists work without parenthesis:
```
>echo [+1] : List ./example.dhall | dhall-3c05125
List Integer

[ +1 ]
```

**Comment by ocharles** [comment]
I'm not entirely sure if this should be closed - I'm not sure if this is intentional. Let's reopen and see what others say.

**Comment by jneira** [comment]
Maybe it is related with the changes in grammar of #413

**Comment by justinwoo** [comment]
I at least want to know what the dhall-format output is, since trailing spaces drive me nuts, and the trailing spaces for imports used to be around because import paths didn't have parens. Maybe this should always require a parens and is just missing something?

**Comment by Gabriel439** [comment]
This is a specification bug.  The specification change introduced in https://github.com/dhall-lang/dhall-lang/pull/161 caused the list type parameter to now require parentheses if it was an import.

The simple explanation is that this should probably be fixed by changing this:

https://github.com/dhall-lang/dhall-lang/blob/d72a9516451559b583cc008f8e6e0b05d05c2189/standard/dhall.abnf#L598-L600

```abnf
empty-collection = close-bracket colon (List / Optional) selector-expression

non-empty-optional = expression close-bracket colon Optional selector-expression
```

... to this:

```abnf
empty-collection = close-bracket colon (List / Optional) import-expression

non-empty-optional = expression close-bracket colon Optional import-expression
```

(and also fixing some other occurrences of `selector-expression` in the grammar to be `import-expression, too)

I'll put up the fix to the specification and the matching change to the Haskell implementation soon

**Comment by Gabriel439** [comment]
The fix to the standard is up here: https://github.com/dhall-lang/dhall-lang/pull/173

**Comment by Gabriel439** [comment]
Matching change to the Haskell implementation here: https://github.com/dhall-lang/dhall-haskell/pull/463
