### ISSUE TITLE
Parser doesn't deal correctly with leading ws in multi-line string literals

### ISSUE THREAD

**Issue by yakrar** [dhall-lang/dhall-haskell#468]
Parsing multi-line strings where the first line has leading whitespace  causes `dhall` to lose a prefix of the same length from every subsequent line. 

That is, if you put the following in a file called `testfile`:
```
let lorem_ipsum : Text =
''
                 Lorem ipsum dolor
 sit amet, consectetur
adipiscing elit sed do ..
''
in lorem_ipsum
```
and run it through `dhall`, you get broken output:
```
~$ dhall <<<  "./testfile"

Text

''
Lorem ipsum dolor
tetur
ed do ..
''
```

Dodging the import system via `dhall <<< "$(cat ./testfile)"` doesn't change the results. 

Moreover, this bug can also be triggered if the whitespace isn't followed by anything, so long as it appears immediately after the opening `''`, e.g. the following definition of `testfile`:
```
let lorem_ipsum : Text =
-- There are 10 trailing spaces on the next line
''          
Lorem ipsum dolor
 sit amet, consectetur
adipiscing elit sed do ..
''
in lorem_ipsum
```
produces similarly garbled output: 
```
~$ dhall <<<  "./testfile"

Text

''

m dolor
 consectetur
 elit sed do ..
''
```

While I've illustrated the issue using the executable, I actually encountered the bug using `exprFromText` and `load`. The above tests used the latest version of `dhall`, but I believe I first discovered this behaviour in a personal project that was using version `1.12.0`.

**Comment by Gabriel439** [comment]
Fix up in https://github.com/dhall-lang/dhall-haskell/pull/469
