### ISSUE TITLE
Question: How to recover Boehm-Berarducci encodings?

### ISSUE THREAD

**Issue by aleator** [dhall-lang/dhall-haskell#476]
Suppose I have some BB encoded dhall value, for example: 

```haskell
\(t:Type) ->
\(c: Natural -> t -> t) -> 
\(add : t -> t -> t) -> 
\(sub : t -> t -> t) ->
add  (c 5) (sub (c 3) (c 0)) : t
``` 

Is it currently possible to read these into Haskell, in any form? Functions cannot currently be injected, I think?

I was thinking of adding a special function for this purpose, but if there already is an obvious solution that I've missed I would like to hear about it.

(I think this is doable by stripping of the first parameter and manually replacing rest of the arguments with `Embed` nodes containing the appropriately wrapped Haskell functions. Then the resulting mess could be normalized with a custom rule of form `App (Embed f) x = dynApp f (rawInput (normalize x))`, resulting in an `Embed` node with the final result in it.)

**Comment by ocharles** [comment]
Here's how it's done in `dhall-to-cabal` for a similar (though bigger) type:

https://github.com/dhall-lang/dhall-to-cabal/blob/master/lib/DhallToCabal.hs#L647-L739

**Comment by ocharles** [comment]
Note, the above should actually find that `Lam` of all those arguments and then immediately apply it to free variables. There is a bug looming here, I never got round to fixing it.

**Comment by joneshf** [comment]
@ocharles trying to follow along, but the above link tracks the `master` branch and I think it has changed (it starts in the middle of one value and continues over two more that seem unrelated).

If it has changed, is this the original link: https://github.com/dhall-lang/dhall-to-cabal/blob/86189af0870e56b5b66cd837a55d02724fce273a/lib/DhallToCabal.hs#L647-L739? I think it is by the dates, but wanted to be sure.

If it hasn't changed, could you expand on what we're supposed to be seeing?

Also, I assume it maps to the `dhall/types/VersionRange.dhall` expression: https://github.com/dhall-lang/dhall-to-cabal/blob/86189af0870e56b5b66cd837a55d02724fce273a/dhall/types/VersionRange.dhall. Is that right?

**Comment by ocharles** [comment]
@joneshf That's almost right, though see https://github.com/dhall-lang/dhall-to-cabal/blob/5768ce97097c10bc3272fbc3e6cffcc513b4480a/lib/DhallToCabal.hs#L592,L699 which is the version in `HEAD` and has an important bug fix.

Essentially, the idea is to take that function, apply it to fresh variables, and then pattern match on uses of those variables.

> Also, I assume it maps to the dhall/types/VersionRange.dhall expression

Yep!

Did this help answer your question?

**Comment by joneshf** [comment]
Yes, I think so. Thanks!
