### ISSUE TITLE
add `--remove-unused` option to `dhall format`

### ISSUE THREAD

**Issue by sellout** [dhall-lang/dhall-haskell#481]
It would be nice to have `dhall format` clean up unused bindings, however, since `dhall format` is also used in editor modes, we don’t want to end up deleting not-_yet_-used bindings while editing, so it should be an explicit option.

**Comment by Gabriel439** [comment]
Would it be alright if I made this a separate `dhall lint` subcommand?  That way we could group any suggestions for automatically improving `dhall` code underneath that command

**Comment by sellout** [comment]
Yeah, that sounds even better to me.

**Comment by Gabriel439** [comment]
Pull request up here: https://github.com/dhall-lang/dhall-haskell/pull/484
