### ISSUE TITLE
Hydra marks some broken builds as successful

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-haskell#487]
While working on #473, I noticed that Hydra marks some builds as "green" here on Github, even though they did not build or passed tests.

Examples:
  - Not building but green:
    - bdeebfa ([build](https://hydra.dhall-lang.org/eval/1672218))
    - 8051981 ([build](https://hydra.dhall-lang.org/eval/1672056)
  - Builds, but tests don't pass:
    - d4dcf44 ([build](https://hydra.dhall-lang.org/eval/1672514))

I think the issue might be either that:
- the `pwd` job always passes, and it's the last one to run
- Hydra compares the build result to the previous one, and if it didn't change then it's a success
(or maybe a combination of the two)

**Comment by Gabriel439** [comment]
Yeah, I noticed the same thing, too.  The issue is that the two builds both produce the same GitHub status named `hydra` so the last one takes precedence.  I can fix it to only mark the status of builds of things beginning with the name `dhall*` so that it doesn't pick up the build named `pwd`
