### ISSUE TITLE
Should let Prelude = … in Prelude.Text.concatMap parse at the moment?

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-haskell#489]
I followed the grammar changes a bit, and thought this should be not a problem anymore:

```
let Prelude = ./Prelude.dhall in
let entriesXML = Prelude.Text.concatMapSep "\n" Entry
in
```

```
Error: Invalid input

(stdin):27:26:
   |
27 | let entriesXML = Prelude.Text.concatMapSep "\n" Entry
   |                          ^
unexpected 'T'
expecting '/'
```

Will it stay like this, or has the haskell implementation just not caught up yet?

**Comment by Profpatsch** [comment]
For reference, `./Prelude.dhall` contains the string `../Prelude/package.dhall` (which is a checkout of current master) and I’m on dhall `1.14.0`.

**Comment by Profpatsch** [comment]
Wait, I need to use `Prelude.\`Text\`.concatMapSep`? When was that introduced?

**Comment by Gabriel439** [comment]
Yes, you need to quote `Text` with backticks because it is a reserved identifier.  That was standardized since this revision:

https://github.com/dhall-lang/dhall-lang/commit/727f68e329a964b8e6580a799b20db0718ad2968#diff-08f598810aa82efee254d96a55b67fdc

**Comment by Profpatsch** [comment]
I think this should be documented explicitely, since it‘s used extensively in `Prelude`. Is the `Tutorial` module still the main source of syntax documentation apart from the ABNF?

**Comment by Gabriel439** [comment]
Yes, the tutorial module is still the main source of documentation at the moment

**Comment by Profpatsch** [comment]
PR: https://github.com/dhall-lang/dhall-haskell/pull/495
