### ISSUE TITLE
Doctests for Dhall/Tutorial.hs

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-haskell#493]
The tutorial’s doctests are not run at the moment.

I imagine the reason is that it does not fare well with dhall imports?
If it’s possible to specify the “file folder” that dhall sees somehow, the example files can be put into a folder and the doctests pointed at it.

**Comment by Gabriel439** [comment]
Fix up here: https://github.com/dhall-lang/dhall-haskell/pull/496
