### ISSUE TITLE
Could we format multi-line function calls with arguments intended?

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#515]
I really struggle to skim things like

```
          λ(key : ./AWSKey.dhall )
        → merge
          { app-production =
                λ(_ : {})
              → { key =
                    "XXX"
                , secret =
                    "YYY"
                }
          }
          key
```

If the arguments to `merge` were intended, I'd have an easier time making sense of this:

```
          λ(key : ./AWSKey.dhall )
        → merge
            { app-production =
                  λ(_ : {})
                → { key =
                      "XXX"
                  , secret =
                      "YYY"
                  }
            }
            key
```

How do others feel about this?

**Comment by Gabriel439** [comment]
Sure, I think that's fine.  The only caveat I would add is that if we do this then we should also adjust the pretty-printing logic to detect and use the number of available columns in the terminal instead of assuming 80 columns because this will conserve indentation less.

**Comment by ocharles** [comment]
> The only caveat I would add is that if we do this then we should also adjust the pretty-printing logic to detect and use the number of available columns in the terminal instead of assuming 80 columns because this will conserve indentation less.

What would you use for files?
