### ISSUE TITLE
Reversed logic in `BoolAnd` etc. cases of `isNormalized`

### ISSUE THREAD

**Issue by MonoidMusician** [dhall-lang/dhall-haskell#516]
This logic (and similar pieces) looks backwards to me:

https://github.com/dhall-lang/dhall-haskell/blob/99db7f715b1515fd9033e2e82985aa9f606be398/src/Dhall/Core.hs#L1776-L1782

This is what I would expect:
```haskell
        case x of
            BoolLit _ -> False
            _ ->
                case y of
                    BoolLit _ -> False
                    _ -> True
```
because `&&` can be normalized if one or both of its operands are literals.

**Comment by Gabriel439** [comment]
Yes, that is a bug.  I'll fix this as soon as possible
