### ISSUE TITLE
Create `man` pages for Dhall

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-haskell#537]

**Comment by Profpatsch** [comment]
What man pages are needed, apart from the documentation of the executables? I think it would be nice to have all documentation in an offline format, be it html files or manpages for e.g. the grammar, the semantics and the tutorial.

**Comment by Gabriel439** [comment]
@Profpatsch: In this case just a basic summary of the command line would be enough.  The main motivation for this was that I was working through packaging Dhall for Debian/Fedora and realized in the process that `man` pages were customary for those distros.  Also, just having the `man` pages at all improves the overall perception of polish for the project.

**Comment by Profpatsch** [comment]
> were customary for those distros

On debian, `man` pages are even required.

**Comment by vmchale** [comment]
I think [pandoc](https://pandoc.org) can generate man pages from markdown.

**Comment by Gabriel439** [comment]
I believe this was fixed by #1677
