### ISSUE TITLE
Cache imports not working in windows by default

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-haskell#549]
Hi, i've tested the [new feature of cache imports](https://github.com/dhall-lang/dhall-haskell/commit/d010464d02836025251b2d061fe93b56625daa3b) using in master version and it seems that it is not working in (at least some versions) of windows.
In Windows 7 the `HOME` environment variable used in the code is not set by default, the more similar one would be `%USERPROFILE%`. 
Setting `HOME` at system configuration level makes it work but no setting it in the dos console.

**Comment by jneira** [comment]
I am working in a pr using `System.Directory.getXdgDirectory` and `System.Directory.getHomeDirectory`.

**Comment by Profpatsch** [comment]
Iirc caching should go either into `%APPDATA%\Roaming` or `%APPDATA%\Local` on newer Windows versions.

**Comment by jneira** [comment]
Yeah, `Directory.getXdgDirectory Directory.XdgCache ""` actually uses `%LOCALAPPDATA%`(`C:\Users\user\AppData\Local`), i hope the change will keep the actual used dir in *nix envs
