### ISSUE TITLE
Nicer errors for “type synonyms”

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-haskell#55]
It’s simple to give a “scheme” to check a config file against:

```
→ echo '{foo : Integer, bar : Double}' > ./ConfigScheme
→ echo '{foo = 3, bar = 4.0} : ./ConfigScheme' | dhall
{ bar : Double, foo : Integer }

{ bar = 4.0, foo = 3 }
```

where `ConfigScheme` is provided by the creator of the config file format and the values are provided by the user.

If the user now inputs a mistyped value, dhall responds with the following error by default:

```
→ echo '{foo = 3, bar = 4} : ./MyType' | dhall

Use "dhall --explain" for detailed errors

Error: Expression doesn't match annotation

{foo = 3, bar = 4} : ./MyType

(stdin):1:1
```

I’d expect something along the lines of:
```
Error: Expression doesn't match annotation

{foo = 3, bar = 4} : ./MyType
bar is Integer
need   Double

(stdin):1:1
```

That’s interesting, because type aliases might be a nice addon? But maybe they aren’t needed since we can already use named files for that. Maybe the dhall type checker should treat files of kind `Type` as type aliases.

**Comment by Gabriel439** [comment]
It sounds like there are several questions being asked here:

*   Can Dhall provide more detail by default (without `--explain`) when there is a type mismatch?

    Yes, I can definitely do that

*   If the types differ by a single field, can Dhall just specify which field was wrong?

    It's possible, but I doubt I will implement this any time soon because it adds a lot of complexity

*   Can Dhall provide support for type synonyms?

    Probably not, for the reasons outlined here: https://github.com/Gabriel439/Haskell-Dhall-Library/issues/10

**Comment by Profpatsch** [comment]
> Yes, I can definitely do that

Yes, I tested that. It’s just that the default output is unhelpful in that case.

> It's possible, but I doubt I will implement this any time soon because it adds a lot of complexity

I was afraid that’s the case, yes.



> Probably not, for the reasons outlined here: #10

Trying to grok the answers in that thread (…processing…)

**Comment by Gabriel439** [comment]
For the first issue you raised I will implement an intermediate solution for now, which is to put the relevant information at the end of `--detail`ed error messages so that it's easier to obtain: https://github.com/Gabriel439/Haskell-Dhall-Library/pull/76

**Comment by AnthonyJacob** [comment]
2. > It's possible, but I doubt I will implement this any time soon because it adds a lot of complexity

Isn't it just simple diff? Why should it report only one field and not all?

**Comment by Gabriel439** [comment]
@AnthonyJacob: I'm referring to the complexity of computing a diff for arbitrary Dhall types (as opposed to just the diff of two record types).  For example, consider this more complex expression:

```haskell
< foo = { bar = 1, baz = 2 } | qux : Bool > : < foo : { bar : Integer, baz : Double } | qux : Bool >
```

This would give us the following error:

```
...
You or the interpreter annotated this expression:

↳ < foo = { bar = 1, baz = 2 } | qux : Bool >

... with this type or kind:

↳ < foo : { bar : Integer, baz : Double } | qux : Bool >

... but the inferred type or kind of the expression is actually:

↳ < foo : { bar : Integer, baz : Integer } | qux : Bool >
...
```

However, really the error we want is that the `baz` field had the wrong type (with a trail of breadcrumbs pointing to how to get to that field from the outermost type

Implementing a diff that supports that sort of type error is more complex to implement

**Comment by Gabriel439** [comment]
Just an update that Dhall now supports type aliases in `master`

However, I'm still keeping this open because there is still the issue of providing better error messages

**Comment by quasicomputational** [comment]
I've been playing with dhall-to-cabal, and the errors really, really aren't good with larger types. See https://gist.github.com/quasicomputational/330193aabe69abdfc1400b37f6af6670 for an example.

**Comment by Gabriel439** [comment]
@quasicomputational: See if you can build `dhall-to-cabal` against `dhall-1.13.0`.  The latest version of the `dhall` package added support for concise type diffs explaining why there is a type mismatch (this was a feature implemented specifically with `dhall-to-cabal` in mind).

See: https://github.com/dhall-lang/dhall-haskell/pull/336

**Comment by Gabriel439** [comment]
I will close this since the original issue was fixed by adding support for type synonyms and the latter issue should be fixed by `dhall`'s support for type diffs in error messages
