### ISSUE TITLE
Problem with hashed import of dhall file that uses constructors keyword

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-haskell#553]
Hi, i've tried to import the [dhall-to-cabal prelude](https://raw.githubusercontent.com/dhall-lang/dhall-to-cabal/master/dhall/prelude.dhall) with the semantic integrity check with this result:
```console
C:\dhall-haskell>type dhall-to-cabal.dhall
    let prelude =
          https://raw.githubusercontent.com/dhall-lang/dhall-to-cabal/master/dha
ll/prelude.dhall

in  prelude

C:\dhall-haskell>dhall freeze < dhall-to-cabal.dhall > dhall-to-cab
al.hashed.dhall

C:\dhall-haskell>type dhall-to-cabal.hashed.dhall
    let prelude =
          https://raw.githubusercontent.com/dhall-lang/dhall-to-cabal/master/dha
ll/prelude.dhall sha256:f3ffaa13c8f2e82121145d4602ee38861b7bacbc3427649e1e6a844e
448a7159

in  prelude

C:\dhall-haskell>dhall < dhall-to-cabal.hashed.dhall

↳ https://raw.githubusercontent.com/dhall-lang/dhall-to-cabal/master/dhall/pre
lude.dhall sha256:f3ffaa13c8f2e82121145d4602ee38861b7bacbc3427649e1e6a844e448a71
59
 Error: Import integrity check failed

Expected hash:

↳ f3ffaa13c8f2e82121145d4602ee38861b7bacbc3427649e1e6a844e448a7159

Actual hash:

↳ 7d5986b777b64d2876c9d966efa7ac755928820571bf7dbb92c817682d6d427d
```
  

- **At this point i edited the file to set the actual hash**
```console
C:\dhall-haskell>type dhall-to-cabal.hashed.dhall
    let prelude =
          https://raw.githubusercontent.com/dhall-lang/dhall-to-cabal/master/dha
ll/prelude.dhall sha256:7d5986b777b64d2876c9d966efa7ac755928820571bf7dbb92c81768
2d6d427d

in  prelude

C:\dhall-haskell>dhall < dhall-to-cabal.hashed.dhall

↳ https://raw.githubusercontent.com/dhall-lang/dhall-to-cabal/master/dhall/pre
lude.dhall sha256:7d5986b777b64d2876c9d966efa7ac755928820571bf7dbb92c817682d6d42
7d
 Error: Import integrity check failed

Expected hash:

↳ 7d5986b777b64d2876c9d966efa7ac755928820571bf7dbb92c817682d6d427d

Actual hash:

↳ f3ffaa13c8f2e82121145d4602ee38861b7bacbc3427649e1e6a844e448a7159

```
  - **At this point dhall created the cache file: https://gist.github.com/jneira/4b2167e8793e3a124b531356e2e190fa**

However, importing the [dhall prelude](https://raw.githubusercontent.com/dhall-lang/dhall-to-cabal/master/dhall/prelude.dhall) works fine:
```console
C:\dhall-haskell>type dhall.prelude.dhall
    let prelude =
          https://raw.githubusercontent.com/dhall-lang/dhall-haskell/master/Prel
ude/package.dhall

in  prelude

C:\dhall-haskell>dhall freeze < dhall.prelude.dhall > dhall.prelude
.hashed.dhall

C:\dhall-haskell>type dhall.prelude.hashed.dhall
    let prelude =
          https://raw.githubusercontent.com/dhall-lang/dhall-haskell/master/Prel
ude/package.dhall sha256:c408c35d66d6ad7cfa275df3f1ee8e83c960d80015c75b1abdd298b
9886e37a9

C:\dhall-haskell>dhall < dhall.prelude.hashed.dhall
{ `Bool` =
    { and =
          λ(_ : List Bool)
        → List/fold Bool _ Bool (λ(_ : Bool) → λ(_ : Bool) → _@1 && _) True
    , build =
        λ(_ : Type → _ → _@1 → _@2) → _ Bool True False
...
```
Tested in windows with dhall master version

**Comment by Profpatsch** [comment]
cc @ocharles as well.

**Comment by ocharles** [comment]
CC received, but I watch all these repositories anyway :laughing: @jneira It might be worth taking the `dhall-to-cabal` prelude and making it simpler and simpler until `freeze` works - it might give an indication of what expression causes the problem.

**Comment by jneira** [comment]
As maybe it was expected, using the expanded equivalent of `constructors` (i hope it is correct!) works:
```console
C:\dhall-haskell>type cons.man.dhall
   let T = < A : {} | B : {} >
in let TCS =
   { A: forall(A:{}) -> T
   , B: forall(B:{}) -> T
   }
in let cs =
   { A = \(A : {}) -> < A = A | B : {} >
   , B = \(B : {}) -> < A : {} | B = B >
   } : TCS
in cs

C:\dhall-haskell>type usecons.dhall
let m = ./cons.man.dhall  in m.A {=}

C:\dhall-haskell>dhall freeze < usecons.dhall > usecons.hashed.dhal
l && dhall --explain < usecons.hashed.dhall
< A = {=} | B : {} >
```

**Comment by Gabriel439** [comment]
From manually decoding the two versions it looks like the difference is that  `2324a5352105b6835db60b127c7096c5d5b81027969ccd368d163edc5d9692e0` is the α-normalized version and `e95ca6fcece107ac7b316ea181ff641e79dfb1682b065df4acde9d9a3671cda7` has not been α-normalized.

I'm now looking into why.

**Comment by Gabriel439** [comment]
I found the problem.  The root cause is that α-normalization and β-normalization do not commute.  This is because β-normalizing a `constructors` expression introduces new bound variables in the generated record, so you need to α-normalize after β-normalizing to ensure that the newly-introduced bound variables get properly α-normalized.

This is bug in the Haskell implementation but not a bug in the standard.  The standard correctly specifies that α-normalization has to come after β-normalization when computing the semantic integrity check, but the Haskell implementation wasn't following the standard and had them in the wrong order.

In fact, I even had a highly relevant comment in my pull request standardizing the semantic integrity check:

https://github.com/dhall-lang/dhall-lang/commit/6a3f5047a9234742ef90b9051e9ae7168c463c2c#diff-f115f64c1525bde8d052ea6248598332

> * Reorder β-normalization and α-normalization
> 
> This is to match the equivalence judgment
> 
> They *probably* commute, but it's probably safer to
> consistently apply α-normalization as the latter step

Turns out that they did not in fact commute and it was in fact safer to consistently apply α-normalization as the latter stap

**Comment by Gabriel439** [comment]
I will put up a pull request later today.  The fix is easy and I've already hand verified that it works but I just need some time to codify the regression test

**Comment by jneira** [comment]
@Gabriel439 That was a really quick fix! I've tested both cases (simple constructors and full dhall-to-cabal prelude) and they work fine.
