### ISSUE TITLE
Is there a wildcard for pattern matching?

### ISSUE THREAD

**Issue by w3rs** [dhall-lang/dhall-haskell#574]
I'd like to be able to do something like this:
```
merge
  { x = λ(_ : {}) → 1
  , _ = λ(_ : {}) → 2
  } < x : {} | y = {=} | z : {} >
```
I guess currently I have to list all possible cases, correct?

**Comment by Gabriel439** [comment]
Related comments:

* https://github.com/dhall-lang/dhall-lang/issues/164#issuecomment-395400874
* https://github.com/dhall-lang/dhall-lang/issues/169#issuecomment-396079351

Yes, you currently have to specify all possible cases.  In the above comments a `wildcard` keyword was suggested to turn a handler into a record of handlers that you could selectively override.

The only reason I haven't made a decision on this feature is because I'm still looking to see intended use cases for this feature to see if there are alternative solutions for the same problem.

Without knowing anything about the specific use case, I'm slightly reticent to add it since wildcard pattern matches are a common source of bugs when refactoring Haskell code.

**Comment by Gabriel439** [comment]
@w3rs: Could you go into more detail about how you would use union equality?  Specifically, I'm interested in the use case where you only want to check for a match against one alternative.

The main reason I haven't added list comprehensions yet is that I'd like to do it in such a way that it can support `do` notation more generally (so that you could also have `Optional` comprehensions).  I have some ideas for how to do that, but none that I've proposed yet.

For the third use case you mentioned, that exists in the form of the `constructors` keyword:

```haskell
    let T = < x : {} | y : {} | z : {} >

in  let t = constructors T

in  [ t.x {=}, t.y {=}, t.z {=} ]
```

The only difference from what you proposed is that you need to apply the constructor to the alternative it expects (`{=}` for each constructor in the above example)

**Comment by w3rs** [comment]
> use case where you only want to check for a match against one alternative.

It's in the end of my snippet. I used `(==)`, but those can be replaced with `isTest` and similar predicates.
```haskell
let    Frequency = < Daily : {} | Hourly : {} | Minutely : {} >
in let Source = < Twitter : {} | Reddit : {} | HackerNews : {} >
in let Target =
  < Download : {}   -- get a copy of data from S3 or HDFS,
  | Test : {}       -- check data integrity
  | Stats : {} -- generate some statistics
  >
in let Frq = constructors Frequency
in let Src = constructors Source
in let Tgt = constructors Target

in let Task = { tgt : Target, frq : Frequency, src : Source }

-- This is not really necessary for this example... just adding it for the context
-- Return list of task dependencies
in let taskDepends = λ(task : Task) → merge
  { Download = λ(_:{}) → [] : List Task            -- Download doesn't depend on anything
  , Test = λ(_:{}) → [task // {tgt = Tgt.Download {=}}]   -- Must download before testing
  , Stats = λ(_:{}) → [task // {tgt = Tgt.Test {=}}]      -- Must test before doing stats
  } task.tgt

-- We have a function of type `Target → [Task]` upstream
-- (just a cartesian product likely).
-- Here we want to add a restrictions because we don't want all the combinations.
-- We'll do `filter (not . uselessTask)` upstream:

in let uselessTask = λ(task : Task) →
  task.tgt == Tgt.Test {=} && task.frq == Fqr.Minutely {=} || -- Don't test Minutely
  task.tgt == Tgt.Stats {=} && task.src == Src.Twitter {=}    -- Don't generate stats for Twitter

in { uselessTask = uselessTask, taskDepends = taskDepends }
```

Without `(==)`, I could define `isX` family, e.g.:
```haskell
let isTest = λ (tgt: Target) → merge
  { Test = λ(_:{}) → True
  , _ = False
  } tgt
```

**Comment by Gabriel439** [comment]
@w3rs: One way to do this without making any changes to the language would be restructure the `Task` type to make useless tasks unrepresentable:

```haskell
    let Task =
          < Download :
              { source :
                  < Twitter : {} | Reddit : {} | HackerNews : {} >
              , frequency :
                  < Daily : {} | Hourly : {} | Minutely : {} >
              }
          | Test :
              { source :
                  < Twitter : {} | Reddit : {} | HackerNews : {} >
              , frequency :
                  < Daily : {} | Hourly : {} > -- Don't run tests minutely
              }
          | Stats :
              { source :
                  < Reddit : {} | HackerNews : {} >  -- No stats for Twitter
              , frequency :
                  < Daily : {} | Hourly : {} | Minutely : {} >
              }
          >

in  Task
```

That won't necessarily scale in the more general case, but my inclination here is that we should be pushing runtime validation failures into type-checking failures, improving Dhall's type system if necessary.

**Comment by sellout** [comment]
> The main reason I haven't added list comprehensions yet is that I'd like to do it in such a way that it can support do notation more generally (so that you could also have Optional comprehensions). I have some ideas for how to do that, but none that I've proposed yet.

Re: this point in particular – I would love something that didn’t bake too much into the language about what a “monad” is, etc. E.g., with #563, FormationAI/dhall-bhat will have a poly-kinded `./Monad` class. The minimal thing I can think of to enable `do`-like support would be some primitive that would somehow make it possible to implement “Traversable” for records. Then a file like
```dhall
-> \(m : Type -> Type)
-> \(a : Type) -- except records are heterogeneous, which is the complication here
-> \(monad : ./Monad m)
-> \(source : Record (m a))
-> \(result : Record a -> m b)
-> monad.bind result ((./Record/traversable).sequence source)
```
Then,
```dhall
./do
Optional
_ -- underscore because again, Record is heterogeneous
./Optional/monad
{ x = someValue
, y = noneValue
}
(\(r : { x : Natural, y : List Text }) -> List/at x y)
```
but … that isn’t exactly terse. I haven’t thought through this, just a rough sketch.

**Comment by Gabriel439** [comment]
@sellout: The way I did this in `annah` was that `do` notation built up a free monad and then a `Monad` was defined as:

```haskell
    let Monad = λ(m : Type → m) → ∀(a : Type) → Free m a → m a

in  Monad
```

This parallels the way that `Monoid` is defined in the Prelude:

```haskell
    let Monoid : ∀(m : Type) → Type = λ(m : Type) → List m → m

in Monoid
```

In other words, if a `Monoid` is defined as a fold of the free monoid, then a `Monad` is defined as a fold of the free monad

So, for example, if you wrote something like:

```haskell
-- foo :: F A
-- bar :: A -> F B
-- baz :: B -> F C
example = do
    x <- foo
    y <- bar x
    baz y
```

... then `example` would have type `Free F C` and then if you had a value `./F/squash : ./Monad F` then you could use that to obtain a value of type `F C`, like this:

```haskell
./F/squash C (do
    x <- foo
    y <- bar x
    baz y ) : F C
```

Another neat thing about this way of doing things is that you get language support for free monads (analogous to language support for lists)

For more details, see: http://hackage.haskell.org/package/annah-1.0.0/docs/Annah-Tutorial.html#g:12
