### ISSUE TITLE
Performance issues with many deeply nested imports

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-haskell#580]
One of the examples in the `dhall-kubernetes` repo ([this one](https://github.com/dhall-lang/dhall-kubernetes/blob/import-hash-bug/examples/deployment.dhall) - if you'd like to test it note that it's on a separate branch) takes roughtly 25s to evaluate on my machine.  
It is not a big deal for me, but after showing it in [the talk's demo](https://twitter.com/fabferrai/status/1040523416112128000) the other day the single most common question I got afterwards was "why does it take so long?" (N = ~20 people)

I think (I did not profile the thing actually, I'll do it asap) the problem comes from the fact that the Kubernetes types and defaults are nesting many imports (e.g. try to evaluate the [Deployment type](https://github.com/dhall-lang/dhall-kubernetes/blob/master/types/io.k8s.api.apps.v1.Deployment.dhall), it's quite huge), and Dhall will typecheck and normalize the imported expression before substituting it in the AST of the current expression (that then will be typechecked and normalized again, and so on for all the levels of nesting).

This work is done because [we are caching the imports in memory](https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#duplicate-imports) (so we have to typecheck and normalize every import to possibly reuse it), but I wonder if we could skip some of this work (e.g. by resolving all nested imports first, then composing everything together, and then typechecking and normalizing the now-pure expression)

**Comment by quasicomputational** [comment]
Minimising the re-typechecking/normalising we do is a very worthy goal. This might also help `dhall-to-cabal` significantly.

**Comment by sellout** [comment]
This may be my fault. I made a couple changes a number of months ago that
1. cached imports more reliably and
2. pre-normalized an import when caching.

At the time, for my use cases, pre-normalizing sped things up like 10×. I don’t recall exactly where the benefit came from – perhaps just pre-resolving would give us the same benefit? Or maybe it’s just different styles of import patterns (but I feel like deeply-nested repeated imports was exactly our problem case).

I wonder if something like an annotation indicating that a sub-tree has already been normalized would eliminate the cost of re-traversing?

**Comment by Gabriel439** [comment]
@f-f: Have you tested what performance you get when you don't prenormalize imported expressions?

Really, the only optimal solution is to implement something like Lamping's algorithm.  Anything short of that will always have the issue of either (A) duplicating work due to substituting expressions that haven't been normalized yet or (B) doing more work than necessary by normalizing unused sub-expressions.

However, I want to firsty verify that the initial diagnosis of repeated re-normalization is the performance bottleneck.

The reason that other languages don't have this problem is that they do ahead-of-time downloading and code-generation of their dependencies (i.e. installing and building a package), which is analogous to `dhall freeze`, Dhall is technically no worse than those languages if you freeze your imports.  However, I'd still like Dhall to be able to efficiently work without freezing.

**Comment by f-f** [comment]
@Gabriel439 
With the latest master a funny thing happens: I `time` the execution and bash says that only 7 seconds were spent on program execution, while the "actual" time passed is 23s

```bash
$ time dhall <<< "./examples/deployment.dhall"  
...
6.81s user 0.22s system 30% cpu 23.136 total
```

But if I run it again the execution time is also the real time:
```bash
$ time dhall <<< "./examples/deployment.dhall"
...
6.85s user 0.19s system 91% cpu 7.682 total
```

With 1.17 the "real time" was consistently 25s (I guess I should bisect when this "fix" happened, but it's a good change so I skipped this part).
I tried not typechecking&normalizing imports, but the running time is still 7s, so my first guess about where the bottleneck was wrong.

**Question n.1:** why does the first execution now take 3x the time of the subsequent executions? 🤔 

I don't know. But 7s is still a lot, s I went on and profiled the thing:

```
        Sun Sep 16 23:31 2018 Time and Allocation Profiling Report  (Final)

           dhall +RTS -p -RTS

        total time  =       32.56 secs   (32564 ticks @ 1000 us, 1 processor)
        total alloc = 23,405,551,360 bytes  (excludes profiling overheads)

COST CENTRE            MODULE                     SRC                                                 %time %alloc

>>=                    Dhall.Parser.Combinators   src/Dhall/Parser/Combinators.hs:54:9-13              36.9   12.0
getParserState         Dhall.Parser.Combinators   src/Dhall/Parser/Combinators.hs:57:9-45               9.9   15.2
==                     Text.Megaparsec.Pos        Text/Megaparsec/Pos.hs:131:27-28                      7.2    0.9
return                 Text.Megaparsec.Internal   Text/Megaparsec/Internal.hs:200:3-15                  6.8    5.1
<|>                    Text.Megaparsec.Internal   Text/Megaparsec/Internal.hs:195:3-16                  6.7   10.7
tokens                 Dhall.Parser.Combinators   src/Dhall/Parser/Combinators.hs:57:9-45               5.7    5.6
takeN_                 Text.Megaparsec.Stream     Text/Megaparsec/Stream.hs:(263,3)-(266,38)            2.9    9.7
label                  Dhall.Parser.Combinators   src/Dhall/Parser/Combinators.hs:57:9-45               2.2    3.8
mplus                  Dhall.Parser.Combinators   src/Dhall/Parser/Combinators.hs:56:9-17               1.7    2.6
<>                     Text.Megaparsec.Error      Text/Megaparsec/Error.hs:152:3-19                     1.4    3.1
reachOffsetNoLine      Text.Megaparsec.Stream     Text/Megaparsec/Stream.hs:(272,3)-(273,60)            1.3    5.4
updateParserState      Dhall.Parser.Combinators   src/Dhall/Parser/Combinators.hs:57:9-45               1.3    2.1
noted                  Dhall.Parser.Expression    src/Dhall/Parser/Expression.hs:(31,1)-(38,58)         1.2    1.7
match                  Text.Megaparsec            Text/Megaparsec.hs:(443,1)-(453,50)                   1.1    2.2
makeOperatorExpression Dhall.Parser.Expression    src/Dhall/Parser/Expression.hs:(169,1)-(173,40)       0.9    1.3
token                  Dhall.Parser.Combinators   src/Dhall/Parser/Combinators.hs:57:9-45               0.8    1.1
take1_                 Text.Megaparsec.Stream     Text/Megaparsec/Stream.hs:262:3-19                    0.6    2.2
fmap                   Data.HashMap.Strict.InsOrd src/Data/HashMap/Strict/InsOrd.hs:155:15-21           0.5    1.2
toList                 Data.HashMap.Strict.InsOrd src/Data/HashMap/Strict/InsOrd.hs:(580,1)-(584,22)    0.5    1.3
```

**Question n.2**: Could it be that the parser is *such* a bottleneck? 🤔

**Comment by Gabriel439** [comment]
@f-f: Yes, it is absolutely possible that the parser is such a bottleneck.  It's way slower than it should be.  For reference, the pathological example in #108 still takes on the order of 50 microseconds per character parsed, which is very slow

**Comment by f-f** [comment]
Update: I went a bit more into the rabbit hole.
@phadej suggested me to implement the `Monad` instance by hand for our `Parser`, to inline `>>=` (which according to the profiling is eating 36% of the execution time).

So I did that, and that *does* work: on the profiled version the execution time goes from `32s` to `23s`.
However, the non-profiled version is not affected, and the exec time stays at `6.8s`.
So the profiling is lying to me, as usual 🤔 (GHC probably optimizes everything away if there are no profile hooks at function entries)

And in general I have the feeling the profiler would like to have all of the derived instances inlined to match the performance of the non-profiled version, after which it would start being useful. But it's a lot of work and not guaranteed to pay off, so I'm searching for a smarter way to figure out.

I'm now trying different profiling flags to see if I hit the magic combination, but if any of you has any ideas I'd love to try them out 😄

**Comment by f-f** [comment]
Memory profiling:

```
  18,088,060,536 bytes allocated in the heap
   1,407,326,864 bytes copied during GC
      12,063,680 bytes maximum residency (48 sample(s))
         111,568 bytes maximum slop
              35 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     17852 colls,     0 par    1.469s   1.497s     0.0001s    0.0005s
  Gen  1        48 colls,     0 par    0.306s   0.321s     0.0067s    0.0141s

  INIT    time    0.000s  (  0.002s elapsed)
  MUT     time    5.102s  (  5.832s elapsed)
  GC      time    1.774s  (  1.818s elapsed)
  EXIT    time    0.000s  (  0.002s elapsed)
  Total   time    6.877s  (  7.654s elapsed)

  %GC     time      25.8%  (23.8% elapsed)

  Alloc rate    3,545,047,119 bytes per MUT second

  Productivity  74.2% of total user, 76.2% of total elapsed
```

Nothing particularly interesting from these graphs (memory usage is constant, all good), except one notable aspect: parsing seems to be done around second `3.0`, and from there the program works with the objects it has.
This seems to again point the bottleneck at whatever happens after parsing:
 
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/5480361/45706352-b6197900-bb84-11e8-9f64-6c1db0ddbe3c.png">

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/5480361/45706460-00025f00-bb85-11e8-858c-5899a3f5d7a7.png">

**Comment by Gabriel439** [comment]
@f-f: There is a very easy way to verify by just using `dhall format` (which only does parsing and pretty-printing).  If parsing is not the bottleneck then it should be much faster.

Similarly, you can do `dhall resolve` to do only parsing and import resolution

**Comment by Gabriel439** [comment]
@f-f: However, from looking at that heap profile map my intuition is that this block of code is responsible for the performance slowdown:

https://github.com/dhall-lang/dhall-haskell/blob/d8e076c6da232267d0a2bb611cde124cc912c4f7/src/Dhall/Parser/Expression.hs#L160-L221

It's having to traverse all of those function calls every time it parses a token, plus `makeOperatorExpression` might be implemented inefficiently

**Comment by Gabriel439** [comment]
Also, `noted` is responsible for a significant chunk of the running time, but I have a work-in-progress pull request to fix that (for real this time), which should approximately double throughput

**Comment by f-f** [comment]
After the latest parser optimizations from @phadej and @Gabriel439 we're down to somewhere around 6 secs (~25% improvement!), which is awesome:
```
5.31s user 0.17s system 89% cpu 6.117 total
``` 
Calling `dhall format` here doesn't help, since most of the stuff happens in imports (runs in no time).  
Calling `dhall resolve` instead leads to a more interesting result:
```
5.33s user 0.17s system 87% cpu 6.273 total
```
But I guess even this doesn't really help, since `resolve` calls `loadWith`, which runs normalization and typechecking on imports.

---

Small note: my test file has an http-import, but making it local doesn't change the effective running time, only helps a bit in maximizing CPU-time. This is `dhall resolve` with all imports being local:
```
5.31s user 0.11s system 98% cpu 5.509 total
```

**Comment by jneira** [comment]
In case it can be useful, this is the profiles of a dhall-to-cabal file after the parsing improvements of #606:
* `dhall +RTS -p < dhall-to-cabal.dhall`
```
	total time  =       50.91 secs   (50907 ticks @ 1000 us, 1 processor)
	total alloc = 67,241,874,632 bytes  (excludes profiling overheads)

COST CENTRE            MODULE                     SRC                                                 %time %alloc

toList                 Data.HashMap.Strict.InsOrd src\Data\HashMap\Strict\InsOrd.hs:(580,1)-(584,22)   19.9   28.4
unsafeInsert.go        Data.HashMap.Base          Data\HashMap\Base.hs:(531,5)-(558,76)                13.4   12.6
fmap                   Data.HashMap.Strict.InsOrd src\Data\HashMap\Strict\InsOrd.hs:155:15-21          12.1   13.3
typeWithA.loop         Dhall.TypeCheck            src\Dhall\TypeCheck.hs:(99,5)-(795,49)                8.2    1.5
toHashMap              Data.HashMap.Strict.InsOrd src\Data\HashMap\Strict\InsOrd.hs:599:1-44            4.7    5.9
copy.\                 Data.HashMap.Array         Data\HashMap\Array.hs:(247,9)-(248,30)                4.2    7.1
sortMap                Dhall.Core                 src\Dhall\Core.hs:(1400,1)-(1403,39)                  4.0    5.3
exprFromUncachedImport Dhall.Import               src\Dhall\Import.hs:(580,1)-(673,45)                  3.9    0.1
>>=                    Dhall.Parser.Combinators   src\Dhall\Parser\Combinators.hs:95:5-48               2.4    0.4
new_                   Data.HashMap.Array         Data\HashMap\Array.hs:177:1-28                        2.2    3.6
_2                     Control.Lens.Tuple         src\Control\Lens\Tuple.hs:227:3-37                    2.0    1.1
getPV                  Data.HashMap.Strict.InsOrd src\Data\HashMap\Strict\InsOrd.hs:129:1-17            1.8    0.0
normalizeWith.loop     Dhall.Core                 src\Dhall\Core.hs:(1423,2)-(1774,22)                  1.4    1.8
fmap                   Data.HashMap.Strict.InsOrd src\Data\HashMap\Strict\InsOrd.hs:122:15-21           1.2    1.2
fromList               Data.HashMap.Strict        Data\HashMap\Strict.hs:438:1-64                       1.2    0.8
newP.\                 Data.HashMap.Strict.InsOrd src\Data\HashMap\Strict\InsOrd.hs:626:24-37           1.1    0.9
fromList               Data.HashMap.Strict.InsOrd src\Data\HashMap\Strict\InsOrd.hs:(571,1)-(577,52)    1.0    1.8
normalize              Dhall.Core                 src\Dhall\Core.hs:1307:1-41                           0.9    1.4
normalizeWith          Dhall.Core                 src\Dhall\Core.hs:(1421,1)-(1774,22)                  0.7    1.6
fmap                   Dhall.Context              src\Dhall\Context.hs:32:15-21                         0.6    2.2
newP                   Data.HashMap.Strict.InsOrd src\Data\HashMap\Strict\InsOrd.hs:626:1-37            0.6    1.8
```
* `dhall resolve +RTS -p < dhall-to-cabal.dhall`
```
	total time  =        7.17 secs   (7174 ticks @ 1000 us, 1 processor)
	total alloc = 9,297,147,760 bytes  (excludes profiling overheads)

COST CENTRE             MODULE                                             SRC                                                                          %time %alloc

>>=                     Dhall.Parser.Combinators                           src\Dhall\Parser\Combinators.hs:95:5-48                                       15.3    2.9
toList                  Data.HashMap.Strict.InsOrd                         src\Data\HashMap\Strict\InsOrd.hs:(580,1)-(584,22)                             6.4   10.2
renderIO.go.\           Data.Text.Prettyprint.Doc.Render.Terminal.Internal src\Data\Text\Prettyprint\Doc\Render\Terminal\Internal.hs:(191,29)-(194,23)    6.4   10.9
typeWithA.loop          Dhall.TypeCheck                                    src\Dhall\TypeCheck.hs:(99,5)-(795,49)                                         5.8    1.6
fmap                    Data.HashMap.Strict.InsOrd                         src\Data\HashMap\Strict\InsOrd.hs:155:15-21                                    4.6    5.5
exprFromUncachedImport  Dhall.Import                                       src\Dhall\Import.hs:(580,1)-(673,45)                                           3.7    0.5
toHashMap               Data.HashMap.Strict.InsOrd                         src\Data\HashMap\Strict\InsOrd.hs:599:1-44                                     3.7    4.5
layoutWadlerLeijen.best Data.Text.Prettyprint.Doc.Internal                 src\Data\Text\Prettyprint\Doc\Internal.hs:(1707,5)-(1724,76)                   3.4    5.8
<|>                     Text.Megaparsec.Internal                           Text\Megaparsec\Internal.hs:195:3-16                                           3.1    2.5
renderIO.go.\           Data.Text.Prettyprint.Doc.Render.Terminal.Internal src\Data\Text\Prettyprint\Doc\Render\Terminal\Internal.hs:(185,29)-(187,23)    2.9    6.2
renderIO.go.\           Data.Text.Prettyprint.Doc.Render.Terminal.Internal src\Data\Text\Prettyprint\Doc\Render\Terminal\Internal.hs:(188,31)-(190,23)    2.7    4.2
unsafeInsert.go         Data.HashMap.Base                                  Data\HashMap\Base.hs:(531,5)-(558,76)                                          2.5    2.2
pure                    Dhall.Parser.Combinators                           src\Dhall\Parser\Combinators.hs:76:5-24                                        1.7    0.9
shift                   Dhall.Core                                         src\Dhall\Core.hs:(693,1)-(855,29)                                             1.6    2.0
fmap                    Dhall.Context                                      src\Dhall\Context.hs:32:15-21                                                  1.4    5.9
getParserState          Dhall.Parser.Combinators                           src\Dhall\Parser\Combinators.hs:156:5-58                                       1.3    0.8
unAnnotateS.go          Data.Text.Prettyprint.Doc.Internal                 src\Data\Text\Prettyprint\Doc\Internal.hs:(1259,5)-(1266,37)                   1.2    1.0
fmap                    Dhall.Parser.Combinators                           src\Dhall\Parser\Combinators.hs:69:5-41                                        1.2    1.3
normalize               Dhall.Core                                         src\Dhall\Core.hs:1307:1-41                                                    1.2    1.7
tokens                  Dhall.Parser.Combinators                           src\Dhall\Parser\Combinators.hs:148:5-54                                       1.1    1.1
copy.\                  Data.HashMap.Array                                 Data\HashMap\Array.hs:(247,9)-(248,30)                                         0.9    1.4
label                   Dhall.Parser.Combinators                           src\Dhall\Parser\Combinators.hs:130:5-59                                       0.9    1.3
normalizeWith           Dhall.Core                                         src\Dhall\Core.hs:(1421,1)-(1774,22)                                           0.9    2.1
new_                    Data.HashMap.Array                                 Data\HashMap\Array.hs:177:1-28                                                 0.8    1.4
fmap                    Data.HashMap.Strict.InsOrd                         src\Data\HashMap\Strict\InsOrd.hs:(435,5)-(436,58)                             0.7    1.1
```
* `dhall format +RTS -p < dhall-to-cabal.dhall`: similar profile to `dhall resolve` but
```
	total time  =        0.07 secs   (73 ticks @ 1000 us, 1 processor)
	total alloc =  51,568,528 bytes  (excludes profiling overheads)
```

**Comment by f-f** [comment]
Fixed in #606

**Comment by Profpatsch** [comment]
> I am afraid that dhall-to-cabal files have not improve with the latest performance gains of #606:

So not really fixed? cc @f-f

**Comment by jneira** [comment]
@Profpatsch my bad, the comment should be in #598 (or elsewhere) and not here

**Comment by f-f** [comment]
@Profpatsch as I mentioned in https://github.com/dhall-lang/dhall-haskell/pull/606#issuecomment-425192979 the problematic expression from this issue now runs in ~1s (8-10x improvement on the original running time), as the parsing was the real bottleneck here

I think #412 is the issue which is most relevant to the (different) `dhall-to-cabal` hotspots
