### ISSUE TITLE
Include Prelude as submodule

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-haskell#581]
Right now we have two distinct copies of Prelude: one in this repo and another in its own repo.
Since new developments happen on the dedicated repo, the two copies will get out of sync ([this has happened already](https://github.com/dhall-lang/Prelude/pull/9#issuecomment-419516143))

To prevent syncing issues we should include that repo as a submodule, but Hydra doesn't like that at the moment, as [seen here](https://github.com/dhall-lang/dhall-haskell/pull/571#issuecomment-420137402)

**Comment by Gabriel439** [comment]
Fixed in https://github.com/dhall-lang/dhall-haskell/pull/639 by using Dhall's import system to retrieve the Prelude
