### ISSUE TITLE
Add encode/decode commands

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-haskell#586]
It would be useful to have a `dhall encode` or `dhall serialize` command (and I guess a complementary `decode/deserialize`), to output the binary representation of an expr.

Use cases:
- "conformance tests" for other implementations (e.g. checking that the binary representation is the same)
- caching outside of the builtin import-hash-cache
- sending Dhall exprs as binary, etc.

**Comment by Gabriel439** [comment]
Pull request up here: https://github.com/dhall-lang/dhall-haskell/pull/588
