### ISSUE TITLE
Don’t `sortMap` during β-normalization.

### ISSUE THREAD

**Issue by sellout** [dhall-lang/dhall-haskell#598]
With the addition of `sortMap` to `normalizeWith` in https://github.com/dhall-lang/dhall-haskell/commit/9ac11a574179b307a74055ccf3e9c7fdbc176b5d, `normalizeWith` sorts records and unions, and we’re spending about 20% of our time in `dhall` in `sortMap`.

Since the sorting is intended to make the hashing consistent, it seems like this sorting should be applied in `Dhall.Binary.encode` instead of `normalizeWith`, both to minimize the number of calls to it and to maintain the user’s intended order as much as possible through normalization.

**Comment by sellout** [comment]
https://github.com/dhall-lang/dhall-haskell/issues/518#issuecomment-421798115 would also probably mitigate the performance issue, but it still seems like `Dhall.Binary.encode` is the right place to do this.

**Comment by Gabriel439** [comment]
I view this as a performance optimization to be made, but I don't think we should deviate from the standard.  I think the right behavior is sorting fields when β-normalizing records as the standard specifies, since a normal form should be a canonical form.

**Comment by sellout** [comment]
Ah, ok.

Well, then the switch to `(Map Text Expr, [Text])` seems like something we should do anyway, and should at least somewhat improve the performance here.

**Comment by Gabriel439** [comment]
@sellout: Here's a very rough branch with a custom ordered map implementation in a new `Dhall.Map` module:

https://github.com/dhall-lang/dhall-haskell/tree/gabriel/new_map

Could you give that a try and see if it improves performance for your use case?

**Comment by Gabriel439** [comment]
Given that the new ordered `Dhall.Map` implementation is now merged, could you check if this is still an issue?

**Comment by sellout** [comment]
Yep. We’re good with this change. Thanks!
