### ISSUE TITLE
Include windows precompiled binaries in releases

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-haskell#627]
For the tortured souls who use it :stuck_out_tongue_closed_eyes:
I could compile it in my windows 10 laptop

**Comment by Gabriel439** [comment]
@jneira: Yeah, feel free to do so.  You're a contributor so you have permission to attach binaries that you build to each release if you want.

In the long run what I would really like to do is to have CI build windows binaries using cross-compilation.  I'm just waiting for this work to get upstreamed so that we can have Dhall's CI build Windows binaries for every branch and every release:

https://github.com/input-output-hk/nix-hs-hello-windows

**Comment by jneira** [comment]
> @jneira: Yeah, feel free to do so. You're a contributor so you have permission to attach binaries that you build to each release if you want.

Hi, i have no experience making binary distributions or github releases so to confirm the steps:
* create a binary distribution: i guess that i only have to zip the win executable in a file named `dhall-1.18.0-x86_64-windows`
* attach the new binary to an existing release: it seems i would need a tool to use the github api (like https://github.com/aktau/github-release or https://github.com/tfausak/github-release) and push permission to the repo (but i don't have it although i am a contributor, right?)

**Comment by basile-henry** [comment]
`jneira` I don't think you need `github-release`, since you are a contributor here you should be able to go to https://github.com/dhall-lang/dhall-haskell/releases and click `Edit` next to `dhall-1.18.0`, you can then drop your binary to be distributed as part of the release. :smile:

**Comment by basile-henry** [comment]
@jneira Ah alright, I thought you would have the permissions already. I have uploaded the windows binary for you from https://github.com/eta-lang/dhall-haskell/releases/tag/1.18.0

**Comment by jneira** [comment]
@basile-henry thanks a lot! i think we can close this then (unless we want to track the future CI build with win binaries).

**Comment by jneira** [comment]
Uploaded binaries for `dhall-1.19.1` and friends! `dhall-1.19.0` is coming

**Comment by Gabriel439** [comment]
@jneira: Thank you! 🙂 

Just as an update, I'm waiting for this to be upstreamed into Nixpkgs so that we can build Windows binaries automatically in CI using a cross compiler:

https://github.com/input-output-hk/nix-hs-hello-windows

**Comment by f-f** [comment]
I was thinking if it would be fine to add Travis or AppVeyor configs to build macOS and Windows binaries while we wait for the cross-compiler?

**Comment by Gabriel439** [comment]
@f-f: I don't know about AppVeyor, but we tried Travis and the issue we ran into at the time was that the build regularly timed out because Dhall had a large dependency tree and most of the dependencies were not in cache

**Comment by f-f** [comment]
@Gabriel439 yeah that's a very common issue with Travis when building on Linux. We do build [spago](https://github.com/spacchetti/spago) on Travis (macOS and Linux), and we depend on Dhall (so we have a larger dependency footprint): the macOS build never had any issue, but the Linux build would time out every time if we didn't use the trick on building on a [docker image with precached dependencies](https://github.com/f-f/docker-haskell-lavello) - I assume everyone builds on Linux so the shared machines have less capacity.

In our case the Hydra build covers Linux, so Travis should work fine at least for macOS. I don't have much experience with Windows, but I could give it a try on Travis or AppVeyor

**Comment by jneira** [comment]
It turns out that appveyor + chocolatey is a pretty common choice for windows. For example it is used in cabal: https://github.com/haskell/cabal/blob/master/appveyor.yml
I am gonna try to build my fork with it here: https://github.com/jneira/dhall-haskell/tree/appveyor

**Comment by jneira** [comment]
Hi, i have a almost finished version of appveyor config: https://github.com/jneira/dhall-haskell/blob/appveyor/appveyor.yml. It builds the project using stack, with the default lts and lts-6 and generates the four artifacts used in releases.
I still have to test the automatic upload of artifacts in tag pushes.

In the meanwhilei've uploaded the zips for 1.20.1 automatically.

**Comment by Gabriel439** [comment]
@jneira: Thanks for doing that! 🙂

**Comment by jneira** [comment]
i think we can close this cause windows artefacts are uploaded auto from appveyor builds in releases
