### ISSUE TITLE
Better implemented Map operations

### ISSUE THREAD

**Issue by FintanH** [dhall-lang/dhall-haskell#640]
I would argue that https://github.com/dhall-lang/dhall-haskell/blob/master/src/Dhall/Map.hs#L463 i.e.:
```haskell
Data.Functor.void (traverseWithKey f m)
```

is wasteful work as `traverseWithKey` calls `toList` and `fromList` which isn't necessary. We could implement this as something more along the lines of:

```haskell
traverseWithKey_ f (Map m _) = Data.Function.void (Data.Map.traverseWithKey f m)
```

I would also think that https://github.com/dhall-lang/dhall-haskell/blob/master/src/Dhall/Map.hs#L449 could perform better if it was implemented as:

```haskell
traverseWithKey f (Map m ks) = fmap (\m' -> Map m' ks) (Data.Map.traverseWithKey f m)
```

**Comment by Gabriel439** [comment]
@FintanH: I think this should be added as a new `unorderedTraverseWithKey` since `Data.Map.traverseWithKey` does not preserve order

**Comment by FintanH** [comment]
Ah of course. So my other thought, and I'm not sure if fusion is already doing this for us, is having traverseWithKey work like:

```
traverseWithKey f (Map m ks) = fmap fromList (traverse (\k -> (k, f' (k, (m Data.Map.! k)) ks)
  where f' (k, v) = fmap (k,) (f k v)
```

And I suppose the traverseWithKey_ case doesn't matter with order because we throw away results anyway?

**Comment by Gabriel439** [comment]
@FintanH: You'd also need an `unorderedTraverseWithKey_` because the user might use `traverseWithKey_` if they care about the order of effects.  For example: `traverseWithKey_ (uncurry print)`

I would prefer using `Data.Map.traverseWithKey` to power `unorderedTraverseWithKey` since that's less code that we have to maintain and it's likely to be efficient since it's a dedicated function from `Data.Map`

For `unorderedTraverseWithKey_ f` I'm not sure whether the optimal implementation is `void . Data.Map.traverseWithKey f . Dhall.Map.toMap` or `traverse_ (curry f) . Dhall.Map.toList`

**Comment by FintanH** [comment]
@Gabriel439: Fair point!

I can take some time this weekend and benchmark different implementations. Getting this right is part of getting performance with the many unions problem we're experiencing :grimacing:

**Comment by FintanH** [comment]
So I finally got around to this! I wanted to add some benchmarking and it hangs on the case of 1 data point which seems _super_ weird.

It'd be cool to get some more eyes on this in case I'm making some rookie mistake
https://github.com/FintanH/dhall-haskell/blob/fintan/unorded-traverse/dhall/benchmark/map/Main.hs

**Comment by Gabriel439** [comment]
@FintanH: I can't reproduce the hang.  I'm using Nix + Cabal to run the benchmark and I was able to run at least the small and medium benchmarks.

**Comment by FintanH** [comment]
@Gabriel439: Hmmmm might be a stack issue. Could you do a quick nix + cabal lesson and tell me the command to benchmark these? I can finish up this PR then and have some solid numbers for improvement over the ordered vs unordered? 😊

**Comment by Gabriel439** [comment]
@FintanH: Install Nix here: https://nixos.org/nix/download.html

Then add these lines to `/etc/nix/nix.conf` (creating the directory and file if they do not exist already):

```
substituters = https://cache.nixos.org https://cache.dhall-lang.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.dhall-lang.org:I9/H18WHd60olG5GsIjolp7CtepSgJmM2CsO813VTmM=
```

Then edit your `~/.cabal/config` file to add this configuration option:

```
nix: True
```

Then `cd` to the `dhall` directory and run:

```
$ cabal configure  # This will download/build any dependencies you need
$ cabal bench benchmark:map-operations  # Run the benchmark
```

**Comment by FintanH** [comment]
@Gabriel439 thanks! I was able to get some numbers. `unorderedTraversWithKey_` scales very well :smile: `unorderedTraverseWithKey` only seems to scale with larger datasets.

```
Running 1 benchmarks...
Benchmark map-operations: RUNNING...
benchmarking Ordered Traversals: small/traverseWithKey
time                 184.0 ns   (165.4 ns .. 210.9 ns)
                     0.915 R²   (0.854 R² .. 0.998 R²)
mean                 172.7 ns   (164.9 ns .. 193.3 ns)
std dev              37.78 ns   (8.377 ns .. 69.80 ns)
variance introduced by outliers: 98% (severely inflated)

benchmarking Ordered Traversals: small/traverseWithKey_
time                 155.9 ns   (154.1 ns .. 157.5 ns)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 155.1 ns   (153.6 ns .. 157.1 ns)
std dev              5.626 ns   (4.228 ns .. 7.372 ns)
variance introduced by outliers: 55% (severely inflated)

benchmarking Unordered Traversals: small/unorderedTraverseWithKey
time                 374.3 ns   (306.3 ns .. 457.8 ns)
                     0.810 R²   (0.786 R² .. 0.873 R²)
mean                 385.9 ns   (336.0 ns .. 456.6 ns)
std dev              187.1 ns   (142.9 ns .. 248.8 ns)
variance introduced by outliers: 100% (severely inflated)

benchmarking Unordered Traversals: small/unorderedTraverseWithKey_
time                 102.8 ns   (97.44 ns .. 109.5 ns)
                     0.933 R²   (0.875 R² .. 0.978 R²)
mean                 116.2 ns   (103.7 ns .. 140.1 ns)
std dev              51.34 ns   (27.80 ns .. 80.91 ns)
variance introduced by outliers: 100% (severely inflated)

benchmarking Ordered Traversals: medium/traverseWithKey
time                 21.90 μs   (21.47 μs .. 22.32 μs)
                     0.996 R²   (0.992 R² .. 0.998 R²)
mean                 21.78 μs   (21.50 μs .. 22.17 μs)
std dev              1.116 μs   (824.2 ns .. 1.724 μs)
variance introduced by outliers: 59% (severely inflated)

benchmarking Ordered Traversals: medium/traverseWithKey_
time                 17.07 μs   (16.88 μs .. 17.36 μs)
                     0.998 R²   (0.997 R² .. 0.999 R²)
mean                 17.16 μs   (16.92 μs .. 17.46 μs)
std dev              940.5 ns   (778.3 ns .. 1.175 μs)
variance introduced by outliers: 63% (severely inflated)

benchmarking Unordered Traversals: medium/unorderedTraverseWithKey
time                 31.44 μs   (30.73 μs .. 32.31 μs)
                     0.996 R²   (0.995 R² .. 0.998 R²)
mean                 31.54 μs   (31.14 μs .. 31.96 μs)
std dev              1.473 μs   (1.209 μs .. 1.799 μs)
variance introduced by outliers: 53% (severely inflated)

benchmarking Unordered Traversals: medium/unorderedTraverseWithKey_
time                 8.445 μs   (8.264 μs .. 8.649 μs)
                     0.996 R²   (0.994 R² .. 0.998 R²)
mean                 8.405 μs   (8.283 μs .. 8.563 μs)
std dev              453.3 ns   (365.7 ns .. 577.7 ns)
variance introduced by outliers: 64% (severely inflated)

benchmarking Ordered Traversals: large/traverseWithKey
time                 16.21 ms   (15.88 ms .. 16.56 ms)
                     0.998 R²   (0.997 R² .. 0.999 R²)
mean                 16.69 ms   (16.32 ms .. 17.76 ms)
std dev              1.515 ms   (462.0 μs .. 2.807 ms)
variance introduced by outliers: 44% (moderately inflated)

benchmarking Ordered Traversals: large/traverseWithKey_
time                 10.71 ms   (9.599 ms .. 12.55 ms)
                     0.925 R²   (0.865 R² .. 0.998 R²)
mean                 9.676 ms   (9.401 ms .. 10.37 ms)
std dev              1.178 ms   (492.1 μs .. 2.314 ms)
variance introduced by outliers: 65% (severely inflated)

benchmarking Unordered Traversals: large/unorderedTraverseWithKey
time                 19.90 ms   (11.30 ms .. 28.08 ms)
                     0.475 R²   (0.160 R² .. 0.779 R²)
mean                 30.21 ms   (24.94 ms .. 37.08 ms)
std dev              13.22 ms   (10.45 ms .. 17.52 ms)
variance introduced by outliers: 94% (severely inflated)

benchmarking Unordered Traversals: large/unorderedTraverseWithKey_
time                 848.1 μs   (799.0 μs .. 922.0 μs)
                     0.944 R²   (0.905 R² .. 0.991 R²)
mean                 915.7 μs   (864.2 μs .. 1.001 ms)
std dev              219.7 μs   (147.5 μs .. 334.7 μs)
variance introduced by outliers: 94% (severely inflated)
```

**Comment by FintanH** [comment]
My thoughts are to replace: [here](https://github.com/dhall-lang/dhall-haskell/blob/master/dhall/src/Dhall/TypeCheck.hs#L513) and [here](https://github.com/dhall-lang/dhall-haskell/blob/master/dhall/src/Dhall/TypeCheck.hs#L563) with `unorderedTraverseWithKey_`.

Then we could probably forget about `unorderedTraverseWithKey` and keep [here](https://github.com/dhall-lang/dhall-haskell/blob/master/dhall/src/Dhall/TypeCheck.hs#L554) as is.

**Comment by Gabriel439** [comment]
@FintanH: Yeah, those are totally safe to replace since the order of the traversal doesn't matter there

**Comment by FintanH** [comment]
@Gabriel439: Great! Do you think I should keep `unorderedTraverseWithKey` for completion sake or drop it from the PR?

**Comment by Gabriel439** [comment]
@FintanH: Probably drop it for now

**Comment by FintanH** [comment]
Sweet, PR inbound!
