### ISSUE TITLE
Recursion on a list

### ISSUE THREAD

**Issue by Michael-Kateregga** [dhall-lang/dhall-haskell#651]
In dhall we can do 
`
    let T = https://raw.githubusercontent.com/dhall-lang/Prelude/master/List/package.dhall
in let h = T.head
in let l = T.last
in let lst = [3, 9, 2, 7, 1]
in [h Natural lst, t Natural lst]  
`
to get [Some 3, Some 1].

But how can I extract 9, 2 or 7 for example?

**Comment by sellout** [comment]
https://github.com/sellout/dada/blob/master/List/at

Dada has a bunch of recursion stuff in it, and more coming.

**Comment by sellout** [comment]
./List/at 1 [3, 9, 2, 7, 1]

9

**Comment by Michael-Kateregga** [comment]
@sellout Thanks Greg! Do you have the url for the actual dhall expression of https://github.com/sellout/dada/blob/master/List/at

**Comment by Michael-Kateregga** [comment]
@sellout Ok I got it, I just needed to click on raw at the repo.
