### ISSUE TITLE
Dhall silently overflows on large Doubles

### ISSUE THREAD

**Issue by drvirgilio** [dhall-lang/dhall-haskell#654]
When given an exponent greater than 2^63-1, dhall silently overflows into negative values starting at 2^-63. I noticed this occurs during normal evaluation and when encoding to CBOR. One fix is to change the specification for the CBOR encoding to somehow allow bignum exponents (CBOR decimal fractions do not allow them). But that seems like an absurd change! Instead, should dhall just exit with an error instead of accepting such large values?

This behavior isn't consistent in the library either. When converting to `Scientific` the exponent goes negative as described above. When converting to `Double` a number larger than the maximum 64-bit double returns `Infinity`. I expect an out of bounds error in both cases would be more consistent.

Here are some examples which induce overflow:
```
> echo '1.0e9223372036854775808' | dhall
1.0e-9223372036854775808
```
```
> echo '1.0e9223372036854775808' | dhall encode | cbor2pretty.rb 
82                              # array(2)
   65                           # text(5)
      332e302e30                # "3.0.0"
   82                           # array(2)
      11                        # unsigned(17)
      c4                        # tag(4)
         82                     # array(2)
            3b 7fffffffffffffff # negative(9223372036854775807)
            01                  # unsigned(1)
```
These examples are in ghci
```
>>> import Dhall
>>> :set -XOverloadedStrings
>>> input auto "1.8e308 : Double" :: IO Double
Infinity
```
```
>>> import Dhall
>>> import Data.Scientific
>>> :set -XOverloadedStrings
>>> input auto "1.0e9223372036854775808 : Double" :: IO Scientific
1.0e-9223372036854775808
```

**Comment by Gabriel439** [comment]
I think this deserves consideration as a language-agnostic issue and should be opened as a discussion in the `dhall-lang` repository:

https://github.com/dhall-lang/dhall-lang/issues

The reason I suggest this is that whatever we decide here will ultimately have to be upstreamed in the standard first, so we need to decide what is appropriate for all language implementations as opposed to just the Haskell implementation.

An example of this is the issue of whether or not to support unlimited precision decimal numbers: maybe we could actually make that work the Haskell implementation but other language implementations but maybe it wouldn't be feasible for other languages.  More generally, I imagine that any issues we struggle with here will affect other implementations, too.

**Comment by Gabriel439** [comment]
This should be fixed now that the corresponding change to the standard was merged and implemented.
