### ISSUE TITLE
Parser bug triggered by `Some`

### ISSUE THREAD

**Issue by vmchale** [dhall-lang/dhall-haskell#655]
With the following Dhall:

```
let Option = < SomeCons : Natural | NoneCons : {} >
in
let SomeCons = λ(x : Natural) → < SomeCons = x | NoneCons : {} >
in
let p = +1
in

SomeCons p
```

I get the following error:

```

Use "dhall --explain" for detailed errors

SomeCons : ∀(x : Natural) → < NoneCons : {} | SomeCons : Natural >
p : Integer

Error: Unbound variable: Cons

    Cons
(stdin):8:5
```

Of course, there is no variable `Cons` so I assume this is a parse error.

Thanks!

**Comment by Gabriel439** [comment]
Yeah, this is a bug in both the standard and the Haskell implementation.  I accidentally added two rules to the standard for parsing `Some`: one requiring non-empty whitespace afterwards and one not.  The correct one is the former one.

**Comment by Gabriel439** [comment]
Whoops, my mistake.  The standard grammar is just fine (I had a brain fart).  The only issue here is that the Haskell implementation is not standards-compliant.

**Comment by Gabriel439** [comment]
Fix up here: https://github.com/dhall-lang/dhall-haskell/pull/658
