### ISSUE TITLE
Handling nested Unions

### ISSUE THREAD

**Issue by Michael-Kateregga** [dhall-lang/dhall-haskell#659]
Hello, I have the following:
`
let ceApp = constructors < X : < P : Natural | Q : Bool > | Y : < R : Natural | S : Bool >> in ceApp.X < P = 4 | Q : Bool >
`
that returns
`
< X = < P = 4 | Q : Bool > | Y : < R : Natural | S : Bool > >
`
Can some one provide an example of handling ceApp.X <...> in the sense:

`
merge handlers (ceApp.X < P = 4 | Q : Bool >)
`

**Comment by Michael-Kateregga** [comment]
I tried the following but it doesn't work:
`
let ceApp = constructors < X : < P : Natural | Q : Bool > | Y : < R : Natural | S : Bool >> in merge {\(x : <P : Natural | Q : Bool>) -> merge {P = Natural/even, Q = \(b : Bool) -> b} x, \(y : <R : Natural | S : Bool>) -> merge {R = Natural/even, S = \(b : Bool) -> b} y} (ceApp.X < P = 4 | Q : Bool >)
`

**Comment by Gabriel439** [comment]
I renamed things a little bit, but here is how you would do a nested `merge`:

```haskell
    let InnerX = < P : Natural | Q : Bool >

in  let innerX = constructors InnerX

in  let InnerY = < R : Natural | S : Bool >

in  let innerY = constructors InnerY

in  let Outer = < X : InnerX | Y : InnerY >

in  let outer = constructors Outer

in  merge
    { X =
        λ(x : InnerX) → merge { P = Natural/even, Q = λ(b : Bool) → b } x
    , Y =
        λ(y : InnerY) → merge { R = Natural/even, S = λ(b : Bool) → b } y
    }
    (outer.X (innerX.P 4))
```

**Comment by Michael-Kateregga** [comment]
@Gabriel439 this is perfect!

**Comment by Michael-Kateregga** [comment]
What would be the equivalent data structure of the nested union 'outer' in haskell? I was thinking along the lines:

type P = Natural
type Q = Bool
type R = Natural
type S = Bool
data innerX = P | Q deriving Show
data innerY = R | S deriving Show
data Outer = Ol innerX | Or innerY deriving Show

**Comment by Gabriel439** [comment]
@Michael-Kateregga: The equivalent Haskell data structure would be:

```haskell
data Outer = X InnerX | U InnerY

data InnerX = P Natural | Q Bool

data InnerY = R Natural | S Bool
```

**Comment by Michael-Kateregga** [comment]
@Gabriel439  Thanks, this works fine.
