### ISSUE TITLE
Allow `dhall freeze` to only freeze specific imports

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#663]
I've found that while working I often want to freeze a subset of imports - in particular, imports from `prelude.dhall-lang.org`. What about adding `--host` to `dhall freeze`, as one solution?

**Comment by Gabriel439** [comment]
@ocharles: Yeah, that seems reasonable to me.  I can't think of another way to accomplish the same thing within the existing set of features

**Comment by ocharles** [comment]
Indeed. I wasn't sure if `--host` was the right interface though. Maybe `--prefix` which could take either a URL or file path. If it's a filepath, we canonicalise it and avoid freezing any imports with a similar prefix?

**Comment by joneshf** [comment]
An interesting option would be an `--interactive` flag that works similar to the `-i`/`--interactive` flag for the `rm` command: prompt before taking the action on each candidate. In this case, prompt for each import whether to freeze it or not.

**Comment by ocharles** [comment]
Alright, I'll try and throw something together for `--prefix`

**Comment by Gabriel439** [comment]
I'll close this since I don't think anybody else has requested this recently and I'm not aware of anybody who plans to work on this.  Feel free to reopen if somebody still needs this feature
