### ISSUE TITLE
Missing from stackage nightly ghc-8.6.1.

### ISSUE THREAD

**Issue by philderbeast** [dhall-lang/dhall-haskell#665]
The latest stackage nightly I can find with `dhall` and `dhall-json` is [2018-09-28 (ghc-8.4.3)](https://www.stackage.org/nightly-2018-09-28/hoogle?q=dhall). They're missing from the next nightly, [2018-09-29 (ghc-8.6.1)](https://www.stackage.org/nightly-2018-09-29/hoogle?q=dhall) and the latest one [2018-10-29 (ghc-8.6.1)](https://www.stackage.org/nightly-2018-10-29/hoogle?q=dhall).

These packages are in [build-constraints.yaml](https://github.com/commercialhaskell/stackage/blob/cb8a98815de062628bc1ece72bd2644d4a1677d6/build-constraints.yaml#L864-L866).

I'd like to put`hpack-dhall` on stackage nightly and it depends on `dhall` and `dhall-json`.

**Comment by Gabriel439** [comment]
@philderbeast: Yes, I plan to add `dhall`/`dhall-json` back to Stackage soon.  They got kicked off Stackage because of https://github.com/commercialhaskell/stackage/issues/4008 and I just haven't had a chance to add them back, yet

**Comment by DanBurton** [comment]
Note that this is blocked by https://github.com/commercialhaskell/stackage/issues/3955, since `dhall-1.18.0` requires `megaparsec >= 7`, while `dhall-1.17.0` requires older `containers` and `template-haskell`.

I'll work on coaxing people to upgrade to megaparsec 7.

**Comment by Gabriel439** [comment]
I believe this will be fixed once https://github.com/commercialhaskell/stackage/pull/4165 is merged, since `dhall-bash` now supports the latest version of `containers` and GHC 8.6 in general.  It appears that `dhall`/`dhall-json`/`dhall-text` were already added back

**Comment by Gabriel439** [comment]
This should be fixed now.  All four of `dhall`/`dhall-text`/`dhall-bash`/`dhall-json` are in Stackage nightly now

**Comment by Gabriel439** [comment]
You're welcome! 🙂
