### ISSUE TITLE
Record type merging ASCII operator not working

### ISSUE THREAD

**Issue by haitlahcen** [dhall-lang/dhall-haskell#678]
The record type merging ASCII operator `//\\` do not work anymore after having upgraded my dhall version from `1.15` to `1.18`. The UNICODE one is working perfectly tho.

The output from the `dhall repl`

```
⊢ { x: Type } //\\ { y: Type }

Error: Invalid input

(stdin):1:15:
  |
1 | { x: Type } //\\ { y: Type }
  |               ^^^^^
unexpected "\\ { "
expecting "Some", "constructors", "merge", '(', built-in expression, double literal, import, integer literal, label, list literal, natural literal, record type or literal, text literal, union type or literal, or whitespace

⊢ { x: Type } ⩓ { y: Type}

{ x : Type, y : Type }
```

**Comment by f-f** [comment]
Yeah, this bug has been fixed in https://github.com/dhall-lang/dhall-haskell/commit/9d0fd42d95ab69fa64da4afd8b60d69aca8e65a6

I think we'll cut a new release with the fix as soon as some other major changes get in 👍

**Comment by haitlahcen** [comment]
Oh, I did not noticed the commit ! Good catch and thanks for the quick answer :)!
