### ISSUE TITLE
Problem parsing an expression

### ISSUE THREAD

**Issue by SupraSummus** [dhall-lang/dhall-haskell#682]
I get error when trying to parse `let env = 1 in env: Integer`, which is quite close to being an env variable import. I believe that the expression is allowed by syntax described by the dhall standard.

```
$ dhall version
1.18.0
$ echo 'let env = 1 in env: Integer' | dhall

Error: Invalid input

(stdin):1:20:
  |
1 | let env = 1 in env: Integer
  |                    ^
unexpected space
expecting '"'

```

**Comment by jneira** [comment]
I think you cant put a type annotation in that place, it should be after variable name in the declaration:
```console
C:\Users\Javier\dev\lang\eta\dhall\dhall-eta>echo let env : Integer = 1 in env | dhall

Use "dhall --explain" for detailed errors

Error: Expression doesn't match annotation

- Integer
+ Natural

let env : Integer = 1 in env

(stdin):1:1

C:\Users\Javier\dev\lang\eta\dhall\dhall-eta>echo let env : Integer = +1 in env | dhall
+1
```

**Comment by f-f** [comment]
Note that the parse error comes from the `env:`, as that's the prefix for importing environment variables.
Type annotations there are allowed there but there should be a space after `env`, e.g. this works:

```haskell
$ echo 'let env = 1 in env : Natural' | dhall
1
```

**Comment by f-f** [comment]
Oh right sorry, I misunderstood.

Right, I agree with @SupraSummus here: the standard is correct, and this is a bug of the Haskell implementation. The example expression works fine in the Clojure implementation:

```clojure
dhall-clj.core> (input "let env = 1 in env: Natural")
1
```

**Comment by f-f** [comment]
@SupraSummus according to the grammar the above example should not even parse:

```
Parse error at line 1, column 44:
let A-1 = Natural in let env = 1 in env:A-1' | A='\(x: Integer) -> x
                                           ^
Expected one of:
%x2192
"?"
"||"
"+"
"++"
"#"
"&&"
%x2227
%x2afd
%x2a53
"*"
"=="
"!="
"."
"@"
" "
%x0041-005a
%x0061-007a
%x0030-0039
"-"
"/"
"_"
%x0009
%x000a
%x000d
"--"
"{-"
"//\\"
"//"
"/\"
"->"
":"
%x0069
%x006c
```

**Comment by SupraSummus** [comment]
You have copied too much from my example, I think. There are two piped bash commands.

**Comment by Gabriel439** [comment]
To help focus this discussion, let's do the following:

* First decide on what the right behavior should be, regardless of what the current standard specifies and regardless of what the two implementations should do
* Then update the standard to match that behavior (if there is any difference from the current specification)
* Then update the implementations to match the standard (if there is any difference)

**Comment by f-f** [comment]
@SupraSummus sorry I deleted my comment as I realized the mistake. This is a nice corner case.

@Gabriel439: from the examples posted so far I'm now thinking that it would probably make sense to require spaces around the `:` in annotations, as without spaces there the code is unreadable anyways

**Comment by SupraSummus** [comment]
I think that requiring spaces around `:` is a good idea. It'll make parsing easier in my case. Actually I think requiring whitespace only after `:` (or only before, or "before or after") has this advantage, and also leaves more whitespace-freedom to the user.

**Comment by MonoidMusician** [comment]
Hmm I wonder, would there be any issue with `$` as the prefix for environment variables? I, too, had problems parsing `env:` correctly – I actually had to add `env` as a reserved keyword (since I am trying to avoid ambiguity in my parser – the miraculous thing is it's actually possible most of the time! :smile:).

**Comment by Gabriel439** [comment]
@f-f: Sounds good! 🙂
