### ISSUE TITLE
Record of records of Types

### ISSUE THREAD

**Issue by haitlahcen** [dhall-lang/dhall-haskell#697]
I have a question about record of records of types.

Since `1.18.0`, I was able to use:
```
let x = { a =  Bool } in { b = x }
```

Now dhall throws an `invalid field` exception.

This was a very useful feature to export modules types (bubble up the types from the base module to the top level) through a single record... !

**Comment by f-f** [comment]
Hi @haitlahcen! This was just discussed in https://github.com/dhall-lang/dhall-haskell/issues/692#issuecomment-440936349, in which there is a [detailed explanation](https://github.com/dhall-lang/dhall-haskell/issues/692#issuecomment-441069496) on why this doesn't work (yet) with the new CCω type system
