### ISSUE TITLE
Add encode-json command

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-haskell#714]
Now that we have the parser tests in the `dhall-lang` repo, there is the issue of keeping them up to date as the standard evolves. This is slightly annoying currently, as the "B side" of a Dhall expression is its CBOR-JSON form; last time (when generating the tests) I tried using some thing from npm to translate the binary encoding from `dhall encode` to JSON, but that was kinda broken.

For this reason it would probably make sense to add a `dhall-to-json encode` command, that would render a Dhall expression in its CBOR-JSON form, so I guess we'd basically need a function `Codec.CBOR.Term -> Data.Aeson.Value`

Example output:
```bash
$ dhall-to-json encode <<< "λ(x : Bool) → x"
[
  1,
  "x",
  "Bool",
  "x"
]
```

**Comment by Gabriel439** [comment]
@f-f: Yeah, this seems reasonable.  The only change I would suggest is to instead add a `--json` flag to `dhall encode` and `dhall decode` rather than adding this to the `dhall-to-json` executable

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/717
