### ISSUE TITLE
Add `dhall freeze` support for safely upgrading

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-haskell#715]
Currently users have to refreeze their hashes if they upgrade to a new version of the language standard, which is potentially unsafe unless they re-audit their dependencies.  It would be nice if `dhall freeze` had a mode that only repairs semantic integrity checks if the only thing that has changed is the version string

**Comment by jneira** [comment]
Mmm, no more version string, right? Now it could repair only decoding the expression to test if it is correct

**Comment by Gabriel439** [comment]
@jneira: It actually already repairs the hash if it is wrong:

https://github.com/dhall-lang/dhall-haskell/blob/bffe2ed2a1e6b8ed2223df0055ba25b31d53e7fa/dhall/src/Dhall/Freeze.hs#L60-L63

... so I believe there is nothing left to do here
