### ISSUE TITLE
[dhall-bash question] How to consume a list of record

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#723]
I am trying to consume a list of record from dhall to bash: 

$config_file
```
{ repos =
    [ { path =
          "foo"
      , checkout =
          "bar"
      }
    ]
}
```
I thought I could do something like this:
```
eval $(dhall-to-bash --declare nb_repo <<< "List/length { path : Text, checkout : Text } ($config_file ).repos")
for ((i = 0; i < ${nb_repo}; ++i)); do
    eval $(dhall-to-bash --declare repo <<< "($config_file ).repos.$i")
    echo "${repo}"
done
```
But searching by indice doesn't seem possible ?

**Comment by Gabriel439** [comment]
@PierreR: Indexing into a `List` is possible, but the language doesn't try to make it easy.  You can find a utility to do this here:

https://github.com/sellout/dada/blob/master/List/at

Example usage:

```
$ dhall <<< 'https://raw.githubusercontent.com/sellout/dada/master/List/at Natural 2 [2, 3, 5]'
Some 5
```

**Comment by PierreR** [comment]
Thanks for your help ;-)

**Comment by Gabriel439** [comment]
@PierreR: You're welcome! :slightly_smiling_face:
