### ISSUE TITLE
Questions on TypeCheck.hs

### ISSUE THREAD

**Issue by MonoidMusician** [dhall-lang/dhall-haskell#741]
Hi, I have a couple small questions on typechecking in the Haskell implementation that emerged out of porting it to PureScript:

- These two lines run `loop ctx t`, but `t` is already the (normalized) result of typechecking – surely it is known to typecheck already?
  https://github.com/dhall-lang/dhall-haskell/blob/cf69f5a953a3264bd4035ed9e60d466ed1267a50/dhall/src/Dhall/TypeCheck.hs#L775-L782
  https://github.com/dhall-lang/dhall-haskell/blob/cf69f5a953a3264bd4035ed9e60d466ed1267a50/dhall/src/Dhall/TypeCheck.hs#L796-L800
  (The laws would be that the type of a typechecked expression should itself typecheck, and that a normalized, typechecked expression should typecheck.)
- This just doesn't look right to me:
  https://github.com/dhall-lang/dhall-haskell/blob/cf69f5a953a3264bd4035ed9e60d466ed1267a50/dhall/src/Dhall/TypeCheck.hs#L815-L816
  I suppose the standard says that you can't typecheck expressions with unresolved imports. But that implementation is very unsatisfying ... What about typechecking both sides and comparing their results? (Taking either side if one typechecks, making sure they are equal if they both typecheck.)

Hmm that's a small list, but I don't think I had any other questions :)

**Comment by sjakobi** [comment]
I have opened #1368 to remove the redundant checks.

Regarding import alternatives: I agree that it is a bit funny. You can do stuff like

```
⊢ 1 ? Natural/even 0.1

1
```

I don't see why it would be a problem though.

**Comment by MonoidMusician** [comment]
Thanks! I think we can close this.
