### ISSUE TITLE
Migrate to the HsYaml package

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-haskell#744]
The `yaml` package doesn't work with GHCJS because it depends on a C library, so if we can migrate to using the `HsYaml` package then we can render YAML for the "Try Dhall" page.

**Comment by Gabriel439** [comment]
@f-f: Oh, I didn't realize that.  Maybe we could hack it by transmitting a JSON object across the Haskell/JavaScript boundary and then doing the YAML rendering in JavaScript

**Comment by jneira** [comment]
I got the same problem for eta and just replace the call to `yaml` with a call to a java external lib (jackson): https://github.com/typelead/eta-hackage/blob/master/patches/dhall-json-1.2.5.patch#L77

**Comment by hvr** [comment]
How much control would you need over the generated YAML (i.e.in terms of formatting options, specifically regarding flow-style or indentation)?

Fwiw, I've suggested completing the yaml-dumping part of the HsYAML pipeline as a GSOC idea for this year, so there's a good chance this will be addressed one way or another this year.

**Comment by Gabriel439** [comment]
@hvr: The only rendering thing that I care about is that multi-line strings are rendered in YAML as "literal" multi-line strings (i.e. ones prefixed with `!`).  Other than that, I'm pretty flexible

**Comment by hvr** [comment]
@Gabriel439 there's afaik no `!`-prefixed block literals, see https://yaml.org/spec/1.2/spec.html#id2793652

I suspect you meant the literal blockstyle ones (i.e. using the `|` indicator), possibly with an indentation indicator (when the multi-line strings happens to start with leading whitespace) and blockchomping indicators for when the string has non-trivial trailing whitespace?

**Comment by Gabriel439** [comment]
@hvr: Whoops, yes, I meant `|`

**Comment by jneira** [comment]
Since #943, we are using [`Data.Yaml.encodeWith :: ToJSON a => EncodeOptions -> a -> ByteString`](http://hackage.haskell.org/package/yaml-0.11.0.0/docs/Data-Yaml.html#v:encodeWith) to " quoted scalars if needed" so `HsYAML` should have that feature to be usable.

**Comment by hvr** [comment]
@jneira Can you elaborate on the semantics of "quoted scalars if needed"? Whether a scalar needs to be quoted really depends on the YAML schema resolver your application defines for a YAML file to be used; the YAML 1.2 spec pre-defines 3 schema resolvers, "failsafe", "core" and "JSON" (see https://yaml.org/spec/1.2/spec.html#Schema) -- and applications can also opt to define their own domain specific schema if needed; and when HsYAML adds support for encoding, it will defer the decision whether to quote partly to the schema resolver you ask it to use in a dual way to the way the decoding currently works, which too defers to the selected YAML schema resolver to resolve which primitive tag/type a scalar node is to be decoded into...

**Comment by jneira** [comment]
Nice! Didn't know about its use of YAML schemas

**Comment by sjakobi** [comment]
This was fixed by https://github.com/dhall-lang/dhall-haskell/pull/1248! :)
