### ISSUE TITLE
Feature request: machine readable "--explain" output

### ISSUE THREAD

**Issue by purcell** [dhall-lang/dhall-haskell#757]
I'd love to build an Emacs flycheck backend for Dhall files, but the output seems to unconditionally contain ANSI escape codes etc., which makes parsing it feel a bit brittle.

It'd be great if there were an option for any errors/hints to be output as JSON or similar, or at least without escape codes.

**Comment by Gabriel439** [comment]
Closing this as I believe that using the Haskell API addresses the original request
