### ISSUE TITLE
Remove duplicated tests between dhall-lang and dhall-haskell

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-haskell#766]
Wouldn't be desirable avoid the duplication between spec tests in this repo and the `dhall-lang` ones?
Modifications could be:
- Remove spec tests from `dhall-haskell`
- Include `dhall-lang` as submodule of `dhall-haskell` (like [`dhall-clj`](https://github.com/f-f/dhall-clj))
- Read spec tests cases from there *and* the implementation specific ones from the actual location
- Set up some way to skip spec tests explicitly in case we want to ship a `dhall-haskell` version not 100% compliant

**Comment by Gabriel439** [comment]
@jneira: The main limitation here is that I haven't figured out how to get Hydra to work with git submodules.  If somebody can get it working I'd accept the change

**Comment by ocharles** [comment]
We use submodules extensively at work, I'll share our patches.

**Comment by ocharles** [comment]
It turns out there are no patches needed. Here's our `hydra.nix` Nixpkgs overlay:

```nix
self: super:
{ hydra =
    super.hydra.overrideAttrs
      ( _:
        { src =
            self.fetchFromGitHub
              { owner = "NixOS";
                repo = "hydra";
                rev = "63a294d4caa1124dd1c7d08c06ccef4113154bc8";
                sha256 = "0xw6kph7zxlq2inb4aglp8g0hinnyz8z4x2dmkjnc2lhkhsdaq1j";
              };

          patches =
            [ # Fix for https://github.com/NixOS/nix/issues/1888
              ./hydra/unrestrict-hydra.diff

              ./hydra/job-name.patch

              ./hydra/hydra-auth-file.patch

              ./hydra/faster-clone.patch
            ];

          doCheck =
            false;
        }
      );
}
```

None of those patches change submodule behaviour.

**Comment by f-f** [comment]
@ocharles @Gabriel439 any further ideas on this? Could it be [this issue](https://github.com/NixOS/hydra/issues/543)?

**Comment by ocharles** [comment]
I would like to know if using the above version of Hydra works

**Comment by Gabriel439** [comment]
@ocharles: Yeah, I need to pin Dhall CI to a specific revision of Nixpkgs.  The Nixpkgs revision I've mostly recently deployed from is:

* https://github.com/NixOS/nixpkgs/commit/d56ec49ae42e99fb03db915cbfb698070d6f96f7

... which corresponds to this revision of Hydra:

* https://github.com/NixOS/hydra/commit/4dca8fe14d3f782bdf927f37efce722acefffff3

... which is a couple of months older than the revision you are using:

* https://github.com/NixOS/hydra/commit/63a294d4caa1124dd1c7d08c06ccef4113154bc8

Here is the difference between the two revision:

https://github.com/NixOS/hydra/compare/4dca8fe14d3f782bdf927f37efce722acefffff3...63a294d4caa1124dd1c7d08c06ccef4113154bc8

From a brief scan of that, it looks like this submodule-related commit might fix things: https://github.com/NixOS/hydra/commit/8bffbb792856d8a4600000fad0296be7a85b712f

I'll try to see if deploying that newer revision of Hydra fixes things

**Comment by jneira** [comment]
Hi, @Gabriel439  test code should be updated to read the tests from the new locations. Should we open a new one about?

**Comment by Gabriel439** [comment]
@jneira: I did update the test code to read the test files from the new location
