### ISSUE TITLE
Complex list types are not interpreted as lists for the purposes of type-annotating empty lists

### ISSUE THREAD

**Issue by ari-becker** [dhall-lang/dhall-haskell#770]
`working.dhall`
```dhall
let RebadgedText = Text : Type
in {
  emptyList = [] : List RebadgedText
}
```
The `working.dhall` passes the type checker and produces an empty list.

`broken.dhall`
```dhall
let RebadgedTextList = (List Text): Type
in {
  emptyList = [] : RebadgedTextList
}
```
The `broken.dhall` produces an error: `An empty list requires a type annotation`.

Expected behavior: `broken.dhall` should pass the type checker and produce an empty list.

Using: dhall-to-yaml v1.2.4 (still latest available on Homebrew)

**Comment by ocharles** [comment]
[] : List T is a single syntactic element, while [] : RebadgedText is
actually three - an annotation node with a (syntactically incomplete) empty
list and the type 'RebadgedText' as children. With the current grammar,
it's not possible to do what you want unfortunately. ([] : List Text) :
RebadgedText should work, but is likely not what you want!

**Comment by oded-dd** [comment]
+1

**Comment by f-f** [comment]
@ari-becker this is a known issue, you might find more info/details in https://github.com/dhall-lang/dhall-haskell/issues/414
