### ISSUE TITLE
The link to the tutorial up on hackage is broken

### ISSUE THREAD

**Issue by philderbeast** [dhall-lang/dhall-haskell#774]
The link to the tutorial up on hackage is broken.

Reproduction steps when 1.20.1 is the latest version:

1. Visit http://hackage.haskell.org/package/dhall
2. Click the [Dhall.Tutorial](http://hackage.haskell.org/package/dhall-1.20.1/docs/Dhall-Tutorial.html) link and get a not found page

> Not Found
There is no documentation for dhall-1.20.1. See http://hackage.haskell.org/package/dhall/docs/Dhall-Tutorial.html for the latest version.

https://github.com/dhall-lang/dhall-haskell/blob/fc3472d0859e11eb059e6f8ec9edc0420546a523/dhall/dhall.cabal#L23

**Comment by toonn** [comment]
It seems like *all* documentation is missing rather.

**Comment by Gabriel439** [comment]
It looks like Hackage failed to build the `repline` dependency on their documentation build process:

https://hackage.haskell.org/package/dhall-1.20.1/reports/1

```
Building library for repline-0.2.0.0..
[1 of 1] Compiling System.Console.Repline ( src/System/Console/Repline.hs, dist/build/System/Console/Repline.o )
/usr/bin/ld.gold: error: cannot find -ltinfo
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
```

I've manually uploaded the documentation to work around this, though, so this is fixed now.
