### ISSUE TITLE
Dhall requires $HOME to be set

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-haskell#788]
Dhall fails when trying to resolve a hash-protected-import and the `HOME` environment variable is not set. To replicate:

```bash
unset HOME
dhall <<< "https://raw.githubusercontent.com/spacchetti/spacchetti/20181209/src/mkPackage.dhall sha256:8e1c6636f8a089f972b21cde0cef4b33fa36a2e503ad4c77928aabf92d2d4ec9"

↳ https://raw.githubusercontent.com/spacchetti/spacchetti/20181209/src/mkPackage.dhall sha256:8e1c6636f8a089f972b21cde0cef4b33fa36a2e503ad4c77928aabf92d2d4ec9
HOME: getXdgDirectory:getHomeDirectory:getEnv: does not exist (no environment variable)
```

The expectation here is that Dhall could warn that caching is not possible, but not fail?

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/789

**Comment by f-f** [comment]
@Gabriel439 thanks!

**Comment by Gabriel439** [comment]
@f-f: You're welcome!  Let me know if you need me to cut a new release

**Comment by f-f** [comment]
I considered it, but then I realized I can just pin the commit with stack for now :)
