### ISSUE TITLE
Generating Dhall’s type files from Haskell’s instances?

### ISSUE THREAD

**Issue by michalrus** [dhall-lang/dhall-haskell#794]
Today, I needed to use an `Optional` on a record with huge type… that I don’t have in Dhall code anywhere.

Since Dhall won’t infer a `Nothing _` on its own, I need some `Nothing ./MyRecord.type`.

Could this `MyRecord.type` be auto-generated from a given `Dhall.Interpret` instance (which is also auto-derived!), when building the project?

This would serve as:
* a type for `Nothing`s,
* a (kinda-self-)documentation for admins later editing this record,
* time saver for developers (not needing to update both Haskell and Dhall types).

**Comment by Gabriel439** [comment]
@michalrus: Yes.  Given an `Interpret` instance for a Haskell type you can print the corresponding Dhall type like this:

```haskell
{-# LANGUAGE DeriveGeneric    #-}
{-# LANGUAGE DeriveAnyClass   #-}
{-# LANGUAGE TypeApplications #-}

import Dhall (Generic, Interpret, Natural, Text)

import qualified Data.Text.IO
import qualified Dhall
import qualified Dhall.Core

data Example = Example { name :: Text, age :: Natural }
    deriving (Generic, Interpret)

main :: IO ()
main = do
    let expression = Dhall.expected (Dhall.auto @Example)

    Data.Text.IO.putStrLn (Dhall.Core.pretty expression)
``` 

... which produces this output when run:

```haskell
{ name : Text, age : Natural }
```

**Comment by michalrus** [comment]
Wonderful, thank you! :sparkles: 

But, I wonder, what is the recommended approach, if we only consume Dhall files from Haskell? Should the Type file still be adjusted manually?

**Comment by sellout** [comment]
@michalrus I would be inclined to treat the Dhall type as the source of truth. There’s already a `Dhall.TH` module that reads a Dhall expression into an AST at compile time. It would be cool to see additional TH in there that would create a Haskell type from a Dhall expression.

**Comment by michalrus** [comment]
I see, thank you, both!

**Comment by Gabriel439** [comment]
You're welcome! 🙂
