### ISSUE TITLE
Function to read a haskell value and cache the expression, returning the hash

### ISSUE THREAD

**Issue by jneira** [dhall-lang/dhall-haskell#796]
Hi, i have to implement a function using the lib low level api and i wonder if it could be common enough to add to the api (`Dhall` main module)

1. Optionally, try to read a dhall expression from cache given a hash. If there is a hash and it is in sync, returning the haskell value and the given hash 
2. Otherwise, parse, resolve, normalize and type check a the source input
3. Compute the hash and put in cache the expression
4. Return the extracted haskell value and the hash (the new one) to save it and use the next time.

The function would have the signature:
```haskell
inputWithCaching :: Type a -> Text -> Maybe (Crypto.Hash.Digest SHA256) -> IO (a ,Crypto.Hash.Digest SHA256)
```

**Comment by jneira** [comment]
I guess the case is not used enough to include it in the api so closing this. Just in case someone is interested I've implemented a external cache, mapping absolute paths to dhall cache keys [here](https://github.com/jneira/etlas/blob/dhall-cache/etlas/Distribution/Client/PackageDescription/Dhall.hs#L107)
The problem with the cache invalidation is computing the hash is almost as costly as extract directly the value (cause you have to parse, beta and alpha normalize) so we had to invalidate it on file raw hash change.

**Comment by Gabriel439** [comment]
@jneira: Sorry for the delay in responding.  If all you need to do is change the path of the cache, you can set the `XDG_CACHE_HOME` environment variable and the interpreter will do the right thing
