### ISSUE TITLE
UTF-8 Symbol Names

### ISSUE THREAD

**Issue by fosskers** [dhall-lang/dhall-haskell#798]
I'm using Dhall as a human-readable data storage format. Previously I had tried such naughtiness as:
```dhall
let 禺 = [ ... ]
```
but Dhall seems not to allow that. Okay, fair, I can use ASCII for bindings. 

That said, I'd expect the import below to work as expected:
```
let entries : List (List Entry) = [ ./families/禺.dhall, hen ]
```
but I get a similar failure:
```
Error: Invalid input

(stdin):133:48:
    |
133 | let entries : List (List Entry) = [ ./families/禺.dhall, hen ]
    |                                                ^
unexpected '禺'
expecting '"'
```
The typechecker says it wants `"` here, but adding them doesn't help. 

It seems to me the entire UTF-8 range should be allowed for imports, since those are just filenames. Thoughts? Please and thanks.

**Comment by Gabriel439** [comment]
@fosskers: As a side note, the original rationale for Dhall disallowing Unicode in identifiers is not as strong as it used to be now that Dhall supports α-normalizing expressions (i.e. converting everything to De Bruijn indices).  However, I'll just stick to discussing file paths for now

I think it makes sense to allow Unicode in quoted file path components.  The language already supports quoted path components for including spaces in file names, so it seems like it should fine to expand quoted path components to support Unicode.  Then you would be able to write:

```
[ ./families/"禺.dhall" ]
```

Would that solution work for you?

**Comment by fosskers** [comment]
Yes, obsolutely! Asking the user (me) to add quotes isn't too much of a burden, since non-UTF8 in filenames is similar in "fringeness" to having spaces.

**Comment by fosskers** [comment]
An aside: by being clever with my imports, Dhall is working well as a storage format. My "schemas" are all typechecked right in the file, and the auto-reformatting keeps everything standardized. This is perfect for finding structural errors, as I was having trouble doing with raw YAML.

**Comment by Gabriel439** [comment]
Here is the corresponding proposal to change the standard: https://github.com/dhall-lang/dhall-lang/pull/353

**Comment by Gabriel439** [comment]
Also, regarding performance, I expect the parsing performance to perform pretty well on a large variety of inputs that I've root-caused and fixed the original issue with it.  Most likely if there are performance issues on large files it will be with either the type checking logic or normalization logic which haven't gotten the same attention as parsing yet.

**Comment by fosskers** [comment]
Luckily my data model is far from rocket surgery, so I don't expect any problems there.

Thanks for your quick response!

**Comment by Gabriel439** [comment]
You're welcome! 🙂

**Comment by JonReppDoneD** [comment]
I think hdvetgre nirnod kgo
