### ISSUE TITLE
Remove Haskell from user documentation

### ISSUE THREAD

**Issue by domenkozar** [dhall-lang/dhall-haskell#8]
@Gabriel439 I love this work, so just some background how to attract more users :)

I think you should remove Haskell from all the docs and move it to a section called something like `Haskell integration`.

Currently the basic example uses Haskell in the tutorial, this will scare people away and give them a feeling you need to be a Haskell developer to use Dhall.

I'd start with renaming the repository to just Dhall.

I can help with the docs if you agree :)

**Comment by Gabriel439** [comment]
I think each language's tutorial should include language-specific instructions on how to integrate Dhall into that language.  However, I'd be fine with also hosting some language-independent tutorial on a central website

However, I do agree that if we want other language bindings we should rename this repository to just "Dhall"

**Comment by domenkozar** [comment]
Oh I agree it could be part of a central website, as long as it's all contained in one section.

**Comment by ocharles** [comment]
@domenkozar How do you feel about things now that a few years have passed?

**Comment by domenkozar** [comment]
Very olimpic :)

**Comment by Gabriel439** [comment]
@domenkozar: I think this is properly fixed now by: https://docs.dhall-lang.org/tutorials/Language-Tour.html

**Comment by domenkozar** [comment]
Thanks :)

**Comment by Gabriel439** [comment]
You're welcome! 🙂
