### ISSUE TITLE
[dhall-bash] Union 

### ISSUE THREAD

**Issue by PierreR** [dhall-lang/dhall-haskell#801]
Is there any way to represent Dhall Union in bash or at least simple enumerated type ?

It is quite useful to be able to indicate to the user what value is permitted in a dhall config:
 ```
let light = < Light = "light" | Dark : Text > 
let dark = < Light : Text | Dark = "dark" >
in
{ theme = light}
```
Unfortunately I don't believe there is a way to use this with `dhall-bash`. Is there some possible workaround ?

**Comment by Gabriel439** [comment]
So, my first impression is that the Dhall representation of the enum should be this type:

```haskell
< light : {} | dark : {} >
```

The main reason I suggest that representation is that it makes invalid states unrepresentable.  If you were to store a string in each alternative then you would permit invalid states like:

```haskell
< Light = "foo" | Dark : Text >
```

Then the main question is how you can convert the union value to a string literal.  You can do that within Dhall using `merge`:

```bash
$ cat ./show
λ(x : < light : {} | dark : {} >) → merge { light = λ(_ : {}) → "light", dark = λ(_ : {}) → "dark" } x
```

**Comment by PierreR** [comment]
@Gabriel439  Thanks for your help.

I like your suggestion but I still wonder if I would not prefer to handle the conversion of the union in the bash file.

So

```
let Theme = < light : {} | dark : {} >
in  { color = Theme.light {=} }
```
instead of
```
let Theme = < light : {} | dark : {} >
in  { color = ./show (Theme.light {=}) }
```

The consumer of the config file doesn't know much about Dhall and might wonder about the extra `./show` function.

But that's not a big deal ;-)

**Comment by Gabriel439** [comment]
@PierreR: We might want to revisit this when https://github.com/dhall-lang/dhall-lang/issues/224 is standardized because the language could then add built-in support for showing enums with empty alternatives (by just converting the alternative name to a string)
