### ISSUE TITLE
[1.18.0] Type Record //\\ parser bug

### ISSUE THREAD

**Issue by FintanH** [dhall-lang/dhall-haskell#813]
I'm not sure if I missed this but I ran into a bug when working on `dhall-bhat` and using dhall-1.18.0. The combine operator for records was broken when using the ascii version of the operator but would work fine for the unicode version of the operator.

Installed `dhall` via:
`stack install dhall --resolver=nightly-2018-11-21`

Reproduce:
The 3 `\` is to compensate for escaping. I was actually working within a file.
```
dhall <<< "{ foo : Natural } //\\\ { bar : Text }"

Error: Invalid input

(stdin):1:21:
  |
1 | { foo : Natural } //\ { bar : Text }
  |                     ^^^^^
unexpected "\ { b"
expecting "Some", "constructors", "merge", '(', built-in expression, double literal, import, integer literal, label, list literal, natural literal, record type or literal, text literal, union type or literal, or whitespace
```

```
dhall <<< "{ foo : Natural } ⩓ { bar : Text }"   
{ bar : Text, foo : Natural }
```

I checked on dhall-1.20.1 and that works fine for both versions of the operator. Are we able to fix the issue within this version tag? Otherwise I could look at updating dhall-bhat to a newer version.

**Comment by Gabriel439** [comment]
@FintanH: Yeah, I think it's fine to create a new tag/release to backport the change to 1.18.0 as long as the order on the releases page is sensible (i.e. it doesn't show up as a newer release than the latest one, 1.20.1)

**Comment by sjakobi** [comment]
v1.18 is pretty out of date now, so I assume this can be closed.
