### ISSUE TITLE
[Feature Request] Add :explain command to REPL

### ISSUE THREAD

**Issue by ari-becker** [dhall-lang/dhall-haskell#823]
Currently, if I try to evaluate an invalid expression in the REPL, the REPL prints the normal error message. Occasionally, this isn't enough information to help me understand the underlying issue. To address this, the `dhall` executable has a `--explain` flag which prints a more verbose error message. However, when using the REPL, there isn't currently a way to evaluate an expression within the REPL and have the REPL print a more verbose error message, as though the `--explain` flag were enabled; thus, a user currently has to switch away from the REPL, copy and paste the expression into a `dhall --explain <<< '...'` template, and then switch back to the REPL to continue. This is a (small) annoyance / headache / drag on productivity.

My request is to add a `:explain` command to the REPL, such that if the expression produces an error, the error printed within the REPL mirrors the error which would be printed by `dhall --explain`. This would make it easier to stay within the REPL during day-to-day development.

**Comment by ocharles** [comment]
We could also imagine `:set --explain`.

**Comment by Gabriel439** [comment]
@ocharles: Actually, `dhall repl` already accepts an `--explain` flag! :slightly_smiling_face: (I didn't know this either until I saw the code for it)

I also think `:set --explain`/`:unset --explain` is the interface I'll go with for this

**Comment by ocharles** [comment]
Ha, I guess that suggests the right interface!

**Comment by basile-henry** [comment]
I guess it's a bit too late to ask but why did you choose `--explain` over `explain`? 

I assumed we use `--` in the CLI argument because it a simple (non positional) option. In the case of `set/unset` where we're interacting with a set of options, I don't think `--` adds anything.

**Comment by Gabriel439** [comment]
@basile-henry: It's mainly for consistency with how `ghci` works, where it uses the exact format of the command-line option (i.e. `:set -XOverloadedStrings`), but I'm not strongly attached to the leading `--`

**Comment by basile-henry** [comment]
I didn't think of the `ghci` equivalent! 👍
It's a good argument to keep it as it is.

I wonder how to make all these options discoverable. Maybe we should get a `:help` / :help cmd` to describe every REPL commands and their arguments.

**Comment by ocharles** [comment]
`:set` could probably have tab completion - that might be supported with repline, I forget.
