### ISSUE TITLE
Possibility to quasiquote Dhall and embed it in a Haskell program

### ISSUE THREAD

**Issue by CMCDragonkai** [dhall-lang/dhall-haskell#838]
Is it possible to use QuasiQuotes feature and Dhall together so that Dhall expressions can be embedded within a Haskell file? Would the Dhall expressions be capable of being type-checked at compile time with Haskell? So an a quasiquoted dhall expression returns the type of a Dhall expression, not some arbitrary string. I didn't see any examples of this on the documentation for Dhall.

**Comment by Gabriel439** [comment]
@CMCDragonkai: I believe you can use `Dhall.TH.staticDhallExpression` for this purpose:

https://hackage.haskell.org/package/dhall-1.20.1/docs/Dhall-TH.html#v:staticDhallExpression

**Comment by Gabriel439** [comment]
Closing for now as I believe `Dhall.TH.staticDhallExpression` addresses this.  Feel free to reopen if you have additional questions
