### ISSUE TITLE
dhall cli: alpha normalization

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-haskell#853]
Would be great if there were a `dhall normalize --including-alpha` or similar that would completely normalize an expression -- trying to debug semantic hashes, but the hash is of encoded alpha-normalized expression and the only output I can get it encoded non-alpha-normalized.

**Comment by Gabriel439** [comment]
I agree!  I've also been meaning to add this for another reason: we could enable Unicode identifiers and optionally α-normalize expressions when auditing them to bypass Unicode obfuscation attempts

**Comment by Gabriel439** [comment]
Pull request up here: https://github.com/dhall-lang/dhall-haskell/pull/855
