### ISSUE TITLE
hGetContents fails on nix

### ISSUE THREAD

**Issue by bbarker** [dhall-lang/dhall-haskell#865]
In a 3rd party package, I'm trying to use dhall files, which frequently have unicode. This is on a Nix system. Here's an example file:

```dhall
let prelude = https://hackage.haskell.org/package/ats-pkg/src/dhall/atspkg-prelude.dhall

in prelude.default ⫽
  { test =
    [ prelude.bin ⫽
      { src = "test/monads.dats"
      , target = "${prelude.atsProject}/monads"
      }
    ]
  }
```

It has two unicode symbols; I'm not sure what they mean in the Dhall language (would be curious to know though). 

When trying to use the 3rd party software (atspkg), I get the following error:

```
$ atspkg build
atspkg: 
 /home/brandon/workspace/monads/atspkg.dhall
/home/brandon/workspace/monads/atspkg.dhall: hGetContents: invalid argument (invalid byte sequence)
```

This can be reproduced by cloning [this small repo](https://github.com/vmchale/monads) and running the above command in it. `atspkg` is available through haskellPackages on nix, though I seemed to have to manually edit in the latest version of atspkg for it to build on my system - YMMV.

I've also tried e.g. `LC_ALL=en_US.UTF-8 atspkg build`, but this also fails. See downstream issue: https://github.com/vmchale/atspkg/issues/11

**Comment by vmchale** [comment]
Might try replacing `readFile` with

```
import qualified Data.Text as T
import System.IO

-- | Read a file as utf-8 (necessary for rpi)
readFile' :: FilePath -> IO T.Text
readFile' filepath = do
    handle <- openFile filepath ReadMode
    hSetEncoding handle utf8
    TIO.hGetContents handle
```

?

**Comment by Gabriel439** [comment]
@vmchale: You might need to add this line to the beginning of the `main` subroutine for `atspkg` if you haven't already done so:

```haskell
GHC.IO.Encoding.setLocaleEncoding System.IO.utf8
```

The `dhall` executable does the same thing here:

https://github.com/dhall-lang/dhall-haskell/blob/dce46fc6c82da4f0e1b80d39df0fc13158c9506c/dhall/src/Dhall/Main.hs#L278

**Comment by sjakobi** [comment]
https://github.com/vmchale/atspkg/issues/11#issuecomment-475920996 indicates that `dhall` was behaving fine.

I'll close this then – feel free to reopen if there are things left that need to be addressed.

If you would like to learn more about Dhall, take a look at https://learnxinyminutes.com/docs/dhall/! :)

**Comment by sjakobi** [comment]
@bbarker Also note that you can use `dhall format --ascii` to convert any Dhall source files to ASCII-only.
