### ISSUE TITLE
Dhall quasiquoter?

### ISSUE THREAD

**Issue by arianvp** [dhall-lang/dhall-haskell#869]
It would be super useful to have quasiquotation support ala http://hackage.haskell.org/package/shakespeare  for code generators written in Haskell. It would make writing things like dhall-kubernetes really easy whilst guaranteeing well-formed code.

**Comment by Gabriel439** [comment]
Yeah, I would welcome a pull request to do this.  I won't have time to address this myself for a bit, though

**Comment by arianvp** [comment]
This seems related but not sure if duplicate. My request seems to be more specific (support interpolating haskell values) https://github.com/dhall-lang/dhall-haskell/issues/838

**Comment by Gabriel439** [comment]
@arianvp: I'll just close the other issue since it's narrow and I believe it is addressed by the proposed solution
