### ISSUE TITLE
Using `input` with derived `Interpret` instances

### ISSUE THREAD

**Issue by mpickering** [dhall-lang/dhall-haskell#879]
I am trying to work out how to use derived `Interpret` instances with the `input` function. 

For example:

```
data Field = A | B deriving (Generic, Show)                                          
                                                                                    
instance Interpret Field                                                    
                                                                                    
data Config = Config { cradle :: Field }                                           
    deriving (Generic, Show)                                                        
                                                                                    
instance Interpret Config                                                           
                                                                                    
readConfig :: FilePath -> IO Config                                                 
readConfig fp = T.readFile fp >>= input auto
```

If the config file is something like 

```
{ cradle = Field.A }
```

Then `Field.A` is not in scope, neither is `A`. I expected that using `input` with `auto` would add the derived constructors to the environment when during the interpretation. 

Then I tried to work out how to add these constructors to the environment so they were automatically in scope but couldn't find an easy way to do that either and gave up.

So, how am I supposed to use these derived instances with `input`?

**Comment by ocharles** [comment]
Dhall doesn't name the types, so your config file would look like:

```
{ cradle = < A = {=} : B : {} > }
```

That's a normal form, so you can of course provide a nicer Dhall API:

```
let Field : Type = < A : {} | B : {} > in { cradle = Field.A {=} >
```

**Comment by mpickering** [comment]
@ocharles I don't want every user to have to write definitions in this way.

Going from the [tutorial](http://hackage.haskell.org/package/dhall-1.21.0/docs/Dhall-Tutorial.html) these convenience constructors are already generated for explicit lets (as in your example) but I wanted to know how to make the let implicit by adding the relevant definitions to a context.

**Comment by ocharles** [comment]
Ok, then I think you want to use `inputWithSettings`, and override the `startingContext` to have your `Field` type in the environment.

**Comment by mpickering** [comment]
I triedreadConfig :: FilePath -> IO Config                                                 
readConfig fp = T.readFile fp >>= inputWithSettings ip auto                                           
  where                                                                         
    ip = (set startingContext sc defaultInputSettings)                          
    sc = C.insert "Field" (expected (auto @Field)) C.empty
```

But this leads to an uninformative error message

```
Field : < A :
                   {}
               | B :
               ===========
               | C :
                   {}
               >

Error: Not a record or a union

           Field.A
```

**Comment by mpickering** [comment]
I also tried adding a normaliser rule but that doesn't work either and behaves differently to wrapping the expression in a `let Cradle : Type = < ... >`.

```
sc = C.insert "Cradle" (Const Dhall.Core.Type) C.empty
                                                                                                  
norm (Var "Cradle") = Just (denote $ expected (auto @CradleConfig))         
norm _ = Nothing
```

**Comment by Gabriel439** [comment]
@mpickering: You definitely want to wrap it in a `let` expression to get the desired behavior.  As far as I know that is the only approach that will do what you want

**Comment by mmhat** [comment]
I had the same issue and used the approach described in #794.
Since I found the neither that solution nor the let-wrapping very satisfying I started working on a simple substitution mechanism: https://github.com/mmhat/dhall-haskell/tree/substitution

@Gabriel439 Would such an extension be accepted?

**Comment by Gabriel439** [comment]
@mmhat: Yeah, I would accept that
