### ISSUE TITLE
Stripping leading tabs from multiline strings

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-haskell#880]
https://github.com/dhall-lang/dhall-lang/blob/master/standard/multiline.md
> This feature only strips spaces (i.e. \u0020) and not any other form of whitespace. For example, leading tabs are not stripped in this way.

However, `dhall-haskell` treats \u0009 as if it were a single space (\u0020) for the purposes of its algorithm.

This has been an *extremely* useful bug for me, since I want to be able to use multiline string literals in indented positions in my Dhall code (which would be impossible if leading tabs were not stripped), so I would like this to be a feature and not a bug.  However, as the standard is currently written it is a bug.

**Comment by Gabriel439** [comment]
@singpolyma: So at the time I standardized that, my rationale for initially omitting tabs was to avoid weird behavior when dealing with mixed tabs and spaces.  I thought that if we supported tabs then we would need to standardize how many spaces a tab is worth for the purpose of stripping leading space.

However, thinking about this more closely, there may be a better solution which avoids that problem.  We could instead specify that the algorithm strips the longest shared whitespace prefix (consisting of either tabs or spaces).  In other words, if line 1 begins with " \t" and line 2 begins with "\t " then the algorithm strips nothing, but if both lines begin with " \t" then the prefix is stripped.

**Comment by singpolyma** [comment]
> In other words, if line 1 begins with " \t" and line 2 begins with "\t " then the algorithm strips nothing, but if both lines begin with " \t" then the prefix is stripped.

Either this or say that if any line starts with a tab, then spaces are not counted. A tab coming *after* a space is basically always a typo.

Your proposal may be simpler and work out the same in practise.

**Comment by singpolyma** [comment]
https://github.com/dhall-lang/dhall-lang/pull/519
