### ISSUE TITLE
Cache local files implicitly

### ISSUE THREAD

**Issue by jvanbruegge** [dhall-lang/dhall-haskell#888]
Dhall features already the ability to cache values by adding their `sha` hashes to the import definition. This works really well for remote files that should only ever get imported in the one version that was vetted by the developer.
But sometimes local files in the same repo can grow quite large and take longer to evaluate. But putting a `sha` hash on every import just to leverage caching is really cumbersome for development and not really needed (as most likely those files are also written by you).

To resolve this, the dhall interpreter could automatically cache **every** dhall file. Currently, importing works like this (assuming no `sha` on the import):
`download/read file -> normalize -> replace import with normalized expression`
in the future, this could be changed to:
`download/read file -> hash file -> check cache for (filepath, hash) -> iff equal use cached expression, else normalize, overwrite cache and use`

I am opening the issue here, because this (IMO) orthogonal to the standard and just a performance improvement of the interpreter.

ADDIT: To do this faithfully, the interpreter would have first resolve all imports of the file (and the imports of that and so on), and check their hashes.

**Comment by jvanbruegge** [comment]
cc @f-f @sellout

**Comment by f-f** [comment]
Yep, this is an interesting idea.

To add another motivation for doing something like this: sometimes you freeze files just for better performance, and there are two possible failure modes in the way the cache works right now:
- let's say you start with a valid `./foo sha256:whatever`. Then upon evaluation the `whatever` file will be written in cache. If you decide to change that import but accidentally leave the hash there (e.g. → `./bar sha256:whatever`), Dhall won't complain and will keep importing the expression from the cache
- similarly, if you have a cached import `./foo sha256:something` and change the source file of `./foo`, Dhall won't complain and will keep importing the expression from the cache

I think having some kind of separate "source hashes cache" would prevent both issues (given that the imports would then not use hashes)

**Comment by Gabriel439** [comment]
Would this improve performance, though?  If the hash is not already present then computing the hash for a file requires parsing and normalizing the file, so by the time you determine that the file is cached you've already done all the work.

**Comment by f-f** [comment]
@Gabriel439 I meant "hashing the source" (i.e. the Bytestring) vs. "hashing the expression" (sorry if it wasn't clear from my comment)

**Comment by jvanbruegge** [comment]
@Gabriel439 only the imports would have to be "parsed", a task that the lexer can do. Yeah for the cache, the source would be hashed not the final expression

**Comment by Gabriel439** [comment]
Hashing the source doesn't guarantee that the expression hasn't changed.  The simple example is if the source code that you hash imports another expression without an integrity check.  The transitive import could then change, which would require invalidating the cache.

**Comment by jvanbruegge** [comment]
@Gabriel439 that's why I said that you would have to use the lexer to quickly get the imports too.
You could do: `imported file -> source hash changed? -> yes: proceed as currently; no: lex for imports & repeat`

**Comment by Gabriel439** [comment]
Ah, I see.  Yeah, then I think this would work

**Comment by f-f** [comment]
However, I'd do this only for local imports, because doing the check transitively becomes really expensive really quickly if there's network latency

**Comment by jvanbruegge** [comment]
Yeah, you would most likely use `sha` imports for remote files anyways

**Comment by jvanbruegge** [comment]
It would also be possible to cache the imports of a file together with the expression, so if the source hash does not change, you could simply use the filepaths from the cache without needing to lex the file.
Also, in the case of renormalization in the case of changes, the leaf imports that did not change can be reused directly from the cache.

**Comment by Gabriel439** [comment]
@jvanbruegge: You might be interested in https://github.com/dhall-lang/dhall-haskell/pull/1040 which is doing something similar just within the scope of a `dhall-lsp-server` session

**Comment by Gabriel439** [comment]
Fixed by #1154
