### ISSUE TITLE
shell.nix for testing/using core Dhall command-line tools

### ISSUE THREAD

**Issue by antislava** [dhall-lang/dhall-haskell#898]
I was missing a user-friendly nix shell (with all the core Dhall executables including shell completions etc) in the root directory, along with `default.nix`: https://github.com/dhall-lang/dhall-haskell/compare/master...antislava:antislava/nix-shell.
I thought that maybe others would find it useful as well? 
At the very least, it would nice for `nix/shared.nix` to export `nixpkgs` (with the respective overlays etc) to facilitate building such shells by end users on an ad-hoc basis and doing development in `nix repl`, or, alternatively export the set of overlays (in which case it would also be nice to factor out the pinned base `nixpkgs` into a separate `nixpkgs.nix` as well to skip copy-pasting the `fetchNixpkgs` argument set or doing something as ugly as `import <nixpkgs> {}` ;-)).

**Comment by Gabriel439** [comment]
@antislava: Yeah, you can open a pull request if you want to add a top-level `shell.nix`
