### ISSUE TITLE
Improve error messages by adding line numbers

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#905]
I have a really hard time parsing the `=====` separator in error messages. I think I'd have a much easier time understanding the output if all lines in the error message were annonated with line numbers.

Here is the error that has me frustrated

```
ou tried to invoke the following function:                                     
                                                                                
↳ List/fold
  (   (   ∀(Instruction : Type)
        → ∀(External : Text → List Text → Instruction)
  ====================================================
        )
    → Instruction
  )
                                                                                
... which expects an argument of type or kind:                                  
                                                                                
↳   (   (   ∀(Instruction : Type)
          → ∀(External : Text → List Text → Instruction)
          → ∀ ( Builtin
  ======================================================
        → Instruction
      )
  → Instruction
                                                                                
... on the following argument:                                                  
                                                                                
↳   λ ( f
      :   (   ∀(Instruction : Type)
            → ∀(External : Text → List Text → Instruction)
  ========================================================
        → Instruction
      )
  → f x
                                                                                
... which has a different type or kind:                                         
                                                                                
↳   ∀ ( f
      :   (   ∀(Instruction : Type)
            → ∀(External : Text → List Text → Instruction)
  ========================================================
        → Instruction
      )
  → Instruction

────────────────────────────────────────────────────────────────────────────────

            List/fold
                (./Instruction.dhall → ./Instruction.dhall)
                instructions
=============================================
                  → f x
                )

/home/ollie/work/dhallix/nix-derivation/examples/execline/Sequence.dhall:4:13
```

Of course this will be difficult as right now I believe the display expression is pretty printed, and not what the user provided as input.

**Comment by Gabriel439** [comment]
@ocharles: Yeah, it's not just pretty-printed, but also normalized, so there is not necessarily any correspondence between the expression and the original source code

**Comment by ocharles** [comment]
Ah yea, I didn't consider normalisation. That makes it even harder!

**Comment by Gabriel439** [comment]
@ocharles: However, note that the last code excerpt at the bottom does correspond to the original source code, so we could add line numbers to that if it would help

**Comment by ari-becker** [comment]
> Of course this will be difficult as right now I believe the display expression is pretty printed, and not what the user provided as input.

For what it's worth, the pretty-printing follows what `dhall format` outputs. So if you write your code according to the auto-formatter, it'll make it easier to follow the error messages.

In general, I find that if the expression at the given location (`4:13` in your case) is so large as to have an incomprehensible error message, it's usually a sign that I need to break the expression up into smaller expressions.

**Comment by Gabriel439** [comment]
I think there is something I can do, which is to just greatly increase the threshold before truncation.  I think only 3 lines of context is not enough.  We could probably increase it to 20 lines on each side of the separator without issue because the separator was only really added to deal with gigantic expressions.

**Comment by Gabriel439** [comment]
Fix is up here:

https://github.com/dhall-lang/dhall-haskell/pull/919

... and the related improvement is up here:

https://github.com/dhall-lang/dhall-haskell/pull/916
