### ISSUE TITLE
API changes not mentioned in 1.22's changelog

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-haskell#914]
I ran into these breaking changes without forewarning while porting dhall-to-cabal:

* #863

* #851 (particularly pernicious because the cleanly removed line doesn't show on blame)

**Comment by quasicomputational** [comment]
Perhaps worth noting that they're both knock-on changes from the new version of the standard, and if I'd carefully inspected that changelog and thought about the impact it'd have on implementations, I could've been less surprised. But I'm not smart enough for that (that's half the reason I'm keen on Dhall, to get the computer to spot my stupidity in more cases!), and I'm not sure many users will be.

**Comment by Gabriel439** [comment]
Yeah, this is my mistake.  I should have at least noted which changes related to 7.0.0 would break the API.  I can fix the CHANGELOG

**Comment by Gabriel439** [comment]
@quasicomputational: Also, while we're on this subject, remember that the offer is still open to merge `dhall-to-cabal` into this repository so that any change that breaks `dhall-to-cabal` blocks merge until we fix `dhall-to-cabal`

**Comment by quasicomputational** [comment]
I'm thoroughly neutral on the idea.

I like monorepos in general, but `dhall-to-cabal` has a complicated GHC upgrade story - it has to adapt to the accompanying Cabal changes first, which could be quite involved, and in a monorepo it's hard (but not impossible) to hold a single package back while also forging ahead with the others. Lagging being easy isn't an untrammelled negative in this case, and might even be positive on balance.

So, yeah. The trade-off isn't obvious to me one way or the other and so I'd tend to leave the status quo be, but I wouldn't object at all if you weigh it differently and want to go ahead with merging.

**Comment by Gabriel439** [comment]
@quasicomputational: Yeah, the proposal is mainly for your benefit, not mine.  If it's easier to manage to `dhall-to-cabal` as a separate repository then keep it that way

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/917
