### ISSUE TITLE
stack-lts-11.yaml seems to have bitrotted

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-haskell#921]
It's not being tested in CI, it seems, and it's currently unhappy:

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for dhall-1.22.0:
    cborg-json must match <0.3, but the stack configuration has no specified version  (latest matching version is 0.2.1.0)
    dotgen must match >=0.4.2 && <0.5, but the stack configuration has no specified version  (latest matching version is 0.4.2)
needed since dhall is a build target.
```

I suggest we either remove it or stick it into CI somehow (AppVeyor?).

**Comment by Gabriel439** [comment]
@quasicomputational: I'm fine with removing it if nobody is using it.  I think we should test at most two Stack configurations: one for the oldest GHC supported and one for the latest GHC supported

**Comment by quasicomputational** [comment]
Yeah, sounds like a plan. LTS 6 and 12 are used in AppVeyor; 13 is in `stack.yaml` which presumably people use in local development, so we'd know if that was broken.
