### ISSUE TITLE
Nix: Upgrade from 8.6.1 to 8.6.5.

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-haskell#925]
8.6.1 had a couple of really awful bugs in it - including two that are being worked around in the derivations. Upgrading will both simplify the configuration and mean that there's less risk of a crazy bug biting in CI.

I had a go in #923, but there are difficulties: @Gabriel439 said

> @quasicomputational: The reason I haven't upgraded to GHC 8.6.5 yet in CI is because we're pinned to a revision of Nixpkgs that precedes it because we depend on it for static linking of executables (See: NixOS/nixpkgs#43795). Once full static linking support is available in Nixpkgs `master then we can upgrade.
>
> As a result, you get an evaluation error on this branch: https://hydra.dhall-lang.org/jobset/dhall-haskell/923#tabs-errors
>
> Alternatively, we could backport the GHC 8.6.5 derivation to the revision of Nixpkgs that we currently use

**Comment by Gabriel439** [comment]
This was fixed by https://github.com/dhall-lang/dhall-haskell/pull/2001
