### ISSUE TITLE
genericAuto is broken

### ISSUE THREAD

**Issue by quasicomputational** [dhall-lang/dhall-haskell#926]
Running against 4f9defec2516edab4707f85c1bfec7e1eac09f72, this program

```haskell
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}
import GHC.Generics (Generic)
import qualified Dhall

data CompilerFlavor =
  GHC | GHCJS
  deriving (Generic, Show)

main =
  print =<< Dhall.input
    (Dhall.genericAuto :: Dhall.Type CompilerFlavor)
    "< GHC : {} | GHCJS : {} >.GHC {=}"
```

produces this output

```
foobar: Error: Invalid Dhall.Type                                                  
                                                                                
Every Type must provide an extract function that succeeds if an expression      
matches the expected type.  You provided a Type that disobeys this contract     
                                                                                
The Type provided has the expected dhall type:                                  
                                                                                
↳ < GHC : {} | GHCJS : {} >
                                                                                
and it couldn't extract a value from the well-typed expression:                 
                                                                                
↳ < GHC : {} | GHCJS : {} >.GHC {=}
```

The unary case also seems to be broken - if you delete the `GHCJS` constructor in both Haskell and the Dhall input, the output is instead

```
Error: Expression doesn't match annotation

- { … : … }
+ < … : … >

1: < GHC : {} >.GHC {=} : {}

(input):1:1
```

but I'd also expect it to have worked.

This code seems to have worked in 1.21, so this is a regression that's probably affecting 1.22, though I haven't actually tested this specific example on the as-released versions.

**Comment by quasicomputational** [comment]
Here's the bug - it's quite like #915:

https://github.com/dhall-lang/dhall-haskell/blob/66df01b26c0985363eba0af1edd9d9cd481b7357/dhall/src/Dhall.hs#L956-L960

That needs to learn about the new style of union. I'll see about a PR.

**Comment by quasicomputational** [comment]
Ah - the single constructor case isn't a bug at all. It just wants to be a record, not a union, which does actually make perfect sense.

**Comment by Gabriel439** [comment]
@quasicomputational: Also, keep in mind that it should expect a type of `< GHC | GHCJS >` now

**Comment by quasicomputational** [comment]
@Gabriel439: I think that's a separable change. This issue's about just getting it to work at all again for sum types; making it use the snazzy new syntax for nullary constructors doesn't overlap (that) much, I don't think.

**Comment by Gabriel439** [comment]
@quasicomputational: Alright.  We can defer that to a separate change
