### ISSUE TITLE
Small url parsing bug

### ISSUE THREAD

**Issue by Nadrieril** [dhall-lang/dhall-haskell#932]
The import `https://example.com/"a%20b"/c` gets parsed as `https://example.com/"a b"/c`, but only unquoted path components should be url-decoded.
I have a test for that in https://github.com/dhall-lang/dhall-lang/pull/523.

**Comment by Gabriel439** [comment]
Yeah, this is definitely a bug.  I will fix this as part of pulling in the latest test suite once you merge your new tests

**Comment by sjakobi** [comment]
Fixed in #1084.
