### ISSUE TITLE
Double quotes with a text value

### ISSUE THREAD

**Issue by erthalion** [dhall-lang/dhall-haskell#933]
Most likely it's a strange question, but I'm struggling with one aspect of dhall.

I want to generate some yaml, that should be processed by another service. The problem is with one value, which happened to be a date in a text format (do not ask me why). Due to quirks of a parsing library, that this service uses, the value should be quoted (like `value: "2000-00-00"`), otherwise it would be parsed as a date time. Of course dhall generates it as `value: 2000-00-00` and all my attempts to put single quotes or load value as a text didn't succeed (I've got `value: ! '2000-00-00'` or `value:|\n2000-00-00` etc, but it didn't help to trick this third party library). So I wonder if it's possible to generate `value: "2000-00-00"` via dhall?

**Comment by f-f** [comment]
@erthalion would this work?

```bash
dhall-to-yaml <<< 'Text/show "2000-00-00"'
'"2000-00-00"'
```

**Comment by erthalion** [comment]
Thanks @f-f - unfortunately no, I've tried this too.

**Comment by Gabriel439** [comment]
Yeah, this can't be fixed within the language.  The place to fix this is in our use of the Haskell `yaml` package.  My guess is that by default it's opinionated about whether or not to quote strings, but this behavior might be configurable.

**Comment by erthalion** [comment]
> Yeah, this can't be fixed within the language. The place to fix this is in our use of the Haskell yaml package. My guess is that by default it's opinionated about whether or not to quote strings, but this behavior might be configurable.

After a short investigation I found out that there are EncodingOptions in the yaml package, so something like that would work for me:

```haskell
isDate s = case parsed :: Maybe UniversalTime of
  Just v  -> True
  Nothing -> False
  where
    parsed = parseTimeM False defaultTimeLocale "%Y-%m-%d" (T.unpack s)

customStyle = \s ->
     case () of
      ()
        | isDate s  -> (NoTag, SingleQuoted)
        | otherwise -> (NoTag, PlainNoTag)

main = print $ encodeWith opts (Object {value = "2000-01-01"})
  where
    opts = setStringStyle customStyle defaultEncodeOptions

-- Produces "version: '2017-09-20'\n"
```

**Comment by Gabriel439** [comment]
@erthalion: Do you need command-line support for that or does the solution with the Haskell API work for you?

**Comment by erthalion** [comment]
I'm actually not sure how to incorporate it easily via just API, so I guess command-line support would be great (as an example of what I'm talking about I've created #941 )
