### ISSUE TITLE
Custom Headers Issue in HTTP/HTTPS Import Request Path

### ISSUE THREAD

**Issue by awseward** [dhall-lang/dhall-haskell#947]
:wave: Hi there!

It looks like dhall 1.22.0 and later has started adding the `using <headers import>` part of the  expression for HTTP/HTTPS imports into the path of the request’s URL, causing the import to fail with a 404 response.

For example,
```sh
dhall <<< 'https://example.com/foo.dhall using ./headers.dhall`
```
results in a request to `https://example.com/foo.dhall%20using%20./headers.dhall` instead
of the intended `https://example.com/foo.dhall`.

---

I put together a gist containing an example to reproduce the issue here: https://gist.github.com/awseward/baba6891b357671843062743c1c02d0d

Hopefully it may be of some help!

I’ll have a look at what it might take to solve this to see if I can help, but as I’m fairly new to dhall and haskell in general I figured it’d be worth pointing out in the meantime.

Thanks!

**Comment by ocharles** [comment]
I think the problem is that you are quoting what goes into <<<. Try
removing the quotes, does that work?

**Comment by awseward** [comment]
Just gave that a try, no luck..

```sh
root@bd10aed9fc2a:/scratch# dhall <<< https://example.com/foo.dhall using ./headers.dhall
Invalid argument `using'

Usage: dhall ([version] | [resolve] | [type] | [normalize] | [repl] | [diff] |
             [hash] | [lint] | [format] | [freeze] | [encode] | [decode] |
             [--annotate] [--alpha]) [--explain] [--plain] [--ascii]
             [--standard-version X.Y.Z]
  Interpreter for the Dhall language
```

I figured I'd try via passing just the name of a file containing that same expression to `dhall <<< ` as well.

Still the same URL path behavior there.

```sh
root@ffd95e453e06:/scratch# cat import.dhall
http://localhost:8000/foo.dhall using ./headers.dhall

root@ffd95e453e06:/scratch# dhall <<< ./import.dhall
WARNING:root:Host: localhost:8000
Accept-Encoding: gzip
Authorization: foo
Accept: text/plain

127.0.0.1 - - [12/May/2019 08:51:38] code 404, message File not found
127.0.0.1 - - [12/May/2019 08:51:38] "GET /foo.dhall%20using%20./headers.dhall HTTP/1.1" 404 -

↳ ./import.dhall
  ↳ http://localhost:8000/foo.dhall using ./headers.dhall

Error: Remote file not found

1: http://localhost:8000/foo.dhall using ./headers.dhall

/scratch/import.dhall:1:1
```

**Comment by Gabriel439** [comment]
@awseward: What output do you get if you run the following command?

```
$ dhall encode --json <<< 'https://example.com/foo.dhall using ./headers.dhall'
```

... also paste the output version of your interpreter:

```
$ dhall version
```

**Comment by Gabriel439** [comment]
@awseward: For some reason I cannot reproduce this locally.

So the reason I suggest using the above command is that it is a much smaller way to reproduce this that doesn't require a running server (and therefore doesn't require a container).  `dhall encode --json` dumps a standard representation of its internal syntax tree and from that representation you can tell how `dhall` parsed the code.

For example, using version 1.22.0 of the Haskell package, I get the following result:

```
$ ./bin/dhall version
Haskell package version: 1.22.0
Standard version: none

$ ./bin/dhall encode --json <<< 'https://example.com/foo.dhall using ./headers.dhall'
[
    24,
    null,
    0,
    1,
    [
        24,
        null,
        0,
        3,
        "headers.dhall"
    ],
    "example.com",
    "foo.dhall",
    null
]
```

... which according to the [official binary encoding](https://github.com/dhall-lang/dhall-lang/blob/v7.0.0/standard/binary.md) means that `using ./headers.dhall` was correctly parsed and not interpreted as part of the URL.

You can also confirm this by just trying to interpret it, and interpretation fails in the expected way:

```
$ ./bin/dhall <<< 'https://example.com/foo.dhall using ./headers.dhall'              

↳ https://example.com/foo.dhall using ./headers.dhall

↳ ./headers.dhall

Error: Missing file /tmp/test/headers.dhall

https://example.com/foo.dhall using ./headers.dhall

(stdin):1:1
```

... which shows that it correctly parsed `headers.dhall` as part of the `using` clause.

For comparison, here is what you get if you quote `foo.dhall using .`:

```
$ ./bin/dhall encode --json <<< 'https://example.com/"foo.dhall using ."/headers.dhall'
[
    24,
    null,
    0,
    1,
    null,
    "example.com",
    "foo.dhall using .",
    "headers.dhall",
    null
]
```

```
$ ./bin/dhall <<< 'https://example.com/"foo.dhall using ."/headers.dhall'              

↳ https://example.com/"foo.dhall using ."/headers.dhall

Error: Remote file not found

https://example.com/"foo.dhall using ."/headers.dhall

(stdin):1:1
```

... which is what I would expect to see if I could reproduce the issue locally, but I don't see that behavior without the explicit quotes.

**Comment by awseward** [comment]
When just encoding, my output matches yours:
```
root@527678ce2ffb:/scratch# /bin/dhall version
Haskell package version: 1.22.0
Standard version: none

root@527678ce2ffb:/scratch# /bin/dhall encode --json <<< 'https://example.com/foo.dhall using ./headers.dhall'
[
    24,
    null,
    0,
    1,
    [
        24,
        null,
        0,
        3,
        "headers.dhall"
    ],
    "example.com",
    "foo.dhall",
    null
]
```

However, I got a different error from yours when I tried actually interpretting it:
```
root@527678ce2ffb:/scratch# /bin/dhall <<< 'https://example.com/foo.dhall using ./headers.dhall'

↳ https://example.com/foo.dhall using ./headers.dhall

Error: Remote file not found

https://example.com/foo.dhall using ./headers.dhall

(stdin):1:1
```
☝️It's still trying to make the request to a URL including the `using ...` clause in its path.

This is also not the same error you had when you tried to interpret the import. Your error just stated that the custom headers file wasn't present.

So I tried this next:  (I should specify that, like its name, `doesnotexist.dhall` does not actually exist)
```
root@527678ce2ffb:/scratch# /bin/dhall <<< 'https://example.com/foo.dhall using ./doesnotexist.dhall'

↳ https://example.com/foo.dhall using ./doesnotexist.dhall

↳ ./doesnotexist.dhall

Error: Missing file /scratch/doesnotexist.dhall

https://example.com/foo.dhall using ./doesnotexist.dhall

(stdin):1:1
```
Now our errors are matching up!

I wonder what the results of your first example of trying to interpret the import would look like if `/tmp/test/headers.dhall` from `Error: Missing file /tmp/test/headers.dhall` actually did exist.

---

I've put a container together that might be helpful to replicate the issue. You can find it in this gist [here](https://gist.github.com/awseward/baba6891b357671843062743c1c02d0d).

If you'd like to try running it to see if this issue still is not reproducible, the following should get you a shell in it:
```sh
git clone git@gist.github.com:baba6891b357671843062743c1c02d0d.git
cd baba6891b357671843062743c1c02d0d
./up.sh
```

**Comment by awseward** [comment]
This may be entirely unrelated, but it looks like the encoding for this expression did change between 1.21.0 and 1.22.0. 

![image](https://user-images.githubusercontent.com/901035/57586148-6cc8c180-74a6-11e9-912e-6491626559dd.png)

In diff form to highlight change from 1.21.0 to 1.22.0:
```diff
 [
     24,
     null,
     0,
     1,
     [
         24,
         null,
         0,
         3,
         "headers.dhall"
     ],
     "example.com",
     "foo.dhall",
-    null,
     null
 ]
```

**Comment by Gabriel439** [comment]
@awseward: Actually, for this example you gave:

```
root@527678ce2ffb:/scratch# /bin/dhall <<< 'https://example.com/foo.dhall using ./headers.dhall'

↳ https://example.com/foo.dhall using ./headers.dhall

Error: Remote file not found

https://example.com/foo.dhall using ./headers.dhall

(stdin):1:1
```

... that doesn't mean that it's including the `using` in the path.  That's only because the error message includes the `using` clause when pretty-printing the import.  If the interpreter had parsed the `using` as part of the path then it would have been quoted when pretty-printing, as in this example:

```
$ ./bin/dhall <<< 'https://example.com/"foo.dhall using ."/headers.dhall'              

↳ https://example.com/"foo.dhall using ."/headers.dhall

Error: Remote file not found

https://example.com/"foo.dhall using ."/headers.dhall

(stdin):1:1
```

Also, the difference in the encoding between versions 1.21.0 and 1.22.0 is expected.  That's because the language dropped support for fragment identifiers in URLs, which is what that final list field was being used to store.

**Comment by Gabriel439** [comment]
Ah, okay, I can reproduce the problem now.  This reproduces the problem (provided any present `./headers.dhall` file):

```
$ ./bin/dhall <<< 'https://httpbin.org/headers using ./headers.dhall as Text'

↳ https://httpbin.org/headers using ./headers.dhall as Text

Error: Remote file not found

https://httpbin.org/headers using ./headers.dhall as Text

(stdin):1:1
```

The problem is that while `dhall` parses things correctly, it accidentally including the `using` clause when rendering the URL to fetch.  I know how to fix this now.

**Comment by Gabriel439** [comment]
The root cause here is 4b7bdd458cf15927521e70a9dbcd13ca7ae2dc83, which is the commit that broke this.  That switched to using the `Pretty` instance for `URL`s to render them, which incorrectly includes the `using` clause.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/948

**Comment by awseward** [comment]
Awesome! Dhall is super neat and I've been really happy trying it out so far!

Thanks so much for taking a look so quickly and giving some context on what the issue was!

**Comment by Gabriel439** [comment]
@awseward: You're welcome!  🙂
