### ISSUE TITLE
Blank lines are counted toward the prefix in multiline strings

### ISSUE THREAD

**Issue by madjar** [dhall-lang/dhall-haskell#960]
It appears that the number of spaces in empty lines has an influence on how a multiline string is parsed.

With trailing whitespace:
```
  ''
  hello
  
  hello''
```
results in `"hello\n\nhello"`

But without:
```
  ''
  hello

  hello''
```
results in `"  hello\n\n  hello"`

If I understand correctly, this does not match the standard (which states "Blank lines, however, are not counted towards this prefix, unless they are the last line").

In practice, it plays very poorly with editors that remove trailing whitespace. For example, my current emacs settings apply `dhall format` and removes trailing whitespace on save, which means that all multiline strings get one additional level of indentation each time I save.

----
This applies to dhall 1.23.0. I have not yet tested master.

**Comment by Gabriel439** [comment]
@madjar: You're correct and that is fixed in #948, specifically by this code: https://github.com/dhall-lang/dhall-haskell/pull/948/files#diff-281e7ffb783d37c08218e547d14115b2R812

That change to the standard to ignore blank lines was recently added

**Comment by madjar** [comment]
Yeah, it just hit me I should have tried to reproduce with master before, and was looking at this exact commit a second ago :)

Thanks for your quick response!

**Comment by Gabriel439** [comment]
You're welcome! 🙂
