### ISSUE TITLE
dhall-json: yaml-pre-0_11 does not build

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-haskell#969]
Says it allows all the way down to yaml 0.5.0, but relies on features introduced in yaml 0.10.2.0 without CPP guards (namely, `encodeWith` and encoding options)

**Comment by quasicomputational** [comment]
Ah, that's annoying. It's been broken for a while, then: in #962, I tried to bump it to 0.11 across the board, but bounds rule it out on GHC 7.10. And 0.10.2.0 similarly requires GHC 8.0.

**Comment by Gabriel439** [comment]
@singpolyma: Do you need `dhall-json` to build for `yaml` versions earlier than `0.10.20` or would revising the lower bound to be `0.10.20.0` be an acceptable solution?

**Comment by jneira** [comment]
Mmm, if `yaml-0.10.20.0` doesnt work with `ghc-7.10.3`, we'll have to remove `dhall-json` from the appveyor build.
Strangely, [the appveyor build for the pr succeded for `ghc-7.10.3`](https://ci.appveyor.com/project/Gabriel439/dhall-haskell/builds/24756894/job/k6apc4yt33qds9yq), using `yaml-0.8.21.1`. 🤔

**Comment by jneira** [comment]
nvm, we dropped support for `dhall-json` with `ghc-7.10.3` in #943 (it introduced `encodeWith` too). So bump up lower bound to `0.10.20.0` would be fine.

**Comment by singpolyma** [comment]
> @singpolyma: Do you need `dhall-json` to build for `yaml` versions earlier than `0.10.20`

Yes. I am maintaining a small local patch for now that allows me to build it -- but it's not a "correct" patch since I just replace calls to encodeWith with calls to encode and ignore the options.

**Comment by Gabriel439** [comment]
@singpolyma: Note that the change I'm going to make is going to do the same thing (ignore the options for older versions of `yaml`), because as far as I know specifying the quoting for multi-line literals is not supported at all by older `yaml` versions.  However, that's the only thing it affects and in the worst case scenario it will just generate a weirdly formatted but still valid string literal.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/981
