### ISSUE TITLE
won't install using nix

### ISSUE THREAD

**Issue by cristim** [dhall-lang/dhall-haskell#979]
I have dhall 1.19.1 installed from nix and tried to update to the latest available from the latest channel, https://hydra.dhall-lang.org/jobset/dhall-haskell/master/channel/latest, but the installation fails with the following error message:

```
$ nix-env -u '*'
error: path '/nix/store/kxj9ss3d28srjqnnkm08fwrwpzi39p57-dhall-1.23.0' does not exist and cannot be created
(use '--show-trace' to show detailed location information)
```

**Comment by Gabriel439** [comment]
@cristim: I have a few questions that might help narrow this down:

* Are you using OS X?
* How did you install `dhall-1.19.1`?
* More generally, what related actions did you perform before `nix-env -u '*'` (i.e. all `nix-channel` or `nix-env` commands that you can remember related to installing `dhall`)

**Comment by cristim** [comment]
I am running nix on Ubuntu.

If I remember correctly, the 1.19.1 comes from the main nix channel, I am currently on the nix channel 19.03. I  noticed that it's an old version and lacks some features used in code written by a colleague who used a newer version.

I installed the additional nix channel from hydra.dhall-lang.org and tried to update the package but it fails. I also saw the same error when trying to install other packages from the same channel, such as the language server.

I suspect something is wrong with the channel or the way I added it to my machine but I just executed the given instructions and I can see the newer package listed when I query for it.

**Comment by Gabriel439** [comment]
@cristim: I don't know if you've tried this yet, but perhaps reinstall `dhall` before upgrading it.  In other words, first run `nix-env --install dhall` before trying to upgrade everything

**Comment by gamb** [comment]
Did you update binary caches? E.g.
```
  nix = {
    binaryCaches = [ "https://cache.nixos.org" "https://cache.dhall-lang.org" ];

    binaryCachePublicKeys = [
      "cache.dhall-lang.org:I9/H18WHd60olG5GsIjolp7CtepSgJmM2CsO813VTmM="
    ];
  };
```

**Comment by cristim** [comment]
Thanks, I'll try these tomorrow

**Comment by freuk** [comment]
I'm experiencing the exact same behavior on a NixOS system for a fresh dhall install, even with binary caches added.

**Comment by Gabriel439** [comment]
@freuk: What command are you using to install `dhall`?

**Comment by freuk** [comment]
```
$ nix-env -i "$(curl -L https://hydra.dhall-lang.org/job/dhall-haskell/master/linux-dhall/latest/api/get-info | jq -r .outPath)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   337  100   337    0     0   1914      0 --:--:-- --:--:-- --:--:--  1903
100   159  100   159    0     0    593      0 --:--:-- --:--:-- --:--:--   593
replacing old 'dhall-1.23.0'
installing 'dhall-1.23.0'
don't know how to build these paths:
  /nix/store/miwi1hmxnpfd2iiykmnzyl8infzhy0c8-dhall-1.23.0
error: path '/nix/store/miwi1hmxnpfd2iiykmnzyl8infzhy0c8-dhall-1.23.0' does not exist and cannot be created
```
This "old" dhall version here is due to using `nix-env` with the trick @PierreR  uses: https://xgitlab.cels.anl.gov/argo/argopkgs/blob/master/pkgs/default.nix#L505 , but the result is really the same regardless of what's in my environment, as can be expected.

**Comment by Gabriel439** [comment]
@freuk: This still looks like your cache settings are not correctly configured (possibly because the `README` instructions are incorrect).

When I run the same test on OS X (using Nix 2 and the cache settings from the `README`), I get this successfull install of the same `/nix/store` path:

```
$ nix-env -i "$(curl -L https://hydra.dhall-lang.org/job/dhall-haskell/master/linux-dhall/latest/api/get-info | jq -r .outPath)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   337  100   337    0     0   3650      0 --:--:-- --:--:-- --:--:--  3663

100   159  100   159    0     0   1112      0 --:--:-- --:--:-- --:--:--  1112
replacing old 'dhall-1.22.0'
installing 'dhall-1.23.0'
these paths will be fetched (0.00 MiB download, 18.53 MiB unpacked):
  /nix/store/937b1ps5v3ixg20s7wird5c5szlmw8pa-musl-1.1.19
  /nix/store/i9b8pkiaj96xx687i1vq964swr8s56jh-ncurses-6.1
  /nix/store/miwi1hmxnpfd2iiykmnzyl8infzhy0c8-dhall-1.23.0
copying path '/nix/store/937b1ps5v3ixg20s7wird5c5szlmw8pa-musl-1.1.19' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/i9b8pkiaj96xx687i1vq964swr8s56jh-ncurses-6.1' from 'https://cache.dhall-lang.org'...
copying path '/nix/store/miwi1hmxnpfd2iiykmnzyl8infzhy0c8-dhall-1.23.0' from 'https://cache.dhall-lang.org'...
building '/nix/store/69mwzza09nh0zqyia4y9blir336a8q2v-user-environment.drv'...
created 66 symlinks in user environment
```

What does your `/etc/nix/nix.conf` looks like (at least the lines related to caching)?

**Comment by cristim** [comment]
@Gabriel439 I just executed the same command you ran:
```
$ nix-env -i "$(curl -L https://hydra.dhall-lang.org/job/dhall-haskell/master/linux-dhall/latest/api/get-info | jq -r .outPath)"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   337  100   337    0     0    370      0 --:--:-- --:--:-- --:--:--   370
100   159  100   159    0     0    138      0  0:00:01  0:00:01 --:--:--   138
replacing old 'dhall-1.19.1'
installing 'dhall-1.23.0'
don't know how to build these paths:
  /nix/store/miwi1hmxnpfd2iiykmnzyl8infzhy0c8-dhall-1.23.0
error: path '/nix/store/miwi1hmxnpfd2iiykmnzyl8infzhy0c8-dhall-1.23.0' does not exist and cannot be created
```

I don't have the `/etc/nix/nix.conf` file, it's entirely missing on my machine.

**Comment by freuk** [comment]
@Gabriel439  I have these settings on:

```
      nix.binaryCaches = [
        "https://cache.nixos.org"
        "https://cache.dhall-lang.org"
      ];
      nix.binaryCachePublicKeys = [
        "cache.dhall-lang.org:I9/H18WHd60olG5GsIjolp7CtepSgJmM2CsO813VTmM="
      ];
      nix.trustedUsers = [ "root" "myuser" "@wheel" ];
```

**Comment by Gabriel439** [comment]
@freuk @cristim: What version of Nix are you using? (i.e. `nix-env --version`)

**Comment by freuk** [comment]
```
$ nix-env --version
nix-env (Nix) 2.2pre6526_9f99d624
```

**Comment by Gabriel439** [comment]
@freuk @cristim: Could you run this command and paste the output:

```
$ nix-env -vvvv --install /nix/store/miwi1hmxnpfd2iiykmnzyl8infzhy0c8-dhall-1.23.0
```

I believe that will provide more detailed information about how Nix is resolving binary substitutes (such as `cache.dhall-lang.org`)

**Comment by freuk** [comment]
Yeah, okay you were totally right. Thanks for your time @Gabriel439 it's an issue with setting the cache up. 

https://gist.github.com/freuk/03c4d2eb249a63788c667239828d1b8f 

My `/etc/nix/nix.conf` contains the right configuration. I ran the command as root and it went through fine, it's just an issue of the user nix-env configuration relying on `~/.config/nix/nix.conf` on NixOs instead of the system config!

**Comment by cristim** [comment]
I confirm it also works for me after adding the required configuration parameters to `/etc/nix/nix.conf`.

I should have read the installation docs more carefully, sorry for this noise.

**Comment by Gabriel439** [comment]
@cristim: No worries 🙂

**Comment by hussein-aitlahcen** [comment]
Hey, just a quick note on that. If someone is under NixOS and previously setup `~/.config/nix/nix.conf` with some binary caches, adding binary caches in the `/etc/nixos/configuration.nix` won't work (they are overwritten by the local conf). You just have to either use the local or the global one or you will face this issue :)
