### ISSUE TITLE
Ensure that asserting directory permissions doesn't end up in "user error: mzero" 

### ISSUE THREAD

**Issue by zudov** [dhall-lang/dhall-haskell#988]
Specifically this line when running in `IO`:

https://github.com/dhall-lang/dhall-haskell/blob/d8f2787745bb9567a4542973f15e807323de4a1a/dhall/src/Dhall/Import.hs#L559

I haven't checked, but unless something atop catches this it wouldn't fail nicely. This should be backported then https://github.com/spacchetti/spago/pull/250.

**Comment by zudov** [comment]
Another nice thing to have would be `assertDirectoryPermissions` of some sort as a part turtle..

**Comment by Gabriel439** [comment]
@zudov: I believe that `getCacheFile` is always run as `MaybeT IO`, so it won't fail with an `IOException`

**Comment by sjakobi** [comment]
These days we produce warnings when there is a permission problem:

https://github.com/dhall-lang/dhall-haskell/blob/a0c3be9ca1ac8c514abf82216f1f4ec735e1a369/dhall/src/Dhall/Import.hs#L791-L814

https://github.com/dhall-lang/dhall-haskell/blob/a0c3be9ca1ac8c514abf82216f1f4ec735e1a369/dhall/src/Dhall/Import.hs#L828-L833

So I believe this is fixed – if I've overlooked something or misunderstood, please reopen! :)
